### ISSUE TITLE
"Extreme Assault" sound setup hangs or crashes if run from setup or installer

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#101]
https://archive.org/details/ExtremeAssault_1020

**Comment by joncampbell123** [comment]
Tried:

cputype=386 vs cputype=pentium
memsize=32 or memsize=8
ems=false
loadfix

**Comment by joncampbell123** [comment]
Setup runs just fine if you run SETSOUND manually

**Comment by joncampbell123** [comment]
Here's a clue.

If you run SETUP.EXE, then exit, and run SETSOUND.EXE, the CauseWay extender complains that it cannot control the A20 line.

The debugger shows the A20 line is off.

**Comment by MX9000** [comment]
@joncampbell123 experimenting with the latest release 2023.03.31 (VS 32-bit SDL2), I noticed that if I set cputype = pentium_mmx as required by the game and segment limits = false when I launch the sound setup option of the setup.exe executable, the emulator restarts with these messages in the log.

LOG: Flush STDIN
LOG:     319675 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:     319753 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG: DOSBox-X has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox-X's options.
LOG:     335033 ERROR BIOS:INT15:Unknown call ax=BF01
LOG: pixratio 1.200, dw true, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: 1283821176 ERROR CPU:CPU:GRP5:Illegal opcode 0xff
LOG: 1283821529 ERROR CPU:CPU:GRP5:Illegal opcode 0xff
LOG: CPU_Exception: Exception 6 already in progress, triggering double fault instead
LOG: CPU_Exception: Double fault already in progress == Triple Fault. Resetting CPU.
LOG: Warning: C++ exception method is not compatible with dynamic core when emulating reset
LOG: Removing UMB block 0xcc00-0xdfff
LOG: Rebooting the system
LOG: Memory I/O complexity optimization enabled aka option 'memory io optimization 1'. If the game or demo is unable to draw to the screen properly, set the option to false.
LOG: The 'scanline render on demand' option is available and may provide a modest boost in video render performance if set to true.
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: DOS keyboard layout loaded with main language code IT for layout it
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: IDE: index 1 slave=0

Under PCem v17 with MS-DOS 6.22 setup.exe works but causes a noticeable slowdown of the emulated CPU (Pentium 166 MMX drops to about 60% speed from the usual 100%).

**Comment by joncampbell123** [comment]
I've been looking at this issue and there seems to be some really bizarre things going on with 32-bit protected mode and SETSOUND.EXE.

For whatever reason, if SETSOUND is run by SETUP, it appears to goof up and write it's driver strings and pieces of code over the interrupt table at 0000:0000 in real mode (????) which of course all it takes is the corrupted interrupt to fire to cause a crash. Is it writing to a NULL pointer? This doesn't happen when SETSOUND is run by itself. The amount of free conventional memory doesn't appear to have any effect on this crash.

I think it has to do with some kind of NULL pointer issue because the number of times it calls INT 21h AH=48h (allocate memory) and 49h (free memory) at startup is wildly different between run as a program and under SETUP.

As a DOS program by itself, I see one, maybe two calls to INT 21h AH=48h once it enters protected mode, and then it runs. However under SETUP, it calls INT 21h AH=48h twice a *lot* apparently unable to allocate the two blocks of memory it's looking for. The call is from protected mode.

Whatever DOS extender is handling INT 21h translates AH=48h to a function to allocate memory and return a LDT descriptor, not a real mode segment. Now the weird thing is that the failing memory allocation from protected mode appears to first allocate one paragraph (16 bytes), which succeeds, but makes no changes to the MCB chain (DOS extender is handling it), and then attempts to allocate 32768 bytes, which fails *despite* the fact that there is clearly a 32768 byte block of free memory right there in the MCB chain. The DOS extender appears to resize it's own memory blocks and allocate and free that 32768 block three times (successfully, I might add) before giving up and returning an error code to the protected mode program.

I noticed that SETUP runs DOS4GW.EXE while SETSOUND.EXE contains the CauseWay DOS extender within it. Could this be a clash of DOS extenders or expected behaviors?

![image](https://user-images.githubusercontent.com/6245486/235195857-3ad19820-7dac-4be0-ab4d-7c15e8641b1b.png)

**Comment by joncampbell123** [comment]
At this point I expect that if I were to run this on real hardware in pure DOS mode that it might crash the same way.

Could this be one of those DOS games that runs better under Windows 95 than in pure DOS mode? Like that 1999 Demoscene production that reliably crashed in DOSBox-X *and* on real hardware unless run under Windows 98.

**Comment by joncampbell123** [comment]
I mean, look, at the DOS kernel level the allocation clearly succeeded, but the DOS extender isn't happy with it?

  26793226 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x0800) = 0x137b-0x1b7a
  26793536 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x080a) blocks=0x01f6
  26793835 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x080a) blocks=0x00f6
  26794139 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x3643) blocks=0x69bd
  26794438 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x3643) blocks=0x68bd
  26794742 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x1b7c) blocks=0x0d84
  26795041 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x1b7c) blocks=0x0c84
  26795345 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x2801) blocks=0x01ff
  26795644 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x2801) blocks=0x00ff
  26795949 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x2e42) blocks=0x08be
  26796248 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x2e42) blocks=0x07be
  26796552 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x3601) blocks=0x01ff
  26796852 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x3601) blocks=0x00ff
  26797156 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x9f01) blocks=0x01ff
  26797455 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x9f01) blocks=0x00ff
  26798227 DEBUG DOSMISC:DOS_FreeMemory(seg=0x137b)
  26800667 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x0800) = 0x137b-0x1b7a
  26801860 DEBUG DOSMISC:DOS_FreeMemory(seg=0x137b)
  26803140 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x0800) = 0x137b-0x1b7a
  26804333 DEBUG DOSMISC:DOS_FreeMemory(seg=0x137b)
  26805585 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x0800) = 0x137b-0x1b7a
  26806778 DEBUG DOSMISC:DOS_FreeMemory(seg=0x137b)

**Comment by joncampbell123** [comment]
Here's another interesting clue:

If you load CWSDPMI.EXE before running SETUP, it can't run SETSOUND.EXE. "CauseWay error 12 : Not enough memory to load application." and nothing using DOS4GW.EXE runs. But CWSDPMI.EXE and SETSOUND.EXE directly works just fine.

**Comment by MX9000** [comment]
@joncampbell123 thank you, your technical explanations are very interesting!
I tried booting MS-DOS 6.22 under DOSBox-X and the issue was solved.

**Comment by joncampbell123** [comment]
Hm...

If you break on INT 31h AH=FFh, the memory allocation function it uses varies whether or not it's run under SETUP.EXE.

If you run SETSOUND.EXE directly, it calls INT 31h AX=FF0Ch: http://www.ctyme.com/intr/rb-5903.htm
If you run it through SETUP.EXE, it calls INT 31h AX=FF0Bh: http://www.ctyme.com/intr/rb-5902.htm

The FF0Bh case is the one failing.

Also FF0Bh with CX:DX = FFFF:FFFF to query available space says that there's only 12KB free despite the gaping 32KB hole visible in the MCB chain. Is CauseWay as a client of DOS4GW.EXE causing an accounting error?

**Comment by joncampbell123** [comment]
I copied the game into a bootable Windows 95 hdd image to run it there... it hangs the same way, except that INT 31h AX=FF0Bh CX:DX=FFFF:FFFF lies and says there's only 8KB free.

**Comment by joncampbell123** [comment]
Ah! But if you boot into Windows 95, bring up a DOS prompt, then run SETUP and then click on "Sound setup", it works.

The DPMI server behind Windows 95 doesn't have this issue, while DOS4GW.EXE or related servers to.

![guest os_000](https://user-images.githubusercontent.com/6245486/235325796-0c348919-c9cf-476d-8acd-806241317b5e.png)

**Comment by joncampbell123** [comment]
I'm starting to think this is a bug with a game that was probably tested more under Windows 95 than under pure DOS mode.

**Comment by joncampbell123** [comment]
:rofl: Oooh, if you boot into Windows 95 pure DOS mode with EMM386.EXE loaded, DOS4GW.EXE and any DOS program that relies on it will straight up cause a full reboot. They clearly did the majority of testing under the Windows 95 desktop than pure DOS mode :laughing:

**Comment by joncampbell123** [comment]
Last instruction before the crash:

    0128:00000583  mov  CR3,eax
    EAX:0000C000 EBX:0000C000 ECX:000013EA EDX:00000020 ESI:0000A928 EDI:00110000 EBP:000014F2 ESP:00000100 DS:0080 ES:0080 FS:0000 GS:00C0 SS:0120 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:1 IF:0

**Comment by grapeli** [comment]
The simplest solution is to use [HX](https://github.com/Baron-von-Riedesel/HX).

Solution.
`DPMILD32.EXE SETUP.EXE`
It works perfectly fine.

This means that this game was prepared with a toolchain more compatible with WIN95/98 than DOS.
Nothing to fix here.
