### ISSUE TITLE
dosbox-x crashed when games create 3D object with directx

### ISSUE THREAD

**Issue by legluondunet** [joncampbell123/dosbox-x#1026]
I compiled today dosbox-x git version and it crashed each time I try to launch a 3DFX game on Windows 95.
This worked great with another dosbox-x git version I compiled in january 2019: 0.82.15 sdl1

This is the log file from dosbox-x 0.82.17 sdl1 when it crashed:
[cyber-gladiator-dosbox-x.log](https://github.com/joncampbell123/dosbox-x/files/2949418/cyber-gladiator-dosbox-x.log)

Config: Ubuntu 18.04 Bionic 64 bits - NVIDIA GeForce GTX 770 - Nvidia drivers 415.27 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 16 Go RAM

Thank you for your help.

**Comment by joncampbell123** [comment]
Try adding under [sdl]
output=surface

MinGW builds were recently fixed to enable Direct3D and will default to it.

**Comment by legluondunet** [comment]
This is my conf file, surface is already set and like I said it worked well with dosbox-x from 2 january git version.
[cyber-gladiator-dosbox-x.zip](https://github.com/joncampbell123/dosbox-x/files/2949777/cyber-gladiator-dosbox-x.zip)

**Comment by legluondunet** [comment]
I just compiled dosbox-x from last today's git version use the ./build-debug script, then the ./build-debug-no-avcodec script and finally the ./build-debug-sdl2, I tested them both with different game installed on Windows 95, they all crashed.
I just found that dosbox-x crashed with different games, 3DFX or D3D, it crashed when game prepare to show 3D object.

**Comment by Koloth** [comment]
I have the same issue.  I have a disk image into which I've installed Windows 95 and Star Trek: Generations.  Using the OS X version from January, the game runs fine (albeit rather slowly).  Using the March release, it crashes immediately.

**Comment by joncampbell123** [comment]
@legluondunet I just noticed in your log file the error message "FPU stack overflow".

A problem was recently fixed with the x86 FPU core where FPU stack overflow or underflow would trigger an E_Exit() abort from the emulator because of code inherited from DOSBox SVN.

I'm not sure why DOSBox SVN is written to error out and exit if the FPU stack overflows or underflows.

The same issue could also be triggered by installing Windows 95, then installing Internet Explorer 4.02 SP1. Something about the ActiveX desktop or Channel guide triggered the same FPU stack overflow error.

Recent commits removed the E_Exit() abort. If you can compile from source, pull the latest code and try again.

**Comment by legluondunet** [comment]
I just compiled dosbox-x from today's git, I can not reproduce this issue, thank you for your help.
