### ISSUE TITLE
I've read on the net that this fork has support for mounting FAT32 (> 2 gb) hard disk images that win95 can see

### ISSUE THREAD

**Issue by i30817** [joncampbell123/dosbox-x#104]
(well i don't quite remember, but i'm pretty sure it's not mounting local directories as FAT drives that win95 can see, which would be revolutionary).

Does a diff file for this feature exist? I'd like to pull it for my ppa svn build.

**Comment by joncampbell123** [comment]
So far > 2GB disk image support has been tested with Linux. Not sure about Windows, you're free to try. Some of the other changes to look at involve the INT 13h extensions that allow disk images larger than 8.4GB.

The reason the code might have the 2GB limit is the use of fopen/fseek/etc in the disk image code, which on most platforms limits file size support to 2GB because those functions are usually defined with int or long data types, except in Linux, where they can be made to exceed the 2GB limit by use of the compile-time flag -D_FILE_OFFSET_BITS=64 on 32-bit platforms.

**Comment by i30817** [comment]
I'm on linux.

**Comment by joncampbell123** [comment]
I've never had a problem with -D_FILE_OFFSET_BITS=64 though my code tends to use the open/close/lseek functions rather than fopen/fseek. I suggest installing Windows 95 OSR2 on a FAT32 partition in DOSBox, then letting Scandisk check the entire disk.

**Comment by joncampbell123** [comment]
It's fixed on my end. Visual C++ stat() has apparently been fixed to ignore files 2GB or larger, thus emulating what Linux has been doing for quite awhile. But there's a _stat64 we can use. The whole reason it didn't work was the use of stat() to check the file.

**Comment by i30817** [comment]
Are you going to try to upstream the patch?

**Comment by joncampbell123** [comment]
The changes are minimal enough it could work. Large (2GB+) hard disk images aren't relevant to DOS games though, so I'm not sure if they would take it.
