### ISSUE TITLE
Windows 9X - ME Black Screen Right After Boot Logo Ends

### ISSUE THREAD

**Issue by cakehonolulu** [joncampbell123/dosbox-x#1046]
**Describe the bug**
Running Windows (95, 98 or ME) off a 8GB image, results in a black screen after boot logo disappears.
If I use previous dosbox-x release, it works correctly (0.82.16).
Re-installing Windows works, but booting it doesn't.
If I use core=full , Windows boots.
Using core=dynamic results in that black screen.

**Environment:**
 - Operating system: Windows 10 x64 Insider Preview 18865
 - DOSBox-X release version: 0.82.17
 - [dosbox.txt](https://github.com/joncampbell123/dosbox-x/files/3051337/dosbox.txt)

**Comment by joncampbell123** [comment]
Do not use dynamic core with preemptive multitasking OSes like Windows 95/NT. Use the normal core.

The full core is known to cause *slight* problems (with the GUI apparently) in Windows 95.

Previous versions locked out dynamic core if 386 paging was enabled. That lockout has been removed because dynamic core is fully functional again with protected mode DOS games that use paging (Quake) and Windows 3.11.

However it only works if the page fault handler returns back to the location of the fault.

To explain, what makes Windows 95/NT incompatible with dynamic core is the fact that the page fault handler in Windows 95 can be preempted by a task switch. More often than not, the task switch back to the first fault does not return in the same order, which ties DOSBox/DOSBox-X's page fault handling into knots and causes problems.

**Comment by joncampbell123** [comment]
Windows 95 is a preemptive multitasking OS, meaning that it switches tasks in a way out of control of the applications running under it. Apparently in Windows 95, that includes the page fault handler, and that's the problem.

Windows 3.11 and earlier are cooperative multitasking environments. Task switching is done when the application calls a function that yields to another process. Windows 3.11 is also heavily dependent on MS-DOS for the disk, so when a page fault occurs, the fault handler calls down to MS-DOS INT 21h and fetches the page from the page file on disk and then returns to the fault location. This dependency on MS-DOS is also the reason Windows 3.11 and earlier never page out MS-DOS even though calls to MS-DOS are done in virtual 8086 mode.

**Comment by joncampbell123** [comment]
You are probably also aware of the "non-recursive page fault handling" in DOSBox-X. That works for all CPU cores EXCEPT dynamic because of the way C++ handles throwing an exception.

When the dynamic core generates executable code for the host, it does so with a focus on making executable code. It does *not* take into consideration the system used by the C++ runtime involved in throwing C++ exceptions.

Because of this, throwing the C++ "guest page fault" exception handler happens to work in Windows (because of the Structured Exception Handling chain in the thread information block), but it does not work on anything else (like Linux) because the generated dynamic code has no exception handler frame data for the C++ runtime to trace. On Linux, this results in the program aborting with an uncaught C++ exception if thrown while called by the dynamic core, even if the code that called the dynamically generated code had a try...catch block to catch it.

So DOSBox-X had to revert to the "recursion" method of handling page faults for dynamic core, same as DOSBox SVN. That recursion assumes the page fault handler will return back to the fault location to continue execution. Windows 95 breaks that assumption.

**Comment by joncampbell123** [comment]
C++ exception handling on Linux is dependent on the .eh_data sections of the compiled ELF binaries. The .eh_data sections are needed by the C++ runtime in order to trace the stack and determine how to handle a C++ exception. dynamic core does not generate any .eh_data, making it impossible for the C++ exception handling to trace the stack and properly dispatch the right try..catch block.
