### ISSUE TITLE
lfn patch

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#105]
Ported lfn patch (by Wengier) to dosbox-x (posted at http://pastebin.com/CBDbj9GA). However, the patch requires a few additional changes which are not yet in the patch:

A. Set -fpermissive (using mingw) to bypass error in drive_cache.cpp: invalid conversion of void\* to dir_information*.

B. hardware.cpp, lines 151,152 require a change for compatibility with modified parameters (commented out for now):

<pre lang=""><code>
    //bool testRead = read_directory_first(dir, tempname, is_directory );
    /*for ( ; testRead; testRead = read_directory_next(dir, tempname, is_directory) ) {
        char * test=strstr(tempname,ext);
        if (!test || strlen(test)!=strlen(ext)) 
            continue;
        *test=0;
        if (strncasecmp(tempname,file_start,strlen(file_start))!=0) continue;
        Bitu num=atoi(&tempname[strlen(file_start)]);
        if (num>=last) last=num+1;
    }*/
</code></pre>

C. Patch is missing a change to shell_cmds.cpp (removal of that bracket to close a loop):

<pre lang=""><code>
    if (!optB) WriteOut(MSG_Get("SHELL_CMD_DIR_INTRO"),sargs);
-   }
</code></pre>

D. And another edit, but must verify whether parameter value should be true and/or false:

<pre lang=""><code>
        Bit8u targetdrive = (args[0] | 0x20)-'a' + 1;
        unsigned char targetdisplay = *reinterpret_cast<unsigned char*>(&args[0]);
-       if(!DOS_GetCurrentDir(targetdrive,dir)) {
+       if(!DOS_GetCurrentDir(targetdrive,dir,true)) {
</code></pre>

E. An optional change: isinf() not defined by mingw (see fpu_instructions.h).

note: github auto-formatting is not ideal.

**Comment by ghoul8765** [comment]
Updated patch here: http://pastebin.com/HpSAdVqZ. This has the above changes for A through D, although A, B, and D could use further verification.

Also, noted that mingw32 doesn't have isinf(), but does have std::isinf():
<pre lang=""><code>
 	if (CPU_ArchitectureType<CPU_ARCHTYPE_386) {
-		if (isinf(fpu.regs[st].d) && isinf(fpu.regs[other].d)) {
+		if (std::isinf(fpu.regs[st].d) && std::isinf(fpu.regs[other].d)) {
</code></pre>

**Comment by joncampbell123** [comment]
I applied the patch. It seems to have broken path lookup. It's also a bit Windows-centric in that some new functions were defined for Win32 but not non-Win32 targets. I'm patching that up now.

**Comment by joncampbell123** [comment]
I'm sorry. The LFN patch seems to completely break DOSBox-X's ability to lookup or access files from anything other than drive Z:
I'm also concerned about the Windows-centric nature of the patch. It adds some new functions but only for Win32 targets, thus causing a compile failure on non-Windows targets.
It will need some work to integrate into DOSBox-X.

I like the idea of adding a ver= parameter to DOSBox-X to set the DOS version, so I'll go ahead and integrate that part of the patch, with my addition to allow specifying the minor DOS version as well (i.e. ver=6.22 to emulate MS-DOS 6.22).

**Comment by ghoul8765** [comment]
I would be glad to try to adapt it for other OS, although I'm typically in a win32 environment. However, I can try to adapt it for Linux -- it may not require those extra functions which are windows specific anyways. I appreciate all your work on this!

**Comment by joncampbell123** [comment]
I just finished the ver= option. Please make sure the patch submitted does not try to add that to the source. Thanks for the help!

**Comment by ghoul8765** [comment]
I'll make sure of that, and thanks again.  :)

**Comment by ghoul8765** [comment]
Made minor changes so it is compatible with your latest commit on dos version#: http://pastebin.com/xpjPSnLP. With the patch, and building in mingw32, DOSBox-X seems to have functional LFN (such as the "copy" command).

I wonder if the issues are solely related to non-win32 clients instead of any particular incompatibility with DOSBox-X. If so, I could eventually setup a linux client for testing, but do you think it is reasonable to submit a win32 only patch and define the lines as such throughout the code?

**Comment by joncampbell123** [comment]
It applies better, but again when compiled on Linux, DOSBox-X can't open files other than drive Z:

Something about this patch completely breaks path lookup. If I mount a directory as drive C: it can see the files but any attempt to open files fails.

I suggest setting up a VirtualBox or QEMU VM with Linux, installing a C++ compiler and the SDL 1.2 libraries, and trying to compile within the VM to see what I mean. Make sure you install GCC 4.8, automake, autoconf, m4, the C++ compiler, libSDL 1.2.

**Comment by ghoul8765** [comment]
I appreciate the walkthrough! I added those functions and unfortunately never tested on non-win32, so I mistakenly placed within a definition block. That should be simple to fix once a VM is setup. Also, your analysis of the "path lookup" should help find the problem in the code, especially since it's on non-Z drives. I would guess the issue is related to the way the path is stored in some variable, such as using "\" instead of "/". It may take some time, but I'm glad to have the help.

**Comment by i30817** [comment]
I'm interested in applying this patch to my ppa if it can be made 'linux compatible'. Damn dosbox fragmentation anyway.

**Comment by ghoul8765** [comment]
I just got the lfn patch to work in dosbox-x in linux. I have to remake the patch to remove the next2, first2 functions which may take some time, but the previously attached patch should work without any debugging (however, it requires modifying the next2, first2 functions which were required by mingw32).

**Comment by ghoul8765** [comment]
Please try this one:
http://pastebin.com/953mi3eG

It applies against yesterday's dosbox-x source code. It's verified in ubuntu linux. However, I have a lot of other changes once this is confirmed to work.

**Comment by joncampbell123** [comment]
"This paste has been removed"

That was fast. Please let me know when it is available again.

**Comment by ghoul8765** [comment]
Sorry! Here it is: http://pastebin.com/GvQxpKmt.

**Comment by ghoul8765** [comment]
I verified that above lfn code in dosbox-x and ubuntu linux (gcc 4.8.1). I also have the new code that you uploaded today in a parsable format. I didn't include the updated portions because I haven't tested them fully, but they work in a custom build under Windows.

I also made several changes not yet uploaded, such as moving the lfn detection routine from xms.cpp to dos.cpp, consistent with your "dos version" patch. I also removed the *_next2 and *_prev2 and commented out a line of code which can be modified at a later time.

If you'd like the updated portions sooner, then I can send this patch which applies to a custom build, but at least it will be simple to update dosbox-x. Otherwise, I can verify that the code applies cleanly.

**Comment by joncampbell123** [comment]
Hm... I'm still running into the issue that I can directory list, but not run or open files. I noticed "del" and "ren" works though. Drive Z: works.

I am mounting a folder to drive c: in my dosbox.conf

mount c: .

I also tried making the path absolute:

mount c: /mnt/main/emu/test

However I see what the problem is. I did an strace on the running DOSBox instance and I noticed that the problem seems to stem from the fact that I am typing the DOS program name in lowercase (nssi.exe), but the DOS program was extracted to the folder on Linux (NSSI.EXE). The DOSBox code prior to your patch handled the case difference just fine, the new code does not.

Remember that on Linux, file operations are case sensitive. That means the system treats HELLO and Hello and hello as different file names.

Does that help with the issue?

**Comment by ghoul8765** [comment]
I did limited testing since I was trying to upload a result as soon as I could. I thought I could fix the untested issues later so that you would have lfn code that applies to dosbox-x (instead of trying to merge new code bits with unknown locations in dosbox-x).

In my testing, I used the copy command made sure I could then open the new file. I mounted the drive like this only:
mount c ./

I did not test the case sensitivity of names inside dosbox-x. I may have used name completion only so that problem went unnoticed.

I'll try to fix the remaining issues today. I'll run tests to detect all issues noted above, too. :)

**Comment by ghoul8765** [comment]
Updated the patch here: http://pastebin.com/dPecXsmp.

It has the latest patch from the forum along with the two changes discussed there to introduce upper case filenames. Also, added many fixes and a few workarounds to compile in linux. This patch applies to the dosbox-x source code and verified that the lfn is working.

Note that workarounds include removing code for detecting Windows (0x1605) so the function matches the original lfn code; temporarily assigning variables for a couple of auxiliary functions (mentioned earlier in this thread); and possible one or two others. Please also verify the CMD_COPY function against the patches from the forum.

This patch will make it simpler to test the lfn in dosbox-x and then verify against the forum's patches and then continue patching from that step.

**Comment by i30817** [comment]
Does it apply on dosbox upstream svn too?

**Comment by i30817** [comment]
Also could you please use something persistent to store the patches, like attaching them here (if possible) or in google drive? All your pastebin links are dead.

**Comment by Rondom** [comment]
Has anyone saved a copy of that patch. @joncampbell123 ? The submitter deleted his GitHub-account. If anyone remembers who the submitter was (maybe from GitHub email notifications stored in ones inbox), maybe one can also contact them.

**Comment by Rondom** [comment]
2015-08-31
> Updated the patch here: http://pastebin.com/dPecXsmp.
http://web.archive.org/web/20150901003341/http://pastebin.com:80/dPecXsmp

**Comment by i30817** [comment]
Thanks, even though i no longer need it (my problem was different).

**Comment by sergeevabc** [comment]
Err… So, does DOSBox-X have long filenames support or not?

**Comment by joncampbell123** [comment]
No, sorry. Forgot this issue even existed, let me grab the patch.

**Comment by joncampbell123** [comment]
It's going to need some work to incorporate, since the patch is probably based on some really old DOSBox code.

**Comment by Wengier** [comment]
I have managed to adapt the patch for the latest DOSBox-X release (v0.82.26). Some newer changes from the DOSBox LFN patch are also incorporated here. Tested under Windows 10 (Visual Studio 2015) and Linux (Fedora 30) platforms. The LFN to seems to be functional (LFN is enabled when DOS version >=7.0). Also tested NSSI.EXE and Windows 3.1 (as well as WFW 3.11) inside DOSBox-X, both appear to work fine. No problems encountered when I tried them.

The source code diff is available from the link:
http://individual.utoronto.ca/wengier/files/dosbox-x-v0.82.26-lfn-patch.diff

And the pre-compiled binary for Windows (64-bit) is also available from the link:
http://individual.utoronto.ca/wengier/files/dosbox-x-lfn.zip

**Comment by voltagex** [comment]
I'm not able to apply that diff using patch or git - can you please send it as a pull request @Wengier?

**Comment by Wengier** [comment]
@voltagex LFN support is already included in DOSBox-X 0.83.1 or later. Set ver=7.1 in dosbox-x.conf to enable it at start. Also, in DOSBox-X 0.83.2 (which will come soon) you can enable it directly with LFN=true in dosbox-x.conf.

**Comment by voltagex** [comment]
Oops! Thanks. Should this issue be closed now?
