### ISSUE TITLE
Gravis Ultrasound emulation causes some demos to miss a cue and stop

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#111]
I'm seeing issues with some demos and games where the GUS fails to fire an event in the demo and strange issues happen at certain cycles counts.

"380 volt" At cycles counts above 15000 the demo will miss a cue of some kind, and the music will stop at the city scape animation and the animation will loop forever.

"Hex Appeal" by Cascada: GUS playback works but then the demo gets stuck at an endlessly moving starfield instead of moving to the credits. Playback through Sound Blaster, LPT DAC, etc. works properly.

"The Good, The Bad, The Ugly" At cycles counts other than 15000 the demo will skip over the moving blobs and move directly to the rotating cube, then stay there for the entire time until the cue to switch to the next part.

It's funny that I don't remember having these issues 8 years ago with DOSBox 0.72 with the same demos even when the cycles count was cranked up to high values.

**Comment by joncampbell123** [comment]
This happens regardless of CPU core.

**Comment by ghoul8765** [comment]
An enthusiast wrote this at Vogons but didn't attach any audio recordings. Probably not fully reliable, but the stereo issue seems reproducible.

1) Tracked down one part of why GUS sounded bad in Star Control 2 with dosbox-X..

I was using 0.74 configs and they did not have this line:
dynamic kernel allocation=false

For anyone testing SC2, be sure to start with starcon2.exe /S:GRAVIS and check the map for coords - the map bypass hacks (incl. GOG's) appear to bring about audio bugs with gus emulation depending on what dosbox built is running it

1b) there's still some intermittent glitching going on that but you need to have quite good ears and headphones to notice .. similar to as in OMF .. I bought a real GUS ACE and it didn't glitch like this, if it does glitch it's not noticeable to me. I'll verify this on another GUS as I bought two... ... maybe same cause as issue 3) below

2) I checked the reversed stereo issue extensively (bought the first ACE rev with reverse stereo) and it appears -X branch has the GUS stereo swapped incorrectly just like the first ace card. One test is to run doom(which doesn't allow reversing stereo), idclev 1 3, and listen where the shots come from. the LFN build on other thread has this right (I believe it's based on recent SVN so that should be ok too)

This is possibly a regression of X-branch caused by the stereo width patch and misleading videos recorded with the reversed stereo in ACE rev 1.0 leading as with older build the stereo is not reversed but the width does not match the typical very wide gus sound (which you could well argue is too wide for headphones but that's how it's in the hw, so similar width adjustment in mixer as in winuae would be useful).

3) There is still some subtle glitch in all dosbox builds I tried, most noticeably in OMF menu theme beginning. It's not present on hardware. I think it can be briefly heard in other places in "quiet" songs but much more rarely.

**Comment by joncampbell123** [comment]
"380 volt" was found to have a timing problem where, if the file I/O was too fast at that point in the demo, it would miss a cue and fail to continue the music.

Adding file I/O delay to emulate a slow hard disk resolved the issue.
