### ISSUE TITLE
Configuration file does not work

### ISSUE THREAD

**Issue by HomerBender77** [joncampbell123/dosbox-x#1178]
When I try to put mount lines in the AUTOEXEC section of the dosbox.reference file, they do not work for some reason.

**Comment by joncampbell123** [comment]
If it does not work, there will usually be an error message on the DOS console stating why.

**Comment by Allofich** [comment]
The reference file? Try copying it and renaming the file to dosbox-x.conf.

**Comment by joncampbell123** [comment]
@Allofich The reference file has literally *every* setting, that's a bit much for a start.

You should be able to add commands under the [autoexec] section and see that they are executing. Try "echo testing" first to see if that works, then try mount commands.

The imgmount and mount commands should say what is wrong if they can't mount anything to the drive letter.

**Comment by Allofich** [comment]
What I mainly meant to convey was, he said dosbox.reference file, and that’s not read by dosbox-x.exe, right? If he's been editing that file, that would explain why nothing is happening.

**Comment by joncampbell123** [comment]
DOSBox-X looks for dosbox.conf, not dosbox.reference.conf.

That would explain it, if that is what's wrong here.

dosbox.reference.conf is there to list all the options for your reference.

**Comment by HomerBender77** [comment]
> DOSBox-X looks for dosbox.conf, not dosbox.reference.conf.
I tried copying the latter file and renaming it to the former, but it still doesn't work.

**Comment by Allofich** [comment]
> I tried copying the latter file and renaming it to the former, but it still doesn't work.

Did you rename it to dosbox.conf? I called it the wrong name ("dosbox-x.conf")in my first post.

> it still doesn't work

All I can suggest, is to make sure you didn't comment out the lines by putting "#" before them.  Should look like, for example:

mount C (path to whatever you want to make drive C)

Should `not` look like:

#mount C (path to whatever you want to make drive C)

If you've got a working .conf for regular DOSBox, you could try copying and pasting over the autoexec commands. I think they're the same. You could also try and make sure whatever you're trying to do works from the command line after you've launched DOSBox-X.

If you are using Windows, another idea is to try running DOSBox-X from a different folder. I've seen every once in a while people having trouble running a game (not DOSBox, just in general) because of access restrictions in the folder they were trying to use. I have no idea if that is the cause of this issue, but you could try putting DOSBox-X  in a folder on a drive other than C if you have one.

That's all I can think of.

> the original ZIP folder doesn't even originally have a file called dosbox.conf,

It's always been like that as far as I know.

**Comment by HomerBender77** [comment]
That which I am trying to do in the command line works. I tried all the above but problem still persists.

**Comment by Allofich** [comment]
1. Can you post your dosbox.conf file here, or copy and paste the commands you're trying to run?
2. Are you using Windows?

> Also, when will version 0.82.20 be released?

They seem to usually come out around the beginning/end of a month.
