### ISSUE TITLE
Windows 98 SE: Setup Detection Notice Message SU0409

### ISSUE THREAD

**Issue by dajhorn** [joncampbell123/dosbox-x#123]
As of commit c764ef322fc3b864a5eb69b904cf4531a244bcf5, the Windows 98 SE setup program fails early on [Error SU0409](https://support.microsoft.com/en-us/kb/129971), but the [dosbox-x notes](https://github.com/joncampbell123/dosbox-x/blob/master/NOTES/Microsoft%20Windows%2098%20SE) suggest that it should work.

Compiled with Visual Studio 2015 using the 64-bit release profile.  Screenshot attached.

![windows 98 setup - message su0409](https://cloud.githubusercontent.com/assets/494022/12221163/a9d51e62-b75c-11e5-919a-760736f67aed.png)

**Comment by ghoul8765** [comment]
Those notes are for core=dynamic but you had disabled that core in favor of the reliable normal core.

**Comment by ghoul8765** [comment]
Set core=normal.

**Comment by dajhorn** [comment]
@ghoul8765, same glitch with `core=dynamic` and `core=normal`.  The `config -all -wc` dump is:

* https://gist.github.com/dajhorn/35a23c16f0d45aade72b

I'm running `mount C` and `mount D` manually.

**Comment by ghoul8765** [comment]
The author knows better, but I would try the code which corresponds to this working release build:
v0.801 (commit: f986c6c)
DOSBox v0.801 Windows 9x/ME friendly

Normal core has been modified extensively to become more page fault reentrant. Windows 95, 98, and (mostly) ME are very stable now in DOSBox-X. Other minor fixes.

Here is the source archive: https://github.com/joncampbell123/dosbox-x/archive/v0.801.zip

This is how I would attempt to find the cause of the issue since this build was tested against 9x/ME. The above issue may be from a more recent commit, or else just a setting like dynamic core cache block size=1 instead of 32. It may take a few tries to solve.

**Comment by ghoul8765** [comment]
Also, try these changes to the primary IDE settings:
enable=true
pnp=true
irq=0
io=0
altio=0
int13fakeio=true
int13fakev86io=true

**Comment by joncampbell123** [comment]
I think the problem may have been a slightly messed up interrupt vector table due to some init reordering I've been working on to make the emulator start up in a manner more like PC hardware (hardware -> BIOS -> DOS) rather than initializing things all at once. On my end, Windows 95 would error out and complain about the "extended memory manager" on install, until I pushed a commit that fixed the interrupt vector table and startup order. I'm able to install Windows 95 again. Could you try Windows 98 with the latest commit?

**Comment by joncampbell123** [comment]
Please try the latest commit. It appears to have fixed the problem. It also fixes a rather nasty flaw in S3 emulation and linear framebuffer emulation.

**Comment by dajhorn** [comment]
@ghoul8765, toggling those options didn't work.

@joncampbell123, same glitch as of commit 6e8ba2f48c846d38421e6fd9672fa5776881907c.  The Win32/Debug target produces this output:

* https://gist.github.com/dajhorn/93e71ca6fd58332fc6fe

This happens with both the First Edition and the Second Edition of Windows 98 as shipped on the MSDN disc.

**Comment by ghoul8765** [comment]
The author knows better, but I would try the code which corresponds to this working release build:
v0.801 (commit: f986c6c)
DOSBox v0.801 Windows 9x/ME friendly

Normal core has been modified extensively to become more page fault reentrant. Windows 95, 98, and (mostly) ME are very stable now in DOSBox-X. Other minor fixes.

Here is the source archive: https://github.com/joncampbell123/dosbox-x/archive/v0.801.zip

This is how I would attempt to find the cause of the issue since this build was tested against 9x/ME. The above issue may be from a more recent commit, or else just a configuration setting.

**Comment by joncampbell123** [comment]
@dajhorn According to the debug output you posted, you're running the setup program directly from the DOSBox-X shell, which is not supported. I'm testing the install by first booting to an MS-DOS 6.22 bootdisk (If Windows 95) or MS-DOS 7.1 bootdisk (if Windows 98/ME), then partitioning a virtual IDE device with FDISK, formatting it, then running the install from a CD-ROM ISO image attached to the IDE controller.

Did installing directly from DOSBox-X's shell ever work?

**Comment by dajhorn** [comment]
> According to the debug output you posted, you're running the setup program directly from the DOSBox-X shell, which is not supported.

Commit 7841f5aa29681b528857725212079166c84f17e7 works with the Emergency Boot Disk, which is `\SETUP\TOOLS\MTSUTIL\FAT32EBD` on the Windows 98 CD-ROM.

@joncampbell123, thanks, I will close this ticket.


> Did installing directly from DOSBox-X's shell ever work?

No, this is the first time that I've used DOSBox-X.

BTW, I'm getting this crash on the host when the Windows 98 desktop starts.  It happens during the video mode switch after the splash.  I will open a separate issue if I dig into troubleshooting it.

![dosbox-x isatty cpp line 17 assertion failure](https://cloud.githubusercontent.com/assets/494022/12238961/728bc944-b854-11e5-8f98-e6db13d11177.png)

**Comment by dajhorn** [comment]
PS: That assertion only happens on Win32/Debug with `core=dynamic`, and is kludged by `core=normal`.

Dosbox-X configuration defaults for a regular 64-bit build on a Windows 10 host seem good.  Sound, video, and large disk images work perfectly with Windows 98 on the current HEAD.

Thanks again. Very nice fork.
