### ISSUE TITLE
PC-98 Vain Dream 2: No music

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#1241]
There is no music, only sound effects, playing Vain Dream 2 from Glodia in DOSBox-X when you set the PC-98 sound board type to the default "board86". There is no sound at all if you set "board26k".

**Comment by joncampbell123** [comment]
Does music happen if you turn on the PC-98 sound BIOS?

Are there debug/log messages indicating calls to the PC-98 sound BIOS?

**Comment by joncampbell123** [comment]
I just pushed new code that will load SOUND.ROM if it exists and present that as the FM board sound BIOS instead of the non-functional stub routines normally put there. Does that help?

**Comment by joncampbell123** [comment]
You need to add 'cascade interrupt ignore in service=true' to get music to work, at least with the copy of "Vain Dream" and "Vain Dream II" that I was able to find.

**Comment by joncampbell123** [comment]
I'm going to push a commit that makes 'cascade interrupt ignore in service' a boolean-ish setting that allows true, false, and "auto".

The "auto" setting will default to true for PC-98 and false for IBM PC.

It's time for that setting to default to "auto" so that correct operation of the game does not constantly require adding 'cascade interrupt ignore in service=true' to your dosbox.conf.

I cannot default to "true" because correct IBM PC emulation requires it to be false.
