### ISSUE TITLE
PC-98 Alone in the Dark: Wrong colors [game does very minimal graphics setup, and a question of 16-color analog / 256-color VGA mode priority]

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#1289]
Booting the HDI in "Alone in the Dark (256-color PC-9821 version) [HD].zip", and the screen resolution and palette is wrong.

![image](https://user-images.githubusercontent.com/37106774/66904751-35eb6e80-f037-11e9-9981-fcea75c2b2ad.png)

Screen resolution is correct when starting INDARK.EXE in DOSBox-X DOS, but the palette is still wrong.
![image](https://user-images.githubusercontent.com/37106774/66904842-5f0bff00-f037-11e9-987c-ad1ab5a8de99.png)

Downloaded from: https://archive.org/download/NeoKobe-NecPc-98012017-11-17/ArrowMicro-techs.zip/Arrow%20Micro-Techs%2FAlone%20in%20the%20Dark%2FAlone%20in%20the%20Dark%20%28256-color%20PC-9821%20version%29%20%5BHD%5D.zip

**Comment by yksoft1** [comment]
By the way, DOSBox-X seemed wrongly tried to switch to 256-color mode while running the HDI in "Alone in the Dark (16-color PC-9801 version) [HD].zip".

**Comment by joncampbell123** [comment]
Okay, it's writing 0x21 to 0x6A which would set up 256-color mode correctly. Not sure what's with the palette though.

**Comment by joncampbell123** [comment]
It's setting up 256-color mode but it's not switching to the analog 16-color mode first, so I think the problem is that palette handling is still in the 8-color digital mode.

I will need to pull out the reference hardware and determine exactly how real hardware acts in this case. It will probably act as if VOPBIT_ANALOG in that case, need to make sure.

**Comment by joncampbell123** [comment]
My impression from one system was that you needed to enable 16-color analog first, but if that's true, Alone in the Dark wouldn't work properly on such systems.

Based on the hardware though this minimal programming effort would still leave it in 200-line mode, because that's controlled by the CRTC. However I had to have DOSBox-X revert graphics to 200-line mode when booting for older games that assume the hardware is in that state (Ys II for example).

**Comment by joncampbell123** [comment]
I've made a commit that disables the auto-switch to 640x200 mode if booting from a hard disk (HDI image) to fix the issue.

I have a TODO list to work from:

https://github.com/joncampbell123/dosbox-x/blob/master/src/dos/dos_programs.cpp#L1485

**Comment by joncampbell123** [comment]
Some games like Ys II assume 640x200 on startup and will misrender otherwise.

This is what it looks like if that 640x200 setup code is disabled.
![guest os_000](https://user-images.githubusercontent.com/6245486/66961377-5ad5e680-f023-11e9-8ae7-58197b18b282.png)

**Comment by joncampbell123** [comment]
Ok. According to a PC-9821Lt2 laptop, the startup state of the graphics layer appears to be 8-color 640x200.

If I boot up MS-DOS, and then run DEBUG and enable the graphics layer and write to VRAM, the scan lines are doubled and blanked as if 200-line.

INT 18h AH=40h enable graphics layer (p steps one instruction or over INT)

A:>DEBUG
-a
mov ah,40
int 18
-p
-p

Write set pixels to the blue plane of the graphics ram. Keep writing and watch where the blue pixels wrap around to, see if they follow the scanline or follow one blank line below. Offset 400h keeps it away from the top where it might be hard to see.

-e a800:400

Then type repeatedly FF followed by spacebar. Blue pixels will appear 8 at a time. Keep going until it wraps around the screen, and stop after it passes the same horizontal position below the first scanline.

**Comment by joncampbell123** [comment]
![pc98-8color-boot-up-debug-test-20191016](https://user-images.githubusercontent.com/6245486/66981897-ef633780-f069-11e9-9116-b3f045e31437.jpg)

**Comment by joncampbell123** [comment]
Writing 21h to 6Ah (enable 256-color mode) does NOT work unless first enabling EGC functions by writing 07h to port 6Ah. Turning EGC functions off with 06h to 6Ah doesn't cancel it back out.

So my initial impression that you had to switch on 16-color analog mode first was wrong, however DOSBox-X's implementation requiring EGC enable first is correct to real hardware.

**Comment by joncampbell123** [comment]
It also seems that, even though scanline doubling was enabled in the 8-color mode, switching on 256-color mode suddenly disables scanline doubling. Typing FFh into bytes at A800:400 and A800:680 shows scanlines that line up without any extra doubling or space.

So this tells me that Alone in the Dark, despite using the hardware in a way that is probably undocumented and not supposed to work like that, will show correctly on real hardware.

Of course, this could be incidental behavior caused by whatever circuit and chip integration NEC did for this particular laptop.

**Comment by joncampbell123** [comment]
Writing 20h to switch off 256-color mode goes straight back to 8-color mode and the scanline doubling is back in force as it was before.

So perhaps the 256-color mode just renders from an entirely different address counter and ignores the address counter normally provided by the GDC? Perhaps the GDC as wired had some address bits chopped off and NEC had to do that for backwards compatibility?

If that's true, then it's also possible you can't use the GDC's "display partitions" in 256-color mode either. If that's the case, then perhaps other GDC functions are not available in 256-color mode either, like setting display pitch (for panning) or starting address.

**Comment by joncampbell123** [comment]
This test also tells me the "workaround" I made this morning for the HDI image is completely wrong, because this was the state of the graphics layer booting from the hard drive in the laptop (which is a CF card that I used to replace the IDE hard drive). This seems to tell me the graphics hardware is always 640x200 8-color mode at BIOS startup, likely for backwards compatibility with older booter games like Ys II that assume it.

**Comment by joncampbell123** [comment]
"What happens if you set 640x200 8-color mode, and then switch directly to 256-color mode by writing 21h to port 6Ah?"

If you first enable EGC functions (command 07h), command 21h will switch the display into 256-color mode. You do not need to switch into 16-color analog mode first.

"Is it possible in any way to make a 640x200 double-scanned 256-color mode?"

It seems like that is not possible. The doublescan bits in the GDC are still there, but 256-color mode seems to ignore them. As much as Alone in the Dark seems to rely on undocumented behavior like this, hardware indicates that the code should set 256-color 640x400 mode anyway and it doesn't matter if the graphics was 8-color 640x200 before.

"What is the state of the graphics plane at system startup (when booting the OS from disk)? Does it matter between hard disk and floppy? Does sector size matter?"

Considering that the hardware was seen in 640x200 8-color mode even after booting MS-DOS 6.22 from a CF card (512 bytes/sector) with a DOS format that is probably 1024 bytes/logical sector, it seems that it doesn't matter the format of the media.

**Comment by joncampbell123** [comment]
Next tests to try (this weekend when I have time to whip up some DOSLIB code to do it):

- Do "display partitions" work in 256-color mode?
- Does setting the GDC pitch (bytes per scanline) work in 256-color mode?
- Is it possible to "pan" in 256-color mode or at least change the starting address the display draws from?

**Comment by joncampbell123** [comment]
@aybe Thanks for tagging but the changes listed do in fact allow the PC-9821 version of Alone in the Dark to display correctly.

**Comment by aybe** [comment]
sorry, fixed.
