### ISSUE TITLE
The special keys don't work on a Mac (startup text needs to properly report F11/F12 key assigned as host)

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#1309]
The special key F11 just don't seem to work on macOS.

F11+m: just acts as if m was pressed
F11+minus: just acts as if - was pressed
F11+plus: just acts as if + was pressed
option+F12: does nothing

Tested on macOS 10.14.6 on a iMac (21.5-inch, 2017) with the apple magic keyboard.

**Comment by emendelson** [comment]
Isn't the host key (by default) F12, not F11? At least that's what it is on my Mac. It works perfectly here when I build DOSBox-X.

Also, I'm sure you've already done this, but just in case someone else reading this hasn't thought of it, you need to make sure that your Keyboard settings in System Preferences have a check mark next to "Use F1, F2, F3 as standard function keys" (or some similar phrasing).

**Comment by sdsnatcher** [comment]
Thanks! It works fine with F12. But why on Earth does it inform you that F11 is the host key on boot?

(Yep, I always have the "Use F1, F2, F3 as standard function keys" checkbox set. It's much better this way.  😃 )

**Comment by joncampbell123** [comment]
That's a mistake that needs to be rectified.

The confusion comes from the fact that F12 was chosen for the host key, but Microsoft Windows reserves F12 for some internal function, so Windows builds had to default to F11 instead.

**Comment by emendelson** [comment]
Meanwhile, the menu tells you which keys to use...

**Comment by joncampbell123** [comment]
I can confirm it says "press F11" even here on Linux.

The hardcoded ANSI text in the source code to generate that makes it a bit harder to just printf strings there, but I'll fix it right now.

**Comment by joncampbell123** [comment]
Here's a link I put in the source code to remind me why that was done:

https://stackoverflow.com/questions/18997754/how-to-disable-f12-to-debug-application-in-visual-studio-2012

**Comment by joncampbell123** [comment]
From Microsoft:

"The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident."

**Comment by joncampbell123** [comment]
By the way, SDL1 Mac OS X builds, if your Macbook Pro has a "touch bar", will add a "host key" directly on the touch bar you can use instead of having to hold down "fn" to get "F12" so that you can hold that down to use shortcuts. You just touch and hold the "host key" to get the same effect.

**Comment by emendelson** [comment]
Interesting. I returned my borrowed Touch Bar MacBook Pro last week. Both the Macs I own are 2015 models with the usable (non-touch-bar) keyboard...

**Comment by emendelson** [comment]
Unless I'm missing something, I think F12 is only reserved when VS is running or debugger is resident, which means that it should certainly be usable as the host key by most users who aren't actually developing something in VS. I run WordPerfect for DOS in DOSBox-X, and the F12 key works exactly as it should in the WPDOS keyboard layout.

**Comment by sdsnatcher** [comment]
Back to the original bug report, I think I found what the problem was: first I was using the dosbox-x that comes in the "dosbox-x" folder. On this one, neither F11 or F12 work as the host key.

When I repeated the test after the @emendelson tip, I used the dosbox-x app that comes inside the "dosbox-x-sdl2" folder. On this version, the F12 key acts just fine as the host key. 

The mistake between versions was because on the 2nd time, I opened dosbox-x via spotlight, just typing the app name.  So I didn't notice that it opened a different version of the app.

-------
Regarding the F11/F12 dilema, why not just pick F11 for all operating systems then? It will make the life much easier for both users and those who'll write documentation.

**Comment by joncampbell123** [comment]
F11/F12 was chosen because it those keys are unlikely to be used by DOS games and Windows applications, except of course keystroke-shortcut-happy DOS editors like Wordperfect.

What the host key was meant to solve were the mess of CTRL and SHIFT combo shortcuts that the original DOSBox project mapped to shortcuts that can conflict with Windows applications and DOS games. DOSBox's taking of ALT+ENTER for example made it difficult to use ALT+ENTER to test "going fullscreen" with the DOS prompt in Windows 3.1 through ME. The idea of the "host key" is to simplify mapper shortcuts by making them all "host key" + a key. It's an idea borrowed from how VirtualBox handles keyboard shortcuts intended for the emulator (Right-Ctrl+something).

The only mapper defaults not changed are the one to terminate DOSBox-X and the one to capture/release the mouse, and only so that users (who may be accustomed to DOSBox SVN) do not panic if the emulator captured the mouse and they need to release it.

You can still map shortcuts to CTRL+ALT+whatever if you like, I never removed that, and you are allowed to re-define the host key as you need to just like any other modifier key.

**Comment by joncampbell123** [comment]
Startup text now displays the actual key assignment. It will update properly if you change it in the mapper and reset the guest system.
