### ISSUE TITLE
Option in dosbox.conf to skip splash screen

### ISSUE THREAD

**Issue by TheKoakuma** [joncampbell123/dosbox-x#1354]
Hi everyone

I've a suggestion since I'm quite bothered about it: Can we have in dosbox.conf some option to skip the splash screen going direct to dos.

This should be a good option for who use autoexec to go directly to emulated application

**Comment by joncampbell123** [comment]
Please try --fastbioslogo which skips the pause in the BIOS screen.

**Comment by Wengier** [comment]
In the latest version there is also a “fastbupioslogo” option which you can add to the config file to skip the BIOS screen. A new command-line option -fastlaunch is added to skip both the BIOS screen and the welcome banner.

**Comment by rderooy** [comment]
@Wengier 

Dosbox-staging also supports similar functionality, but uses differently named settings. Perhaps it would be better to sync them?

This is from the staging reference config:
```
# startup_verbosity: Controls verbosity prior to displaying the program:
#                           | Show splash | Show welcome | Show early stdout
#                    high   |     yes     |     yes      |       yes
#                    medium |     no      |     yes      |       yes
#                    low    |     no      |     no       |       yes
#                    quiet  |     no      |     no       |       no
#                    auto   | 'low' if exec or dir is passed, otherwise 'high'
#                    Possible values: high, medium, low, quiet, auto.
```

**Comment by Wengier** [comment]
@rderooy DOSBox-X never shows the “earlier stout” as in dosbox-staging - it does mounting automatically and transparently for users when launching programs at start, so I am not sure if a full sync with this setting is necessary in this case. On the other hand, you can optionally disable either the BIOS screen (fastbioslogo=true) or the welcome banner (startbanner=false) in DOSBox-X’s config, or you can disable both (either disabling them in the config file individually or with the -fastlaunch command-line option) which is essentially the same thing as dosbox-staging’s “Instant Launch” feature.

**Comment by rderooy** [comment]
@Wengier it was not so much about copying functionality, but more about naming of the options that have a similar effect. Was just thinking it would be better if similar options had similar names in the different forks. It just makes it easier if you have multiple configs to switch between forks for testing without having to re-write the config file.

**Comment by Wengier** [comment]
@rderooy I agree with this in principle of course, but the problem is that we simply do not have a standard (similar to W3C standards for web browsers) for all DOSBox forks to follow at this time. When we do not have such a standard, all DOSBox forks are doing their own stuff in general, and even if I try to use the exactly same option as dosbox-staging for this one, dosbox-staging does not necessarily do the same for other options that already exist in DOSBox-X. An example is "Add an option for setting monochrome palette colour" in dosbox-staging's recent commit (https://github.com/dosbox-staging/dosbox-staging/commit/ce533d038654a3595d5a5ac0d46cd822f6f477ae): a new config option "monochrome_palette" is added for the feature in dosbox-staging, even if this feature has already existed in DOSBox-X for some time with a different name ("monochrome_pal"). So without a standard similar to W3C, it won't help in general even if I try to do use the exactly same option as dosbox-staging for the fast launch/instant launch feature.

**Comment by kcgen** [comment]
Yeah, in general in staging we're trying to remove configurable options if we can determine an objective "best setting" without exceptions. 

When it comes to adding a new config item, it's named using full words separated with underscores (yes, this can be verbose, but it's written by dosbox on empty startup, so the user isn't expected to remember these or type them out). Potential values however are often typed by users, so we stay consistent with other dosbox conf values and don't use underscores.

I think for existing variables it might be harder for the projects to overlap.  But going forward for new common features we will always see if the DOSBox-X approach makes sense and fits. 

Just as an example: `monochrome_pal` mixes using a longer-full word with a truncated shorter word (palette is 7 chars vs 10 for monochrome.. so the logic of why one was truncated but the other left full doesn't make sense if saving characters is the goal.  ie: mono_palette would have done a better job. But perhaps other rules are at play like using a full first word followed by truncating additional words?). Also, _pal might be easily confused as the video standard versus ntsc; so I would always try to differentiate pallette (colors space) vs PAL (the video standard). 

Just sharing my thinking; not criticizing. 

When we add munt and 3dfx, we will certainly see if we can use the existing set (and likely subset) from DOSBox-X.

Thanks for bringing this up @rderooy ; the more seanless we can make life for users and ourselves, the better!

**Comment by Wengier** [comment]
@kcgen The config option "monochrome_pal" was added long time ago, and I agree that some existing config items may not be named or placed very well. For example, looking at the dosbox-x.reference.conf file, I found that there are many video-related config options, which really should have its own [video] section, instead of all scattered in the [dosbox] section (thus it may not look very organized). So I decided to reorganize these config options by moving them to the new [video] section in the latest DOSBox-X code, and DOSBox-X will also automatically redirect existing config options from the [dosbox] section to the new section when it starts so that it won't break existing config files. By doing something like this, I think I can even rename existing config options like "monochrome_pal" as well without breaking existing config files.

So maybe there can be a better way for DOSBox-X and dosbox-staging to communicate about new config options. Perhaps we can have a page (viewable by both projects) so that when either project tries to add new config option(s), they can post in this page. If the other project has some concerns about the naming, they can post the concerns there for both projects to discuss. In any case, when the naming is agreed by both projects (either from the beginning or after discussion), then both projects will follow it. How about this?

**Comment by kcgen** [comment]
> So I decided to reorganize these config options by moving them to the new [video] section in the latest DOSBox-X code, and DOSBox-X will also automatically redirect existing config options from the [dosbox] section to the new section when it starts so that it won't break existing config files. By doing something like this, I think I can even rename existing config options like "monochrome_pal" as well without breaking existing config files.

Wow - that's really slick @Wengier , and give you a lot more flexibility to refactor the configuration across releases (without users even noticing!).  I know this is pretty common in commercial (and open source), and was hoping we would get features like this "for free" by migrating to a 3rd party INI handler library; but sounds like you've already got code to do this.

> So maybe there can be a better way for DOSBox-X and dosbox-staging to communicate about new config options. Perhaps we can have a page (viewable by both projects) so that when either project tries to add new config option(s), they can post in this page. If the other project has some concerns about the naming, they can post the concerns there for both projects to discuss. In any case, when the naming is agreed by both projects (either from the beginning or after discussion), then both projects will follow it. How about this?

This sounds great.  For the near term, I suspect many new settings in staging will already exist in some form in DOSBox-X (ie: MT-32, 3dFX/Voodoo, ... ) so when the time comes to add it, that will be a good time to coordinate with you and see if there's a fit (and perhaps it might cooincide with you refactor across another release.. ).  I'm getting ahead of myself!

@dreamer, curious what you think!

**Comment by joncampbell123** [comment]
As long as all the options remain in DOSBox-X, that's fine. I don't expect DOSBox SVN and staging to carry over all the options.

Remember all the options are there either as hacks and adjustment for demoscene stuff or for retro developers to test their code against various configurations.

**Comment by Wengier** [comment]
@joncampbell123 Of course! DOSBox-X features a flexible configuration, which is useful as a full emulator. Config options are only added to it (occasionally modified), but none of them are ever removed I believe.

**Comment by Wengier** [comment]
And this feature makes DOSBox-X useful for **both** normal and advanced users. For advanced users they can do whatever they want with the customizable configuration,  and for normal users, DOSBox-X also has a Configuration GUI which makes it easier to use than other DOSBox-X forks. In order to make it even easier to use for non-advanced users, perhaps the Configuration GUI can have two modes: standard modes (showing common options) and advanced modes (showing all options), similar to some other software offers. This will make DOSBox-X a complete DOS emulation package for everyone.
