### ISSUE TITLE
I need 16:10 Aspect Ratio Correction and more features

### ISSUE THREAD

**Issue by skyrain128** [joncampbell123/dosbox-x#1367]
16:10 Aspect Ratio Correction
I use fullscreen mode when I play games.
Rise of the Triad runs at 320x200 resolution, and 16:9 display distorts the game screen.... and 4:3 aspect ratio distorts the screen too...
I REALLY need 16:10 Aspect Ratio Correction for fullscreen
and I need force mouse autolock option.
Original DOSBox has force mouse autolock.
But DOSBox-X doesn't have it :(

**Comment by yksoft1** [comment]
However many displays in that age output 320x200/640x200/640x400 as 4:3 with non-square pixels.

**Comment by skyrain128** [comment]
> However many displays in that age output 320x200/640x200/640x400 as 4:3 with non-square pixels.

But some games like Doom, designed for 16:10 screen.

**Comment by joncampbell123** [comment]
@skyrain128 Did 16:10 monitors even exist back in 1993? Even if so, I doubt the iD Software team would have them back then.

**Comment by skyrain128** [comment]
Someone said 'Doom is designed for 16:10 screen but most of screen was 4:3 at that time' at Doom internet bulletin board. 
[](https://cafe.naver.com/doomguy/6969) (Korean)

**Comment by joncampbell123** [comment]
@skyrain128 It's possible some things look squeezed not because they made the graphics for 16:10 but because the graphics were authored on a system that had square pixels, then converted for use on the non-square pixels of 320x200 mode.

I used to make the same mistake when using Photoshop to make 256-color BMPs to load into DOS programming experiments back in the day.

https://en.wikipedia.org/wiki/Development_of_Doom
