### ISSUE TITLE
windows build faild on Visual Studio 2019 version 16.5

### ISSUE THREAD

**Issue by yxmline** [joncampbell123/dosbox-x#1453]
**Describe the bug**
xbrz.cpp
fatal error C1605 Compiler limit: object file size cannot exceed 4 GB
fatal error LNK1257

OS:WINDOWS 10
RAM:20GB
MSVC toolset versions 14.25
MSC_VER 1925

**Comment by joncampbell123** [comment]
Oh come on Microsoft, there aren't *that* many templates in that code.

That looks like a screw-up that a solution clean + rebuild might take care of.

**Comment by Allofich** [comment]
I can confirm this issue.

> That looks like a screw-up that a solution clean + rebuild might take care of.

Unfortunately, that doesn't fix it.

Someone else recently reported this same issue, then closed it because they had a workaround of building with an older version of Visual Studio.

https://github.com/joncampbell123/dosbox-x/issues/1444

I experimented with xbrz.cpp, and even if all 4 of the xbrz files are completely erased of contents, the same error still happens. Building from the command prompt in Visual Studio, however, gave the "object file size cannot exceed 4 GB" for a different file, sdlmain.cpp, so maybe something in there is causing the issue.

I also found someone mentioning what may be the same or a related issue:
https://developercommunity.visualstudio.com/content/problem/893951/new-fatal-error-c1002-compiler-is-out-of-heap-spac.html

A response from a Microsoft developer there was:

"The fix is likely targeted to be in VS 2019 16.7. In the meantime, as you’ve noted, there are some cosmetic workarounds such as avoiding the overloaded nested-type-and-data-member name (i.e. naming one of the something different), or also you can move the type definition to be adjacent to the data member, or vice versa."

So, if someone can figure out the appropriate workarounds, that may be one option. Otherwise, downgrade to a an earlier version than 16.5, or wait until 16.7 is out, and hopefully 16.7 will fix the issue.

**Comment by joncampbell123** [comment]
I'll remember not to upgrade to 16.5 then. My version is still 16.4.5 which seems to be able to compile DOSBox-X perfectly fine.

**Comment by yxmline** [comment]
thks

**Comment by Allofich** [comment]
We have a workaround for this now and latest VS2019 should build.
