### ISSUE TITLE
Some config -get commands crash DOSBox-x

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1458]
In current code (as of March 28), built for SDL1, some "config -get" commands cause DOSBox-X to crash, and some give false responses.

**To Reproduce**
1. Build DOSBox-X for SDL1 in Visual Studio
2. Launch DOSBox-X
3. Enter this command:

`config -get "int15 mouse callback does not preserve registers"`

4. DOSBox-X quits without an error message.

The same thing occurs with some other multiple-word properties.

Other config -get commands seem to misinterpret the first word of the property is the same as the name of the section. For example,

`config -get "dos clipboard device name"`

gives the response: "There is no property clipboard device name in section dos. (Maybe the properties should simply not have the same first word as the name of the sections?)

Also, the command "config -get files" produces the message "false" instead of the actual number of files.

Tested under Windows 10, 64-bit; no conf file.

**Comment by Wengier** [comment]
@emendelson The syntax for config -get commands is:
config -get "section property"

I think you have omitted the "section" ("dos" in this case) part in all your tests, which is why they do not work as expected. If I add "section" in these commands, then they appear to work fine on my computer. For example:

config -get "dos int15 mouse callback does not preserve registers"
Returns "false".

config -get "dos dos clipboard device name"
Returns "CLIP$".

config -get "dos files"
Returns "127".

Hope this helps.

**Comment by Wengier** [comment]
On the other hand, the command (without typing the section name "dos")
`config -get "int15 mouse callback does not preserve registers"`
Returns "Section (null) doesn't exist" on my computer (albeit it won't crash here).

And the command:
`config -get "ide, primary enable"`
Also returns "Section (null) doesn't exist" on my computer, even though there is indeed a section named "ide, primary". Apparently, config -get does not work properly with section names with spaces.

**Comment by Wengier** [comment]
@joncampbell123 I have made a patch that fixes the issues I mentioned above. If the specified section does not exist config -get will now return "Section \<name\> doesn't exist" (where \<name\> is the actual name) instead of "Section (null) doesn't exist", and it will no longer recognize ", " (with a comma before the space) as a separator between section and property if there are further space(s) in the string. So for example:
`config -get "ide, primary enable"`
now returns "true" or "false" instead of "Section (null) doesn't exist" or "Section ide, doesn't exist".

It also fixes the issue that if user inputs span more than one line in the DOSBox-X command shell, keys such as ESC and Backspace were unable to clear user inputs except for the last line.

The diff file for the latest commit 8cf5913 is available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-8cf5913-patch.diff

A pre-compiled Windows 64-bit binary is also available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by Wengier** [comment]
Just want to note that even though "config -get \<section\> \<property\>" only showed "Section (null) doesn't exist" instead of crashing on my Windows system if the specified section did not exist, it did result in "Segmentation fault" when I tested on Linux. My patch posted above will fix the error that resulted in either the "Section (null) doesn't exist" error message or crashing.

**Comment by emendelson** [comment]
Thank you, Wengier. The odd thing is that you can omit the section for some properties but not others. I don't know what the logic is, but it does seem to work, especially if the property name is one word, not more than one.

**Comment by Wengier** [comment]
@emendelson From the source code it looks like the logic is like this: if the argument for config -get is one word, then the argument is considered to be *either* "section" *or* "property" to be retrieved. Otherwise (i.e. if the argument is more than one word such as "dos xms"), then the argument is considered to be "section + property", so the first word is considered to be "section", and the rest is considered to be "property". For example, in the case "dos xms handles", the first word ("dos") is considered to be "section", and the rest ("xms handles") is considered to be "property". There is indeed a difference between the handling of one word and more than one word in "config -get".

**Comment by joncampbell123** [comment]
@Wengier Applying and trying the patch now

**Comment by Wengier** [comment]
@joncampbell123 Yes, as I said in my earlier post "It also fixes the issue that if user inputs span more than one line in the DOSBox-X command shell, keys such as ESC and Backspace were unable to clear user inputs except for the last line". This fix is ported from vDosPlus to make multi-line inputs work in the DOSBox-X command shell.

**Comment by Wengier** [comment]
@joncampbell123 You can see the screenshots below to see more clearly what I meant in my previous post.

Suppose the current user input in the DOSBox-X command shell is now like this:
![image](http://individual.utoronto.ca/wengier/files/img1.png)

And then you press the ESC key, then previously it will only clear the last line, and you will have no way to clear the first line (which is an incorrect behavior):
![image](http://individual.utoronto.ca/wengier/files/img2.png)

But with the fix, the input in both lines will be cleared by pressing the ESC key (as in a real-DOS system):
![image](http://individual.utoronto.ca/wengier/files/img3.png)

Similarly, with the fix the BackSpace and the arrow keys will be able to delete or navigate between characters in the first and second lines, instead of only in the second line.

**Comment by Wengier** [comment]
@joncampbell123 By the way, even though the command shell fix should be considered useful, but I guess it will probably be better to submit it as a separate issue next time.
