### ISSUE TITLE
SDL2  in Windows: Alt-F4 closes without warning

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1460]
Under Windows, DOSBox-X built with SDL2 immediately exits if the user presses Alt-F4 (the Windows Quit key). This happens even if the user is in the middle of using an application or doing anything else, and it happens without warning.

I think this is dangerous behavior, and it can be fixed by editing

vs2015/src/video/windows/SDL_windowsevents.c

and changing line 357 so that it reads:

`return !SDL_GetHintBoolean(SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4, SDL_TRUE); `

instead of SDL_FALSE.

**Comment by sikthehedgehog** [comment]
Pretty sure that the proper fix would be to handle the `SDL_QUIT` event (which takes care of all platform-appropriate shortcuts)… in fact from what I remember SDL2 is not going to do anything on its own if that event isn't handled, so this sounds more like the event is handled but the code is not bothering to do any proper checks.

Mind that I don't recall DOSBox doing any checks either (in fact I often resort to Ctrl+F9 to quit from games that get stuck with no way out and it never prompts me)

**Comment by sikthehedgehog** [comment]
OK decided to check and yeah, it seems to bail out immediately when `SDL_QUIT` is found:
https://github.com/joncampbell123/dosbox-x/blob/df6366f9ee7f7af8cac73207909f2478dfa93eab/src/gui/sdl_gui.cpp#L1478
https://github.com/joncampbell123/dosbox-x/blob/df6366f9ee7f7af8cac73207909f2478dfa93eab/src/gui/sdl_gui.cpp#L1330
https://github.com/joncampbell123/dosbox-x/blob/df6366f9ee7f7af8cac73207909f2478dfa93eab/src/gui/sdlmain.cpp#L1039

(and a bunch more in that last file where `SDL_QUIT` leads to `throw(0);` for some reason)

You probably want to change the handling of `SDL_QUIT` to perform more checks and show a message box if you aren't in the shell (this would also only work if it didn't boot an OS from an image, may be better to always ask instead when doing that).

**Comment by emendelson** [comment]
In my fork I'commented out some of those `throw(0);` lines years ago, presumably to prevent this kind of quitting, but it didn't help in the situation I described in my first post.

**Comment by sikthehedgehog** [comment]
I think the `throw(0);` are there only as a form of assert. The important ones are the lines I linked.

In particular: the ones that set `running = false;` make the main loop quit (which is a `while (running)` loop), meaning they cause DOSBox-X to quit immediately. Not sure what the `KillSwitch(true)` one does, but I imagine it's similar. You probably want to take care of those instead of the `throw`s.

> One reason you don't want to show a message box on Alt-F4 is that many DOS applications use that keystroke for their own purposes, so you want to send the keystroke to the application, and not have to deal with a message box from DOSBox-X.

Which I think is the reason why quit is mapped to Ctrl+F9 in DOSBox… but that one does also have the same issue of quitting without warning, so point stands. If you want to completely nullify Alt+F4 being close, you want `SDL_QUIT` to do absolutely nothing (i.e. the event to go ignored). Note that doing this should also nullify Ctrl+Q in OSX.

One annoying catch is that you probably *do* want it to handle the window close button (as opposed to keyboard shortcuts)… It seems you want `SDL_WINDOWEVENT_CLOSE` for that, though no idea if that also includes shortcuts or not.

**Comment by sikthehedgehog** [comment]
Actually in hindsight I think we're talking about two different problems:

* Alt+F4 shouldn't always trigger the quit command
* Quitting should prompt you first if you're not in the shell

The former can be solved by ignoring `SDL_QUIT` and let the built-in shortcuts do their thing. The latter would require modifying how quitting DOSBox-X works tho (checking if it's "safe" to quit, showing a message box if not).

**Comment by emendelson** [comment]
DOS applications can and do use ALL four states of ALL 12 function keys (unshifted, Shift, Alt, and Ctrl). Absolutely NO keystroke should close DOSBox-X (when not at the shell). 

The close button should NOT close DOSBox when not at the shell. Otherwise, it should display a message but it should not make it possible to close without warning. It's far too easy to click the close button by mistake.

If you're working on a spreadsheet or a word-processing document, the last you thing you want is a keystroke that would close the application without warning.

**Comment by sikthehedgehog** [comment]
> DOS applications can and do use ALL four states of ALL 12 function keys (unshifted, Shift, Alt, and Ctrl). Absolutely NO keystroke should close DOSBox-X (when not at the shell).

Then you're stuck if you're fullscreen (since you presumably also want to have a shortcut that undoes fullscreen, though admittedly Windows gave us Alt+Enter for that purpose so there are likely lots of DOS programs trying to avoid that), or if there isn't a working mouse (hey, I had that issue several times :v), or more likely the mouse is captured (which means you need a way to release it… again, shortcuts).

But yeah, this is precisely why there's a key remapper, so if any shortcut gets in the way you can reassign it to something else (or unmap it, if not needed). You ultimately still have to pick a default tho (which is what's going on with Ctrl+F9 for quit, you can remap it if needed). Sadly the obvious unlikely combinations (Ctrl+Alt+F#, Ctrl+Shift+F#, Alt+Shift+F#) also tend to be hogged by the OS.

**Comment by emendelson** [comment]
Exactly! Yes, the fork that I've been distributing for years uses Alt-Enter to get out of full-screen. And I use Ctrl-Alt-F# for a few other functions. It took a bit of work modifying the code, but it saves users from losing hours of work because they hit the wrong key or the wrong button.

**Comment by Wengier** [comment]
I have added a config option "quit warning" in my latest pull request, which can be set to true, false, or auto. DOSBox-X will always display a warning message if it is set to "true", and will never display a warning if it is set to "false". If set to "auto" (default), DOSBox-X will show a warning message only if at least one file handle is still open. This will make it much less likely to accidentally close the DOSBox-X window if a program is currently running and working with files inside DOSBox-X.

**Comment by Wengier** [comment]
Optional warning messages were already added to the current DOSBox-X version.
