### ISSUE TITLE
Add an option to write-protect a diskette

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1463]
**Is your feature request related to a problem? Please describe.**
Right now there is no way to write-protect a diskette in DOSBox or DOSBox-X. As a work-around, when using image files, you can make the image file read-only in the host system, which will cause DOSBox-X to treat it as write-protected. But it would be easier in some cases if you could just add a mount option to indicate it should be write-protected.

**Describe the solution you'd like**
Something along the lines of:

IMGMOUNT A disk.img -RO
or
MOUNT A . -RO
or
BOOT dos.img -RO

**Describe alternatives you've considered**
As mentioned, making image files read-only seems to have the desired effect, but only works for image files and does not allow you to quickly change it within DOSBox.

**Comment by rderooy** [comment]
Realised that for the IMGMOUNT and BOOT commands, it is not as straight forward as you can specify multiple image files, so you would need to be able to specify it per image.

As an example, there is the MS-DOS 4.0x installer, which will corrupt its own disks if given the chance, but it also requires that you make backup disks during the installation, so you also also need a disk to write to.

So perhaps something like this:
IMGMOUNT A disk1.img -RO disk2.img disk3.img -RO
BOOT disk1.img -RO disk2.img disk3.img -RO

note how in the above example, disk1 and 3 are marked read-only, but disk2 is not.

**Comment by Wengier** [comment]
@joncampbell123 and @rderooy I have made a patch for DOSBox-X that allows the IMGMOUNT and BOOT commands to write-protect disk images by putting a ":" prefix before the image file name. This way the feature is completely compatible with disk swapping. For example:

BOOT :C:\DOS.IMG (with a ':' before "C:\DOS.IMG")

Will boot the image C:\DOS.IMG in write-protect mode.

IMGMOUNT A :disk1.img disk2.img :disk3.img

Will write-protect disk1.img and disk3.img, but not disk2.img.

The patch also adds /A, /AS, /A-S, /AH, /A-H, /AR, /A-R, /AA, /A-A options to the DIR command; DIR /A shows all entries whereas DIR alone shows all except system/hidden ones as in a real DOS system.

The diff file for the latest commit 75e1e4d is available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-75e1e4d-patch.diff

A pre-compiled Windows 64-bit binary is also available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by joncampbell123** [comment]
Why a leading colon? Why not just add another option like --read-only or -ro?

**Comment by joncampbell123** [comment]
The -ro / -read-only option could create the disk image C++ object with a flag to fopen() the image read-only. The read-only file handle then stays read-only as long as the disk image is allocated, even if the pointer to the image is moved in and out of swap disk rotation.

**Comment by Wengier** [comment]
@joncampbell123 I used a leading colon instead of an option like -ro because as rderooy mentioned in his second post, for multiple image files you may need to be able to specify read-only option per image (i.e. individually) instead of making all image files read-only. For example, in the same command you may want to mark disk1 and disk3 as read-only, but not disk2, as mentioned by him. If I use an option like -ro in this case then I have to specify this option more than once, so it is not a regular option like the others. On the other hand, using a leading colon will avoid this problem and make the whole syntax a lot simpler. If we do not have this requirement then an option like -ro will be easier to implement of course.

**Comment by joncampbell123** [comment]
That's OK then.

Just so you know though, filenames in Linux can have literally any byte value in them other than forward slash and NUL.

:diskimage.img is a valid filename in Linux :)

**Comment by rderooy** [comment]
@joncampbell123 Good point about a filename starting with a column is valid on Linux, but you could also have a file named "-ro" :)

**Comment by joncampbell123** [comment]
Files that start with a hyphen is why GNU tools in Linux have the -- switch to disable switch parsing past that point so you can specify the filename.

**Comment by rderooy** [comment]
Perhaps you could specify in the doc that if the first character of the file is a column, you need to specify the filename between quotes. e.g. :":filename.dsk"

**Comment by Wengier** [comment]
@joncampbell123 and @rderooy The handling of quotes is done separately; it is possible to the change that behavior but will require some work. Instead, for the patch I have added a new config option "leading colon write protect image" (default: true) in the [dosbox] section which will disable or enable the behavior for BOOT and IMGMOUNT to treat the leading colon as a marker for write-protecting images, and you can change this behavior as you want (if disabled it will be considered part of the filename as before).

Suppose "leading colon write protect image" is currently enabled. If there is indeed an image file name starting with a colon in Linux, and you do not want to write-protect it, you can temporarily disable the "leading colon write protect image" config option, e.g. 

config -set "dosbox leading colon write protect image=false"
imgmount a :disk.img
config -set "dosbox leading colon write protect image=true"

Note that I fixed "config -set" as part of the patch to make this work.

By the way, with "leading colon write protect image" enabled, if you do want to write-protect an image file name starting with a colon in Linux, you can just put the ":" prefix as usual, e.g. "BOOT ::disk.img" to boot the image file named ":disk.img" in write-protect mode.

The new diff file for the latest commit 75e1e4d is still available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-75e1e4d-patch.diff

**Comment by Wengier** [comment]
@joncampbell123 I made some small cleanups to the MOUNT and IMGMOUNT commands in the patch. For example, "MOUNT /?" will now show its options such as -nocachedir (no caching drive), -ro (read-only mode) and -u (unmount drive). Previously the help message for MOUNT did not show any options. Also, "IMGMOUNT /?" will now show its usage just like "IMGMOUNT -?" instead of showing the error message "Must specify drive letter to mount image at" (which is apparently unexpected).

I think I have finished the patch for now. MOUNT, IMGMOUNT and BOOT commands as mentioned by rderooy now all support the write-protect (or read-only) feature, along with the new config option "leading colon write protect image" to disable or enable the behavior for BOOT and IMGMOUNT commands to treat the leading colon as a marker for write-protecting images, and some enhancements to DIR and CONFIG -set commands as mentioned earlier.

The diff file for the latest commit 75e1e4d is located at:
http://individual.utoronto.ca/wengier/files/dosbox-x-75e1e4d-patch.diff

**Comment by joncampbell123** [comment]
Patch applied, with some additional changes and comments.

**Comment by rderooy** [comment]
Something strange when a disk is write protected with the integrated DOS.
doing something like:
echo foo > file
works fine on a disk not write protected, but doing it on a write-protected disk will cause it to echo to the console. Likewise it will also echo it to console if the drive does not exist.

Disk a: is write-protected in these examples and Disk b: is not.

Running a guest OS:
![guest os_000](https://user-images.githubusercontent.com/17701098/79119073-c230e100-7d8f-11ea-94f1-404cd155c18c.png)

Running the integrated DOS:
![command_003](https://user-images.githubusercontent.com/17701098/79119122-e260a000-7d8f-11ea-8c80-8d291dcb859c.png)

**Comment by Wengier** [comment]
@rderooy This is actually *expected* considering how piping is currently implemented in DOSBox-X. For example, you will get this result on *any* read-only drives, including the internal drive Z:, e.g.

echo foo > z:file

Will behave this way too, even with the earlier 0.83.0 release. So it is a completely separate issue. I would recommend you to close this issue and then open a separate issue for that.

**Comment by Wengier** [comment]
@rderooy In any case, I have fixed the redirection issue as part of the patch I posted in Issue #1474. Now it will show the error message "File creation error" in that case (as in real DOS) instead of bypassing the redirection altogether.

**Comment by Wengier** [comment]
I have already open a new issue for the redirection updates and support for pipes, see Issue #1476.
