### ISSUE TITLE
ERROR IOCTL:DOS:IOCTL Call 0D:40 Drive 0 unhandled

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1467]
**Describe the bug**
As mentioned in https://github.com/joncampbell123/dosbox-x/issues/1466 running LOADDSKF in DOSBox-X to write a DSKF format disk to a diskette image fails.

**To Reproduce**
In the directory where I have a DSKF file and LOADDSKF.EXE, I start DOSBox-X.
MOUNT C .
IMGMAKE fdd.img -t fd_1440
IMGMOUNT A fdd.img
LOADDSKF 144US1.DSK A:
Target disk is wrong format

Expecting 2 side(s) - 80 tracks - 18 sectors per track
LOADDSKF 144US1.DSK A: /F

Disk error 0001 00 01 00 0000 00

**Expected behavior**
Being able to convert a DSKF file to regular MFM DSK.

**Environment (please complete the following information):**
- DOSBox-X 0.83.0
- Fedora 31
- Tried setting every possible option under [fdc, primary], but it made no difference.

**Additional context**
The second command (with /F flag) causes an error to get logged:
LOG: Identified 'fdd.img' as C/H/S 80/2/18 512 bytes/sector
LOG: FAT: BPB says 18 sectors/track 2 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT12 with 2847 clusters
LOG: 430184269 ERROR IOCTL:DOS:IOCTL Call 0D:40 Drive 0 unhandled

**Comment by Wengier** [comment]
With the patch in pull request #1491 to fix the FORMAT.COM crash, LOADDSKF should now also go further in DOSBox-X as follows:

MOUNT C .
IMGMAKE fdd.img -t fd_1440
IMGMOUNT A fdd.img
LOADDSKF 144US1.DSK A:

``        Drive A         1.44M``

``This diskette is about to be overwritten.``
``Be sure it contains no data that you want to keep!``
``Also check to be sure the diskette presently``
``installed in the drive is the correct type.``

``Press "Y" to continue, any other key to cancel.``

If you press the Y key, then the following error message will be shown:

``Error while writing the disk data``

And it will return to DOS.

This is currently expected because the required low-level function to perform this operation is not yet implemented in DOSBox-X (it might be implemented in later versions).

**Comment by Wengier** [comment]
@rderooy With the latest code I believe the "LOADDSKF 144US1.DSK A:" command already works as expected.

**Comment by rderooy** [comment]
@Wengier I just tried it, and indeed it work. Thanks for pointing it out!
