### ISSUE TITLE
Paratrooper game missing helicopter/airplane sound

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1492]
**Is your feature request related to a problem? Please describe.**
Paratrooper, a early PC game published in 1982.
https://www.mobygames.com/game/pc-booter/paratrooper

This game when run on an actual IBM PC as shown here:
https://www.youtube.com/watch?v=krb4ave2_Mg

Produces helicopter and airplane sound, but not when played in any emulator.

This was reported on Vogons, and user ripsaw80 had a look at it, and had this to say:
"For the helicopter sound, the game alternates between square wave counter values of 1 and 2, which are not audible frequencies, but just the re-programming of the timer counter value apparently causes a subtle noise. I suppose it could be considered an undesirable artifact, like the "snow" effect seen on old CGA hardware, but the game is making use of it and DOSBox does not emulate it."
https://www.vogons.org/viewtopic.php?t=73347

**Describe the solution you'd like**
Not sure if emulating this makes sense. If it is to be emulated, perhaps it should be behind an option to prevent unwanted effects on later games.

**Comment by sikthehedgehog** [comment]
I wouldn't call it inaudible, basically the game is relying on the speaker making "clicks" whenever it switches position (you know when a sample is cut off away from the middle and there's a pop? exactly the same effect).

Now, that's something that *should* work as-is (assuming PC speaker is properly emulated rather than only when the timer is used)… but this method was also sometimes abused for PWM to play sound with more than 1-bit resolution. Is there any code specifically to handle that case? Because I could see that interfering and failing to account for mere clicks.

Also again, not emulating PC speaker when timer is not in use also would do it, but I suppose DOSBox-X does better than that… right?

**Comment by joncampbell123** [comment]
It should be emulated, the question is how to implement it, and writing code in DOSLIB to do to the PIT what Paratrooper is doing.

Now as far as I know, writing the mode byte of a timer causes it to stop and reset to a known state depending on the mode. So if it is changing between mode 1 and 2, it is relying on the PIT reverting to initial states of each mode and then running.

I will add debug code to DOSBox-X right now to see what it is writing.

**Comment by joncampbell123** [comment]
Paratrooper writes the mode byte only ONCE at startup.

   1096783 ERROR PIT:port 43 B6

After that, all sound effects are just 16-bit (two 8-bit) writes to port 42h to change the counter.

However what is probably preventing this from working is that DOSBox-X inherits DOSBox SVN's performance optimization of enforcing a minimum counter value (one that is well above audible range) so that very small values do not bog down PC speaker emulation.

I see Paratrooper's helicopter noises are made by alternately writing counter=1 and counter=2.

  10876253 ERROR PIT:port 42 write:1 state:3
  10876255 ERROR PIT:port 42 write:0 state:0
  10891577 ERROR PIT:port 42 write:2 state:3
  10891579 ERROR PIT:port 42 write:0 state:0
  10906868 ERROR PIT:port 42 write:1 state:3
  10906870 ERROR PIT:port 42 write:0 state:0
  10922240 ERROR PIT:port 42 write:2 state:3
  10922242 ERROR PIT:port 42 write:0 state:0
  10937750 ERROR PIT:port 42 write:1 state:3
  10937752 ERROR PIT:port 42 write:0 state:0
  10953148 ERROR PIT:port 42 write:2 state:3
  10953150 ERROR PIT:port 42 write:0 state:0
  10968537 ERROR PIT:port 42 write:1 state:3
  10968539 ERROR PIT:port 42 write:0 state:0
  10984021 ERROR PIT:port 42 write:2 state:3
  10984023 ERROR PIT:port 42 write:0 state:0
  10999379 ERROR PIT:port 42 write:1 state:3
  10999381 ERROR PIT:port 42 write:0 state:0

So while either frequency is too high to hear, switching between them should make an audible click. DOSBox-X enforces a minimum count based on the PC speaker sample rate setting in dosbox.conf which these values are limited to, so, no noise.

**Comment by joncampbell123** [comment]
The way the PC speaker queue is implemented right now makes emulating clicks caused by sudden frequency change non-trivial to implement at this time, however I have an idea I've been going over for a few weeks on how PC speaker emulation could be rendered 100% accurately without too much of a performance drop. It's basically synthesizing a 1.1MHz 1-bit audio output with some lookup tables and basic filtering to decimate it down to audio sample rates.

**Comment by joncampbell123** [comment]
The plan is the rewrite will be done as an alternate mode you can turn on so that in the meantime the "good enough" emulation is still available. When the new mode proves itself, it eventually becomes default. When  it can do everything the current implementation does but better, then the old code is removed.

**Comment by joncampbell123** [comment]
But enough perfectionism... you want an audible click to happen if Paratrooper switches between count=1 and count=2? I could add that as a hack in the meantime. If the counter value is below minimum_counter, add a PIT event that causes a click.

**Comment by joncampbell123** [comment]
Hey wait a minute... doesn't mode 3 of the 8254 count down by 2 in order to do each half of the square wave?

So... wouldn't count=1 cause a square wave with one cycle counting from 65536 and the other 1?

**Comment by joncampbell123** [comment]
According to this, Paratrooper should make noise because N=1, (N - 1) / 2 = 0 (and therefore 65536) and (N + 1) / 2 = 1.

**Comment by joncampbell123** [comment]
Pulling out the trusty old 486 laptop... PIT timer 2, mode 3, count=1 does indeed generate a low frequency square wave. That's what Paratrooper is relying on here.

**Comment by joncampbell123** [comment]
If you can compile from source, try Paratrooper with the latest build. The PC speaker emulation sounds at least very close to the video now.

**Comment by rderooy** [comment]
I compiled the latest source, and indeed I now get sound. Thanks!
