### ISSUE TITLE
Documentation: How to disable ALT+ENTER SDL mapper shortcut to make Windows ALT+ENTER usable

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#152]
I've got Windows 98 SE running as a VM in dosbox

I've somehow set the command prompt window to be fullscreen, and the usual keyboard shortcut alt+enter just maximizes dosbox instead.

any idea how to get the Windows 98 command prompt back to windowed mode?

**Comment by joncampbell123** [comment]
Bring up the SDL mapper (CTRL+F1 or CTRL+SHIFT+F1 on Linux), click on the "fullscreen" button, and delete the mapping. That makes sure that only Windows within responds to ALT+ENTER.

**Comment by sikthehedgehog** [comment]
I would suggest changing the mapping rather than disabling it, otherwise you'd get stuck in fullscreen in DOSBox instead =P

And as for Windows: I'm pretty sure there's a button in the toolbar that makes it fullscreen. But yeah, the shortcut is the only way out (actually I'm not sure if alt+tabbing out of the program lets you unfullscreen it, but again, conflict with the host OS)

**Comment by joncampbell123** [comment]
From what I know about Windows, yes, you can ALT+TAB out of a DOS box.

Any suggestions for a new mapping?

**Comment by sikthehedgehog** [comment]
Ctrl+Enter?

I'm not suggesting to change the default mapping though (most people are not going to be running programs where Alt+Enter is relevant), just saying that disabling the mapping completely is a bad tip for precisely the same reason it's trying to work around.

**Comment by toddfraser88** [comment]
that fixed it

thanks very much.

**Comment by joncampbell123** [comment]
The default mapping in the latest DOSBox-X no longer assigned ALT+ENTER by default.
