### ISSUE TITLE
Crash when mounting a single-quoted path

### ISSUE THREAD

**Issue by UltraHex** [joncampbell123/dosbox-x#1535]
**Description**
MOUNT crashes DOSBox-X when the path is enclosed in single-quotes.

**To Reproduce**
run: MOUNT C 'C:'

**Expected behavior**
Mount the directory. (or at the very least don't crash the application)

**Environment**
 - OS: Windows 10
 - Version: 0.83.1 x64 SDL2 (also tested 0.83.0 x64 SDL2)
 - Config: default

**Additional context**
Needed for compatibility with LaunchBox.

**Comment by Wengier** [comment]
I already found this issue and fixed the crash a few days ago. Instead, it will show the error message:

Cannot create PhysFS drive.

You can try build the current code too.

**Comment by UltraHex** [comment]
Just built the current version and noticed the error message. Is anyone planning to get single-quotes working?

**Comment by Wengier** [comment]
Use the double quotes instead of single quotes for this (and other places too). Direct support for single quotes requires changes to the basic command-line handling function that will affect a lot of places in the code.

**Comment by UltraHex** [comment]
**Temporary Workaround for LaunchBox**
Create a batch script to replace single-quotes with escaped double-quotes like this:
```batch
set v_params=%*
set v_params=%v_params:'=\"%
call dosbox-x.exe %v_params%
```

**Comment by Wengier** [comment]
Since LaunchBox only works in Windows, I think this issue can be worked around - for Windows platform DOSBox-X can treat the following as a special case instead of treating it as a PhysFS drive (which is not supported anyway) and throwing an error:

If the path given is in this exact format: ```'X:\...'```, where X is the drive letter (A-Z), then remove the opening and closing single quotes if it is the Windows platform. This will allow for example the command below to work:

```MOUNT C 'C:\DOS'```

Since X:\ is apparently the drive letter in Windows, I think this will solve the issue with LaunchBox, while not causing any negative effects.

**Comment by Wengier** [comment]
For reference, there was a previous discussion in Issue #770. It is still recommended to use double quotes instead of single quotes in such case, but a workaround was provided above to LaunchBox which is mainly designed for the Windows platform anyway.
