### ISSUE TITLE
Music from Sound Blaster 16 sounds incorrect in Aladdin

### ISSUE THREAD

**Issue by maximus105** [joncampbell123/dosbox-x#1537]
**Describe the bug**
Music from Sound Blaster 16 sounds incorrect in Aladdin.

![86Box_2020_05_08_18_01_00_017](https://user-images.githubusercontent.com/58270614/81499321-73656100-92d3-11ea-8f80-97beef70197f.png)

If you set the sound settings in setsnd.exe, as in the screenshot, then the music in the Aladdin game sounds as if it were mono. Although, with the same settings in DOSBox-Staging v0.75.0, DOSBox ECE r4338, DOSBox SVN-Daum, the music sounds stereo (you can clearly hear the music flowing from the left speaker to the right and vice versa).

**To Reproduce**
1. In the folder with the game Aladdin, run setsnd.exe and set the following settings:
Sound card: Sound Blaster Pro
Play enhanced music: Yes
I/O address: 220
IRQ number: 7
DMA channel: 1
2. Launch aladdin.exe and listen to how the music sounds.

**Environment (please complete the following information):**
 - Windows 10 x64
 - DOSBox-X 0.83.1 x64 SDL2
[cpu]
cycles = 40000
[sblaster]
sbtype = sb16
sbbase = 220
irq = 7
mindma = -1
irq hack = none
dma = 1
hdma = 5

**Comment by joncampbell123** [comment]
Is Aladdin's "enhanced music" rendered with FM synthesis or "wavetable synthesis" through the DSP?

The reason I ask is that DOSBox-X emulates SB16 behavior, in that SB16 cards ignore the Sound Blaster Pro stereo bit. The only way to get stereo PCM playback on SB16 is to use the new DSP commands. A side effect of this is that games written for Sound Blaster Pro stereo (unaware of SB16 hardware) play in mono on SB16 hardware and in emulation. This is confirmed behavior from real SB16 cards.

Assuming that is the issue here, you will need to set sbtype=sbpro2 to get stereo sound with the game.

**Comment by joncampbell123** [comment]
To clarify my previous comments, if you are running with sbtype=sb16, you are not going to get stereo audio if you tell the game you have a Sound Blaster Pro because of the differences mentioned between SBPro and SB16. Either select option (2) which is Sound Blaster & AWE32 or set sbtype=sbpro2 and select option (3).

**Comment by rderooy** [comment]
Just curious, you say Pro 2, but how do you really know it is not Pro 1 (dual OPL2)?

The soundcard setup shows it a "Sound Blaster Pro", which I typically assume to be the Pro 1.

In any case, I did try it with DOSBox-X, with sbtype=sbpro1 and sbpro2 and I got stereo in both cases.

**Comment by maximus105** [comment]
You can still get stereo if you install in setsnd.exe:
Sound card: (3) Sound Blaster Pro
And in DOSBox-X:
sbtype = ess688

**Comment by rderooy** [comment]
@maximus105 why would you set sbtype=ess688 when you can set sbtype=sbpro1 or sbpro2 and it will work fine?

**Comment by joncampbell123** [comment]
sbpro2 gets you OPL3 music, if that helps anything, and sbpro1 gets you OPL2 instead.

SBPro and SB16 differ in how you enable stereo PCM. Apparently when Creative made the SB16 they forgot to support the bit in the mixer register that you set to get stereo PCM.

**Comment by maximus105** [comment]
> @maximus105 why would you set sbtype=ess688 when you can set sbtype=sbpro1 or sbpro2 and it will work fine?

It seems to me that sbtype = sbpro1 & sbpro2 sound muffled. At sbtype = ess688, the music sounds cleaner.

**Comment by rderooy** [comment]
@joncampbell123 regarding option 2 "Sound Blaster & AWE32", I tried that in combination with sbtype=sb16, and I loose stereo separation. Not sure if it would behave the same on a real SB16 though. The LOG does not show any messages.

I find the "Sound Blaster & AWE32" a curious option. the original SB types were mono, so it is strange to see it paired with the AWE32.

**Comment by rderooy** [comment]
@maximus105 would perhaps have to record the output of both sbpro[1,2] and ess688 and compare it in audacity to be sure, but to me it seems the volume level of the ess688 is just set a bit higher by default. Something you can adjust with the "mixer" command in your dosbox [autoexec] section. e.g.

mixer.com master 140:140

**Comment by joncampbell123** [comment]
sbpro1 and sbpro2 are muffled because there is yet an unanswered question whether or not the initial state of the mixer "filter" (lowpass) bit at hardware reset,

Currently DOSBox-X assumes it is 0 (filter enable). I haven't yet checked whether it is 1 (bypass) or not. That's why it is muffled. SB Pro aware games sometimes know about the bit and set the bypass for clearer audio.

**Comment by joncampbell123** [comment]
There is a dosbox.conf/dosbox-x.conf setting to control the initial state of that filter bit if you want the lowpass filter disabled at startup.

**Comment by joncampbell123** [comment]
@rderooy The issue at hand is the "filter" bit on SB Pro cards. I do not yet know the initial hardware state, so it is "on" by default in DOSBox-X. The "filter" bit appears to control whether audio is passed as-is from the DSP or filtered through a lowpass filter (presumably to reduce the grungy metallic sound of low sample rates).

**Comment by joncampbell123** [comment]
SB Pro mixer register 0x0E which controls stereo and filter:

The Output register determines whether to output sound in stereo or mono, in
stereo two bytes must be sent for each sample, the first one goes to the left
channel and the next one goes to the right. This register allows you to
bypass the output filter.

              Index = 0Eh
              ┌───┬───┬───┬───┬───┬───┬───┬───┐
              │ 7 │ 6 │ 5 │ 4 │ 3 │ 2 │ 1 │ 0 │
              └───┴───┴───┴───┴───┴───┴───┴───┘
                        │               │
           ┌────────────┴──────────┐ ┌──┴─────────┐
           │ DNFI                  │ │ VSTC       │
           │ 0 - Use O/P Filter    │ │ 0 - Mono   │
           │ 1 - Bypass O/P Filter │ │ 1 - Stereo │
           └───────────────────────┘ └────────────┘

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Sound%20and%20Music/Creative%20Labs/Sound%20Blaster/Programming%20the%20SoundBlaster%20Pro%2etxt

**Comment by maximus105** [comment]
I got the sound of stereo music with sbtype = sb16 and in setsnd.exe:
Sound card: (3) Sound Blaster Pro
when installed in DOSBox-X
stereo control with sbpro only = false
And the music sounds clean, just like in DOSBox-Staging v0.75.0, DOSBox ECE r4338, DOSBox SVN-Daum.

**Comment by joncampbell123** [comment]
I just tested a CT1600 Sound Blaster Pro 2, and it seems the initial hardware state has the lowpass filter enabled (bit 5 is clear). So if the game does not clear that bit, then the audio is a bit muffled (lowpass filter) just like real Sound Blaster Pro hardware.

**Comment by joncampbell123** [comment]
This is a dump of the mixer registers on a CT1600 after hardware and mixer reset.

Notice that only registers 0x00-0x0F exist and there is some bizarre mirror of them 0x10-0x3F, 0x40-0xFF correctly read 0xFF.

Also register 0x0E is mirrored in register 0x0F, 0x1E, 0x1F for some reason.

Also register 0x0E only allows changing bits 1 and 5, which means the mixer register can only be one of four values: 0x11, 0x13, 0x31, 0x33.

**Comment by joncampbell123** [comment]
Register 0x0E is also mirrored on read from 0x00, 0x01, 0x10, 0x11 even though writing them resets the mixer as documented.

**Comment by joncampbell123** [comment]
sbtype=sbpro2 and option (3) Sound Blaster Pro produces stereo music as expected. It also sounds like the game knows to turn off the lowpass filter.

sbtype=sb16 isn't going to produce Sound Blaster Pro stereo as expected because SB16 cards do not pay attention to that bit in the mixer. DOSBox-X emulates real SB16 behavior. Funny enough most SB clones implemented it properly :)

**Comment by joncampbell123** [comment]
sbtype=sb16 and the Pro option (3) produces scratchy sounding audio as expected, because it's rendering interleaved stereo PCM that isn't being interpreted as stereo (like real hardware). That's correct emulation. That's what real SB16 hardware apparently does.

sbtype=sb16 and the Sound Blaster (2) option produces monural audio.

Perhaps this game predates proper SB16 support, and enough clone cards were on the market so that it didn't really matter. Run the game with sbtype=sbpro2 and it will work and sound as it should.

**Comment by joncampbell123** [comment]
If you insist on sbtype=sb16, there is the dosbox.conf option to allow SB Pro stereo anyway (as other branches do), but it's not the default because DOSBox-X prefers to accurately emulate the original hardware.
