### ISSUE TITLE
config -all -wcd still writes to wrong location

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1596]
**Describe the bug**
With the new default config directory, I was expecting config to write to it. But it does not.

```
config -l
DOSBox-X 0.83.2 configuration directory:
/home/robert/.config/dosbox-x/
```

But running ```config -all -wcd``` still writes to ~/.dosbox

**Comment by rderooy** [comment]
Actually, it seems -wcd no longer writes to the config directory, but rather the current directory.

**Comment by rderooy** [comment]
I also think config -wcd should print the path where it wrote the file.
```
config -all -wcd
Writing config file dosbox-x-0.83.2.conf
```

The help for ```config``` states for the -wcd option
```
-wcd
 Write to the default config file in the config directory
```

It is also very sensitive to the order of the options.
```config -all -wcd``` functions different then ```config -wcd -all```

**Comment by Wengier** [comment]
I have fixed both issues with the "config -wcd -all" command, i.e. , the issue that it writes to the current directory instead of the config directory, and the issue that "config -wcd -all" does not work the same way as "config -all -wcd".

As for the config -wc or -wcd options, it will indeed print out the path of the file written, if the path is anything other than the current directory. If there is no directory mentioned, then it means that it writes to the file in the current directory.

**Comment by rderooy** [comment]
@Wengier 

One more issue with writing the default config file. If the directory does not yet exist, you will get an error.

![command_000](https://user-images.githubusercontent.com/17701098/82987111-4dd89700-9ff7-11ea-9034-2855ad2b318b.png)

After manually creating the directory, it succeeds.

**Comment by Wengier** [comment]
@rderooy In my pull request #1604, I added the ability to auto-create the ~/.config/dosbox-x directory if it does not yet exist. For now I will assume the parent directory already exists.

**Comment by rderooy** [comment]
I think the ~/.config directory should exist in most cases, at least with the Gnome and KDE desktops for sure, and lots of Linux applications use it as it is the default directory as defined by XDG, so I'm reasonably sure other desktop environments should also have it.
