### ISSUE TITLE
Patch to add EMS subfunctions 52h and 59h

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1618]
**Is your feature request related to a problem? Please describe.**
I'm working on some other stuff right now. So not sure when I will get around to it, but:

https://www.vogons.org/viewtopic.php?f=32&t=74254

**Comment by joncampbell123** [comment]
May also help:

http://hackipedia.org/browse.cgi/Computer/Operating%20Systems/MS-DOS/EMS,%20Expanded%20Memory

**Comment by Wengier** [comment]
I had a look at the patch. It is pretty small and simple, and since it only implements the missing subfunctions of the existing EMS feature, but not to add any new features and also it apparently won't break existing things, I have included it as part of my pull request #1617. But even so from this point on my pull request will no longer include such improvement, but only pure bug fixes.
