### ISSUE TITLE
[FR] save / load state

### ISSUE THREAD

**Issue by ildar** [joncampbell123/dosbox-x#166]
pull from http://ykhwong.x-y.net/

**Comment by joncampbell123** [comment]
I'm not interested in savestate type code at this time only because of the organizational changes going on in DOSBox-X that would constantly break your save states. The code in this fork of DOSBox-X has changed a lot from the last time I merged code from Ykhowng's fork, I doubt the merge would work.

I suggest that if save/load state support is your interest, that you maintain your own parallel branch of DOSBox-X where you can develop it to your heart's content and cautiously merge DOSBox-X changes when you think it's appropriate to do so. I have focus at this time on sound cards, BIOS/kernel fixups, and some organizational changes related to how ISA/PCI devices register and respond to I/O and memory-mapped I/O.

**Comment by Corak667** [comment]
ref: https://github.com/joncampbell123/dosbox-x/issues/246

**Comment by joncampbell123** [comment]
Save/load state handling has been implemented since this issue was opened, though it's very basic at this time.
