### ISSUE TITLE
Make HX DOS script needs some fixup

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1705]
@Wengier has taken the time to update the script so that the ZIP contains a self-contained HX-DOS environment, however some paths need correction before using it to release DOSBox-X.

**Comment by Wengier** [comment]
@joncampbell123 I noticed that the latest version (0.83.3) won't work with HX DOS Extender because of a missing import in HX-DOS's USER32.DLL (version 0.83.2 did work however), so need to do a minor change in the DOSBox-X code in order to make it work with HX DOS Extender.

**Comment by Wengier** [comment]
@joncampbell123 I tried with the official release packge, i.e. dosbox-x-mingw-hx-dos-20200630163326.zip

**Comment by Wengier** [comment]
I have already made a pull request to fix this, along with minor change to the build script and included README.TXT file.

**Comment by joncampbell123** [comment]
I just fixed the script and posted an updated HX-DOS binary. It seems to work, at lest in a Windows 98 VirtualBox instance running in pure DOS mode. Apparently 64MB is not enough though.

**Comment by joncampbell123** [comment]
I also need to figure out how to modify the "stub" it attaches so that it can sense whether or not it's running under actual Windows. Somewhere in the stub there is a direct call to INT 31h which happens to work from Win32 in Windows 98 (yes, it does run in the Windows 98 desktop environment!) but causes a crash in Windows XP. The executable is intended for HX-DOS, of course, but prior to the stubbing the executable at least ran under XP.

**Comment by Wengier** [comment]
@joncampbell123 Great! I can confirm it works too. The VER command for this build shows "0.83.4" instead of "0.83.3" though.

**Comment by Wengier** [comment]
DOSBox-X.exe as in this full package does not run on Windows 10 etc because the included WINMM.DLL file is not compatible with these Windows versions (it will run if this file is renamed). But I think this is in fact a good result - some users may attempt to run the HX DOS builds in these Windows versions even though they are in fact made for the HX DOS Extender environment. As a result, they will encounter various problems such as getting stuck in full-screen mode and not able to adjust the options in the menus, and even complain about them, as we have already seen in Issue #1663.

**Comment by Wengier** [comment]
@joncampbell123 I just tried it in Windows XP, and it is the same -- dosbox-x.exe as in this package will run in Windows XP if you rename the WINMM.DLL file. If you prefer, it is possible to modify PELOAD.ASM (one of the source files of HX DOS Extender) to redirect WINMM.DLL to a different name (just like KERNEL32.DLL=>DKRNL32.DLL, USER32.DLL=>DUSER32.DLL etc) so that it will run in Windows XP in this case, though it will still encounter various issues such as stuck in full-screen mode etc.

Regarding VER showing "0.83.4" instead of "0.83.3" in this build, as I said earlier it is not a issue at all,
