### ISSUE TITLE
DOSBox-X Git (2016/02/23) has a bug

### ISSUE THREAD

**Issue by win3200** [joncampbell123/dosbox-x#173]
I tried to change mode "hercules"

and press F11 button

but can not change amber/whiie/green

Did it test?

**Comment by joncampbell123** [comment]
Type CTRL+F1 or CTRL+SHIFT+F1 to bring up the mapper. Check to see what key is bound to that function.

**Comment by aybe** [comment]
TODO the original FAQ lacks these kind of usability details, add and close

**Comment by joncampbell123** [comment]
Hm, before I can document the shortcut, I need to resolve the issue that the shortcut is there, but not shown in the mapper interface.

**Comment by joncampbell123** [comment]
The design of the mapper UI is apparently based on whatever mapper handlers were registered at the time MAPPER_Init() is called. Some code, such as the VGA/EGA/Hercules emulation, registers more mapper handlers after the fact which is why they don't show up.

**Comment by joncampbell123** [comment]
I added code so that MAPPER_AddHandler() adds the new buttons to the UI even after MAPPER_Init().

The only remaining issue is that if you change the bind through the mapper UI and save, your saved bind makes it to the mapper file, but does not get loaded back when you restart. It gets forgotten.

I think I can resolve that too...

**Comment by joncampbell123** [comment]
I just fixed that now as well.

**Comment by joncampbell123** [comment]
Confirmed that when machine=hercules this fix allows F11 to change the Hercules color palette.
