### ISSUE TITLE
dosbox-staging Copyright stripped and replaced with DOSBox-X

### ISSUE THREAD

**Issue by kcgen** [joncampbell123/dosbox-x#1752]
**commit 207a2a0**, titled **updated info** added the DOSBox-X team as the copyright owner and by extension, the authors of the `flac.c` and `mp3.cpp` files - despite not authoring those files.

Even worse, this commit **removes the dosbox-staging team as the copyright holder and author.**

I'm not sure what's going on here - but I hope it was an accident of the author and an oversight by whoever merged this change.

If this is fair play, then lets edit out Lucasfilm and Disney as the copyright owners of Star Wars, and claim it as our own.
Tongue in cheek aside.. let's not treat eachothers' works like this, likewise for content from the DOSBox team or other tangential projects - we're all after the same common goals!  Thanks.

``` diff
[02:50:59@hoya dosbox-x] (master *%) git show 207a2a029748cab964d187935eaa4244ad921f8a
commit 207a2a029748cab964d187935eaa4244ad921f8a
Author: Wengier <wengierwu@yahoo.com>
Date:   Sun Jun 7 18:21:48 2020 -0400

    updated info

diff --git a/src/libs/decoders/flac.c b/src/libs/decoders/flac.c
index 588410f..b50a2c4 100644
--- a/src/libs/decoders/flac.c
+++ b/src/libs/decoders/flac.c
@@ -3,7 +3,7 @@
  *
  *  Copyright (C) 2001-2017  Ryan C. Gordon <icculus@icculus.org>
  *  Copyright (C) 2018-2019  Kevin R. Croft <krcroft@gmail.com>
- *  Copyright (C) 2020-2020  The dosbox-staging team
+ *  Copyright (C) 2020-2020  The DOSBox-X project
  *

 diff --git a/src/libs/decoders/mp3.cpp b/src/libs/decoders/mp3.cpp
index d62ce86..6076cea 100644
--- a/src/libs/decoders/mp3.cpp
+++ b/src/libs/decoders/mp3.cpp
@@ -3,7 +3,7 @@
  *
  *  Copyright (C) 2001-2017  Ryan C. Gordon <icculus@icculus.org>
  *  Copyright (C) 2018-2019  Kevin R. Croft <krcroft@gmail.com>
- *  Copyright (C) 2020-2020  The dosbox-staging team
+ *  Copyright (C) 2020-2020  The DOSBox-X project
  *

```

**Comment by joncampbell123** [comment]
It might have been an honest mistake. Let's undo the copyright message changes.

**Comment by kcgen** [comment]
Yup, I agree - thanks @joncampbell123

**Comment by kcgen** [comment]
As a rule of thumb, I believe it's acceptable to claim full authorship of an opensource file (or other content) when you've meaningfully changed over 50% of the content. And even then, prior authorship should be retained up to the last date prior to your changes. 
That's my general understanding; however if anyone has a definitive guide or references - I am very interested!

**Comment by JoshuaFern** [comment]
In my opinion, anyone who has contributed to the code should be credited if they choose. No one should ever be removed unless the entire thing has been rewritten from scratch.

**Comment by Wengier** [comment]
@kcgen It was indeed an incident. I had been clean up strings in some files so that DOSBox-X shows itself as "DOSBox-X" instead of "DOSBox" in the code (see e.g. Issue #1483), but apparently should have left the copyright headers intact, especially regarding dosbox-staging. Thanks for pointing this out, and I already undid the copyright message changes.

**Comment by kcgen** [comment]
All good Wengier; thank you!

**Comment by Wengier** [comment]
Some decoder source files still referred to "DOSBox Team" instead of either DOSBox-X or dosbox-staging. I have changed all of them to "dosbox-staging team" instead in my latest PR. In any case, the [CREDITS.md](https://github.com/joncampbell123/dosbox-x/blob/master/CREDITS.md) page have been explicitly giving dosbox-staging credits for features like FLAC, Opus, Vorbis, and MP3 CD-DA tracks support for some time, which are where most users are looking at (instead of the source files).
