### ISSUE TITLE
Won't launch on Windows XP x86 - Not a valid Win32 Application

### ISSUE THREAD

**Issue by Hack3Rz4LIFE** [joncampbell123/dosbox-x#180]
When attempting to start the x32 release on my retroPC/EmulatorPC it says its an invalid Win32 Application
            is this by design or accident?

The system:

Windows XP Proffesional SP3 x86 with All applicable .net and c++  updates
Dell Intel QX43 based socket LGA 775 Motherboard
Intel Core 2 Duo E8400 @ 3GHZ (Wolfdale Core, SSE4.1)
XFX NVIDIA GeForce 8800GTX 768MB running NVIDIA 291.92 Beta Drivers
4GB Crucial 800MHZ DDR2 (2x2GB)
SoundBlaster X-Fi Go! Pro USB Audio
500GB Seagate Barricuda SATA HDD

If this was by design was there any particular motive for not supporting Windows XP?
It would seem most illogical not to support one of the more common retro gaming OS's out there
Is it due to the use of Visual Studio 2015 package? 
[DxDiag.txt](https://github.com/joncampbell123/dosbox-x/files/154218/DxDiag.txt)

**Comment by joncampbell123** [comment]
I was not aware the Win32 build was incompatible with Windows XP. It may be some default in Visual Studio 2015. Are you sure you're attempting to run the 32-bit build?

**Comment by Hack3Rz4LIFE** [comment]
I'll double check it but yes i'd bet my life on it.

On Wed, Mar 2, 2016 at 12:39 AM, Jonathan Campbell <notifications@github.com

**Comment by joncampbell123** [comment]
I have VirtualBox setup with a Windows XP VM, I'll see if I can tweak the build to get it to run.

**Comment by joncampbell123** [comment]
Well, there you go: VS2015 is marking the DOSBox executable as OS version 6.0 (Windows Vista or higher) when Windows XP thinks of itself as OS version 5.1.
![dosbox ver6](https://cloud.githubusercontent.com/assets/6245486/13485948/6e936b68-e0c1-11e5-8579-e911c85b0297.png)

**Comment by joncampbell123** [comment]
I tried to compile it for Windows XP using Visual Studio 2015. VS2015 said it could not find dxguid.lib. I tried installing the 2010 DirectX SDK but it failed every time installing the DirectX runtime *even though I explicitly told it not install the runtime*. I tried forcing VS2015 to link against dxguid.lib provided by that SDK, only to find that Windows XP tries to run the compiled EXE but crashes for reasons I don't have time at this point to figure out.

So my official response is: No, the Win32 builds I put out do not support XP. VS2015 makes that enough of a pain to prevent that, otherwise I would.

My primary dev system is Linux. I don't consider Windows important enough to pursue this issue any further. But if anyone else wants to take on making and releasing Windows XP compatible binaries, they are welcome to do so.

**Comment by Hack3Rz4LIFE** [comment]
Sadly im not a coder, as my name states im merely a hack3r4Lif3. You said
it was an issue with the OS identifying itself as 5.1. Im going to persue
making xp think its infact 6.0. I remember pulling a similiar trick to get
.net 4.0 onto an SP2 system.

Oh well i just wanted DosBoxX because i read something about it supporting
AWE32 Emulation. Anyways could you up the executable that crashed
somewhere? maybe its just the VM, i intend to try it on actual Hardware.

A build that starts and crashs has more potential than one that doesnt even
start.

On Thu, Mar 3, 2016 at 11:11 AM, Jonathan Campbell <notifications@github.com

**Comment by joncampbell123** [comment]
So you're going to hook the GetVersion / GetVersionEx API calls, and the part of the system EXE loader that checks the version?

An easier method would be to patch the EXE header to report OS version 5.1 instead of 6.0, and see what happens.

**Comment by Hack3Rz4LIFE** [comment]
I was hoping the version was indentified by a registry variable same as the Service Pack version but that doesnt appear to be the case.

**Comment by aybe** [comment]
Adding link to related topic : 
DosBox-X 0.801 will not run on XP SP3 #238

**Comment by joncampbell123** [comment]
Current builds require Vista or higher. It looks like VS2017's XP target is slightly broken with respect to a few crucial C runtime library functions like _stat.
