### ISSUE TITLE
drivez folder not always possible

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1859]
**Describe the bug**
The way the drivez folder is implemented, it requires that the drivez folder is in the same directory as the dosbox-x executable. However, if dosbox-x is installed system-wide, such as by default on Linux under /usr/bin/dosbox-x this is not realistic.

I guess the same issue would happen on Windows, if it was installed in "Program Files", instead of under "C:\Users\john smith"

So perhaps, allow the directory to exist (at least on Linux) in the same directory as the config file ~/.config/dosbox-x
I don't think this requires another config option, just first check the config directory, and then you can always still check the bin directory.

**Comment by Wengier** [comment]
@rderooy Good suggestion! But I think perhaps it can check the program directory fist, then the config directory, similar to how the config file is read (first program directory, then config directory).

**Comment by Wengier** [comment]
The latest code will first check the drivez directory in the program directory, and then the drivez directory in the config directory. Also, the config option "drive z hide files" now supports the option to just hide the files by giving hidden attributes (instead of making them disappear from the Z drive) by putting a leading "/" in the file name (e.g. "/A20GATE.COM"), so that DIR alone will not list these files (but DIR /A will). ZIP/UNZIP tools are added to the Z drive as well.

**Comment by rderooy** [comment]
@Wengier I just gave it a try.

Files in ~/.config/dosbox-x/drivez show up now, but sub-directories underneath drivez don't work. They don't show up.

**Comment by Wengier** [comment]
@rderooy Subdirectories on the Z: drive are not yet supported. It is a virtual drive after all, not backed by a real file system.

**Comment by rderooy** [comment]
Understood. That does make it more difficult to keep a bunch of different
SB drivers (e.g. CT-VOICE.DRV), grouped by SB type depending on directory
:-)

**Comment by Wengier** [comment]
@rderooy In that case why not just make a directory mount instead (e.g. MOUNT Y C:\SB). The Z drive is for primarily for core executable files in DOSBox-X.
