### ISSUE TITLE
[Linux] [SDL2] [OpenGL] segfault when booting DOS and loading EMM386

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1878]
**Describe the bug**
Let's start a new issue for this...

Running DOSBox-X SDL2 on Linux with ``output=opengl`` crashes when booting DOS and loading EMM386.EXE or (sometimes) DISPLAY.SYS. DISPLAY.SYS causing the crash is not consistent, unlike EMM386 which is sure to cause the crash.  I tried reducing the config.sys to just ``DEVICE=C:\DOS\EMM386.EXE`` to rule out interaction with other statements, and only loading EMM386 is sufficient to cause the crash. Specifying NOEMS as an option to EMM386 makes no difference.

The issue can be worked around by setting ``core=normal``, or by setting ``output=surface``

The error in the LOG:
```
LOG: DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.
LOG: Setting execute permission on the code cache has failed
Segmentation fault (core dumped)
```
This also causes an SElinux alert.
```
SELinux is preventing dosbox-x-sdl2 from using the execheap access on a process.

*****  Plugin allow_execheap (53.1 confidence) suggests   ********************

If you do not think dosbox-x-sdl2 should need to map heap memory that is both writable and executable.
Then you need to report a bug. This is a potentially dangerous access.
Do
contact your security administrator and report this issue.

*****  Plugin catchall_boolean (42.6 confidence) suggests   ******************

If you want to allow selinuxuser to execheap
Then you must tell SELinux about this by enabling the 'selinuxuser_execheap' boolean.

Do
setsebool -P selinuxuser_execheap 1

*****  Plugin catchall (5.76 confidence) suggests   **************************

If you believe that dosbox-x-sdl2 should be allowed execheap access on processes labeled unconfined_t by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'dosbox-x-sdl2' --raw | audit2allow -M my-dosboxxsdl2
# semodule -X 300 -i my-dosboxxsdl2.pp

Additional Information:
Source Context                unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1
                              023
Target Context                unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1
                              023
Target Objects                Unknown [ process ]
Source                        dosbox-x-sdl2
Source Path                   dosbox-x-sdl2
Port                          <Unknown>
Host                          e93z
```

DOSBox conf file:
```
[sdl]
output=opengl
[autoexec]
imgmount c hdd.img
boot c:
```

I unsuccessfully tried to step back to older versions, to find a version where it worked.

- v0.83.6-git crashes
- v0.83.5 crashes
- v0.83.4 crashes
- v0.83.3 broken SDL2 on Linux
- v0.83.2 crashes
- v0.83.1 crashes
- v0.83.0 crashes
- v0.82.26 not tested
- v0.82.25 not tested
- v0.82.24 crashes
- v0.82.23 not tested
- v0.82.22 not tested
- v0.82.21 not tested
- v0.82.20 not tested
- v0.82.19 not tested
- v0.82.18 crashes
- v0.82.17 crashes (first version with SDL2 OpenGL support)

I don't know if it helps, but I have a core dump I can share, I just cannot attach it here as the max file size is 10MB and the file is 135.5MB.

**Comment by Wengier** [comment]
@rderooy You checked that it crashed for SDL2 on your system even in the case of DOSBox-X 0.82.17 released long time ago. Nevertheless, booting with EMM386 works fine on my Linux VM with the settings output=opengl and core=dynamic, at least the first time it is booted and this result is very consistent here. But if I try to reboot the DOS guest system still with EMM386 loaded (but without restarting DOSBox-X), it may reset the system while loading EMM386, which seems to happen regardless of the setting (core/output) and DOSBox-X version.

**Comment by kcgen** [comment]
Does disabling selinux avoid the segfault?
(Not a solution, just seeing if dosbox's W^X problem is ultimately the issue).

**Comment by rderooy** [comment]
@kcgen yes running ``sudo setenforce 0`` before prevents the crash. But as you mentioned disabling selinux is not a real solution.

**Comment by rderooy** [comment]
FYI, the issue is not limited to booting DOS. It also happens on Fedora when starting various games. Particular those using DOS extenders apparently. Including Duke Nukem 3D, DOOM, DOOM II, Final DOOM, Quake and LSL6. The SDL1 version does not trigger the selinux alert.

**Comment by rderooy** [comment]
@kcgen I had seen that thread originally where jmarsh discussed the issue, but had forgotten about it. That seems like a reasonable solution to the problem. But it needs someone more skilled than me to port it.

And this issue is not limited to DOSBox-X. I am having the exact same crashes with dosbox-staging when running these games.

**Comment by kcgen** [comment]
Yes; it's quite involved. @dreamer's modifying jmarsh's solution for staging.  My guess is that it will be equally portable as jmarsh's solution is to X; which as I understand from @dreamer has a somewhat older and modified CPU core and dynrec (likely for improved win95 compatibility); vershs SVN and staging.

**Comment by rderooy** [comment]
@kcgen dosbox-x does not support Win9x with the dynrec core either. You need to use the normal core, which indeed has had improvements to handle Win9x and WinME better. In particular for page fault handling.

**Comment by dreamer** [comment]
> Does disabling selinux avoid the segfault?
> 
> Not a solution, just seeing if dosbox's W^X problem is ultimately the issue. As I understand it, Fedora 33 or 34 is going to make selinux mandatory, so were closing in on this being a showstopping bug.

It's a bit more complicated than that: selinux is enabled by default on Fedora for a long, long time already. Fedora 34 is going to remove option of disabling selinux in runtime (it will still be possible to disable it, but will require a restart). Other Linux distros (and BSDs, and also future ARM-based macOS) have such protections as well (sometimes enabled by default, sometimes not).

> Ref where jmarsh proposes a solution and patch: https://www.vogons.org/viewtopic.php?t=66690

I imported this patch to dosbox-staging branch some time ago (for easier reading and cherry-picking): https://github.com/dosbox-staging/dosbox-staging/commit/ed27c060b699f604b91481c2b65c3ef5476b52e4

> @kcgen I had seen that thread originally where jmarsh discussed the issue, but had forgotten about it. That seems like a reasonable solution to the problem. But it needs someone more skilled than me to port it.
> 
> And this issue is not limited to DOSBox-X. I am having the exact same crashes with dosbox-staging when running these games.

Yup, it's a problem for all DOSBox forks :( dosbox-staging issue: https://github.com/dosbox-staging/dosbox-staging/issues/253

As of September 2020, jmarsh's patch *almost* applies cleanly to trunk (there are numerous conflicts, but Git auto-resolves them correctly, with 1 exception). The patch does *not* apply to dosbox-staging master any more (since early 2020 - because we simplified the code and fixed alignment-related issues at the same time). I guess it never applied to DOSBox-X master (because `src/cpu` in SVN and -X diverged over the years), but should still be portable.

I am in process of porting this patch to dosbox-staging for several weeks now (as I am learning how CPU module works) - @rderooy, @Wengier  I will include you in the draft/review so you'll see what parts are relevant to W^X.

The jmarsh patch is generally ok, except:

- It does 2 big things at the same time - big refactor of cpu dynrec cache, *and* introduces W^X (which touches exactly the same code area) - I already ported all those "refactor" parts to dosbox-staging (~August)
- I *think* it has some buggy code in core_dynrec-specific parts - at least I noticed some code, that was suspiciously omitted
- It uses a tricky code to distinguish writeable ptr from executable ptr for consumers of those pointers (but arguably, this was probably the fastest way to implement it, given how other code in CPU module looks like; I suspect this tricky solution is an overkill, but I am probably missing understanding of some important details about how CPU emulation works)
- To the best of my knowledge, it was tested only on x86_64 with `core_dyn_x86`
- It makes some changes to `core_dynrec` architecture-specific bits, but is probably likely bits for PPC and PPC64LE cores (because neither one is included in SVN); I ported both PPC and PPC64LE backends to dosbox-staging already, because it was easier to port them before W^X.

The principle behind the patch is not complicated: instead of a single writeable+executable pointer storing code generated by dynamic recompiler, we want two separate pointers to the same memory, one pointer `mmap`ed with flags `PROT_READ | PROT_WRITE` and other one with flags `PROT_READ | PROT_EXEC`. The tricky and tedious part is: we then need to feed appropriate pointer, depending on how it's supposed to be used… And there are many uses of these cache pointers - it's not clear which ones are writeable (the majority) and which ones are supposed to be executable. I expected that only 1-2 uses will be executable, but *that's not the case in jmarsh's patch*.

**Comment by grapeli** [comment]
@dreamer  I applied this @jmarsch patch to dosbox-staging with no problems. Without an additional patch (in the risc_x64.h file) it will not compile.
I checked it quickly and it looks like it works.
```
systemd-run --user --pty -p MemoryDenyWriteExecute=yes src/dosbox 
pmap -X $(pidof dosbox) | grep rwxp

```

@rderooy  You don't need to disable SELinux globally.
Enough.
`setsebool -P selinuxuser_execheap 1`
You have this suggestion in the log you posted.

**Comment by dreamer** [comment]
@grapeli you would need to show me what you did so I could decide if it was "no problems" ;).

We already removed two `cache.h` headers removed by jmarsh's patch and merged them in a new header (named differently than the new header from jmarsh's patch). Without seeing your work I suspect result of applying the patch is just new, unused, header + some random changes breaking compilation. No patch in risc_x64.h (which one? there are two ;)) should be required - you are likely experiencing a conflict with work already done in dosbox-staging. Can't tell for sure without seeing the code, sorry.

**Comment by grapeli** [comment]
@dreamer Without this patch, there is no way to run dosbox-staging with W^X restrictions (except sluggish cpu = normal).
[dynrec_wx.dosbox-staging.patch.txt](https://github.com/joncampbell123/dosbox-x/files/5299748/dynrec_wx.dosbox-staging.patch.txt)

**Comment by dreamer** [comment]
@grapeli 

1. Your patch is missing crucial part - `cache.h` header introduced by jmarsh's patch; I presume you just used it as it was, without modifications.
2. I presume you replaced our carefully merged `dyn_cache.h` header with aforementioned `cache.h` (I can't tell for sure, because it's missing - after committing your work use `git format-patch -1` to create a patch).

In effect, you partially reverted 28 reviewed and tested commits done in this area over last 9 months (some are trivial, but other ones are very important). You can look up details of the work you reverted by using this command:  `$ git log --stat --since=2020-01-16 --follow src/cpu/dyn_cache.h`.

If you intend to keep working on this, feel free to send a PR.

**Comment by rderooy** [comment]
I have not had a lot of time lately, but decided to check with the latest build, and I can no longer run EMM386 when booting DOS regardless of ``output=`` setting (surface, opengl, openglnb, ttf), regardless of ``core=`` setting (normal, dynamic). And this issue is happening with both SDL1 and SDL2.

The error I get when booting DOS 6.22 and loading EMM386:

```
LOG: CPU_Exception: Exception 13 already in progress, triggering double fault instead
LOG: CPU_Exception: Double fault already in progress == Triple Fault. Resetting CPU.
LOG: Rebooting the system
```

I can bypass the error by hitting F8 on boot and saying No to loading EMM386.

The config.sys in question.
```
DEVICE=C:\DOS\HIMEM.SYS /TESTMEM:OFF
DEVICE=C:\DOS\EMM386.EXE NOEMS
BUFFERS=15,0
FILES=40
DOS=UMB
LASTDRIVE=Z
FCBS=4,0
DEVICEHIGH /L:1,12048 =C:\DOS\SETVER.EXE
DOS=HIGH
DEVICEHIGH /L:1,4560 =C:\WINDOWS\IFSHLP.SYS
STACKS=9,256
DEVICEHIGH /L:1,40800 =C:\DOS\OAKCDROM.SYS /D:OEMCD001
```

**Comment by rderooy** [comment]
After ensuring that avcodec no longer got compiled in, the above issue is gone. I can now also run EMM386 with output=opengl with the SDL2 build.
