### ISSUE TITLE
Internal Glide Emulation works in dosbox-x?

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#191]
I've been wondering for quite some time if dosbox-x (windows build) really supports glide emulation in comparison to dosbox svn-daum, because I've noticed that there is no option to set "glide=emu". I know it supports Opengl and D3D of course, but I'm not so sure about glide as far the Voodoo graphics under win9x is concerned. Any info? Thank-you!

**Comment by box-tortoise** [comment]
https://github.com/joncampbell123/dosbox-x/issues/188

**Comment by Gui55** [comment]
Yes I'm fully aware of that decision. Nevertheless, I would still like to know _for reference_ if TheGreatCodeholio's latest build for windows has glide, not just Opengl+D3D. I already suspect that it does, I just don't understand how/why though when it doesn't have to load glide2x.dll+glide2x_emu.ovl on startup.

**Comment by box-tortoise** [comment]
It sounds like you resolved your own question since it doesn't load that closed source library. It is preferable to use open source solutions.

**Comment by joncampbell123** [comment]
I don't know how exactly a program loads and executes the Glide API, but I do know that it has something to do with GLIDE2.OVL being in the search path, and that somehow exposes entry points to provide 3D acceleration.

My thought is: if DOSBox-X were to somehow generate a fake GLIDE2.OVL file in the Z:\ drive and populate it's entry points with callback instructions, perhaps native code could emulate the Glide API directly? It's a bit harder than faking .COM or .EXE files since as I understand there is both the MS-DOS EXE header, and the linear EXE (LE) header to spoof, but it could be done.

**Comment by joncampbell123** [comment]
A quicker alternative (but not as legal) is if we were to just embed GLIDE2.OVL and GLIDE2.DLL directly into drive Z: where 3Dfx-aware DOS programs could find it....

**Comment by joncampbell123** [comment]
I want to point out that the 3Dfx emulation in DOSBox/DOSBox-X uses OpenGL and is not tied to Windows at all, OpenGL works on Linux and Mac OS X too. No DirectX shaders though.

**Comment by Gui55** [comment]
Okay, so I was wrong then? Dosbox-X really does _not_ support glide in the current windows build, and supports only OpenGL/D3D options for Voodoo output then?

**Comment by joncampbell123** [comment]
Do you mean rendering *to* the Glide API on the host? Or do you mean emulating the Glide API for the DOS program?

**Comment by Gui55** [comment]
I mean for Glide Games under Win9x/DOS under DOSBox.

**Comment by joncampbell123** [comment]
DOSBox-X only emulates the Voodoo/3Dfx hardware, it does not emulate the Glide API. It emulates the Voodoo card at the PCI card level and it emulates the MMIO and I/O needed to talk to the chip. For DOS and Windows 9x to talk to that hardware emulation you will need to install 3Dfx drivers so that Windows 9x can talk to it, and then copy off the GLIDE2.OVL and GLIDE2.DLL files which you can then use in DOS for games that need them, to use 3D acceleration.

**Comment by Gui55** [comment]
Okay, I think I understand what you're saying.... Thanks! Also, thank-you for dropping Windows support for DOSBox-X, I'll probably find myself using mostly Linux (probably Ubuntu Desktop or something) too in the very near future due to what Microsoft is wrongfully doing to their customers. I'm glad I'm not the only one ticked-off! ;)

BTW - So you're last name is Campbell then, right? Same Here! (I'm serious)

**Comment by box-tortoise** [comment]
https://en.wikipedia.org/wiki/The_Enemy_Within_%28Star_Trek:_The_Original_Series%29

**Comment by Wengier** [comment]
Internal Glide emulation is already supported in DOSBox 0.83.5.
