### ISSUE TITLE
GUI Drive menu is not available when booted form disk images

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [joncampbell123/dosbox-x#1925]
I have some softwares which need to boot from system disk and then swap disks.
So, even when booted from disk images, I want to use gui's unmount and imgmount.

**Comment by Wengier** [comment]
You can still swap floppy disks when booted from disk images. However, you cannot mount new drives or unmount existing drives. The reason is very simple: once you booted from disk images, the DOS guest system takes control of drives, not DOSBox-X. DOSBox-X no longer has direct control over drives that you see once booted into a guest operating system.

**Comment by tokumeiwokiboushimasu** [comment]
I know that "DOS -> Swap floppy" works, but "Drive -> A -> swap disk" is grayed out.
I want GUI menu for swap disk images which can work even under guest OSs.

**Comment by Wengier** [comment]
When you booted into a guest system, the drive letters A, B, C, D etc are assigned by the guest system, not DOSBox-X. So DOSBox-X has no idea how they are actually assigned. DOSBox-X only know them clearly when you are running the integral DOS, which is why you can only control drives from the menu when the integrated DOS is currently active.

**Comment by tokumeiwokiboushimasu** [comment]
Ah, I see.  So, if we want to do something about this, we need to use physical drive numbers instead of drive letters.

**Comment by Wengier** [comment]
Yes, that is right. Once you boot into guest systems DOSBox-X only knows the drive number and IDE assignments, but not the drive letters. The drive letters are assigned by the guest systems and not DOSBox-X in such cases.

**Comment by tokumeiwokiboushimasu** [comment]
Then if there are some items like "floppy1" and "floppy2" in the Drive menu, they are convenient, I think.

Most of softwares for pc9801 needs to boot from their original system disks and change disks.

DOS/V is software extension of DOS running on IBM compatible machines, and can run softwares using kanji.
DOS/V's software of cource needs to be run under DOS/V OS, so we first boot DOS/V os, and then swap the disk
to application's one.

**Comment by Wengier** [comment]
If you just want to swap disks in such case, why not select "DOS -> Swap floppy" then? I doubt that functions other than swap disks (such as mount and unmount) are safe for guest systems, as drives are already assigned by guest systems when they start so forcing unmount for example at runtime may cause immediate malfunctions.

**Comment by tokumeiwokiboushimasu** [comment]
I'm afraid I don't understand the usage of "DOS -> Swap floppy", but if I want to use it, I need to boot from some disk image
(say "disk.ima"), then rename other disk image (disk2.ima) to "disk.ima", and do "DOS -> Swap floppy", right?
I think it is not very smart, and I want to use gui.

**Comment by Wengier** [comment]
DOSBox-X allows you to mount multiple disk images to a single drive (e.g. disk1.img, disk2.img, disk3.img) at the same time, but with only one active disk image at a time. But right now for mounting multiple disk images you can only use the command line, not the GUI, e.g.

```
IMGMOUNT A DISK1.IMG DISK2.IMG DISK3.IMG
```

Then you will be able to swap disks among these 3 disk images. Indeed, right now this can only be done from the command-line, but I think you have made a good suggestion to add support for mounting multiple disk images through the GUI. I hope this feature will be added soon (available by the next version).

**Comment by tokumeiwokiboushimasu** [comment]
Oh, I didn't know the functionality.  Thank you.  I hope the GUI come soon.

**Comment by tokumeiwokiboushimasu** [comment]
And I think it is good if we can swap disks of drives independently i.e. swap only disks in drive B: or something.

**Comment by Wengier** [comment]
There can be only one drive number (0 or 1) using multiple disks. So it will only work for either drive A or B, but never both.

**Comment by tokumeiwokiboushimasu** [comment]
Oh, it is not good then.  Most of softwares require each disk set to its own drive.  And we want swap system disks
(drive 0 for most cases) as well as data disks (drive 1).

**Comment by rderooy** [comment]
I do agree that it would be great to extend the ability to mount floppies and CDs directly from the menu when you boot an OS. But a couple of things would need to be taken into account I think.

- We should hide the current drive letters under the drive menu once a guest OS is booted to prevent confusion.
- As @wengier already mentioned, dosbox-x has no notion of drive letters once a guest OS is booted, so drive numbers will have to be used. But it can be done a little intelligent I think. We know for instance that 0 and 1 are normally floppy disks.
- We should only allow removable media to be swapped (floppies and CDs)
- I think it will be necessary to pre-define which drive numbers are what type. This such that you can boot Win98 without a floppy or CD inserted, but still insert one later.

something like:
```
[ide, secondary]
master=cdrom
slave=dvdrom

[fdc, primary]
device0=1200
device1=1440
```
Notes
- The use of master/slave naming is of course no longer PC these days. But that is what it was called originally.
- I don't know if windows cares about the type of optical disk. Perhaps we can just always emulate a DVD-ROM since it can read CD-ROMs anyway.
- The floppy device definition does limit what can be inserted. e.g. we should not allow a 1.44MB disk to be inserted into a 1.2MB drive.
- Some way of indicating a disk should be mounted read-only

**Comment by Wengier** [comment]
@tokumeiwokiboushimasu I have already improved the GUI menu mounting image file feature to allow mounting multiple disk/CD image files from the Drive menu. There is now a new "Mount multiple disk/CD images" option to the mounting options of the Drive menu so that you can mount more than one disk/CD images to a drive, just like doing so from the command-line. Support for swapping more than one floppy drives may come later.

**Comment by tokumeiwokiboushimasu** [comment]
Oh, thank you.  I can mount multiple images now.  But, how to swap the images of drive 2 after booting drive a?
I suppose "swap floppy" menu command or F12+Ctrl+D changes images in drive 1, right?

**Comment by Wengier** [comment]
@tokumeiwokiboushimasu Right now you can swap either the Drive 1 images or the Drive 2 images ("DOS" => "Swap floppy"), but not both. As I said above support for swapping more than one floppy drives may come later.

**Comment by tokumeiwokiboushimasu** [comment]
Ah, I understand.  Thank you and I'm looking forward to seeing the support of swapping images of multiple drives ;-)

**Comment by Wengier** [comment]
@rderooy Hiding drive letters under Drive menu and show the active device numbers once a guest OS is booted can be a good suggestion, but this will require reconstruction of the menu at runtime (back and forth). I have never tried myself, but I hope it can be done.

**Comment by rderooy** [comment]
@Wengier I don't know if there is an easy way to hide/unhide menu options, if there is than you don't need to reconstruct the menu but you simply hide device numbers by default and show drive letters, and swap it when an OS is booted.

The problem with this is that you don't know the device type beforehand. So you cannot adjust things once the boot command is issued. As such you would probably be limited to showing something like:
```
Drive
  - FDC
    - Device 0
    - Device 1
  - IDE Primary
    - Device 2
    - Device 3
  - IDE Secondary
    - Device 4
    - Device 5
```

Of course device numbers is limited by the amount of FDC and IDE controllers active in the config. It seems that you can have up to 1 FDC controller (with 2 devices), and up to 8 IDE controllers with 2 devices each. So a max of 18 devices. 

Assuming you do dynamically adjust things when the boot command is issued, Perhaps you could show them as something like this, assuming either the config was properly setup, or an image was mounted before boot was issued.
```
Drive
 - FDC
   - 1.2MB
   - 1.44MB
  - IDE Primary
    - HDD
  - IDE Secondary
    - CD/DVD
```

**Comment by tokumeiwokiboushimasu** [comment]
Now we can change disk images.  So I close this issue.  Thank you.
