### ISSUE TITLE
Wrong file names on mounted ISO image

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#1952]
**Describe the bug**
The names/extensions of files in the ISO image "Titus Software - 10 Awesome Games (1995).iso" are not displayed correctly.

**To Reproduce**
Try to mount the ISO and type DIR at DOS prompt.

**Expected behavior**
See the correct file names.

**Environment (please complete the following information):**
 - Windows 10 Pro 64 bit (version 2004)
 - dosbox-x-vsbuild-win-20200930224615.zip (tried both SDL1 and 2)
 - I tried also to set Reported DOS version 7.10 and Long filename support enabled, but it's strange because the files are in the short 8+3 format.

**Additional context**
I attach DIR output from DOSBox-X and Windows 10 prompt after mounting the ISO with Explorer integrated function:
[DIR DOSBox-X.txt](https://github.com/joncampbell123/dosbox-x/files/5391350/DIR.DOSBox-X.txt)
[DIR Windows command prompt.txt](https://github.com/joncampbell123/dosbox-x/files/5391351/DIR.Windows.command.prompt.txt)

Thank you.

**Comment by rderooy** [comment]
What I suspect is going on, is that DOSBox-X uses the ISO9660 **Level 1** index, which is limited to 8+3 and was meant for DOS compatible systems.

CD's can optionally contain _additional_ ISO9660 levels for operating systems supporting more than 8+3, I recall that this was supported by MacOS, Linux, OS/2, NT and such.

So this CD has more than one ISO9660 Level, in addition to Level 1, it also has Level 3 which supports mixed case filenames and filenames up to 31 characters.

There is also the Rock Ridge extension for Unix systems, and the Juliet extension for unicode, which I'm sure are also not supported by DOSBox-X.

https://en.wikipedia.org/wiki/ISO_9660

**Comment by rderooy** [comment]
So in short, I think DOSBox-X does the right thing. On legacy DOS systems you would also only have access to the Level 1 index. On legacy systems this is handled by MSCDEX (or a MSCDEX clone), which apparently never gained support for higher levels.
https://web.archive.org/web/20080708235428/http://support.microsoft.com/kb/q123408/

**Comment by Wengier** [comment]
@MX9000 DOSBox-X supports long file names (LFN) on mounted local drives, overlay drives, virtual drives and FAT drives pretty well at this time. However, support for LFNs on CD drives is currently rather limited indeed (almost non-existent). It can be a good future improvement, so thanks for the suggestion.

@rderooy MSCDEX certainly does not support LFNs well even with the DOSLFN drive loaded in MS-DOS 7.x. However, if you use SHSUCDX instead of MSCDEX, then long file names on CD drives will work much better with SHUSCDX+DOSLFN (both currently maintained by Jason Hood, who I communicated with a lot in the past). So I hope support for long file names on CD drives can eventually reach a similar level as with SHUSCDX+DOSLFN in DOS.

**Comment by MX9000** [comment]
@rderooy , @Wengier interesting technical details, thank you.

**Comment by Wengier** [comment]
Henrik Haftmann is the original author of the DOSLFN software and is very familiar with LFN support on CD drives and more. It will be great if he is willing to help with this.

**Comment by MX9000** [comment]
@joncampbell123 the work you did to add support for Joliet and Rock Ridge ISO file system extensions fixed this bug: tested on the latest version 2022.08.0 with reported DOS versions 7.0 and 7.1.

The only remaining differences from the Windows 10 prompt DIR command output are:
- the CD-ROM volume name is "Titus So.ftw" instead of "Titus Software -"
- the volume serial number is "0000-1234" instead of "386A-A3DF"

Thank you.
