### ISSUE TITLE
CUE wont load

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#1964]
I am trying to play The Town With No Name, but when I load the cue file, DOSBox-x says, "Could not load image file: TWNN.CUE MSCDEX: Failure: Invalid file or unable to open" This is the list:
AUDIO2.OPUS
AUDIO3.OPUS
TWNN.BIN
TWNN.CUE
TWNN.BIN runs the game but does not play the opus files. Here is a hint, everything works with DOSBox ECE. What do I do?

**Comment by rderooy** [comment]
@jadasse I'm not sure opus support has been tested. Could you however paste the contents of the CUE file here? And I assume the CUE file and the *.OPUS and .BIN file are all in the same directory?

In addition, depending on the OS, the real filename and the filename as specified in the CUE file may need to be identical. So if the actual filenames are all uppercase, they should be uppercase in the CUE file also.

**Comment by Wengier** [comment]
DOSBox-X currently supports for cue sheets with FLAC, MP3, WAV, and OGG Vorbis CD-DA tracks. Unfortunately OPUS support is not enabled yet as it will apparently require external libraries. I think the OPUS support code is not fully included in the DOSBox ECE source tree either, but will require external linkage, unlike the code for FLAC, MP3, WAV and OGG audios.

**Comment by jadasse** [comment]
They are in the same directory

**Comment by Wengier** [comment]
@jadasse The only file there is opus.c, but it requires additional files (opusfile.h, speex_resampler.h, plus many more) which are apparently not included.

**Comment by jadasse** [comment]
Wengier, do you have any recommendations where I cant find external linkage for it to work?

**Comment by Wengier** [comment]
@kcgen IIRC you wrote the backend for the audio decoders. Unlike the FLAC, MP3, WAV, and Vorbis decoders, the Opus decoder seems to require a lot of external files (not included in the respository). Do you have any suggestions on the best approach to include such linkages for Opus support in the resposity? Thanks!

**Comment by jadasse** [comment]
LOG:  1. rpcap://\Device\NPF_{64838B0A-838D-4C53-80F1-8FDA9CF1856F}
    (Network adapter 'Microsoft' on local host)
LOG:  2. rpcap://\Device\NPF_{5473511F-D8F5-480D-9A9C-120DCC3743BB}
    (Network adapter 'Microsoft' on local host)
LOG:  3. rpcap://\Device\NPF_{7AA66DB6-31F6-4F74-B48E-BA253D3B10EE}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  4. rpcap://\Device\NPF_{4C79354F-A1B1-4DE7-B018-F59BE5AB19CF}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  5. rpcap://\Device\NPF_{718E69B8-0F93-4604-A1EB-3CB75F7E3C2A}
    (Network adapter 'Oracle' on local host)
LOG:  6. rpcap://\Device\NPF_{78567E31-39F6-4785-A276-79C496276FB9}
    (Network adapter 'rpcap://\Device\NPF_{78567E31-39F6-4785-A276-79C496276FB9}' on local host)
LOG:  7. rpcap://\Device\NPF_{B7222EB6-9426-4613-BFA9-C64D6419EF28}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  8. rpcap://\Device\NPF_{E46495F0-4B37-400E-B63C-435E4082A370}
    (Network adapter 'Microsoft' on local host)
LOG:  9. rpcap://\Device\NPF_{54E39370-3753-41FC-A213-7BF5CA0D8538}
    (Network adapter 'Microsoft' on local host)
LOG: 10. rpcap://\Device\NPF_Loopback
    (Network adapter 'Adapter for loopback traffic capture' on local host)
LOG: 11. rpcap://\Device\NPF_{C80D45B2-1875-486A-BE10-DF81622212AF}
    (Network adapter 'TAP-NordVPN Windows Adapter V9' on local host)
LOG: 12. rpcap://\Device\NPF_{5F06FACD-F7F5-4D7D-B95D-4439C5A0D8F7}
    (Network adapter 'Intel(R) Ethernet Connection I217-LM' on local host)

**Comment by jadasse** [comment]
Although I chose 12, the network still won't connect. I tried reinstalling npacp, but it still won't work.

**Comment by jadasse** [comment]
I assume kcgen works with compatibility with audio.

**Comment by jadasse** [comment]
There's also another rip of TWNN where the audio is included inside the bin and cue, but I'm having trouble finding it.
https://archive.org/download/town-with-no-name-msdos

**Comment by jadasse** [comment]
This is the rip that works with DOSBox-x, but I'm having trouble trying to find the voice files.

**Comment by jadasse** [comment]
It's ripped differently

**Comment by jadasse** [comment]
Here's the other copy, ripped differently https://www.dropbox.com/s/zo3q3b88fwkyrqu/TWNN.7z

**Comment by kcgen** [comment]
@Wengier , sorry for the late reply. 

For ECE, the patch I gave them builds all of the dependencies and links them statically into the binary (`libogg`, `libopus`, and `libopusfile`) - it works for ECE because users typically only want those binaries, but it's not an elegant solution. 

For Staging and X, it's easier to depend on `libopusfile` (and ask users to install it), and let their repository manager deal with any knock-on dependencies such as `libopus`, `libopushttp`, `libssl`, `libogg`, etc..

Even `vcpkg` for Winows offer `libopusfile`, so we use that for those builds.

Here's the **configure.ac chunk:**

``` shell
dnl Ogg Opus handling
dnl -----------------
dnl    We want Opus tracks supported by default, and we also want the user
dnl    to be aware if there's a problem finding the Opus dependencies so
dnl    they can either a) install the opusfile library or b) explicitly
dnl    disable Opus.

dnl    To achieve this, we provide a --disable-opus-cdda configure option
dnl    but by default we look for Opus and fail if we can't find it.
dnl    We only skip supporting Opus if the user explicitly passes the
dnl    --disable-opus-cdda argument.
AC_ARG_ENABLE(opus-cdda,
              AS_HELP_STRING([--disable-opus-cdda],
                             [Disable Opus CD audio track support]))
AS_IF([test "x${enable_opus_cdda}" != "xno"],
      [PKG_CHECK_MODULES([OPUSFILE],
                         [opusfile],
                         [LIBS="$LIBS $OPUSFILE_LIBS" HAVE_OPUS=yes])])

AM_CONDITIONAL(USE_OPUS, test "${HAVE_OPUS}" = "yes")
```

Some platforms don't have all of the latest Opus libs or have broken `pkg-config` setups, so for that I put together [a static-builder Makefile](https://github.com/dosbox-staging/dosbox-staging/blob/master/contrib/static-opus/Makefile). Users can then:

``` shell
cd contrib/static-opus
make
```

Copy and paste the two resulting `export ...` lines back into their shell, after which `./configure ..` will then use those static libs instead.  It works on macOS, Haiku, and others. I also like using it for personal builds because I wants the very latest Opus improvements.. ;-)

**Comment by Wengier** [comment]
@kcgen Thanks a lot for the detailed information about the opus dependencies that you developed. I definitely hope to make the feature cross-platform (at least with Visual Studio, MinGW, Linux, and macOS). I can certainly use vcpkg to try to link to libopusfile on my own computer for Visual Studio builds (x86 and x64; not sure if it is also available for the ARM32 and ARM64 triplets which are also expected for DOSBox-X Visual Studio builds), but this also means an extra requirement for other users to build the system and also for @joncampbell123 to make official releases, so for now I would still prefer a static linking that is built into the DOSBox-X make system. The full library source code will then appear in the repository (updatable with a script), and because of this I don't want too many libraries initially (though additional libraries may be added later on). Do you still have the patch that you gave to DOSBox ECE for this purpose? Thank you so much for developing this feature.

**Comment by kcgen** [comment]
I actually don't have that version; at the time I was maintaining the code in an ever-evolving directory on top of the SVN copies (which a nightmare), as ECE stopped taking it roughly halfway through the evolution of it when I dropped the embedded codec stuff. 

The good news though is that ECE does provide all the patches in his source zip: https://dosboxece.yesterplay.net/download/DOSBox%20ECE%20r4387%20(source).7z

So that's the best bet!

**Comment by Wengier** [comment]
@kcgen I see. You are certainly right that maintaining code atop SVN updates is indeed a nightmare. I have remembered that I used to maintain LFN patches etc for SVN updates too, but I stopped doing so after the features were integrated into DOSBox-X. That process was indeed a nightmare as you said.

Meanwhile, I was able to find the Makefile inside the zip file you posted that seems to provide library sources, but there are no actual source files inside the "internal" directory, nor the Visual Studio solution includes these files. On the other hand, I noticed that DOSBox Optionals seems to provide source files inside the "internal" directory. So I downloaded the source files and cleaned them up as well as adding them to the Visual Studio solution. And it WORKS! The next step will be to make the update process automatic, but the OPUS feature appears to already working now with commit https://github.com/joncampbell123/dosbox-x/commit/85c80c985ce0cbf320a32ed8329cb7ff33b8285e. Thank you so much!

**Comment by Wengier** [comment]
@jadasse I have uploaded the updated Windows binary which should now have support for OPUS CD tracks. Please check it out:

Download link: [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

No external linkage is required any more.

**Comment by jadasse** [comment]
thanks! :)

**Comment by kcgen** [comment]
Great find in dosbox optionals!
 I knew Marty was using it too, but didn't realize he was bundling all the sources! That's great you found a solution that works for -X!

**Comment by Wengier** [comment]
Many thanks to both Martin and kcgen!

**Comment by Wengier** [comment]
Many thanks to both Marty and kcgen! It works for DOSBox-X because of you both.
