### ISSUE TITLE
Mount multiple disk images from GUI

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#1972]
**Is your feature request related to a problem? Please describe.**
I tried to install a game from 2 floppy images but I could not figure out how to load all the images from the menu: I tried to select both files with the CTRL or SHIFT keys with the "Drive > A > Mount disk image" menu item without success.
I had to add the line "IMGMOUNT A D:\DOSBox-X\FD\disk1.img D:\DOSBox-X\FD\disk2.img -t floppy" to the dosbox-x.conf file.
Afterwards I could exchange the images with "DOS > Swap floppy" and "Drive > A > Swap disk" menu functions.

**Describe the solution you'd like**
1) Select multiple files with Mount disk image menu function.
2) Perhaps integrate/move the menu items "Swap floppy", "Swap CD", "Rescan all drives", "Show mounted drive numbers" from DOS menu to Drive menu removing duplicates.

**Comment by rderooy** [comment]
With the released version of DOSBox-X it is not possible to mount multiple disk images using the menu. Only from the command line.

Thanks to @Wengier , with the next version (which should be out soon), there is a new menu option that does allow it.
![Screenshot from 2020-10-30 12-37-02](https://user-images.githubusercontent.com/17701098/97700874-d084e700-1aac-11eb-9f9e-acb4e2909a71.png)

**Comment by Wengier** [comment]
@MX9000 As @rderooy said the new DOSBox-X version (0.83.7) that has support for mounting multiple disk images from GUI is expected to be released very soon.

In the Windows SDL1 build, there is already a long list of drive letters (A-Z) in the Drive menu, but the menu items "Swap floppy", "Swap CD", "Rescan all drives", "Show mounted drive numbers" are drive-independent. In other words, they either apply to all drives or a class of drives, instead of a specific drive from A-Z. Moving them from DOS menu to Drive menu will make the menu list in Drive menu even longer and may not look very good (at least for the current representation). But I think it may be something worth consideration later (especially after some kind of Drive menu reconstruction) .

**Comment by MX9000** [comment]
@rderooy, @Wengier thanks to all.
I can't wait to try the new version!

**Comment by MX9000** [comment]
@rderooy, @Wengier I tested the new version (0.83.7 x64 under Windows 10, both SDL1 and 2) and I can't change the floppies with the function "Drive > A > Swap disk".
If I'm not wrong, it seems that only "DOS > Swap floppy" works.
Thank you for your efforts.

**Comment by Wengier** [comment]
@MX9000 Yes, I guess that can be fixed. On the other hand, you can just use "DOS > Swap floppy" for now.

**Comment by MX9000** [comment]
@Wengier of course, it's not a big issue.
Thank you.

**Comment by Wengier** [comment]
@MX9000 I think I have found the problem - the menu items "Rescan drive" and "Swap disk" are reversed! So when you click "Rescan drive" it will actually swap disk, and when you click "Swap disk" it will actually rescan drive. It is a very easy fix then.

**Comment by MX9000** [comment]
@Wengier , great!
Thank you.

**Comment by MX9000** [comment]
Issue solved.
Thanks.
