### ISSUE TITLE
Request: scalable, resizable windows with TTF output

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2024]
With the new, terrific ttf output feature, it would be good to be able to increase/decrease font size by dragging on the window corner, and change the number of lines and columns by dragging on the horizontal or vertical borders. Is there any hope that this might be possible?

**Comment by Wengier** [comment]
@emendelson Right now you can increase or decrease font size from the menu ("Video" => "Text-mode" => "Increase TTF font size"/"Decrease TTF font size"), or on Windows you can press Win+F11/F12 to do so. You can also change the number of lines and columns from that menu group. I am not sure about dragging on the window corner though, because this is of course not a precise way of changing font size or number of lines/columns related to TTF support.

**Comment by emendelson** [comment]
@Wengier - That's good enough. I didn't realize that those keystrokes were available. My fault.

**Comment by emendelson** [comment]
One last question: Where in the code is the Win+F11/F12 keystroke set?

**Comment by Wengier** [comment]
The Win+F11/F12 keystrokes are currently fixed for Windows. I do hope to add them to the keyboard mapper so they are customizable, but right now there is no room for additional shortcuts in the mapper editor, so some interface cleanup for the mapper editor is desired before adding more shortcuts.

**Comment by joncampbell123** [comment]
@Wengier Why not make it a mapper shortcut? F11 on Windows / F12 everywhere else is already the "host" key, which is configurable in the mapper.

**Comment by Wengier** [comment]
@joncampbell123 Because the mapper editor screen is already full, apparently. Some cleanup to the mapper editor interface needs to be done to add more shortcuts.

**Comment by joncampbell123** [comment]
@Wengier I've thought about that too... perhaps the mapper shortcuts on the right hand side could be reduced in size if they were to use a smaller bitmap font. The 8x14 font does make them a bit big.

Another idea might be to make the mapper shortcuts appear in "pages" with <- and -> arrow buttons below to change pages.

**Comment by Wengier** [comment]
@joncampbell123 I think the best apparoach would be to add “pages” as you said, which is apparently the most future-proof solution. The other approaches will eventually face the same issue. By adding page support the text in the grids can be made longer and clearer too.

**Comment by joncampbell123** [comment]
@Wengier Perfect. The thing is, buttons in the mapper currently assume they're always visible. So the first step is to add a flag that says whether the button is visible or not, and set the flag to false for anything on the second page. The mouse code will have to ignore any button that's not visible so that you're not clicking on invisible buttons. Simple enough, I think.

**Comment by Wengier** [comment]
@joncampbell123 I have already cleaned up the mapper interface so that it now allows more keyboard shortcuts to be added, shown in multiple pages in the mapper, navigable with the "Previous Page" and "Next Page" buttons. The default shortcuts for increasing/decreasing the TTF font size are now Host(F11/F12)+Up and Host(F11/F12)+Down respectively (for all platforms).
