### ISSUE TITLE
Request: keystroke to interrupt clipboard paste

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2073]
It's easy to make a mistake and paste a lot of text into DOSBox-X using Wengier's excellent clipboard paste feature. I can't find any way to interrupt the paste after it begins.

While the clipboard is being pasted, could DOSBox-X test for the Ctrl-C (or maybe Esc) keystroke, and stop the paste if the key is pressed?

**Comment by Wengier** [comment]
@emendelson You can just select "Main" => "Shared clipboard functions" => "Stop clipboard pasting" to stop the pasting in the middle. There is no keyboard shortcut for this though.

**Comment by emendelson** [comment]
@Wengier - The trouble is that the user might not have the menu open (the menu is hidden in my fork because it only distracts someone who is working in a word-processor). A keystroke would be much faster, and Ctrl-C or Esc are easy to remember. But this is not essential.

**Comment by joncampbell123** [comment]
Pasting is faking keystrokes from the keyboard, so perhaps pressing any key should cause it to stop.

**Comment by Wengier** [comment]
@joncampbell123 The current clipboard pasting function will paste with some delays (instead of continuously) in order to overcome the keyboard buffer limit, so pressing a key won't cause it to stop. But I have already added mapper binds to this one and the "Load mapper file" function in my PR so that you can define your own shortcuts for them (they are unbound by default). There is now virtually limited room for the mapper editor, so you can add more binds as you want.

**Comment by Wengier** [comment]
@emendelson You can download the updated Windows binary that has this function in the mapper from:

http://cndos.fam.cx/dosware/dosbox-x-update.zip

**Comment by emendelson** [comment]
@Wengier - Thank you for this. It's very helpful.
