### ISSUE TITLE
Add LPT4-9?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2083]
Many years ago, I tried adding LPT4 through LPT9 to DOSBox-X, without success. I hope someone who knows something about coding might consider this now.

Under vDos, I can use LP1 through 9, and use the output files to each port in different ways (print to different printers, pop up a select-printer dialog, create PDF files in different locations, etc. DOSBox-X only allows the standard LPT1-3.

I hoped I could use COM1-4 for this purpose, but programs like WPDOS probe the COM ports if they exist, and produce undesirable results when the ports are emulated.

DOSBox-X already includes the CLIP device. Is there any hope that it might also add LPT4-9 as devices?

**Comment by Wengier** [comment]
@emendelson I have already added the option to optionally add LPT4-9 devices as you suggested, similar to LPT1-3. Since they don't have default BIOS base addresses, you will need to set one for them by yourself if you enable these ports, e.g. 

```
parallel4 = base:2bc file file:output4.prn timeout:1000 openpcl:pcl6 ...
```

You can download the updated Windows binary from:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by emendelson** [comment]
Thank you, Wengier! Are there any guidelines of what base addresses will work? I don't want to specify an address that will interfere with anything else.

**Comment by Wengier** [comment]
@emendelson You can try the following updated DOSBox-X Windows binary where the base addresses for LPT4-9 are now optional (but you can still specify for them; for LPT1-3 you are never required to specify base addresses for them since they have default base addresses):

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Hope this helps.

**Comment by emendelson** [comment]
Thank you, Wengier. I just tried it out with LPT4 and it worked perfectly.
