### ISSUE TITLE
Print to clipboard like I did in vDosPlus

### ISSUE THREAD

**Issue by JoeC4281** [joncampbell123/dosbox-x#2097]
Back in the vDosPlus days, in the `config.txt` file, I had `LPT1 = CLIP` so that when I printed to LPT1, the output would go to the clipboard.

Try as I might, I cannot locate in the DosBox-X documentation on how to do this.

I have no problem using the clipboard with the 4DOS shell;

![image](https://user-images.githubusercontent.com/58880711/102560732-f12aef80-40a0-11eb-8ee4-64c440500945.png)

I have the following set in my .CONF file;

![image](https://user-images.githubusercontent.com/58880711/102560842-3a7b3f00-40a1-11eb-8f5b-7b39e0b0f37a.png)

@Wengier and @emendelson helped me get this working on vDosPlus previously;
https://sourceforge.net/p/vdosplus/discussion/general/thread/361607bf/#fe45

Note that in vDosPlus with the 4DOS shell, _win equaled 1;
https://sourceforge.net/p/vdosplus/discussion/general/thread/361607bf/#2fc5

In DosBox-X with the 4DOS shell, _win equals 0.

What other settings do I need to be able to print to the clipboard from DosBox-X?

Again, apologies for not being able to locate in the DosBox-X documentation on how to do this.

Joe
![image](https://user-images.githubusercontent.com/58880711/102561593-19b3e900-40a3-11eb-8cdb-0ed978573b60.png)

**Comment by Wengier** [comment]
@JoeC4281 Printing to clipboard is very easy in DOSBox-X, but it works differently from vDosPlus. Basically you specify a clipboard device name with the "dos clipboard device name" option ("CLIP$" by default), so that anything that prints to it will go to the clipboard. For example, if you want to "print" to clipboard via LPT1 (or any other name you want), you can set something like:

```
[dos]
dos clipboard device enable = true
dos clipboard device name = LPT1

[parallel]
parallel1 = disabled
```

In this case, LPT1 becomes the dos clipboard device (note that it is *bidirectional*), instead of the parallel port device. More information about using the DOS clipboard device can be found in this Wiki page:

https://dosbox-x.com/wiki/Guide%3AClipboard-support-in-DOSBox%E2%80%90X

**Comment by JoeC4281** [comment]
Thanks @Wengier for you assistance. I now have in my .conf file;
```
[dos]
dos clipboard device enable     = true
dos clipboard device name       = LPT1
dos clipboard api               = true
```
and
```
[parallel]
parallel1 = disabled
parallel2 = disabled
parallel3 = disabled
parallel4 = disabled
```
From 4DOS, I can now send to lpt1: and have it end up on the clipboard;
```
C>echo Test of DosBox-X > lpt1:

C>type clip:
Test of DosBox-X
```
Thankyou also for the link about how to use the Clipboard from the DosBox-X documentation.

Joe
