### ISSUE TITLE
Paste-Clipboard keystroke enters different text from CLIP$

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2098]
If I copy some text to the Windows clipboard that contains French or German accented characters, and then, in DOSBox-X, retrieve the text from the CLIP$ device, the accented characters appear correctly. 

However, if I use the Ctrl-Alt-V keystroke to use the Paste Clipboard function, the characters are all entered incorrectly. Is it possible to make the Paste Clipboard function produce the same accurate result as the CLIP$ device?

**Comment by Wengier** [comment]
The ways that the CLIP$ device and Past Clipboard function work are not the same. For the CLIP$ device, it is handled as an internal device so that there does not have much limitations and will indeed produce highly accurate result as you said.

On the other hand, for the Paste Clipboard function, it is pasted via keyboard functions, which means it depends on factors like the available ASCII characters in the current code page. As long as the keyboard method is used, it can never achieve the exactly same accurate result for non-standard ASCII characters as the CLIP$ device.

That said, I tried to paste some French or German accented characters using the Paste Clipboard function, and it does works. So the problem may occur due to reasons such as the operating system, whether the build is SDL1 or SDL2, and the current code page you are using, as these can interfere with the actual result too.

**Comment by emendelson** [comment]
Hello Wengier, Thank you for that explanation. First of all, I completely misreported the problem in my first post - actually the French and German characters DO get pasted correctly. My apologies! I was too lazy and impatient to notice that the problem had to do with formatting and extra characters, as shown in the screen shot below.

I copied the highlighted characters in Firefox from the address at the top, https://www.rocketlanguages.com/french/lessons/french-accents - then opened WPDOS 5.1, saved an empty file, and used Shift-F10 to retrieve CLIP$. Then I used Ctrl-Alt-V to paste from the clipboard. As you see WP treats ASCII 13 as a musical note, not as CR. There may be no way to fix that, but I thought it might be worth asking. 

If this is impossible to fix, please just close this issue.

**Comment by Wengier** [comment]
@emendelson It seems that WPDOS does not recognize CR as the end of line character. But please note that Windows SDL1 and SDL2 builds handle this slightly differently (SDL1 build uses SDL keystroke whereas SDL2 build uses BIOS keyboard function), so can you please try Windows SDL1 build for this?

**Comment by emendelson** [comment]
@Wengier - You're right; SDL1 works perfectly. I had been planning to use SDL2 builds for my projects, but this issue is enough to make me prefer SDL1. Is there any chance that the SDL2 build can work around the issue?

**Comment by Wengier** [comment]
@emendelson The said issue is hopefully fixed in #2137.

**Comment by emendelson** [comment]
Thank you, @Wengier
