### ISSUE TITLE
So, how did the code base grew up to such monster ?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#210]
After spending a few days with it, that's the conclusion I came up to ! There's definitely a lot of redundant code, copy/paste, insane nesting and so on, making it quite difficult to follow at times. As you've seen on my commits, I either try to make short methods, give meaningful names, document appropriately or use defensive programming, [not trusting what's happening on the upper-layer](https://github.com/joncampbell123/dosbox-x/commit/f5e49aa65722d259b8aff434134770ebb7ab5d15). 

I think there should be a coding convention written down somewhere ...

(note: I'm talking about the SDL-related code)

I was wondering, in regards to rendering, why simply not ditch out scalers and outputs in favor of OpenGL and shaders ? OGL is multi-platform and pretty much all scalers are available as shaders. Even being a Windows user, I simply see no point in fixing/enabling Direct3D output. But I agree, this will take time...

What do you think ?

**Comment by joncampbell123** [comment]
Yes, OpenGL is everywhere, but don't forget it's also a very large codebase to compile and a large binary when installed (especially MesaGL). I like leaving open the option _not_ to use OpenGL because DOS emulation doesn't involve it (much) at all. All rendering is 2D. I also like leaving open the option to run DOSBox/DOSBox-X in embedded systems where OpenGL would add too much weight to the memory requirements.

The other reason is that I'm very handy with writing fast 2D software rendering code. Writing such code can be done cleanly, especially with judicious use of C++ static inline functions and C++ templates. I work on a commercial video playback program where I have written fast 2D bilinear scaling and YUV->RGB conversion. Also, I know from experience that reliance on OpenGL would cause major performance issues with code that needs to read it back (the video capture and screenshot functions).

I'm all for cleaning up the codebase, in fact sometimes I make that the goal of a weekend or two when I have time to work on DOSBox-X. I think it has to do with DOSBox's development since 2003 and the mixed programming techniques contributed by 100s of DOS gamers on the Vogons forums. I've noted several places where one place will use C style concatenation and sprintf, where another part will use C++ iostream style string construction.

I believe it's possible to cleanup the codebase in a way that can accomodate both OpenGL and non-OpenGL rendering code. I'd rather keep my options open then rely on OpenGL.

**Comment by joncampbell123** [comment]
I'll clarify that I'm open to the idea of allowing DOSBox's rendering to use OpenGL and the GPU especially where elements are overlaid on the video (S3 hardware cursor for example), but I don't want OpenGL and GPU acceleration to be a hard requirement.

**Comment by aybe** [comment]
Yes I understand, was going to look at it but I won't then ... 2 cents here, why bother supporting it then if it won't be widely deployed ? :D one won't get less than what's currently available after all

After reading you I'm also thinking why bother re-factoring large pans of the code ? i.e. changes I did in the mapper/joystick are I guess, okay ... this layer will hardly evolve any further, so not sure it's worth the trouble seeking for clean code regarding the time it'll take, I mean when one is used to such mess then I guess he can live with it :D

**Comment by joncampbell123** [comment]
I would love flawless perfectly organized code, true. I also know that's not possible with this code, especially when improvements are being made. So I generally keep refactoring down to parts I can do it to without breaking it or messing it up further, and carefully, in small steps. And only if I have a clear idea how to do it. It does mean that you'll have to live with the mess while changes are carefully made.

**Comment by joncampbell123** [comment]
Perhaps the biggest breaking change I've made within the last year would be the audio mixer code (mixer.cpp), and that was done carefully. Then when that was done, I was able to put in the slew rate and lowpass code to better emulate what certain sound cards actually sound like.

**Comment by aybe** [comment]
Yes, this class is clean code.Other than these joystick-related changes I'm not sure if I'll be of any help, all DOS-emulation-related stuff is beyond my knowledge.
For the rest I'm not sure but things are working rather correctly, right ?

**Comment by joncampbell123** [comment]
Yes. Sometimes I'll do idle testing with DOS games and utilities, Windows 3.1/95/98/ME, random demoscene stuff, etc. to see if any problems arise. This is also why the "Dosbox integration device" is being developed to allow a DOS program to fake inputs and diagnose DOSBox itself, where I have automated testing in mind. I'm also spending some time writing documentation and comments in the code to help development.

**Comment by aybe** [comment]
Great ! Actually I still might have a few cosmetic changes to bring, such as an installer for Windows, going to look at it. Other than that when there's a new issue and if I think I can address it, I will take a look. And also play old DOS games a bit because it was the first intent :D
