### ISSUE TITLE
CGA composite (and generally, display type) as config

### ISSUE THREAD

**Issue by dani-jozsef** [joncampbell123/dosbox-x#213]
Hey, love how you are giving DosBox some long overdue love. I might even start contributing! :) The historical accuracy thing is a great idea, following in the footsteps of mame and vice... :)

Anyway, one of the biggest problems I have with dosbox is its weird approach to cga composite artifacting. Afaik it tries to 'autodetect' it, which is anything but historically accurate... Cga artifact color happened in the television set due to ntsc limitations ('it's not a bug, it's a feature').

So instead of trying to guess it, the type of display should really be a separate config. Preferrably a separate display emulation subsystem, independent of the video card emulation, and modeling what happens to the signal in an ntsc tv, vga monochrome monitor, or maybe even old lcd laptop screen.

Is something like this on the roadmap? Also I remember reading that dosbox uses 256 color mode, which makes accurate display emulation needlessly hard. Has this been already addressed in db-x?

**Comment by joncampbell123** [comment]
I added code to dosbox-x that allows you to specify that the CGA composite mode is always on, you should be able to assign (off the top of my head) machine=cga_composite or something like that.

The original DOSBox developers that wrote the 256-color based emulation obviously did it for performance, since they can reduce it down to pixel math and a lookup table. If you can write better, by all means, do it. However I recommend doing in the form of being able to choose which CGA composite emulation you want. If you read the Vogons forum where they talk about writing their CGA composite emulation you see that they put a lot of effort into tweaking the colors and brightness to look like what CGA composite appears on their TV sets, so it's not something I'd throw out or take for granted.

Describing the display as separate from the computer output is something I've been wanting to add as well. I've been thinking of updating the video emulation to render both active display, overscan border, and blanking border and then describe to the GUI a source and destination rectangle that the GUI could stretch-blit (or hardware stretch) to in order to better match what the display does. DOSBox and DOSBox-X currently only render what the VGA registers have been programmed to count as "active display" but that doesn't give you the full picture, nor does it give you the 8-pixel overscan border or blanking border, which I'd like to see DOSBox-X render. The other reason is that if you are writing your own VGA modesetting code, not seeing the border or how it centers on the screen can give you a false impression your code is working correctly until you run it on real hardware to find that your vsync/hsync blanking puts the picture way off center. The reason I want to see the scanline render include the horizontal/vertical blanking is because I think it would be cool for the video capture to have it as well. It would mean that when I do demoscene captures I no longer have to instruct FFMPEG to add a black border around the video when I transcode to prevent the outermost part of the picture from falling into the TV overscan area.

Monitor emulation could be written to specify the type (VGA tube, laptop LCD display, or modern LCD monitor) and then a preset. User-specified tunables would come later, If emulating a VGA tube I envision writing the code that accepts the next scanline to either display it as is, or if HSYNC is not what the monitor is designed for, to render the scanline off-kilter (so it's "scrambled" the way a VGA monitor would do when the horizontal sync is not what it expects), and if VSYNC is not what it was designed for, it would render the fixed scanlines anyway and let the picture "roll". Modern LCD display emulation would match the HSYNC/VSYNC and stretch it, or it would fail to match and do the "no signal" thing that modern LCD displays do. Laptop LCD emulation would set a fixed resolution (of the LCD display in the laptop) then work with the VGA emulation code to map VGA output the way laptop LCD displays do it. Up until about 1996 or so most laptops had a 640x480 display and the hardware would force VGA output to 60Hz for it and then just pad the VGA output around the edges to produce 640x480 at 60Hz (so, your DOS game running at 320x200 means it just doubles the pixels both ways and then centers the 640x400 on the 640x480 display). You can tell laptops do this in their VGA chipset because if you use it's "simultaneous" mode to drive the LCD and external VGA monitor, both will always see 640x480 60Hz no matter what VGA mode the DOS application sets. Later laptops follow the same pattern when they started shipping with 800x600 60Hz LCD displays. Even a more recent laptop I have (2008-ish) with an Intel chipset will upscale VGA output to the panel's native 1366x768 resolution and then drive VGA output the same in simultaneous mode. Starting about 1997 or so laptop VGA chipsets only then began to incorporate circuitry to upscale the VGA output to the display, but it was nearest-neighbor pixel duplication and it looked awful so it was usually left off. Hardware at the time couldn't fit the bilinear interpolation and scaling we take for granted in laptop VGA chipsets these days. Emulating laptop hardware upscaling shouldn't be all that hard, I can add that. Another thing that might be worth adding is emulating really old laptops with greyscale displays. Also, do you envision LCD ghosting emulation? You hardly see ghosting anymore today but it used to be very noticeable up until about the mid 2000s.

**Comment by sikthehedgehog** [comment]
> DOSBox and DOSBox-X currently only render what the VGA registers have been programmed to count as "active display" but that doesn't give you the full picture, nor does it give you the 8-pixel overscan border or blanking border, which I'd like to see DOSBox-X render.

May want to start with Rusty then, the intro shows up as 640×291 in windowed mode and captures because of the letterboxing (which really confused me until I remembered VGA allowed you to select the start and end scanlines - one of those features nearly nobody used).

> Another thing that might be worth adding is emulating really old laptops with greyscale displays.

This one is gonna be fun for those that had a variant of CGA. Text mode was always black on white, 640×200 also had the colors reversed, and... not sure what they did with 320×200.

**Comment by daniel-jozsef** [comment]
Ghosting in lcd may be an interesting addition from a completionist standpoint, with unlimited resources, I'd definitely say it should be part of the 'final milestone'...

Whether it should be added anytime soon may depend on its relevance from a demoscene standpoint. :) Since I'm not aware of demos making use of lcd ghosting, I'd say there may be a number of more important stuff to handle. Maybe if someone adds it for the kicks. ;) Unfortunately I haven't had a laptop that did ghosting in my hand since I was 13 or so, so I'm not even sure how it actually looked.

**Comment by Dwedit** [comment]
Is this still an open issue?  It looks like setting machine=cga_composite is indeed forcing composite mode on.

**Comment by dani-jozsef** [comment]
Not as such, as there's now an option for it. :)
