### ISSUE TITLE
ZIP Releases

### ISSUE THREAD

**Issue by coughlanio** [joncampbell123/dosbox-x#217]
Will zip releases be discontinued with the new installer? I would much prefer zips being made available alongside the installers.

**Comment by joncampbell123** [comment]
No. I'd rather have ZIP archives as well. I rather like DOSBox-X as a standalone executable so that you can just run it with the DOS game rather than have to install it.

However I've stopped working on the Win32 side of DOSBox-X so I myself won't be making ZIP archives. I believe I can develop better if I just focus on Linux and Mac OS X rather than hack up the code with support for Microsoft C runtime weirdness.

I'm told there is a branch of this repository where someone else is willing to keep up a Win32 build. Ask him, and refer to this issue.

**Comment by aybe** [comment]
Will do that soon just like I did for the enhancements for the installer : zip it with a name like `dosbox_date_time` to easily differentiate them.

**Comment by aybe** [comment]
vow fulfilled 😃 

https://github.com/joncampbell123/dosbox-x/releases

expect more frequent updates in the future since it's being scripted now.
