### ISSUE TITLE
Minor suggestion [for the DOSBox-X start banner]

### ISSUE THREAD

**Issue by DSN9990** [joncampbell123/dosbox-x#2170]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'll really like to see the DOSBox-X start banner in yellow now instead of blue (the default color).

**Comment by Wengier** [comment]
@DSN9990 Thanks for the suggestion! But I don't think it is as easy as just changing the background color, because if you do so you will need to change the color of some text too (otherwise the foreground and background colors will be the same for them). Perhaps there can be some different (preset) "themes" to choose from, and in such case it is necessary to design such themes one by one.

**Comment by Banjo-Oz** [comment]
It's not something I'd be after so much personally, but the idea of being able to set the background and text color of the welcome box would be nice... then again, being able to do a custom welcome box would be cool too (I actually did it with vanilla DOSBox ages ago so it showed info on various tools I had installed, but it was a batch file that generated my own "welcome" text after cls-ing the original welcome, since vanilla can't skip it like X can).

**Comment by DSN9990** [comment]
@Wengier How about that?

![sample](https://user-images.githubusercontent.com/69558812/104111599-75e4e400-52c2-11eb-88c5-0efd1a7b37e3.png)

**Comment by Wengier** [comment]
@DSN9990 Sure, this can be added as a “theme” to select from. Can you (or anyone else) design some other themes too by changing the background (and foreground colors if necessary) so that they can also be selected? Thanks.

**Comment by DSN9990** [comment]
This would be good also:

![sample](https://user-images.githubusercontent.com/69558812/104112240-0d4e3500-52cb-11eb-9a83-3c617a4ede30.png)

There can be 3 themes (along with the blue default). I think this would be sufficient by now.

**Comment by DSN9990** [comment]
I do plan to design some other themes soon.

**Comment by Wengier** [comment]
@DSN9990 Great! I will appreciate that.

**Comment by DSN9990** [comment]
@Wengier Could you give me a update named dosbox-x-update.zip (which includes the latest commit)?

**Comment by Wengier** [comment]
@DSN9990 Sure! Here it is:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

There is now a config option named bannercolortheme which allows you to change the background color of the start banner, e.g. "bannercolorthem=red" will use the red color theme. I have modified some foreground text colors that you posted above to make it look slightly better. Other than red, white and blue, I decided to extend to other background colors myself too, including black, green, yellow, magenta and cyan. Please check it out and see how it works. Thanks for suggesting this!

**Comment by DSN9990** [comment]
@Wengier Could you make the build above as MinGW SDL2 64bit? That was the one I'm using.

**Comment by Wengier** [comment]
@DSN9990 Can you try the updated MinGW SDL1 64bit build for now:

* [dosbox-x-mingw64.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64.zip)
