### ISSUE TITLE
Documentation: How to run Turrican 2 in DOSBox-X

### ISSUE THREAD

**Issue by darkstar** [joncampbell123/dosbox-x#22]
Turrican 2 doesn't work, neither in stock DosBox nor in DosBox-X.

After launching turrican.bat (which in turn launches t2.exe), the (text-mode) setup starts but the screen is mostly blank, so you cannot see what it detects. After pressing enter on what presumably means "keyboard", the screen switches to VGA and gets garbled

If you need the game files I can provide them for testing

**Comment by joncampbell123** [comment]
Interesting...

Let me know where i can download the game files. I might find a way to make it run.

**Comment by darkstar** [comment]
I uploaded it here: https://mega.co.nz/#!9gshybSQ!zQUtN_TJ7LbY6QcmJgRHrH_k7IOw73FxFxNEPBgTiCQ

**Comment by joncampbell123** [comment]
OK. Here's what I've found so far:

If you just unzip that zipfile to a directory and run it as C:, the demo screws up the way you described. The setup screen prior to the game will complain that it can't create directory TURRICAN.CFG (what?? TURRICAN.CFG is a file!).

If you instead create a subdirectory to run it from (I used C:\GAME) and unzip it there, then make drive C: one level up, then use SETUP.EXE to initialize C:\TURRICAN.CFG, then the setup program can't offer any sound cards, but if you select "-none-" for a sound card the game runs just fine, silently.

Then, it turned out that for some reason the configuration program needs to be able to write the various *.MSD files that correspond to sound cards, in order to use them. So if I (using Linux) chmod +w all the files (your ZIP archive had them all read only), then the configuration program is able to list sound cards and I can configure it to use Sound Blaster. Then the game runs fine.

Finally, I found out the demo is able to support Sound Blaster 16. What is not well explained in the configuration program is that you need to select the high 16-bit DMA channel, not the 8-bit low DMA channel. So when it offers 1,0,3,5,6,7, you need to select "5" not "1".

After all that, the game is quite playable and works fine.

**Comment by darkstar** [comment]
Hm. this is not how it works for me. I have the game in C:\T2. I run setup.exe, it tells me that I need to make changes to my config.sys, I tell it to ignore it and it asks where to install (C:\TURRICAN), and nothing related to sound pops up. After installation, the C:\TURRICAN directory is empty, but I have a C:\TURRICAN.CFG directory with a couple of files in it. Trying to run T2.exe or TURRICAN.BAT in C:\T2 results in the same error.

I didn't notice the readonly bit (it's probably because it was copied from CD) so I removed it but that still  doesn't change a thing, I still have the same "no sound" screen where I can select the empty line above the word "joystick" followed by VGA garbage.

I'll try a few things and see if I can get it to work...

**Comment by darkstar** [comment]
Ah okay now it runs. Copying everything to c:\turrican.cfg seems to have worked. However, if you try the "video setup" and screw with the frequency, it seems to break the text-mode VGA afterwards (but that's probably a minor issue)...

**Comment by heydojo** [comment]
This game works fine for me. dosbox-x-windows-20180228-135015.
I have C:\TURRIC containing only the following:

- DIR>          MSD
- DIR>          OMD
- ENGLISH.LNG
- GUS.MSD
- OVERSMPL.EXE
- PAS16.MSD
- README.TXT
- SB.MSD
- SB16.MSD
- SBPRO.MSD
- T.BAT
- T2.EXE
- TURRICAN.CFG
- TURRICAN.HSC
- WSS.MSD

The file TURRICAN.CFG contains:

``` dosbatch
CardName=Creative Labs SoundBlaster 16 
SoundDriver=SB16.MSD
Port=544
Interrupt=7
DMAChannel=5
PlayingFrequency=44100

VideoMode=60
VerticalTotal=527
VerticalCenter=490
HorizontalCenter=84

InputDevice=0
JoyCal1=535
JoyCal2=188
JoyCal3=191
JoyCal4=542
```

The file T.BAT contains:

``` dosbatch
@ECHO OFF
@oversmpl on
@set t2dir=C:\TURRIC
@t2.exe
```

The game is run by CD into C:\TURRIC and running T.BAT. Then you just press enter.
(And prepare yourself for the gorgeous synth wave title track :)

Works here with cputype=auto and ems=true but you don't need gus=true. You won't be able to test Gravis unless you have installed the ultrasnd drivers into your dosbox-x instance and you select ultra sound in the turrican config program. If you do have the ultrasnd drivers installed, it doesn't cause any trouble to leave gus=true.
To be honest, stick with the sb16 sound driver for this game.
I found that the gravis output currently produces sporadic audible popping noises along with the sound.
