### ISSUE TITLE
Big Red Racing, graphical problem!

### ISSUE THREAD

**Issue by starinspace** [joncampbell123/dosbox-x#2225]
I have played this game many times on real ms-dos pc without any problem. But something is wrong here, when I play the picture is jumping like crazy. Its okey when moving through the menu, but when the game starts it starts with this problem. It is suppose to be smoother, not this extremly jumpy.

https://youtu.be/zCWkjkpLeaM

I did try Big Red Racing (v216R) and (v227WR) + tried the patch

I don't know what version is [here](https://www.myabandonware.com/game/big-red-racing-2n8#download), but I tried it as well with same problem. I also tried the demo and still same problem.

Hope this could be fixed.

**Comment by starinspace** [comment]
I'm using the latest dosbox-x to date. Forgott to write. I use a Windows 10, 64-bit computer.

**Comment by joncampbell123** [comment]
Does this happen with MinGW builds? VS2019 builds are subject to floating point issues because Microsoft's C++ compiler does not recognize the "long double" floating point type needed to emulate the full 80-bit precision that the FPU uses internally. MinGW (based on GCC) does recognize "long double".

**Comment by joncampbell123** [comment]
There are some known issues with certain games and demoscene productions where the full 80-bit precision is needed, or else rendering issues and motion issues occur.

**Comment by grapeli** [comment]
Isn't that intentional? In my opinion, she does.
I tested it under dosbox-x, dosbox-SVN, qemu (kvm), dosemu2. It works similarly, if not exactly the same, everywhere.

The game menu itself indicates that everything is shaking here.

It will be off-road and dirt tracks. Take care, it's easy to tip over and roll over.
There is a gameplay on youtube made on pentium III under winme. It looks almost identical to the dosbox.
https://www.youtube.com/watch?v=2Eka-zFIHhQ

There is a noticeable difference between individual routes (for example - Japan and Kenya).
This is what it looks like under dosemu2.
https://drive.google.com/file/d/1hZC2Xx6ruAgI_QeU_exWfO4A3PGF87cS/view

**Comment by starinspace** [comment]
> Does this happen with MinGW builds? VS2019 builds are subject to floating point issues because Microsoft's C++ compiler does not recognize the "long double" floating point type needed to emulate the full 80-bit precision that the FPU uses internally. MinGW (based on GCC) does recognize "long double".

I have try it with MinGW build as well, Inclusive lowend, sdl1 and sdldraw.

However, DOSBox-0.65 does play it better but horrible slow!

It is suppose to look more like this:
https://www.youtube.com/watch?v=YtOtfMbgJMI

Or like this:
https://youtu.be/VHDSOXt_ZfE


> Isn't that intentional? In my opinion, she does.
> I tested it under dosbox-x, dosbox-SVN, qemu (kvm), dosemu2. It works similarly, if not exactly the same, everywhere.
> 
> The game menu itself indicates that everything is shaking here.
> 
> It will be off-road and dirt tracks. Take care, it's easy to tip over and roll over.
> There is a gameplay on youtube made on pentium III under winme. It looks almost identical to the dosbox.
> https://www.youtube.com/watch?v=2Eka-zFIHhQ
> 
> There is a noticeable difference between individual routes (for example - Japan and Kenya).
> This is what it looks like under dosemu2.
> https://drive.google.com/file/d/1hZC2Xx6ruAgI_QeU_exWfO4A3PGF87cS/view

Its a bit wierd, cause I played it not long ago, but it is suppose to "shake" a little bit, but it goes out crazy in Dosbox-x.

The last link dosemu2 does not shake so much as Dosbox-x, it looks more smooth. When playing it in dosbox-x it does shake like crazy. I do agree some shaking is suppose to be there cause its bumpy roads but, as can see on dosemu2 it does look more like its suppose to look like, how does it "shake" when the car is standing still there? Is it shaking like crazy also?

**Comment by joncampbell123** [comment]
Does it help if you increase/decrease the cycle count? I wonder if this game is just moving things with floating point based on dt (delta time) between frames, therefore the frame rate would somehow affect how well things drive or clip against ground.

Remember MS-DOS is not multi-threaded, so the game cannot just have a thread respond to keys and move cars while rendering at the same time.

**Comment by starinspace** [comment]
settings:

```
core                              = auto
fpu                               = true
cputype                           = auto
cycles                            = fixed 50000 #40000 60000   #auto ["realmode default"] ["protected mode default"%] [limit "cycle limit"]
cycleup                           = 1000
cycledown                         = 1000
cycle emulation percentage adjust = 0
apmbios                           = true
```

**Comment by grapeli** [comment]
I tried to run under Wine, which has a big problem with games in 8-bit color palette.
https://wiki.winehq.org/256_Color_Mode
The only plus is that the game starts. The main drawback is bad color mapping, there is also non-working fullscreen, poor dithering. Two different versions of wine 1.8.7 and 6.1.
https://drive.google.com/file/d/1PgwSuQbeqjk764IO6LxmafUb-x-HX_cq/view
https://drive.google.com/file/d/1QZOIYjn6xQVvn-NzTCOI1Lqf5z1EM109/view
It's hard to even judge because bad mapping has a big impact, but it doesn't differ much from the DOS version in the intensity of "shaking".

Under Win95 in DOSBox-X Big red Racing does not start (blue screen).

**Comment by starinspace** [comment]
Wine... isn't DosBox what they intergraded? So it should mostly have the same issue?

Under win95 i think it does need the latest cd-rom or patch. There were some problems on earlier release that had that problem. Or...i think it was, long time ago I read about the patch.

**Comment by grapeli** [comment]
Another video of wine-staging-6.1. It is best to see that there is no difference between dosbox here. Interestingly, the color mapping is different in each version of wine.
https://drive.google.com/file/d/1Oh4viXDGPqtmlJSFom3Rn_yiEpgKCXHB/view

**Comment by joncampbell123** [comment]
Please note that if you are using dynamic core, there is a problem with crashing whenever the MS-DOS prompt or a DOS VM is started. If you need to run MS-DOS under Windows 95 please use the normal core.

**Comment by grapeli** [comment]
Somehow I am not really interested in the Win95 version. I don't think she works better. Probably the developers have put more time into the DOS version.

This is the version downloaded from eXoDOS.
`core = normal`
![guest_os_000](https://user-images.githubusercontent.com/452325/106394274-a9172080-63f3-11eb-883a-1de1d195e1ea.png)
