### ISSUE TITLE
IPXNet seems to connect but does not appear to be working

### ISSUE THREAD

**Issue by MrMe85** [joncampbell123/dosbox-x#2240]
I regularly use ipxnet to join online multiplayer with friends on DOSBox.  One thing I've noticed with DOSBox-X's ipxnet is that, while it connects to a dedicated server, the game itself does not seem to work properly in seeing other players in a lobby--as though the connection is not actually working.  

The multiplayer game I have been testing this on is Mechwarrior 2's netmech for DOS.

There is no problem when using other DOSBox's, such as 0.74-3 Vanilla DOSBox, and DOSBox ECE.  One can see other players on the lobby.  If running two instances of DOSBox, with two separate installs of the game, its possible to see myself twice in the lobby.

This is not the case with DOSBox-X, however.  It can neither see other players, nor see itself when running two DOSBox-X instances and two separate installs.

In both regular dosbox and dosbox-x, a connection is made to the server using the command "ipxnet connect [server] [port]", and both show a connected status after the command.  The problem is that the other DOSBox's appear to work fine, although DOSBox-X does not appear to, at least when running an actual game.

Any ideas why this is the case?  I have not tested other games yet.

**Comment by rderooy** [comment]
Can you try running ``loadfix -a`` before running the game to see if it makes a difference?

**Comment by MrMe85** [comment]
Tried it, makes no difference.

**Comment by Wengier** [comment]
@MrMe85 Yes, I agree that it may be related to issue #1962. In such case just load LSL, NE2000 and IPXODI before loading IPXTEST, then it will hopefully work.

**Comment by tokariu** [comment]
Any update on this issue?
I'm using Dosbox-x v0.83.21 and I've come over the same problem trying to host a lan network game with Slipstream 5000 using `ipx=true` and ipxnet commands.
The issue is the same: the clients can connect to each other via ipxnet commands, and even ping each other, but in the game it is stuck at the network connection/sync screen - not being able to establish a handshake and start a multiplayer session. I notice high CPU-usage during the attempts to establish a connection on both PCs but nothing ever happens.

When I try the exact same thing with the classic Dosbox 0.74 it immediately works and the network session starts as soon as both PCs start to call/answer the multiplayer session.

the workaround using LSL,NE2000 and IPXODI is way to complicated for mainstream usage (if you have to explain to people without dosbox knowledge). We wanted to combine Dosbox-X new features with a working IPX emulation, now we ended up using classic dosbox.

**Comment by tokariu** [comment]
IPX emulation is really broken in these builds. 

I managed to get Slipstream5000 working over nullmodem emulation instead of IPX.
But the next thing I tried had the same problem.

Worms 1 multiplayer with IPX emulation: IPX connection is succesfully established between both dosbox's on the LAN. But when it comes to start a multiplayer IPX session with the game, the clients don't find each other. And again, trying this with Dosbox 0.74.3 works immediately. It's a dilemma, old dosbox has working IPX emulation but lacks all the dosbox-x features otherwise..

I hope the IPX emulation gets some love in the future to fix these things.

**Comment by SuperIlu** [comment]
I (re)discovered the IPX problems while working on DOjS today:
- DOOM and DOjS work fine on a dual DOSBox setup. (original, non-X version)
- ipxnet startserver, connect and status work as expected on DOSBox-X
- DOOM is not able to find the other node after pressing F10
- DOjS hangs when loading the IPX plugin. Debugging showed it hangs in the function below (using INT 0x7a, FUNC 0x09):
```
static void Get_Local_Address() {
    _go32_dpmi_registers r;

    // Clear out the registers
    memset(&r, 0, sizeof(r));
    memset(&local_address, 0, sizeof(local_address));

    r.x.bx = 0x0009;  // Subfunction 0x0009, get internetwork address
    r.x.es = segment_of_dos_buffer;
    r.x.si = offset_of_dos_buffer;

    Copy_Into_Dos_Buffer(&local_address, sizeof(local_address));
    _go32_dpmi_simulate_int(0x7a, &r);
    Copy_From_Dos_Buffer(&local_address, sizeof(local_address));

    LOGF("net  %02x:%02x:%02x:%02x\n", local_address.net[0], local_address.net[1], local_address.net[2], local_address.net[3]);
    LOGF("node %02x:%02x:%02x:%02x:%02x:%02x\n", local_address.node_address[0], local_address.node_address[1], local_address.node_address[2], local_address.node_address[3],
         local_address.node_address[4], local_address.node_address[5]);
}
```

**Comment by RetroWolf92** [comment]
> I regularly use ipxnet to join online multiplayer with friends on DOSBox. One thing I've noticed with DOSBox-X's ipxnet is that, while it connects to a dedicated server, the game itself does not seem to work properly in seeing other players in a lobby--as though the connection is not actually working.
> 
> The multiplayer game I have been testing this on is Mechwarrior 2's netmech for DOS.
> 
> There is no problem when using other DOSBox's, such as 0.74-3 Vanilla DOSBox, and DOSBox ECE. One can see other players on the lobby. If running two instances of DOSBox, with two separate installs of the game, its possible to see myself twice in the lobby.
> 
> This is not the case with DOSBox-X, however. It can neither see other players, nor see itself when running two DOSBox-X instances and two separate installs.
> 
> In both regular dosbox and dosbox-x, a connection is made to the server using the command "ipxnet connect [server] [port]", and both show a connected status after the command. The problem is that the other DOSBox's appear to work fine, although DOSBox-X does not appear to, at least when running an actual game.
> 
> Any ideas why this is the case? I have not tested other games yet.

Interesting, so this issue is actually over two years old now.

**Comment by tokariu** [comment]
> Interesting, so this issue is actually over two years old now.

the network stuff doesn't get the same love as other stuff it seems. i still miss a working ipxnet, but it was possible to use modem as a workaround in most cases, but it's still not an option in all cases.

**Comment by joncampbell123** [comment]
I see two problems here:

1. IPX is apparently using IRQ 11. That interrupt is getting masked because---
2. IPX emulation is setting up it's IRQ 11 handler, which is then overwritten by the BIOS during POST. It's setting up the IRQ 11 handler too early.

**Comment by rderooy** [comment]
Perhaps it should use IRQ10 as that is not used by default. But obviously that will not work if you only have a single PIC, as is typical on an 8086. In that case perhaps IRQ3, and just disable COM2.

Perhaps COM2 should just be disabled by default anyway. It conflicts with the NE2000 also unless you change the IRQ, and who uses two serial ports these days... (I know serial mouse and serial modem is possible, but common, no).

**Comment by joncampbell123** [comment]
No. The bug would occur no matter what IRQ. Anyway, I think I fixed it, check the latest commit. Multiplayer IPX DOOM works now, at least.
