### ISSUE TITLE
Inf. error displaying when calling a program via batch file with "absolute path" in that batch file, also current working directory is not root.

### ISSUE THREAD

**Issue by playerlin** [joncampbell123/dosbox-x#2252]
**Describe the bug**
DOSBOX-X showing "Unable to change to _directory name_" forever and softlocked.
I'm not sure if it caused by the program I'm using but not such problem in official DOSBox and SVN Daum.
I have set the program's path in "set path" on my conf's [config] section.

![image](https://user-images.githubusercontent.com/11241268/107140972-c94d5f00-6960-11eb-9cbf-77e98902f351.png)

**To Reproduce**
0. Set "the path=" on the conf file I'm using : "set path    = Z:\;C:\;D:\;D:\FPE6" , the program I'm using is in D:\FPE6\ 
    It has a batch file called FPE.BAT with parameters like this.
![image](https://user-images.githubusercontent.com/11241268/107141122-b5eec380-6961-11eb-909d-2f8da3b8be9c.png)

1. Start DOSBox-X
2. Change any current work directory path to any like D:\game\
3. Run FPE.BAT by just input fpe and press Enter to execute.
4. ...full of "Unable to change to fpe6" message like the first screenshot and cannot be stop without reset VM.

==

I can just run the main program(FPE4G.COM) and other batch file that didn't use "absolute path" as one of parameters(for its temp directory path)...and it works fine on DOSBox-X)
![image](https://user-images.githubusercontent.com/11241268/107141258-8be9d100-6962-11eb-96c8-335370d948de.png)

**Expected behavior**
Shows the normal program startup screen without any of problems. Using final build of SVN Daum as following screenshots.
![image](https://user-images.githubusercontent.com/11241268/107141366-34983080-6963-11eb-9308-1c188971e568.png)
![image](https://user-images.githubusercontent.com/11241268/107141371-437ee300-6963-11eb-8d7a-0e9901a9f40f.png)

**Environment (please complete the following information):**
 - Operating system : Win 7 Home Premium SP1 64-bits 
 - DOSBox-X release 0.83.10, VC build both SDL1 and 2(this problem also happened with older versions of DOSBox-X.
 - My conf file: 
[dosbox-x-conf.zip](https://github.com/joncampbell123/dosbox-x/files/5938533/dosbox-x-conf.zip)
The program I'm using: (I'm not sure if it working if just put it on any other system, I did "installed" on DOSBox Daum and since it still working file on DOSBox 0.74.3 and DOSBox-X then I think it should...?)
And here is the program package:
[FPE6.zip](https://github.com/joncampbell123/dosbox-x/files/5938534/FPE6.zip)
It's a cheat program like Cheat Engine and Game Wizard, a TSR program can doing memory scanning and lock or edit the values in the memory. Also has in-built CD-Player, Screenshot function with its own format(using SPE.EXE to read them) and text reader(can read Chinese Big5(ETEN) characters if provided ETEN Chinese System .15 font file on C:\ET3 by default but maybe other Chinese System font would working too...?) and BOSS Key (LOL!)
It's named FPE 2000 for DOS v1.0 as final version of DOS version. 
FPE 2000 was actually v6.0 for Win95/98(I only give the DOS version -- also installed files -- of that as it was bonus for FPE 2000's owner and the install file had protected but it has been cracked after someone in internet found out it's too easy to crack...), and it had a updated version called FPE 2001 and working on both Win95/98 and Win2000, and FPE 2001 was the final version of the program. I also have FPE v4.0(but I cannot access its files now) and v5.11, the previous and final retail version for DOS, but I never got it properly working in any of DOSBox version, for some reasons it always ask to reinstall again after restart the DOSBox.

**Comment by Wengier** [comment]
I have tried the FPE 2000 program you linked, and with your config file in DOSBox-X 0.83.10 (both SDL1 & SDL2 builds). But so far I have not yet been able to reproduce the said issue. Simply typing "fpe" when I am in the D:\GAME directory seems to work fine here:

SDL1 version:

![image](https://user-images.githubusercontent.com/8216923/107152006-a5bfef80-6933-11eb-8562-48dffd9559fb.png)

SDL2 version:

![image](https://user-images.githubusercontent.com/8216923/107152023-ba03ec80-6933-11eb-8515-83202054f51e.png)

I am using Windows 10 instead of Windows 7 for testing though. Perhaps the issue on your end is related to this or some other factor(s)?

**Comment by Wengier** [comment]
Also, the error message "Unable to change to: fpe6" as you showed in your first screenshot can only come from the built-in CD command (just calling the batch file will never display such an error). But I am unable to find any CD command in your FPE.BAT (or FPE6.BAT) batch file. Perhaps it comes from another batch file?

**Comment by playerlin** [comment]
Well, I'm not sure what's you mean about other batch file TBH...unless it tried read something from my mounted CD-ROMs(the virtual one do have a game image loaded)

And here is my D:\GAME\ directory:
![image](https://user-images.githubusercontent.com/11241268/107155825-8f5a7800-69b5-11eb-8dfb-28bbb860fbfb.png)

**Comment by playerlin** [comment]
Okay, after recheck and carefully finding, I found a other FPE.BAT on the drive D's root directory, delete it and seems the problem went gone. Still, it's weird to me...and that file already on that place long time ago but I'm not sure anymore and that file may created after properly installed FPE I think.


![image](https://user-images.githubusercontent.com/11241268/107243681-3697e780-6a68-11eb-9817-75504f3754c0.png)

**Comment by Wengier** [comment]
@playerlin Glad that you have found the cause of the problem. I also used the FPE program long time (10+ years) ago myself.

**Comment by playerlin** [comment]
Yeah, I use FPE since...hmm, 11 or 12 I think, and keep using that (FPE2001 still working in NT-based Windows after Win2000, just needed to set it Win9x level of compatibility).

Still, I would keep that file as only DOSBox-X hate that and I can just on root to call.

**Comment by Wengier** [comment]
@playerlin I think DOSBox-X's behavior is certainly correct with the the content of the D:\FPE.BAT batch file you posted. You can take another look at the D:\FPE.BAT file yourself:

```
cd fpe6
fpe.bat %1 %2 %3 %4 %5 %6 %7 %8 %9
```

Note that you are currently in the D:\GAME directory, so the command ```cd fpe6``` will clearly fail with the error message "Unable to change to: fpe6". Then the next command ```fpe.bat %1 %2 %3 %4 %5 %6 %7 %8 %9``` will run which executes D:\FPE.BAT itself again... Thus you will get the message "Unable to change to: fpe6" forever and softlocked.

The solution is to simply change the command ```cd fpe6``` to ```cd \fpe6```. Then D:\FPE6\FPE.BAT (instead of D:\FPE.BAT) will be executed by the command ```fpe.bat %1 %2 %3 %4 %5 %6 %7 %8 %9``` so that it will work correctly.

I have also tried official DOSBox and SVN Daum which will also show the same errors if you set ```SET PATH=Z:\;C:\;D:\;D:\FPE6``` manually or in [autoexec] section. But with your config file you posted the errors won't show simply because the [config] section as in your config file is specific to DOSBox-X so it has no effect in official DOSBox and SVN Daum.

Clearly all DOSBox versions hate that file, not just DOSBox-X.

**Comment by playerlin** [comment]
I do set PATH for D:\FPE6 in SVN Daum.
![image](https://user-images.githubusercontent.com/11241268/107358555-7f09e080-6b0e-11eb-8efb-cf48e2b13b9c.png)
But, didn't set the D:\ , so it never found the D:\FPE.BAT and try to run it.

If added a "\" can get it working then I think it's fine...
