### ISSUE TITLE
"dosbox-x -exit" doesn't always exit

### ISSUE THREAD

**Issue by Andrew-D0** [joncampbell123/dosbox-x#2284]
If I run "dosbox-x -exit" then it sometimes exits after the program I run has completed, but sometimes doesn't.

Steps to reproduce:

Create a batch file. I called mine "exittest.bat". At first I added one ECHO line to the batch file, but have since discovered that it can be entirely empty.

Add to [autoexec]:
`mount c ~/DOS`
`c:`
`exittest.bat`

(Where ~/DOS is the location of exittest.bat.)

Run `dosbox-x -exit`

DOSBox-X should run the autoexec and batch file then exit, but it stays running.

I originally discovered this with our Clipper application. To find a simpler test, I also tested by running "edit" and that sometimes caused DOSBox-X to stay running after closing, but not consistently. The batch file seems to show up the problem consistently.

Tested in DOSBox-X version 0.83.10 in Linux and Windows 10 20H2 64-bit.
Tested with a freshly created dosbox-x.conf, with the additions above.

**Comment by Wengier** [comment]
I think this case is a special one, because the -exit command-line option basically adds an EXIT command to the end of AUTOEXEC.BAT file, but loading a batch file (exittest.bat) without a CALL command will cause the EXIT command in the end to be ignored. This behavior is expected for a regular batch file, but unexpected for the -exit command-line option. I think I have fixed it as part of #2285.

**Comment by Wengier** [comment]
More fix is done in #2289.

**Comment by Andrew-D0** [comment]
This does appear to fix the problem. I've tested with the empty batch file and a 'real' one where I first found the problem, both now exit. Thanks!
