### ISSUE TITLE
Dosbox-x and Linux...

### ISSUE THREAD

**Issue by Irishtiger77** [joncampbell123/dosbox-x#2301]
Can I have NE2000 emulation on Linux at all?  If so, how?  

So I was reading over the requirements for using NE2000 adapter in Dosbox-x. I use Linux Mint 20+. I see a message on https://flathub.org/apps/details/com.dosbox_x.DOSBox-X that says, "Network adapter emulation: NE2000 (not for Flatpak or Snap installs)."

Linux Mint has no obvious candidate for Dosbox-x without using snap or flatpak. So am I out of luck if I want to use Dosbox-x and my main need is NE2000 on Linux Mint?  Do I have to go to an RPM-based OS like Fedora or Centos?

**Comment by rderooy** [comment]
You can have NE2000 if you compile it yourself.

The flatpak version does not have NE2000 because of flatpak sandbox limitations.

As to Fedora or CentOS, there are no official packages yet of the latest version, but it is being worked on to get it added to the official repos.

Also, be aware that NE2000 only works with Ethernet adapters. Supposedly there are some wifi adapters that support the necessary promiscuous mode, but I have not seen one in a very long time.

**Comment by Andrew-D0** [comment]
It looks like you might be able to install the RPM version in Linux Mint:
https://community.linuxmint.com/tutorial/view/821

**Comment by Jookia** [comment]
You would have to build it yourself for now. Note that I do have a PR in progress #2327 that will add TCP/UDP networking over the NE2000 to Flatpak.

**Comment by Wengier** [comment]
It is certainly great to make TCP/UDP networking over the NE2000 work in the Flatpak package.

**Comment by Jookia** [comment]
Any updates on this? It seems like it would be time to close this as the official release and I think Flatpak includes this feature.

**Comment by Wengier** [comment]
Yes, closing this now as Flatpak does support NE2000 networking in the latest release.
