### ISSUE TITLE
SDL1 vs SDL2 builds

### ISSUE THREAD

**Issue by viki-t-s** [joncampbell123/dosbox-x#2392]
Why do we have two builds? Is there any significant differences between them? I use SDL2 version on manjaro regularly, tried using SDL1 version out of curiosity. I cannot find any difference for my use cases.

**Comment by crashGG** [comment]
If you pass a large number of game tests, you will understand that the sdl1 version is more stable, and the sdl2 version sometimes crashes inexplicably

**Comment by Wengier** [comment]
DOSBox-X officially supports both SDL1 and SDL2 builds. While most things are same in both builds, there are some differences between them. If you use Windows, the differences between them are more obvious since Windows SDL1 versionAt this point there are tradeoffs between the two.

SDL1 at this point means the heavily modified SDL1 library included in the DOSBox-X source tree, which I can modify as I need to add features or fix bugs. However as of yet, touchscreen input is not supported.

SDL2 support allows DOSBox-X to benefit from the improvements, bug fixes, and feature additions offered by the actively developed SDL2 library and it allows DOSBox-X to respond to touchscreen events. However, I don't get the same flexibility to modify it as I need or want because my changes will be replaced whenever SDL2 releases another version (unless I submit the change upstream), and OpenGL support with SDL2 is not working yet.

**Comment by Wengier** [comment]
Closed since it is a duplicate of Issue #963.

**Comment by viki-t-s** [comment]
Thanks for the explanation.
