### ISSUE TITLE
Some HDD image drives mounting unsupported. "Cannot create drive from file"

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#2419]
Hi. 
Some HDD image drives mounting unsupported. "Cannot create drive from file. This operation requires DOS 7.10 or higher"
http://coraksoft1.narod.ru/scr/2021-02/161758139155_kiss_27kb.png
Dosbox Daum(2015) build mounted it normally.
http://coraksoft1.narod.ru/scr/2021-02/161758146955_kiss_11kb.png

example to test:
https://cloud.mail.ru/public/itxK/TDnvVnbL3/0Holy-Sword-GameRip-TChn-win98-dosbox.7z
or:
https://vk.com/doc-77686617_596584433

**Comment by rderooy** [comment]
As indicated by the error, if your mounting a fat32 volume you need to set your dos version to 7.1

Either in your dosbox-x config file by setting ver=7.1

Or by running ``ver set 7.1`` before the imgmount command.

**Comment by Wengier** [comment]
@Corak667 I have checked the image file you mentioned. Please note that this is a **FAT32** disk image. In fact, DOSBox-X is the only DOSBox build that fully supports this type of disk images. Do note the following:

1. DOSBox Daum appears to mount this drive, but "DIR C:" simply shows nothing. You may boot from this drive with BOOT command, but you are apparently not able to browse or change the contents of this drive from DOSBox Daum's built-in DOS shell. This is simply not supported by DOSBox Daum.

2. For DOSBox-X, please note the message it shows ("This operation requires DOS 7.10 or higher"). This simply means that you need to change the reported DOS version to 7.10 (or higher) to mount this drive, because FAT32 drives are only supported by MS-DOS 7.10 and higher versions. Try this:

```
VER 7.1
imgmount c ..\RING\win98.ima -t hdd -ide 1m
```
Then you will be able to mount and also directly access to the drive. For example, you can try "DIR C:" and you will see the contents inside the disk image. Other DOS comands (CD, DEL, MD, RD, etc) will all work as well, as if it is a FAT12 or FAT16 disk image. DOSBox-X is currently the only DOSBox build that fully supports FAT32 disk images.

**Comment by Corak667** [comment]
Ah, thank you very much. I didn't knew "VER 7.1" or "set ver 7.1" command are nessary to mount such image. 
Daum build seems already pre-set this in config.

**Comment by rderooy** [comment]
No. As wengier mentioned, daum does not support fat32, and it doesn't set ver=7.1

Daum silently continues but when you try to list the contents of the drive it appears empty.

Dosbox-x instead has full fat32 support, but for that you need to set ver=7.1 as otherwise some programs can get confused. So this is to prevent people from shooting themselves in the foot.

**Comment by Wengier** [comment]
I think @Corak667 has a point though as the message "This operation requires DOS 7.10 or higher" may cause some users to think that mounting such images is not supported instead of simply needing to change the reported DOS version. In the updated Windows binary DOSBox-X will now show a message to ask if the user wants DOSBox-X to set the required DOS version automatically in such case so that the user no longer needs to do this manually:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
