### ISSUE TITLE
spellcasting_101 does not start anymore

### ISSUE THREAD

**Issue by nickbe** [joncampbell123/dosbox-x#243]
This seems to be a bug.

**Comment by joncampbell123** [comment]
Where can I obtain this program for testing?

**Comment by nickbe** [comment]
Here: 
http://www.myabandonware.com/game/spellcasting-101-sorcerers-get-all-the-girls-10m#download

**Comment by nickbe** [comment]
btw. there also seems to be a problem with the scaler settings. 
Using ddraw with higher resolution and scaler does not seem to be working right now.

**Comment by nickbe** [comment]
Any solution to that problem yet?

**Comment by joncampbell123** [comment]
I'll try it now.

In the meantime, does running loadfix before running the game fix anything?

**Comment by joncampbell123** [comment]
Do you run the game by running S101.EXE or S101MAIN.EXE?

I can get it to run by running S101.EXE

**Comment by nickbe** [comment]
What exactly does loadfix do?
I'm startig with s101.exe.

**Comment by joncampbell123** [comment]
Loadfix allocates memory to fill the lower 64KB so that programs load above the 64KB boundary.

Some programs, especially older programs compressed by Microsoft's EXEPACK function in their linker, won't run properly if they're loaded too low in memory.

I'm running s101.exe with ems=true and umb=true, memsize=8, cputype=pentium. It seems to load fine. I can't help but notice that during gameplay it likes to allocate and free memory a lot.

**Comment by nickbe** [comment]
ok I'll try that tonight and report back to you

**Comment by nickbe** [comment]
btw. I'm playing this game with the default dosbox without problems. Only thing I've changed is the resolution.

**Comment by joncampbell123** [comment]
I'm not having any issue with the game and DOSBox-X. I'll close this soon unless a dosbox.conf configuration can be provided that makes it fail as described.
