### ISSUE TITLE
Possible to use Command.com or 4DOS shell normally (with History)

### ISSUE THREAD

**Issue by viki-t-s** [joncampbell123/dosbox-x#2459]
I am using 4DOS as shell and basically use dosbox for gaming. I have a few favorites and keep using the same. 4DOS has enhanced command history, directory history, etc., But i am unable to use any history related features because (i think) z drive is read-only. Kindly advise if there is any workaround to use 4DOS shell on a daily basis.

**Comment by rderooy** [comment]
Yes the Z:\ drive is read only. You would have to mount another drive and have it use that drive for any files it creates.

**Comment by viki-t-s** [comment]
@rderooy Thanks for the reply. Any idea how to configure that? I am pretty new to 4dos. I know that I have to possibly edit 4dos section of the dosbox-x.conf file.

**Comment by Wengier** [comment]
You can use the 4DOS shell normally of course, but for the purpose of history logs you will probably need to specify a different path that is mounted and accessible from DOSBox-X (other than Z:\), by using e.g. the HistLogName option in the 4DOS config ("4dos" section of the dosbox-x.conf file). When you are in the 4DOS shell, enter HELP command for 4DOS help, and select "4DOS.INI" => ".INI File Directives" => "Configuration Directives" for more information on relevant options.

**Comment by viki-t-s** [comment]
Thanks! Will try setting it up. Closing the question

**Comment by viki-t-s** [comment]
I tried to set the log and history to a different file with these commands but still it does not work
LogOn = Yes
HistLogName = D:\Config\4DOSHLOG
LogName = D:\Config\4DOSLOG

In addition, I see this error when I open dosbox-x
Invalid path "D:\Config\4DOSLOG"
I am pretty sure the file is there since I created them before opening Dosbox-X.

Can anybody help here?

**Comment by Wengier** [comment]
@viki-t-s The issue is related to where you mounted the drive. If you mount the D drive in the [autoexec] section of the config file, then the drive is mounted AFTER 4DOS is loaded, and in such case the D drive is not available when 4DOS is loaded, which is why you saw the error message "Invalid path "D:\Config\4DOSLOG". Instead, you need to mount the drive in [config] section of the config file (via INSTALL command) so that the drive will be mounted BEFORE 4DOS is loaded. Try something like this:

```
[config]
INSTALL = MOUNT.COM D D:\
...
```

Instead of:

```
[autoexec]
MOUNT D D:\
...
```

Hope this helps.

**Comment by viki-t-s** [comment]
Yes, it is working now. Thanks!
