### ISSUE TITLE
Save state features

### ISSUE THREAD

**Issue by mjnman** [joncampbell123/dosbox-x#246]
Hi,
please, is it possible to implement the features save state?
thank you

**Comment by joncampbell123** [comment]
It is.

Here are the challenges to save states with DOSBox-X:

- There's a lot of state to save
- It may change over time as I improve accuracy
- The save state will have to preserve pending events as well

So adding save states will require patient implementation of state save/restore for each part. For this reason I recommend that the saved data carry a version number so that older save state data can be identified and loaded properly. You bump the version number written when additional information is added to the save dump.

**Comment by joncampbell123** [comment]
Don't let my comments discourage you. Understand there's a lot to keep track of in DOS emulation. Try implementing each part one at a time.

**Comment by Corak667** [comment]
It will be a greatest feature ever. Could you look at Tae Wong sources he made for his dosbox-daum/ykhwong mod and use it as example? 
http://coraksoft1.narod.ru/emu/dos/Dosbox_daum_20140126_source.7z
http://coraksoft1.narod.ru/emu/dos/Dosbox_daum_20150125_source.7z

Also it's partly bad in ykhwong (so something there need to be fixed):
1. Crashing at some games (Abuse)
2. Can overload process memory on unknown caching (maybe compression)
3. Making compressed states only (better to make it optional, so it will be faster for big mem-games)

**Comment by joncampbell123** [comment]
Save/load state handling has been implemented since this issue was opened, though it's very basic at this time.
