### ISSUE TITLE
Adding an option in configuration panel to deactivate prompt-folder feature

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#2464]
**Is your feature request related to a problem? Please describe.**
Since prompt folder feature was added, when I launch dosbox-x using its desktop icon, I get the prompt folder dialog, even after setting the path in the configuration file.

**Describe the solution you'd like**
Like you add an entry to set up working folder path, adding a checkbox  to activate/deactivate prompt folder dialog will be awesome.

**Describe alternatives you've considered**
None

**Additional context**
Prompt folder feature as it is set up on April 20th, 2021 is really annoying. I'm using a build based on revision e4658fb2abe4166ee3d96e2b1977e141c2342054

**Comment by Wengier** [comment]
@FredBezies There are currently already config option(s) to change this behavior, by setting the following in the dosbox-x.conf file in the DOSBox-X program directory or the user config directory:

``
working directory option: Select an option for DOSBox-X's working directory when it runs.
working directory default: The default directory to act as DOSBox-X's working directory.
``

For example, you can set ``working directory option=program`` to auto-select the DOSBox-X program directory as the working directory without prompting the folder at start.

Apart from this, I am thinking about the possibility of a dialog box to ask the user whether to "save" the folder they selected for the first time the file selection dialog shows up, and in such case the setting will be saved to the above config options (``working directory option`` and ``working directory default``) by DOSBox-X automatically.

**Comment by FredBezies** [comment]
[...]
> For example, you can set `working directory option=program` to auto-select the DOSBox-X program directory as the working directory without prompting the folder at start, or `working directory option=custom` along with the `working directory default` option for any custom path.

Setting custom and the path I want and there is no more the dialog box jumping to my eyes. Thanks for the info.

> 
> Apart from this, I am thinking about the possibility of a dialog box to ask the user whether to "save" the folder they selected for the first time the file selection dialog shows up, and in such case the setting will be saved to the above config options (`working directory option` and `working directory default`) by DOSBox-X automatically.

Please, do so. This is the kind of dialog you don't like to see more than once.

**Comment by Wengier** [comment]
@FredBezies See PR #2466, which allows to save the folder that user have selected to the above settings in global config files automatically.

**Comment by joncampbell123** [comment]
@Wengier The whole idea for the folder prompt, especially for GUI-based users, is that they can start the emulator and select the game to play. From what I understand of your code, if they select 'save' either accidentally or intentionally, their GUI driven approach (launch from the Finder or from the Windows start menu) will always go to that game. The intent is to prompt for a folder from that point so they can pick any game on their drive.

Again, the code as written has two options to avoid the prompt: Add --nopromptfolder to the command line when running DOSBox-X, or place a dosbox.conf or dosbox-x.conf in the current working directory where you run DOSBox-X. Either one causes DOSBox-X to skip the prompt.

My understanding is that users accustomed to DOSBox SVN already put a copy of the executable in the same folder as the game along with dosbox.conf, which is why it skips the prompt if that file is in the current working directory.

Mac users who run it from the Finder, and Windows users who run it from the Start menu, are probably going to want to choose the game to run, therefore they need the folder prompt.

Frontends can pass --nopromptfolder to unconditionally skip the folder prompt, as can tech savvy Windows users who probably make their own .BAT files to run DOSBox-X anyway.

Asking the user after the folder prompt if they want to save means two prompts, therefore you've made it *worse* and *more annoying*. It encourages the user to save a default path just to get it to shut up, but then when they launch DOSBox-X it always runs that one game. I am perfectly fine with a global configuration file that tells DOSBox-X to skip the prompt and/or a default path, but that should not be made the default.

When you run a ROM image in, say, Gens, or SNES9X, the emulator doesn't automatically load and run any specific ROM (unless you set up a .BAT file or shortcut link to tell it so on the command line of course). It lets you browse for the ROM to run, and then runs it. Understand?

**Comment by Wengier** [comment]
@joncampbell123 The code asks whether to save the folder selection _only in the very first time_, for those who hopes to make the selection fixed. If they select "No", the code will never ask whether to save again. Even if the path is already saved to a global config file, you can change it easily by e.g. setting "working directory option" to "prompt" or "autoprompt". it is highly customizable, as everything can be always modified by changing the two settings in the config file. But new users may not know the existence of such options at all, that is why the code will ask whether to save the folder selection _once_.

**Comment by joncampbell123** [comment]
@Wengier Ah, my misunderstanding then. I'll merge it in.

**Comment by FredBezies** [comment]
> @FredBezies See PR #2466, which allows DOSBox-X to save the folder that user has selected to the above settings in global config files automatically.

I built dosbox-x with this PR, and it worked perfectly. No more dialog asking on start to set the working directory. Thanks a lot!
