### ISSUE TITLE
Increase/decrease TTF font size - add a hotkey

### ISSUE THREAD

**Issue by ptakgit** [joncampbell123/dosbox-x#2480]
Is it possible add a hotkey into the main DOSBOX menu for items Increase/decrease TTF font size? 
The VDOS use Win+F12 and Win+F11 keys.
Controlling the size of the window using the keys is more convenient for the knowledgeable user than selecting from the menu. 

![DOSBOXMenu](https://user-images.githubusercontent.com/60302325/116007287-54103280-a60f-11eb-819c-95915235945b.png)

VDOS:
![VDOSMenu](https://user-images.githubusercontent.com/60302325/116007291-583c5000-a60f-11eb-99f6-30224b6c1d05.png)

Thank you

**Comment by Wengier** [comment]
Sure you can! Even if they are not assigned to hotkeys in the default DOSBox-X setting, you can indeed assign _any_ shortcuts you want to the "Increase TTF font size" and "Decrease TTF font size" functions in DOSBox-X's Mapper Editor (on the other hand, the shortcuts are fixed in vDos). Just go to "Mapper editor" from the "Main" menu, select ""Increase TTF size"/"Decrease TTF size" and add shortcut(s) to them. Click "Save" and "Exit" once finished and the assigned hotkeys will be saved for current and future sessions. Hope this helps.

**Comment by ptakgit** [comment]
Thank you. But if I understand well, Win+F11 are not acceptable . Or yes? Only Ctrl, Shift and Alt modifiers are supported, not Win?

Can I also translate the main form DOSBOX menu items (see the first picture above)? I didn't found this items in the message.txt.

**Comment by Wengier** [comment]
@ptakgit You can indeed assign the hotkey to Win+key if you want. There are 4 modifiers in the mapper editor, namely "Mod1", "Mod2", "Mod3", and "Host". They correspond to "Ctrl", "Alt", "Shift", and "F11" (on Windows systems) by default, but you can in fact change these modifiers as well. For example, you can assign "Host" to the Win key if you desire, so that Host+key becomes Win+key.

If you want to translate the DOSBox-X system menu as shown in your first picture, please check out the updated Windows binary below, and the text shown in the system menu will be the same as the text shown in DOSBox-X's drop-down menus (with or without translations):

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by ptakgit** [comment]
Great. It works. Now I at last understand the concept of the key mapper. It was unclear for me, how to work with modifiers. Maybe this sample could be included into wiki documentation.
If I can help you with anything, write me - redlich@redlich.cz. But I am not a C++ programmer and my english is very simple with Google translator help.
