### ISSUE TITLE
Regression: Giving an emulation path on the command-line is ignored

### ISSUE THREAD

**Issue by tonypdmtr** [joncampbell123/dosbox-x#2493]
Giving the emulation path on the command line would start emulation in that path.
Now, it either always asks or always goes to the same directory.

**Comment by joncampbell123** [comment]
It should not prompt if there is a dosbox.conf in the current working directory. At least when I modified that code...

**Comment by Wengier** [comment]
@tonypdmtr I am not quite sure if you are talking about the -defaultdir command-line ption? It appears to work fine for me with the latest code...

**Comment by Wengier** [comment]
@tonypdmtr If you are instead talking about ```dosbox-x <dir>```, then DOSBox-X should not prompt if there is a dosbox.conf or dosbox-x.conf in the current working directory as @joncampbell123 stated. I have also confirmed this with the latest code. You can use ```dosbox-x <dir>``` in combination with -defaultdir option as well.

**Comment by tonypdmtr** [comment]
Previous versions I would (under Windows) go to any directory and type "dosbox ." and it would start in that directory.
This no longer works.

**Comment by tonypdmtr** [comment]
> It should not prompt if there is a dosbox.conf or dosbox-x.conf in the current working directory. At least when I modified that code...

From the above, I guess this behavior was changed in the last release.

However, I don't see why providing an explicit path should bother with the existence of the conf file, and not take the built-in defaults or a conf file from the same path as the executable.

I can see this behavior making sense if giving no path at all or having a predefined path but when I explicitly say I want to run in "this path" having to first create a dummy conf file is annoying.

**Comment by Wengier** [comment]
@tonypdmtr Yes, this is changed behaviour rather than regression. However, please note the difference between the concepts of DOSBox-X’s working directory and the starting directory inside DOSBox-X’s shell. The command ```dosbox-x <dir>``` simply sets the starting directory inside DOSBox-X’s shell, rather than providing a working directory for DOSBox-X. On the other hand, the command-line option -defaultconf sets the working directory for DOSBox-X.

You see that DOSBox-X asks for a directory when it starts if there is no a dosbox-x.conf or dosbox.conf in the current working directory. Just select a directory from the file browser, answer “Yes” to save the working directory, then DOSBox-X will not ask again, and the selected directory will become the working directory for DOSBox-X in future sessions. Once again, the concept of working directory is different from starting directory inside DOSBox-X’s shell, so they do not conflict with each other. Hope this helps.

**Comment by tonypdmtr** [comment]
>The command dosbox-x <dir> simply sets the starting directory inside DOSBox-X’s shell

Exactly.  That's what stopped working.  But I know see where the problem/regression is.
It used to be that when I was inside some directory (say, c:\temp) and I gave the command `dosbox .` (notice the dot for current directory) the shell's starting directory would be c:\temp (as c:\ inside the emulator).

Now, the same command takes me to a predefined dir set during the prompting stage.
However, if I give the path explicitly (i.e., dosbox c:\temp) it works.
So, the regression is that a relative path (a dot) is taken to mean the predefined directory.  Perhaps, the emulator first switches to the predefined directory and *then* tries to interpret the user provided path (a dot).  Therefore, starting from any directory will not interpret dot as the directory the user was in when giving the command but rather the predefined one.

If my observation is correct, I think this is a now promoted to a bug!

**Comment by Wengier** [comment]
@tonypdmtr I don't think it is a bug, but the way it works *with the current setting you have*. Since you have pre-set a directory as the DOSBox-X working directory, the dot "." refers to that working directory. If you instead want "." to refer to the current directory when you run DOSBox-X, you just need to do either of the following:

1. Start DOSBox-X with the following:

```dosbox-x . -defaultdir .```

With the above the current directory you start DOSBox-X will become the working directory, and "." refers to this directory.

2. To make the above permanent by change the setting of the following option in the *global* config file for DOSBox-X:

```
[dosbox]
working directory option  = noprompt
```

With the above setting, DOSBox-X will never prompt for a working directory, and the working directory always refers to the current directory when DOSBox-X starts.

Hope this helps.

**Comment by tonypdmtr** [comment]
I find this awkward and certainly different from how it used to be.  I have multiple DOS 'roots' (unzip a file to a new directory, run a program, delete the directory) so I have to type this long extra thing to make it understand `.` is what it understood correctly in previous versions. (OK, I could make a batch file to bypass the problem but still, doesn't feel right.)

And why `dosbox . c:\temp` works and not require `dosbox . c:\temp -defaultdir c:\temp` ?

**Comment by Wengier** [comment]
@tonypdmtr ```dosbox-x c:\temp``` works because it refers to an absolute path, so the predefined working directory won't affect it in any way; on the other hand, a predefined working directory will change what "." refers to.

Glad to hear that you solved it by using the "working directory option  = noprompt" option as mentioned above.
