### ISSUE TITLE
clipboard with diacritics - need be converted from local CP to the windows CP

### ISSUE THREAD

**Issue by ptakgit** [joncampbell123/dosbox-x#2503]
I tested some clipboard functions in the Czech language settings and there is missing convertion from CP 852 (DOSBOX-X CP) to Windows CP 1250.
For example this part of the screen is saved to the clipboard by menu item "shared clipboard function - quick edit: copy on select and paste text"
![852Screen](https://user-images.githubusercontent.com/60302325/116877396-2da95300-ac1e-11eb-8cfe-da773c23ad89.png)
after paste from clipboard into the notepad is text with wrong diacritics chars: 
![1250Screen](https://user-images.githubusercontent.com/60302325/116877567-6812f000-ac1e-11eb-9387-9dd8330c25ec.png)

**Comment by Wengier** [comment]
@ptakgit The current code directly converts the DOS code page to Unicode (UTF-16). So please make sure the encoding in your text editor is in Unicode rather than Windows CP 1250. I don't have Czech version of FoxPro, but I tried to copy the translated Czech messages to Notepad with Unicode encoding and it appears to paste fine here.

![image](https://user-images.githubusercontent.com/8216923/116920262-677b5900-ac20-11eb-9754-423b08ea1dfb.png)

**Comment by ptakgit** [comment]
It was the same problem on my side - the codepage didn't set correctly to CP852, sorry. I use separated keyboard driver for fast switching between czech and english keyboard, so I don't use the KEYB command (resp. only for KEYB us).

Result - maybe could be best solution to explain how to set correctly the codepage with all possibilities in documentation (+ examples). Or to expand possibilities to set CP also in the COUNTRY command.

Thank you.

**Comment by Wengier** [comment]
Closing since it seems no longer a problem.
