### ISSUE TITLE
Using mouse arrow ICON instead of block pointer in QB/QBX/VBDOS and MS EDIT applications et al.

### ISSUE THREAD

**Issue by Jesae09** [joncampbell123/dosbox-x#2540]
When using the text applications specifically QB style IDE.  The cursor is shown as a text block (very ugly).  However in vdos-plus it is shown as a pointer ICON.  Functionally they are both the same except the pointer ICON is much nicer to view as opposed to the text block shown in the QB/VBDOS IDE.  This behavior is also show in the DOS version of EDIT.EXE and probably other such programs.  Maybe I am missing a setting?  But I have been unable to find that setting.  Also, I don't remember if that was the default in vdos-plus or if there was a setting to change it.

**Comment by Wengier** [comment]
Mouse support in vDosPlus is actually very simplistic - indeed, mouse support is DISABLED in vDosPlus by default, and the mouse icon you saw is just the exactly same icon used by Windows itself. On the other hand, the mouse support is enabled by default in DOSBox-X, and the mouse cursor you see in DOSBox-X is the actual mouse cursor you will see when using these IDEs in DOS. DOSBox-X tries to emulate these functions properly as if you are using a real DOS system, instead of just giving you the Windows mouse icon (note that unlike vDosPlus, DOSBox-X is a cross-platform DOS emulator and does not rely on Windows-specific functions). You will get the exactly same mouse cursor if you run these IDEs in virtual machines too. Hope this helps.

**Comment by Wengier** [comment]
In case you still prefer to just use the system mouse cursor instead of drawing the actual DOS mouse cursor, please check out the updated DOSBox-X Windows binary below. With the setting `usesystemcursor=true` you will get the Windows mouse cursor for your IDEs instead, similar to vDosPlus. Hope this helps.

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Jesae09** [comment]
Thank you for the swift response!!!  I did try the version you suggested. It works just as you describe.  Setting `usesystemcursor=true` shows the windows mouse cursor.  So much nicer than the one shown by the DOS QB/VBDOS IDE.  Now with True Type set and your fix for the mouse the QB/VBDOS IDE is very usable.  **Question:** Will this setting be in the next program updates?  So if I update to subsequent releases it will also have that switch?
FYI: Your setting does not take effect immediately like some other command changes.  I needed to reboot/restart DOSBox-X.  No big deal.  Just wanted you to know if you were aware of this.  

Love DOSBox-X so far!  I have only been using for a regularly few days but it is great for development and support of these older QB/VBDOS programs.  Was using VDOSPlus before that but it was not properly showing 50 Lines in the DOS programs.  DOSBox-X does that perfectly.

**Comment by Wengier** [comment]
Thanks for your support! Yes, DOSBox-X does intend to support such programs and development tools well (on the other hand, vDosPlus was not primarily designed for such programs). Newly added options will generally appear in future versions as well, although settings like this will not be enabled by default (c.f. mouse support is disabled in vDosPlus too), but can be modified by users as needed. Also, at this time only some of the config settings can be changed at run-time indeed. It is impossible to make all settings changeable at run-time, but I do hope more config options can be changed this way in the future. Thanks again.

**Comment by Jesae09** [comment]
The feature you added for the cursor arrow has been working great!  No problems with it I can see.  I do notice that if unusual screen sizes are used in text mode that the mouse is not pointing to the actual mouse position.  But I believe it is because the IDE does not support those sizes.
