### ISSUE TITLE
DOSBox-X 0.83.13 silent install/uninstall

### ISSUE THREAD

**Issue by phrossignol** [joncampbell123/dosbox-x#2542]
Hello,
I want to create a WPKG (silent software deployment tool) package for DOSBox-X.
For the silent install the following command line seems to work correctly ... and silently:
**dosbox-x-windows-0.83.13-setup.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES**
First question : Is there a command line parameter allowing to choose the installation directory (for example C:\TEST) instead having the default installation directory C;\DOSBox-X ?
For the silent uninstall the following command:
**unins000.exe /VERYSILENT**
displays a window asking "Do you want to keep the configuration file dosbox-x.conf ?" .
Second question : how to avoid this windows to have a fully silent uninstall ?.
Many thanks for some help ...

**Comment by Wengier** [comment]
@phrossignol Sure, the Setup itself has a command-line option /DIR to set the installation directory. For example, if you want to install DOSBox-X to C:\TEST as you said, you can use the following command-line:

`dosbox-x-windows-0.83.13-setup.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /DIR="C:\TEST"`

You can see a full list of options from:

https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

Also, I have updated the installer so that when you run the command `unins000.exe /VERYSILENT` no more window will pop up. Hope this helps.

**Comment by phrossignol** [comment]
Sounds good ... Many thanks for your help.
