### ISSUE TITLE
DOSBox-X deployment

### ISSUE THREAD

**Issue by phrossignol** [joncampbell123/dosbox-x#2545]
Two problems encountered when using software deployment tool WPKG. 
WPKG process checks the installed software version against newest version. The installed DOSBox-X version cannot be checked due to both problems:
1. No version number is available for executable file DOSBox-X.exe (easy to improve ...).
2. DOSBox-X application is not listed in Program and Features uninstall list. The uninstall registry key is created in HKCU instead HKLM. I tried to install with /ALLUSERS command line parameter which might solve the problem but without success.
Many thanks for your help.

**Comment by Wengier** [comment]
@phrossignol Thanks for the feedback. Please check out the updated installer below, which hopefully solves both problems:

* [dosbox-x-windows-0.83.13-setup.exe](http://cndos.fam.cx/dosware/dosbox-x-windows-0.83.13-setup.exe)

1. The DOSBox-X version number is now saved in the registry key HKCU\Software\DOSBox-X\Version (or HKLM\Software\DOSBox-X\Version for the as administrative install mode), which your tool can use to check.

2. The previous installer was created using Inno Setup 5 which did not support the /ALLUSERS command line parameter (or administrative install mode). The installer above has been updated to use Inno Setup 6 which should now support this so that you can use the /ALLUSERS command line parameter to enable administrative install mode.

Hope this helps.

**Comment by phrossignol** [comment]
Everything runs fine !!!. Many thanks again for your help ...
