### ISSUE TITLE
Issue in Configuration Tool

### ISSUE THREAD

**Issue by Dalekamistoso** [joncampbell123/dosbox-x#2548]
BUG:

When using a "TrueType Font" video output and you invoke "Configuration Tool" go to any configuration option than requires typing, whe you try to type anything the keyboard mapping is messed up and renders it unusable.

In detail when you try to delete a word you obtain a special character the same while typing, pressing F and G return number 3 for example, no matter if you are using a customized or default dosbox.conf configurations SDL1 and SDL2 versions are affected.

Versions affected: 

All I have tried almost all versions from the last year and a half (probably earlier are affected too but I did not tested those).

OS tested:

This affects all versions (x86/x64) I have tested under a spanish Windows 10 LTSC / Windows 10 Pro 1909 64 bits version.

The bug is not present under under a native japanese Windows 7 Enterprise SP1 32 bits version.

1. Go to 'Main->Configuration Tool'
2. Click on for example 'Main'
3. Scroll down to any option that requires typing a 'command/parameter'
4. Try to delete the current value and type something

Correct behaviour:
![bug-001-surface-output-no-issues](https://user-images.githubusercontent.com/67012746/119372659-d7c54980-bcb7-11eb-82ee-42eb90e34fd2.png)

Bugged behaviour:
![bug-002-truetype-output-issue](https://user-images.githubusercontent.com/67012746/119372661-d85de000-bcb7-11eb-9d5c-b4f04ab506dc.png)

The issue *only happens* if Truetype video output is selected the rest works fine.

Thanks in advance for your time :)

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for reporting! I have checked this, and found the said issue could indeed happen, although not on all systems. The issue has nothing to do with the TrueType font output itself, but it is related to the recent scaling feature introduced since DOSBox-X 0.83.11. The issue happens when the TrueType font output is enabled on your computer only because the window size of the TrueType font output is usually larger and thus triggers scaling of the Configuration Tool. I think I have fixed this, and please check out the updated Windows builds:

* Visual Studio SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Visual Studio SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Dalekamistoso** [comment]
Issue has been solved in both builds 👍
