### ISSUE TITLE
[Japanese language] Menu translations

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#2554]
I'm trying to prepare a Japanese translation, however, Dosbox-x menu seems that it cannot handle Japanese characters.
I tried file-encoding both UTF-8 and Shift-JIS but it doesn't display properly. 
The screenshots below shows something, but not Japanese.
Are there any other settings that I have to change?
Thanks in advance.

Language file encoded in Shift-JIS
![translations2](https://user-images.githubusercontent.com/68574602/119784509-3d5c4480-bf09-11eb-97cb-ce5cf00d2af6.png)

Language file encoded in UTF-8 (PC-98 mode)
![translations](https://user-images.githubusercontent.com/68574602/119784011-c1fa9300-bf08-11eb-8122-d42af4f86349.png)

**Comment by Wengier** [comment]
First of all, thanks for preparing a Japanese translation.

There are 3 types of menus in various DOSBox-X builds, namely Windows SDL1 menu, macOS NSMenu, and SDL-drawn menu. The first two types of menus should support Japanese characters just fine (with the latest code). The last one (used by Windows SDL2 and Linux builds) unfortunately not at this time. Also, please make sure to use the latest DOSBox-X 0.83.14 testing builds for the Japanese translations, not DOSBox-X 0.83.13 release version, as version 0.83.14 (to be officially released by the end of month) improves CJK support significantly, especially for TrueType font (TTF) output (set `output=ttf` and a Japanese TTF font e.g. `ttf.font=UnifontFullMediumMono.ttf`), and set `country=81,932` so that Japanese support should work for all machine types, not just PC-98 mode.

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by Wengier** [comment]
@maron2000 Below is a screenshot showing latest DOSBox-X 0.83.14 Windows SDL1 build with Simplified Chinese translation:

![image](https://user-images.githubusercontent.com/8216923/119788295-056ce700-bea0-11eb-9cdb-265b976b77f3.png)

**Comment by maron2000** [comment]
Tested the DOSBox-X 0.83.14 Windows SDL1 build, and confirmed the menu shown in Japanese.
It's a huge improvement than the present version!

There are some glitches when using half-width Kana, as shown in the first line of the screenshot below.
Also, when a line exceeds 80 columns there are glitches probably because of a hyphenation issue of multi-byte characters at the end of the line. (found in the 8th row explaining overlay option)

![translations4](https://user-images.githubusercontent.com/68574602/119832638-567ce980-bf39-11eb-96e0-298241a2ccbf.png)

**Comment by Wengier** [comment]
@maron2000 Glad to hear that you confirmed that the menu now shows correctly in Japanese, and also thanks for pointing out the half-width Kana. I have added a new config option "ttf.halfwidthkana" in the code so that when you set it to true, then half-width Katakana will be displayed instead of upper ASCII characters A1-DF even for standard (non-PC98) modes with code page 932. Do note that by doing so there will be no longer ASCII box-drawing characters available as they are replaced with half-width Katakana. But you can toggle this option from the menu dynamically ("Video" => "TTF options" => "CJK: Allow half-width Japanese Katakana").

A screenshot showing the ASCII characters with half-width Katakana (code page 932) using UnifontFullMediumMono.ttf uploaded by @roytam1 earlier.

![image](https://user-images.githubusercontent.com/8216923/119916250-2bdb6280-bf32-11eb-9633-a76e579b6c7e.png)

The updated Windows SDL1 build based on the latest code:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Meanwhile, you can certainly upload your Japanese translation file for us to test out too, even if it is not yet finished. I am sure many people hope to see DOSBox-X with full Japanese interface.

For the Japanese keyboard, do you mean PC-98 mode or in general? In PC-98 mode the Japanese keyboard layout is always used (unless you set `pc-98 force ibm keyboard layout = true`), even for SDL1 builds of course. I don't have a Japanese keyboard to test myself, but I do notice the apparent differences between the setting `pc-98 force ibm keyboard layout = true` and `pc-98 force ibm keyboard layout = false` when I type various special keys on the keyboard, for both SDL1 and SDL2 builds.

As for lines exceeding 80 columns and happen to split DBCS characters, I suspect it may cause similar glitches in real DOS systems too, but you can always force a new line (inserting a "\n" for example) in such case so that they will be displayed correctly.

**Comment by maron2000** [comment]
@Wengier 
Thanks for your update.
I'll check your comments later on.
Meanwhile, I uploaded the present version of my Japanese translation [here](https://github.com/maron2000/dosbox-x/tree/ja_translation/contrib/translations/ja).
It's not finished, and I haven't proof-read it, but it may help anyway.

**Comment by Wengier** [comment]
@maron2000 Thanks for the Japanese language file! I see that the menu is almost fully translated, so are help messages of some DOS commands. Keep up the great work!

**Comment by maron2000** [comment]
I noticed that if I display DOS command help from the menu, it switches to full-screen mode and shows help as the screenshot below.
The font is not the TTF font set in config, and therefore seems to fail to display Japanese characters.
I don't think to fix this is an urgent matter, but I think it better that DOSBox-x don't switch to full screen just to show a help.

BTW: The Japanese translation is mostly finished, though we have to check the alignment of words, etc.
![translations5](https://user-images.githubusercontent.com/68574602/120126790-59f1c880-c1f8-11eb-9af4-e77fa9fc79ec.png)

**Comment by maron2000** [comment]
@Wengier
Regarding the SDL1, SDL2 matter, the SDL1 version omits some keys in the Japanese keyboard.
Your 0.83.14 SDL1 pre-release provided above seems that the problem is resolved to some extent, and I have no critical problems so far in using the SDL1 version.
However, keys such as "Katakana/Hiragana" key is still not recognized in the mapper tool, and I cannot allocate the key to a certain function.
This issue is applicable not only to PC-98 mode but the normal mode as well.

This is not related to the title of this thread, so may be I should start a new thread for this matter.

**Comment by Wengier** [comment]
@maron2000 Thanks for reporting. Yes, it is a known issue that the Configuration Tool interface (and SDL drawn menu) does not support DBCS characters at this time, although I had improved its compatibility with other SBCS code pages (e.g. 852 and 858) recently. We had also discussed that it may be possible to apply FreeType support to them so that they will support CJK characters too, but this will require more significant code changes and will not be included in the upcoming version.

The reason that the DOS command help function switches to full-screen mode automatically is that the DOSBox-X window size when in a windowed mode may be small, and in such cases the DOS command help window may only be shown partially. But I have changed the code so that if the DOSBox-X window is already maximized, then there will no longer be a full-screen switch.

For the Japanese keyboard, it is indeed a separate issue really. I don't have a Japanese keyboard myself, and below is a screenshot from the SDL2 build, and I wonder which key(s) you refer to above:

![image](https://user-images.githubusercontent.com/8216923/120130323-e5853e00-c193-11eb-9d72-5355fd9597d5.png)

You can certainly open a separate thread with more such information. Thanks.

**Comment by Wengier** [comment]
@maron2000 Great to see that you have already finished the Japanese language translation by now (https://github.com/joncampbell123/dosbox-x/pull/2564). Well done!

**Comment by maron2000** [comment]
@Wengier 
Thank you for your prompt response to my pull request.
There are a few items not translated, and I want to clarify what it actually means before translated.

1. :MENU:pc98_allow_4partitions
    Allow 4 display partitions in graphics layer
I want to now what display partitions means.

Regarding the 2 options in the "Debug" menu, I propose to put Japanese saying:
:MENU:debug_pageflip
# page flip debug line -> Display debug line (Write CRTC Register)
デバッグ用ライン表示 (CRTCレジスタ書込み)
.
:MENU:debug_retracepoll
# retrace poll debug line　-> Display debug line (Read CRTC Status)
デバッグ用ライン表示 (CRTCステータス読取り)

It may be too long to display in the menu, so I appreciate your advise for this.

**Comment by joncampbell123** [comment]
@maron2000 PC-98 video hardware uses a video chipset by NEC that allows the display to be divided into "partitions" as defined by values written to a 16-byte RAM region on the device.

![Firefox_Screenshot_2021-05-31T15-10-27 455Z](https://user-images.githubusercontent.com/6245486/120213179-c4e6d380-c1e7-11eb-847d-ed9170ad7e39.png)

See also page 7-8 of this PDF file:

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20NEC%20PC%2d98/Video/NEC%20High%2dPerformance%20Graphics%20Display%20Controller%207220/%c2%b5PD7220%2c%20%c2%b5PD7220%2d1%2c%20%c2%b5PD7220%2d2%20Graphics%20Display%20Controller%2epdf

**Comment by Wengier** [comment]
@maron2000 These menu items were added by @joncampbell123 earlier, so you can take a look at his explanations. Meanwhile, I have updated the Japanese language file slightly, and you can certainly check it out.

P.S. I decided to buy a USB Japanese keyboard to try out myself, but the (international) delivery will take some time of course.

**Comment by maron2000** [comment]
@joncampbell123 @Wengier 
Thank you for your comments. 
I understood the meaning of the 4 partition option, that it enhances the scrollable partitions of graphic mode of GDC from two to four. 
I believe that text mode of actual GDC already allows four partitions by default,
according to the [uPD7220A Users manual](http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20NEC%20PC%2d98/Video/NEC%20High%2dPerformance%20Graphics%20Display%20Controller%207220/%c2%b5PD7220%2c%20%c2%b5PD7220A%20Users%20Manual%20%281985%2d12%29%2epdf) provided at the same site you pointed out.

If my understanding is correct, I'll translate the option like:
GDCのグラフィック分割領域を4つに拡張 (Enhance graphic partitions of GDC to four)

**Comment by Wengier** [comment]
@maron2000 I have updated this translation already, but please free feel to make further updates to the language file.

**Comment by Wengier** [comment]
With the release of DOSBox-X 0.83.14 support for Japanese language is improved further significantly (compared with earlier release versions), and the Japanese language file is available from [contrib/translations/ja/ja_JP.lng](https://github.com/joncampbell123/dosbox-x/blob/master/contrib/translations/ja/ja_JP.lng). @yksoft1 may be interested in it too.

**Comment by maron2000** [comment]
I'll close this issue, since translation of most of the items are finished.

**Comment by Wengier** [comment]
@maron2000 Thanks for the Japanese translation. Also, I would like to let you know that the Windows SDL2 build (and Linux builds, both using SDL-drawn menu) now supports Japanese menu text as well (as long as it is not using OpenGL output). The updated Windows SDL2 build of DOSBox-X build is available from:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

A screenshot using your Japanese language file:

![image](https://user-images.githubusercontent.com/8216923/121727925-9061fa00-caba-11eb-8f3e-4ca24a69a795.png)

**Comment by Wengier** [comment]
@maron2000 Furthermore, the DOS command help (which uses the Configuration Tool interface) should now show CJK characters too. An screenshot is available below:

![image](https://user-images.githubusercontent.com/8216923/121754026-915a5200-cae1-11eb-98da-d9e4d56630c7.png)

In addition to the updated Windows SDL2 build above, the updated Windows SDL1 build is also available from:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by roytam1** [comment]
> A screenshot using your Japanese language file:
> 
> ![image](https://user-images.githubusercontent.com/8216923/121727925-9061fa00-caba-11eb-8f3e-4ca24a69a795.png)

I think you did notice there is some kanji displayed glitchy

**Comment by Wengier** [comment]
> I think you did notice there is some kanji displayed glitchy

The first screenshot was intended to show the menu text in the menu bar, but I yes did notice the glitches in some Kanji of the welcome banner messages after I posted the screenshot. It was due to a bug in the border-character replacement code which has already been fixed, and the Windows binaries have been updated accordingly.

> and at least first line of kanji is not displayed in dialog.

This is because the Configuration Tool expects fonts of 14-pixel height, but the Japanese fonts to be used are 16-pixel height. I think it is the best result that can be achieved for now since it is not really noticeable I think.

**Comment by Wengier** [comment]
A new screenshot showing both the welcome messages and the SDL-drawn menu in Japanese DOS/V mode:

![image](https://user-images.githubusercontent.com/8216923/121762529-72b98280-cb04-11eb-87ab-0a05a7698892.png)

And when using the JEGA machine and TrueType font (TTF) output:

![image](https://user-images.githubusercontent.com/8216923/121762581-c2984980-cb04-11eb-90df-cd84096c588a.png)

**Comment by maron2000** [comment]
@Wengier 
Hi, very nice to see a SDL2 version supporting menu in Japanese!
Here is a [link](http://izumilib.web.fc2.com/sinonome/shn14fx2.lzh) to a 14dot bitmap Japanese font. 
It's a public domain font converted to FONTX2 style, where the original can be found here ([http://openlab.ring.gr.jp/efont/shinonome/](http://openlab.ring.gr.jp/efont/shinonome/))

**Comment by Wengier** [comment]
@maron2000 Thanks for providing a 14-dot bitmap Japanese font! Since at this point it may only be used by DOS command help (and nothing else), I am not sure if integrating another DBCS font is a good idea at this time (but it will probably be so when the Configuration Tool becomes fully translatable). In any case, I have already added a "jfontdbcs14" config option (similar to other similarly-named config options in [render] section) which allows you to load such a font, and in this case this font file will be used instead of the default 16-dot bitmap Japanese font. Both Windows SDL1 and SDL2 builds have been updated accordingly:

* Windows SDL1: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

* Windows SDL2: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Wengier** [comment]
A screenshot showing the DOS command help with the use of this font:

![image](https://user-images.githubusercontent.com/8216923/121770866-f04bb580-cb39-11eb-8bce-bb1236b81a06.png)

**Comment by Wengier** [comment]
@maron2000 I have already added support for translations of the main Configuration Tool interface, and also integrated the 14-dot Japanese font you provided during this. Meanwhile, I have added some new entries in the Japanese language file (https://github.com/joncampbell123/dosbox-x/blob/master/contrib/translations/ja/ja_JP.lng) for the Configuration Tool text. Can you translate them accordingly? Thanks. The updated Windows builds are available from:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by maron2000** [comment]
@Wengier Thank you for your information. I'll inform you after the translation is finished.

**Comment by maron2000** [comment]
@Wengier I translated the added items, which can be found [here](https://github.com/maron2000/dosbox-x-1/commit/0dd4591fde1f325ddc444e22042dba0495bdfbb1#diff-4f9d1948dde30cb07eba2822aa3e5e52077ddb3cd10d24bcfeaaf474b0f731e9).
As you can see in the screenshot below, we need some more width in some boxes and/or use half-width katakanas in order to fit the translated words such as "キャンセル" (Cancel) and "クリップボードに貼付" (Paste Clipboard). 

![configtool_translated](https://user-images.githubusercontent.com/68574602/121831128-ae6d6b80-cd01-11eb-951c-d434eba7bf62.png)

**Comment by Wengier** [comment]
@maron2000 Thanks for the translation! I have already fixed the issue with button width, and some button layout has been adjusted too. You can get the latest Windows builds below:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

A screenshot showing the [autoexec] section editor:

![image](https://user-images.githubusercontent.com/8216923/121844409-f4024800-ccb1-11eb-8418-3faad67ec4da.png)

**Comment by maron2000** [comment]
@Wengier Thank you, and I appreciate your prompt actions.
I checked and see that most of the translation is okay.
I made some minor fixes regarding overflow of boxes and line feeds, which can be found below.
https://github.com/maron2000/dosbox-x-1/commit/eb84792f989d62b818e2d7399b4e8c71f4f055b6

**Comment by Wengier** [comment]
@maron2000 Thanks for the updates. I have uploaded it accordingly. Meanwhile, I have added the ability to translate the button names in the Mapper Editor interface (probably the last interface needing such support). In order to reduce the work to translate them, for most of them I decided to re-use the translated text from the drop-down menus. There are some remaining button names (along with some title names) needed to be translated though. And because of the re-use of menu text, there may be some overflow text in some buttons, so can you please fix them accordingly? If this is not possible, you can also manually add new mapper-specific labels (e.g. `:MAPPER:caprawmidi`) in the end of the language file so that these will be forced to be used instead of the text as used by the menu text. Please check out the updated Windows builds:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

Thanks!

**Comment by maron2000** [comment]
@Wengier
I translated the items for Mapper Editor and uploaded it, which can be found below.
https://github.com/maron2000/dosbox-x-1/commit/2c26102553bc4c44cc39fd0821685b639f178055

I made some minor changes in the existing translations for the menu bar etc. to make it consistent as much as possible.
Though there are some boxes with text overflowing, but I think it is fairly acceptable.
There are not enough space for the "Capture (キャプチャ)" button, so it may be better to enlarge the box for that button.
 
The items to translate for "Exit" button and the message while button capturing is on-going are missing,
so it remains as English. The suggested translation for them are as follows.
"Exit" -> "終了"
"Capture enabled. Hit ESC to release capture." -> "キャプチャしています。ESCで終了します。"

![mapper_editor_translation](https://user-images.githubusercontent.com/68574602/122015256-e73d3b80-cdfa-11eb-9a03-5930e9e77b87.png)

**Comment by Wengier** [comment]
@maron2000 Thanks for the update. I think you probably downloaded an earlier build (which I updated again later), so there are some items missing in the language file (although this does not include "Capture enabled. Hit ESC to release capture". Can you check the new build? Thanks!

P.S. Support for DBCS text is now supported in OpenGL-mode SDL-drawn menu as well. So all types of DOSBox-X menus now support Chinese/Japanese/Korean characters by now.

**Comment by maron2000** [comment]
@Wengier 
Sorry that I uploaded a translation file based on an old update.
Please find the following updates.
https://github.com/maron2000/dosbox-x-1/commit/2859779f1b2496c7388db8f3ef036363354baa23#diff-4f9d1948dde30cb07eba2822aa3e5e52077ddb3cd10d24bcfeaaf474b0f731e9

In Japanese,  "Help" - "About" will be  XXXXについて (About XXXX), and we cannot omit XXXX in this case.
So in the menu bar, I translated "About" as "DOSBox-Xについて", which is very usual for other Japanese software as well.
If you are to add "DOSBox-X" in the window as below, please consider adding it to the menu bar as well so that both menu bar and window displays are consistent.

```
:ABOUT
%s について (About %s in English)
```

![about_dosbox](https://user-images.githubusercontent.com/68574602/122041957-87ec2500-ce14-11eb-9bf0-73ec75a3653d.png)

**Comment by Wengier** [comment]
@maron2000 Thanks. I have enlarged the relevant mapper buttons accordingly, so that the mapper interface should now look better (no overflow any more):

![image](https://user-images.githubusercontent.com/8216923/122164218-728eef00-ce44-11eb-9554-5ecc463b73b4.png)

For the "About" button, I decided to re-use the "About DOSBox-X" text from the drop-down menu, so that the displayed text will be "About DOSBox-X" (or DOSBox-Xについて in Japanese) everywhere. Please check out the updated Windows builds:

* Windows SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Wengier** [comment]
I have also added a Traditional Chinese language file below, using Simplified => Traditional Chinese conversion tool plus some manual fixes. If any Traditional Chinese user finds errors in the language file please let me know:

https://github.com/joncampbell123/dosbox-x/blob/master/contrib/translations/zh/zh_TW.lng

**Comment by 1abcd** [comment]
@Wengier
I am Traditional Chinese user, I made a lot of corrections to zh_TW translation. I wish I don't do the wrong action.

**Comment by Wengier** [comment]
@1abcd Thank you so much for the corrections! I am sure the language file is greatly improved with this. Please let me know if you find any issues with the Traditional Chinese system etc. Thanks!

**Comment by Wengier** [comment]
A screenshot showing the Traditional Chinese interface (with your updated language file in TTF mode):

![image](https://user-images.githubusercontent.com/8216923/126128664-ec851eca-b290-4f0a-b7ab-d7569cb92d3c.png)

**Comment by Wengier** [comment]
I tried to make a sample Korean language file for testing, and Korean characters appear to look fine in both Korean DOS/V and TTF modes. Only welcome messages and drop-down menu are translated with Google though for demo purpose:

* [ko_KO.zip](https://github.com/joncampbell123/dosbox-x/files/6852838/ko_KO.zip)

A screenshot in TTF mode (code page 949) with SarasaGothicFixed.ttf font:

![image](https://user-images.githubusercontent.com/8216923/126431480-35c67981-ffc7-4c13-8328-6cae29d238b4.png)

**Comment by Allofich** [comment]
@maron2000, can this issue be closed? I have not read the entire thread.

**Comment by maron2000** [comment]
Closing this issue with many thanks to @Wengier .
