### ISSUE TITLE
Package selection and installation help wanted (Mac OS X)

### ISSUE THREAD

**Issue by cszstl** [joncampbell123/dosbox-x#2560]
My goal:  Find a DOS emulation package that will run under Mac OS X 10.14 (Mojave) to provide a DOS 6.1 (or equivalent) command line environment that can run DOS native programs (.EXE files) including Borland Turbo Pascal.  I am not interested in Windows, and I do not need mouse support.

Problem 1:  Can't find how to use DOSBox-X on Mac OS X 10.14 (Mojave).  The current release only runs on 10.15 or newer, and the archive of all releases and change logs apparently does not say what releases of DOSBox-X run on various older versions of Mac OS X.  The statement that "macOS versions earlier than 10.12 (Sierra) are not officially supported" seems to imply that some version(s) of DOSBox-X ought to work for 10.14; but which one(s)?

Problem 2:  Can't find instructions on how to use a DOSBox-X download package to set up a DOS emulation environment.  (There are lots of instructions on how to configure DOSBox-X for Windows once it's set up, but that's not relevant to my goal.)  The "macOS Packages" section of the INSTALL.md page is vastly incomplete.

Problem 3:  Can't find an explanation for what distinguishes SDL1 from SDL2, or what those terms mean.

Solutions to these problems might lead to improvements in available documentation.

**Comment by Wengier** [comment]
Thanks for asking for help here. DOSBox-X is completely free and open-source, and there are both binary and source packages available from the website and the release section. Apart from the binary release packages which may target more recent macOS versions, you can always build the source code by yourself on your macOS so that it will definitely run on your macOS system. There are `build-macosx` and `build-macosx-sdl2` scripts available for this purpose. But if you could not build the source code yourself for some reason, you can try the following macOS binaries (both SDL1 and SDL2 builds), which I built by myself on my macOS 10.13 (High Sierra) and will hopefully work on your system too:

* [dosbox-x-macosx-x86_64-10.13.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-macosx-x86_64-10.13.zip)

Moreover, I have updated the INSTALL.md file to add more instructions for macOS, which should answer your Problem 2 and Problem 3:

"The macOS package requires 64-bit Intel or ARM-based macOS operating system. It should run natively on the recent versions of macOS such as macOS Catalina (10.15) and Big Sur (11.0). Both SDL1 and SDL2 binaries (in .app format) are provided in the macOS package, in the directories named dosbox-x and dosbox-x-sdl2 respectively inside the zip file. While the SDL1 version is the default version, the SDL2 version may be preferred over the SDL1 version for certain features (particularly related to input handling) such as touchscreen input support. You can select either SDL1 or SDL2 version according to your preference.

There are two ways to run DOSBox-X in macOS, either from the Finder or from the command-line (Terminal):

From the Finder, go to the directory where the macOS zip package is downloaded, you will see a folder name which is the same as the file name of the downloaded zip package. Inside this folder you will see dosbox-x (SDL1) and dosbox-x-sdl2 (SDL2). Go to either one and click the program "dosbox-x" to start DOSBox-X. If you see a dialog asking you to select a folder, please select one which will then become your DOSBox-X working directory. You can choose to save this folder after you select one so that the folder selection dialog will no show up again next time, or let DOSBox-X show the folder selection dialog every time you run it from the Finder.

From the Terminal, go to the directory where the macOS zip package is downloaded, you will see a folder name which is the same as the file name of the downloaded zip package. Starting from this folder, use cd command to go to the directory where the DOSBox-X executable is located. For SDL1 build, type cd dosbox-x/dosbox-x.app/Contents/MacOS, and for SDL2 build, type cd dosbox-x-sdl2/dosbox-x.app/Contents/MacOS. Run DOSBox-X with ./DosBox and you will see the DOSBox-X window."

For the above dosbox-x-macosx-x86_64-10.13.zip package though, you will just find two binaries named dosbox-x-sdl1 and dosbox-x-sdl2 for SDL1 and SDL2 respectively. You can run either one, or just start with SDL1 version if you are not sure.

Once you get DOSBox-X running, you should go to the [DOSBox-X Wiki](https://dosbox-x/wiki) for user guides, including actually setting up your DOS application. You are trying to DOS programs like Borland Turbo Pascal, which are text-mode applications, so I would suggest you to run them with the TrueType font (TTF) output (`output=ttf`). Let me know if you have further questions. Hope this helps.

**Comment by cszstl** [comment]
This works -- all I had to do was tell SysPref to allow execution, since the app didn't come from the App Store &c.
Thank you!
