### ISSUE TITLE
DOSbox-X 0.83.14 administrative install

### ISSUE THREAD

**Issue by phrossignol** [joncampbell123/dosbox-x#2570]
Your answer related to version 0.83.13:

    _The DOSBox-X version number is now saved in the registry key HKCU\Software\DOSBox-X\Version (or HKLM\Software\DOSBox-X\Version in the case of administrative install mode), which your tool can use to check.

    The previous installer was created using Inno Setup 5 which did not support the /ALLUSERS command line parameter (or administrative install mode). The installer above has been updated to use Inno Setup 6 which should now support this so that you can use the /ALLUSERS command line parameter to enable administrative install mode.

Hope this helps (the updates should appear in future installers too)._

With version 0.83.14 and Administrative installation (/ALLUSERS option) the DOSBox-X version number key is created in HKCU instead HKLM. It was OK with version 0.83.13.

Many thanks for your help.

**Comment by Wengier** [comment]
@phrossignol There are more than one Windows installers for 0.83.14, because I became aware that the installer which supports the /ALLUSERES option (created with Inno Setup 6) does not support Windows XP, so it is not possible for the installer to support the administrative install mode and Windows XP at the same time. Make sure you download and use the Windows installer that supports the administrative install mode, not the one that is designed to be compatible with Windows XP. Hope this helps.

**Comment by phrossignol** [comment]
dosbox-x-windows-0.83.14-setup-allusers.exe installer solves my problem ...
Many thanks for your help.
