### ISSUE TITLE
A START mystery

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2593]
Apparently, I do not understand the START command, because I can't figure out why this is happening.

I have two copies of the same VBS script, named ClipToWordPerfect.vbs. One is in this folder:

`D:\Dropbox`

The other in this folder

`C:\Users\myname\DOSBoxWP\VirtualHD\Util`

I mount the host D:\ drive as D:\ in DOSBox-X.

I mount the host folder `c:\Users\myname\DOSBoxWP\VirtualHD` as drive B: in DOSBox, so the Util subfolder in the VirtualHD host folder is B:\UTIL in DOSBox-X.

In both folders, the short name of the VBS file is CLIPTO~1.VBS.

Here is the mystery. If I run this command:

`start d:\dropbox\CLIPTO~1.VBS`

then the command runs correctly. But if I run this command:

`start c:\users\myname\DOSBoxWP\virtualHD\util\CLIPTO~1.VBS`

then I get the error message "This program cannot be run in DOS mode. Now run it as a Windows application."

I get the same message if I CD to the "B:\UTIL" folder and enter `start .\CLIPTO~1.VBS`.

The VBS always runs correctly when I start it from D:\DROPBOX. It always produces the error message when I run it from C:\Users\etc. or as .\CLIPTO~1.VBS from that same folder.

I tested this on the current release version, 0.83.14. Any enlightenment would be welcome. What I want to do is to run the command from the \Users\... etc. folder, and I can't figure out how to make that happen.

**Comment by Wengier** [comment]
@emendelson The message "This program cannot be run in DOS mode. Now run it as a Windows application." is not an error message from the built-in START command itself. It seems to indicate that another Windows application has been executed from within DOSBox-X so that it is automatically launched as a Windows application instead. Perhaps there is another START program on the Windows host system which got executed, or there is something special about your user folder. I tried to launch some file located in my user folder via the built-in START command and it seems to work fine here.

**Comment by emendelson** [comment]
@Wengier Of course you are right. I had an old "START.EXE" program in the same folder; it was the version that you helped me write four years ago. I am sorry to have wasted your time testing this - I simply forgot that it existed. Apologies again!
