### ISSUE TITLE
NE2000.COM does not appear in Z:\SYSTEM

### ISSUE THREAD

**Issue by LowLevelMahn** [joncampbell123/dosbox-x#2638]
im using latest: https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.15/dosbox-x-vsbuild-win64-20210701083944.zip

and got NE2000 support activated with menu/config - the checkbox is checked also after restart

but i can't find the NE2000 packet driver in Z:\SYSTEM?

**Comment by LowLevelMahn** [comment]
another question: is that a special dosbox-x packet driver or a common used one?

**Comment by yxmline** [comment]
```
[config]
set path    = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL
```

**Comment by Wengier** [comment]
Thanks for the question! DOSBox-X uses the standard NE2000 packet driver (NE2000.COM) for NE2000 networking (no special one for DOSBox-X), and NE2000.COM will only appear when the NE2000 networking has been activated, either the PCAP backend or the Slirp backend. If you use the PCAP backend (as supported by the Windows builds you linked), this means that the PCAP backend must be activated in order for NE2000.COM to appear in C:\SYSTEM, and this includes the "realnic" option in [ethernet, pcap] section. A minimal config file to activate the PCAP backend for NE2000 networking is the following:

```
[ne2000]
ne2000  = true

[ethernet, pcap]
realnic = 1
```

Where "realnic=1" specifies a host network interface for use with the PCAP backend, and you change it based on your actual network setting. Then the PCAP backend is activated and NE2000.COM should appear in Z:\SYSTEM.

Hope this helps.

**Comment by RBTCHENTPE** [comment]
Dear Wengier,
the problems:
LOAD LSL.COM OK IN GOOD ORDER
LOAD NE2000.COM NOT OK AND SHOW:
NE2000-DOS-50: The board cannot be found.
NE2000-DOS-6: The adapter did not initialize.  NE2000 did not load.

according to : https://github.com/joncampbell123/dosbox-x/issues/2638

I had download the package ne2000.zip for NE2000 networking 

question: 
1. I can't find the NE2000 packet driver in Z:\SYSTEM?
2. How to put NE2000.COM in the  Z drive and will appear on Z drive 
3. How to let the NE2000 networking has been activated

NEED HELP TO find the solution to this problem to load ne2000 (REF. TO Graphic STEP1~4 ):
My Win7 notbook, I HAD INSTALLED AND RUN DOSBox-X version 0.83.15 SDL2 
I HAD INSTALLED WinPCAP headers and enabled NE2000 emulation.
from the DOSBox-X menu bar, select Help followed by List network interfaces
ALERT : cannot enumerate network interfaces: PacketGetAdapterNames: SYSTEM UNABLE TO FIND ROUTE (系統找不到指定的路徑)

part of my config as attach files
[Part of My config.docx](https://github.com/joncampbell123/dosbox-x/files/7043303/Part.of.My.config.docx)
[SCREENSHOT DOSBOX-X SDL2 FOR LOAD NE2000 ADAPTOR01.docx](https://github.com/joncampbell123/dosbox-x/files/7043305/SCREENSHOT.DOSBOX-X.SDL2.FOR.LOAD.NE2000.ADAPTOR01.docx)

ROBERT CHEN/sales.yrsoft@msa.hinet.net

**Comment by Dobby233Liu** [comment]
@RBTCHENTPE please try adapting this following config first: https://github.com/joncampbell123/dosbox-x/issues/2638#issuecomment-873648845
(as you're on windows, ensure you're using the vsbuilds)

**Comment by rderooy** [comment]
Did you have a look at the wiki?
https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X

**Comment by RBTCHENTPE** [comment]
DEAR SIR,
Many thanks for kindly prompt reply,
Download : dosbox-x-vsbuild-win64-20210701083944.zip 
Extract to be a folder: 
dosbox-x-vsbuild-win64-20210701083944 including bin including a folder x64 including 2 folders Release & Release SDLS  
1.	I already copy the all files of \dosbox-x-vsbuild-win64-20210701083944\bin\x64\Release SDL2 to the directory of  : C:\DOSBox-X\Win64_builds\x64_Release_SDL2
2.	There is **another folder Release** under \dosbox-x-vsbuild-win64-20210701083944\bin\x64\Release, Please kindly advise the Release folder that I should copy it to which folder & location of C:\DOSBox-X\. 
[DOXBOX-S VSBUILD.docx](https://github.com/joncampbell123/dosbox-x/files/7044337/DOXBOX-S.VSBUILD.docx)

rdercopy, Yes, I do look at the url  look at the wiki?
https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X

I had installed the PCAP in order.

I do not yet install mTCP 
Due I do not realize how to test if networking is working in DOSBox-X.

I do not understand :  start DOSBox-X with the ne2000.conf config file that you created:
dosbox-x -conf ne2000.conf ( I had  created dosbox-x -conf ne2000.conf put it in the folder  of C:\DOSBox-X\

but the command does not work : dosbox-x -conf ne2000.conf

**Comment by rderooy** [comment]
It will look for the config file in the current directory unless you specify a path.
So either CD to the directory that has the config file, or specify the path to the file.

e.g.
```
cd c:\dosbox-x
dosbox-x -conf ne2000.conf
```

or
```
dosbox-x -conf c:\dosbox-x\ne2000.conf
```

**Comment by RBTCHENTPE** [comment]
Yes, I do look at the wiki?
https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X

**Comment by RBTCHENTPE** [comment]
Dear Sir,

I had successed to[SCREENSHOT OF NE2000 test if networking.docx](https://github.com/joncampbell123/dosbox-x/files/7045004/SCREENSHOT.OF.NE2000.test.if.networking.docx) is working in DosBox-X as follows with commond problems:  MAC Address all FF
Common problem: Invalid MAC Address When loading the NE2000 DOS Packet driver you get an all FF MAC address:
C:\>NE2000 0x60 10 0x300
Packet driver for NE2000, version 11.4.3
Packet driver skeleton copyright 1988-93, Crynwr Software.
This program is freely copyable; source must be available; NO WARRANTY.
See the file COPYING.DOC for details; send FAX to +1-315-268-9201 for a copy.

System: [345]86 processor, ISA bus, Two 8259s
Packet driver software interrupt is 0x60 (96)
Interrupt number 0xA (10)
I/O port 0x300 (768)
My Ethernet address is FF:FF:FF:FF:FF:FF

DHCP> BAD COMMAND

**Comment by RBTCHENTPE** [comment]
Dear all,

 

Thanks a lot,

 

I had made a success to test if network is working in DosBox-X as follows with commond problems: MAC Address all FF!!!
Common problem: Invalid MAC Address When loading the NE2000 DOS Packet driver you get an all FF MAC address:
C:>NE2000 0x60 10 0x300
Packet driver for NE2000, version 11.4.3
Packet driver skeleton copyright 1988-93, Crynwr Software.
This program is freely copyable; source must be available; NO WARRANTY.
See the file COPYING.DOC for details; send FAX to +1-315-268-9201 for a copy.

System: [345]86 processor, ISA bus, Two 8259s
Packet driver software interrupt is 0x60 (96)
Interrupt number 0xA (10)
I/O port 0x300 (768)
My Ethernet address is FF:FF:FF:FF:FF:FF

DHCP> BAD COMMAND

B. Rgds.,

Robert Chen

**Comment by RBTCHENTPE** [comment]
Dear all,

 

Thanks a lot,

 

Attachment is the config file , SCREENSHOT OF NE2000 test if networking.docx

 

I had made a success to test if network is working in DosBox-X as follows with commond problems: MAC Address all FF!!!
Common problem: Invalid MAC Address When loading the NE2000 DOS Packet driver you get an all FF MAC address:
C:>NE2000 0x60 10 0x300
Packet driver for NE2000, version 11.4.3
Packet driver skeleton copyright 1988-93, Crynwr Software.
This program is freely copyable; source must be available; NO WARRANTY.
See the file COPYING.DOC for details; send FAX to +1-315-268-9201 for a copy.

System: [345]86 processor, ISA bus, Two 8259s
Packet driver software interrupt is 0x60 (96)
Interrupt number 0xA (10)
I/O port 0x300 (768)
My Ethernet address is FF:FF:FF:FF:FF:FF

DHCP> BAD COMMAND

B. Rgds.,

Robert Chen

**Comment by RBTCHENTPE** [comment]
Dear All,

 

Following question about dosbox-x-vsbuild-win64, wish to get kindly help too.

 

Many thanks for kindly prompt reply,

Download : dosbox-x-vsbuild-win64-20210701083944.zip 

Extract to be a folder: 

dosbox-x-vsbuild-win64-20210701083944 including bin including a folder x64 including 2 folders Release & Release SDLS  

1.    I already copy the all files of \dosbox-x-vsbuild-win64-20210701083944\bin\x64\Release SDL2 to the directory of  : C:\DOSBox-X\Win64_builds\x64_Release_SDL2

2.    There is another folder Release under \dosbox-x-vsbuild-win64-20210701083944\bin\x64\Release, Please kindly advise the Release folder that I should copy it to which folder & location of C:\DOSBox-X\. 





 

B. Rgds.,

Robert Chen

 

From: ***@***.*** ***@***.*** 
Sent: Wednesday, August 25, 2021 4:21 PM
To: 'joncampbell123/dosbox-x'; 'joncampbell123/dosbox-x'
Cc: 'Mention'
Subject: RE: [joncampbell123/dosbox-x] NE2000.COM does not appear in Z:\SYSTEM (#2638)

 

Dear all,

 

Thanks a lot,

 

Attachment is the config file , SCREENSHOT OF NE2000 test if networking.docx

 

I had made a success to test if network is working in DosBox-X as follows with commond problems: MAC Address all FF!!!
Common problem: Invalid MAC Address When loading the NE2000 DOS Packet driver you get an all FF MAC address:
C:>NE2000 0x60 10 0x300
Packet driver for NE2000, version 11.4.3
Packet driver skeleton copyright 1988-93, Crynwr Software.
This program is freely copyable; source must be available; NO WARRANTY.
See the file COPYING.DOC for details; send FAX to +1-315-268-9201 for a copy.

System: [345]86 processor, ISA bus, Two 8259s
Packet driver software interrupt is 0x60 (96)
Interrupt number 0xA (10)
I/O port 0x300 (768)
My Ethernet address is FF:FF:FF:FF:FF:FF

DHCP> BAD COMMAND

B. Rgds.,

Robert Chen

**Comment by RBTCHENTPE** [comment]
Please kindly advise me how to make donate with thanks all for your help and keep  you busy.
Robert Chen

**Comment by rderooy** [comment]
The different windows builds are partially documented here:
https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md#windows-packages-installer-or-portable

The mingw builds work better for DOS programs needing the FPU (Floating Point Unit), or if you have an older Windows PC.

**Comment by RBTCHENTPE** [comment]
MY WIN7 NOTEBOOK IS INSTALL dosbox-x-windows-0.83.15-setup.exe (version 0.83.15) 64-bit MinGW SDL2

**Comment by RBTCHENTPE** [comment]
Anything new issue for the solution of loading NE2000 DOS Packet driver get an all FF MAC address:

**Comment by rderooy** [comment]
@RBTCHENTPE you did not answer my question. There are several known cases that can result in a all FF mac address. Those are listed on the wiki page, but just in case let me list them again:
- Your DOSBox-X binary lacks networking support
  - Should be ok, but make sure your not trying to use SLIRP with the VS (visual studio) built version
- (Linux) Your DOSBox-X binary does not have the right PCAP permissions to access networking
- You do not have PCAP installed (libpcap on Linux, Npcap on Windows), or SLIRP
  - This can also happen if your using a 32bit version of PCAP with a 64bit version of DOSBox-X (or vice-versa)
- When loading the NE2000 driver you gave the wrong IRQ or IO port.
  - This should only effect non-standard setups where you specified a different nicirq= or nicbase= in your ne2000.conf config file.

Also, make sure your NOT trying to use pcap in combination with a wifi network adapter.

**Comment by RBTCHENTPE** [comment]
Dear Sir,

Sincerely thanks a lot,
It is great for the DOSBOX-X 0.83.24: 3000 cycles. 
It’s function is almost the same as netro Dos PC. on Dos6.22.
Installed PCAP & mTCP and dosbox-x -conf ne2000.conf is workable in good order

1.	I had made several test of DOSBOX-X to access netro Clipper/Xbase application that 95% is excellent without any 
problems including Chinese Language characters cpg 950/Big5 of Eten for more than a week.
3.	The only problem is not able to send printing job to the Novell Server’s Printer Server Queue which seems not able to access Login command login script in good order.  Once the login script accessed the Clipper application will not be able to run.
4.	I thank the problem should be the protocol of Frame ETHERNET_802.2 is default unable to change to Frame ETHERNET_802.3 while our network is based on Frame ETHERNET_802.3 of NE2000.
5.	It will be very appreciated, if you can adjust the configure function being able to change the protocol of Frame ETHERNET_802.2 to Frame ETHERNET_802.3 by user setting.  I would like to test the command Login & capture whether is able to be accessed for printer server of Novell as well as netro netro Dos PC. on Dos6.22 that print job is able to transmit to the printer Queue.
6.	For your information, the DOSBOX-X 0.83.24 IPXNET connect ServerIPaddress the command IPXNET is not exist?
7.	I sincerely hope the above problems will have solution asap.
8.	Please kindly refer to the attachment of report one is the configuration of DOSBOX-X(dosbox-x conf Test report01.txt) another is the step by step testing record (dosbox-x conf Test record report02.txt)

B. Regards,
Robert Chen/Taipei Taiwan

Attachment:
[dosbox-x conf Test report01.txt](https://github.com/joncampbell123/dosbox-x/files/8562084/dosbox-x.conf.Test.report01.txt)

[dosbox-x conf Test record report02.txt](https://github.com/joncampbell123/dosbox-x/files/8562087/dosbox-x.conf.Test.record.report02.txt)

**Comment by Wengier** [comment]
For the IPXNET command, have you tried the Visual Studio build with ``ipx=true`` and see if the IPXNET command works?

I don't personally have the Novell Server’s Printer Server to test, so I cannot really say how well it will work in this case.

**Comment by RBTCHENTPE** [comment]
Hi Wengier,

Great to see your answer again,
I already set ipx=true. the IPXNET command not works and not existed.

[ipx]
# ipx: Enable ipx over UDP/IP emulation.
# ipx = false
ipx = true
[ne2000]

Robert Chen/Taipei, Taiwan

**Comment by Wengier** [comment]
@RBTCHENTPE As far as I know IPX/Modem support was indeed unavailable in MinGW builds of DOSBox-X 0.83.24 (or earlier), but it was fixed later. I believe you actually use one of these builds, and in such case you can try the latest MinGW builds and see how it works (when ``ipx=true`` is set):

32-bit MinGW builds: https://github.com/joncampbell123/dosbox-x/suites/6271701204/artifacts/224043677
64-bit MinGW builds: https://github.com/joncampbell123/dosbox-x/suites/6271701208/artifacts/224044273

Or Visual Studio builds:

32-bit Visual Studio builds: https://github.com/joncampbell123/dosbox-x/suites/6271701203/artifacts/224032283
64-bit Visual Studio builds: https://github.com/joncampbell123/dosbox-x/suites/6271701201/artifacts/224036675

Hope this helps.

**Comment by RBTCHENTPE** [comment]
Hi Wengier,

Thanks a lot,
Hopefully, IPX/Modem support will be available soon.

Robert Chen/Taipei, Taiwan

**Comment by Jookia** [comment]
Hi @RBTCHENTPE 

You are using two different NE2000 drivers: One by Novell and one by Crynwr. I believe the Crynwr may use 802.3.

Could you explain some more about what issues you are having?

**Comment by RBTCHENTPE** [comment]
Hi, Jookia,

1. I only use one emulated NE2000 drivers to test the network connection to the Novell File Server (ANDYS) as what netro Dos PC. on Dos6.22.
2. I would like to run the command Login & capture to see if it is able to access for the server of Novell & printer server job as well as the netro Dos PC. on Dos6.22 that print job is able to transmit to the printer server Queue then printout via network printer.

3. Host Win10 with Intel network card installed to emulate as NE2000:
Following configration for your reference & check it up what wrong about the setting:

[sdl]
# #### usesystemcursor   = false
usesystemcursor   = true

# mouse_emulation   = locked
mouse_emulation   = always

[dosbox]
Mount C: C:\
Mount D: D:\
Mount E: E:\
Mount F: F:\
cls
#
language                  = zh_TW
captures                  = capture
# captures                  = C:\DOSIMAGE

[render]
# scaler         = normal2x
scaler         = normal5x

[dosv]
# dosv             = off
dosv             = on

[keyboard]
# auxdevice               = intellimouse
auxdevice               = 3button

[ttf]
font         = 
outputswitch = auto
# winperc      = 60
winperc      = 95

[gus]
gus               = false
gusrate           = 44100
gusmemsize        = -1
gus master volume = 0.00
gusbase           = 240
gusirq            = 5
gusdma            = 3
gustype           = classic
ultradir          = C:\ULTRASND

[serial]
# serial9       =directserial realport:COM9
serial9       = serialmouse

[dos]
xms                             = true
xms handles                     = 0
shell configuration as commands = false
hma                             = true
hard drive data rate limit      = -1
floppy drive data rate limit    = -1
ansi.sys                        = true
log console                     = false
share                           = true
file access tries               = 3
network redirector              = true
minimum mcb free                = 0
ems                             = true
umb                             = true
quick reboot                    = false
ver                             = 6.22
lfn                             = auto
fat32setversion                 = ask
shellhigh                       = auto
automount                       = true
automountall                    = false
mountwarning                    = true
autofixwarning                  = false
startcmd                        = false
starttranspath                  = true
startwait                       = true
startquiet                      = false
vmware                          = true
int33                           = true
keyboardlayout                  = auto
customcodepage                  = 
dbcs                            = true
# dos clipboard device enable     = false
dos clipboard device enable     = true
dos clipboard device name       = CLIP$
dos clipboard api               = true

[ipx]
# ipx: Enable ipx over UDP/IP emulation.
# ipx = false
ipx = true

[ne2000]
ne2000  = true
nicbase = 300
nicirq  = 3
macaddr = AC:DE:48:88:99:AA

REM PCAP ALREADY INSTALLED IN ORDER
# backend = auto
backend=pcap

[ethernet, pcap]
realnic = "Intel(R) Ethernet Connection (10) I219-V"
timeout = default

[ethernet, slirp]
#ipv4_network    = 10.0.2.0 ## workstation IP address
ipv4_network    = 192.168.1.98
ipv4_netmask    = 255.255.255.0
ipv4_host       = 192.168.1.1
#ipv4_nameserver = 10.0.2.3
ipv4_nameserver = 192.168.1.1
#ipv4_dhcp_start = 10.0.2.15
ipv4_dhcp_start = 192.168.1.100

[config]
rem         = This section is DOS's CONFIG.SYS file, not all CONFIG.SYS options supported
break       = off
numlock     = 
# shell       = 
shell       = COMMAND.COM
dos         = high, umb
fcbs        = 100

## files       = 200
# due FILE HANDLES 100 in NET.CFG if files=200 default will be "file handles=" in NET.CFG exceeds 254.  Please reconfigure one of these parameters.
files       = 100

country     = 886,950
lastdrive   = a
set path    = C:\;C:\DOS622;C:\IPXDOSBX;C:\CLIENT02;C:\BAT;C:\ET3;F:\;Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL
set prompt  = $P$G
set temp    = 
install     = 
# installhigh = 
# installhigh = DOSKEY
LH DOSKEY
device      = 
# devicehigh  = 
# 檔案遺失或損壞 無效 devicehigh  = C:\DOS622\SETVER.EXE
# DEVICEHIGH=C:\DOS622\SETVER.EXE
# 檔案遺失或損壞 無效 SHELL=C:\DOS622\COMMAND.COM /P/E:512
# stacks=9,128  seems no need

[autoexec]
# Lines in this section will be run at startup.
SET CLIPPER = F80
# You can put your MOUNT lines here.
MOUNT C D:\DOS622
C:
    PROMPT $P$G
    C:\IPXDOSBX\LSL.COM
    C:\IPXDOSBX\NE2000.COM
    C:\IPXDOSBX\IPXODI.COM
##  above all correct and successful

    C:\IPXDOSBX\NETX PS=ANDYS
##  unable to attach server ANDYS:I think due DosBox is set 802.2 but my server ANDYS IS 802.3 
##  cause term error(1) unable to printout after access C:\IPXDOSBX\NETX PS=ANDYS

##  the F: network driver is connected by the Novell Client 2 SP4 (IR2) for Windows 10  
F:

##  follows invlid not able to access
##   \LOGIN\LOGIN opa
##   map root f:=andys/andys:
##   CD \
##   capture /ec
REM  not able to access Login command login script invalid.  
REM  Once the login script accessed the Clipper application will not be able to run.


REM Follows not successful
##   c:
##   MTCP ALREADY INSTALLED BUT USELESS
##   set mtcpcfg=c:\mtcp.cfg
##   echo packetint 0x60>c:\mtcp.cfg
##   echo hostname cli1>>c:\mtcp.cfg
##   #Client## echo IPADDR 192.168.8.1>>c:\mtcp.cfg
##   echo IPADDR 192.168.1.98>>c:\mtcp.cfg
##   echo NETMASK 255.255.255.0>>c:\mtcp.cfg
##   
##   PAUSE
##   CLS

##   TRY TO CONNECT TO SERVER ANDYS VIA IPXNET INVALID
##   #ipxnet connect 127.0.0.1 33213
##   ipxnet connect 192.168.1.249
##   PAUSE
##   CLS
##   
##   ipxnet status
##   PAUSE
##   CLS
##   
##   ipxnet ping
##   PAUSE
##   CLS
##   
##   # load/install IPXPKT with 0x60
##   ipxpkt 0x60
##   PAUSE
##   CLS
##   
##   #SERVER## nc -echo -target 192.168.1.2 22222
##   nc -echo -target 192.168.1.249 22222
##   PAUSE
##   CLS
##   
##   # Uninstall IPXPKT with -u
##   ipxpkt -u
##   PAUSE
##   CLS
##   
##   ipxnet disconnect
##   PAUSE
##   CLS

**Comment by RBTCHENTPE** [comment]
Hi, Jookia,

Due the post text message seems not complete same as what the setting of configration so please kindly refer to the attachment.
The attachment of configration for your reference & check it up what wrong about the setting:
[TEST REPORT 20220511.txt](https://github.com/joncampbell123/dosbox-x/files/8666375/TEST.REPORT.20220511.txt)

**Comment by Jookia** [comment]
I'm not sure if there's much we can do about switching to 802.3 outside you trying the NE2000.COM made by crynwr.

**Comment by LowLevelMahn** [comment]
The 802.3 support is based on the driver you use not the ethernet card emulation of dosbox-x

**Comment by RBTCHENTPE** [comment]
Jookia,

1. Had tried crynwr NE2000.COM does not work.
2. Further trying Novell NE2000.COM got question:

following testing with QUESTION: 
1. But when the login script tries to map drives some servers are saying "Warning: Unexpected error 9 (89ff)ATC: Unknown file serder"

2.  - Added NE2000.COM (packet driver for NE2000 network card) which will appear in Z:\SYSTEM directory when NE2000 networking feature is enabled. (Wengier)
   Found the NE2000   COM  8,693 2002/10/01 12:34   This is different from Novell NE2000   COM   23,023 1994/10/14 22:02 
   I think if DOSBOX-X is able to add the driver of Novell NE2000.COM then the network connection & login problems could be solved.

3. Implemented the DOS network redirector functions so that the host name can be reported to DOS programs, unless the secure mode is enabled. You may need to
   set either the option ipx=true in [ipx] section or the option ne2000=true in [ne2000] section. Also added config option "network redirector" to [dos]
   section which if set to false disables the network redirector even with IPX/NE2000 enabled. (Wengier)
   ansi.sys                        = true
   log console                     = false
   share                           = true
   file access tries               = 3
   network redirector              = true
   minimum mcb free                = 0

Following try to replace NE2000.COM with NOVELL NE2000.COM but not allow

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
z:>cd \system
Z:\SYSTEM>

Z:\SYSTEM>DIR C:\IPXDOSBX\NE2*.*
 磁碟機 C 中的磁碟區是 C_DRIVE
 磁碟區序號為 50AF-C10E
 C:\IPXDOSBX 的目錄
NE2000   COM             23,023 1994/10/14 22:02
NE2000   INS                961 1994/10/06  8:47
NE2000CW COM              5,571 2022/05/11 16:42
NE2000NV COM             23,023 1994/10/14 22:02
NE2220DB COM              8,693 2002/10/01 12:34

Z:\SYSTEM>
Z:\SYSTEM>DIR
.              <DIR>            2002/10/01 12:34
..             <DIR>            2002/10/01 12:34
NE2000   COM              8,693 2002/10/01 12:34
PARALLEL COM                 21 2002/10/01 12:34
SERIAL   COM                 21 2002/10/01 12:34
MIXER    COM                 21 2002/10/01 12:34
INTRO    COM                 21 2002/10/01 12:34
HELP     COM                 21 2002/10/01 12:34

Z:\SYSTEM>COPY NE2000.COM C:\IPXDOSBX\NE2SYS.COM
 NE2000.COM
   已複製 1 個檔案.

Z:\SYSTEM>REN NE2000.COM NE2SYS.COM
無法更改名稱 - NE2000.COM

Z:\SYSTEM>COPY C:\IPXDOSBX\NE2000.COM
覆寫 "Z:\SYSTEM\NE2000.COM" (Y:是/N:否/A:全部)?Y
檔案拷貝失敗 - .
   已複製 0 個檔案.

Z:\SYSTEM>DEL NE2000.COM
無法刪除 - Z:\SYSTEM\NE2000.COM

Z:\SYSTEM>MD TEMP
不能建立目錄 - TEMP

cd \
Z:\>TYPE CONFIG.SYS | MORE
rem=This section is DOS's CONFIG.SYS file, not all CONFIG.SYS options supported
break=off
numlock=
shell=COMMAND.COM
dos=high, umb
fcbs=100
files=100
country=886,950
lastdrive=a
set path=C:\;C:\DOS622;C:\IPXDOSBX;C:\CLIENT02;C:\BAT;C:\ET3;F:\;Z:\;Z:\SYSTEM;Z
:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL
set prompt=$P$G
set temp=
install=
device=

Z:\>

''''''''''''''''recorder step by stap of network connection & login procedure'''''''''''''''''''''''''''''''''''''''''''''''
Z:\>SET CLIPPER = F80
Z:\>MOUNT C D:\DOS622
磁碟機 C 掛載到 local directory D:\DOS622\
Z:\>C:
C:\>PROMPT $P$G
C:\>C:\IPXDOSBX\LSL.COM
NetWare Link Support Layer v2.14 (941011)
(C) Copyright 1990-1994 Novell, Inc. All Rights Reserved.
The configuration file used was "C:\IPXDOSBX\NET.CFG".
Max Boards 4, Max Stacks 4

C:\>C:\IPXDOSBX\NE2000.COM
Novell NE2000 Ethernet MLID v2.02 (941014)
(C) Copyright 1991 - 1994 Novell, Inc.  All Rights Reserved.

IRQ 3, Port 300, Node Address ACDE488899AA L
Max Frame 1514 bytes, Line Speed 10 Mbps, Bus ID 0
Board 1, Frame ETHERNET_802.2, LSB Mode
NetWare Link Support Layer v2.14 (941011)
(C) Copyright 1990-1994 Novell, Inc. All Rights Reserved.
The configuration file used was "C:\IPXDOSBX\NET.CFG".
Max Boards 4, Max Stacks 4

C:\>C:\IPXDOSBX\IPXODI.COM
NetWare IPX/SPX Protocol  v3.01 (941031)
(C) Copyright 1990-1994 Novell, Inc.  All Rights Reserved.
SPX CONNECTIONS 65
Bound to logical board 1 (NE2000) : Protocol ID E0

C:\>c:\IPXDOSBX\netx ps=ANDYS
NetWare Workstation Shell  v3.32 (931117) PTF
(C) Copyright 1993 Novell, Inc.  All Rights Reserved.
Patent Pending.
Running on DOS V6.22
FILE HANDLES 100
PREFERRED SERVER ANDYS
Configuration File NET.CFG

Command line preferred server overrides configuration file parameter.
Established Preferred Server connection.
Attached to server ANDYS

<2/05/12    10:35:58C:\>

C:>PATH
PATH=C:\;C:\D0S622;C:\IPXDOSBX:C:\CLIENT02;C,\BAT;CSDH;F:\;Z:\;2:<SYSIEM:Z N;2:\DOS;Z:\4D0S;Z:\DEBUG;2: TEXTUTIL

C:\>LOGIN OPA
Warning: Unexpected error 9 (89ff)ATC: Unknown file serder。
Drive	I: = ANDYS\SYS:
Drive	F: = ANDYS\ANDYS:
Driue	G:= ANDYS\ADM:
Attempt to map drive to seruer to which you are not currently attached. The map command was "ROOT J:=ATC/SYS:SNWENOP".
Attempt to map drive to seruer to which you are not currently attached. The map command was "ROOT K:=ATC/SYS : SNWENACT".
Drive H: =ANDYSVACCT:
The following drive mapping operation could not be completed. "INS S3:=ANDYS/ANDYS:COMMON/PE2"
The error code was 8802.
The following drive mapping operation could not be completed. INS S4:=ANDYS/ANDYS :COMMON/DBASE"
The error code was 8802.
Drive F: = ANDYS\ANDYS:
Drive	F: = ANDYS\ANDYS:
Good afternoon,OPA.

Drive  W:   maps to a local disk.
Drive  X:   maps to a local disk.
Drive  Y:   maps to a local disk.
Drive  Z:   maps to a local disk.
      -----
SEARCH1:  = C:\
SEARCH2:  = C:\DOS622
SEARCH3:  = C:\IPXDOSBX
SEARCH4:  = C:\CLIENT02
SEARCH5:  = C:\BAT
SEARCH6:  = C:\ET3
SEARCH7:  = Z:\
SEARCH8:  = Z:\SYSTEM
SEARCH9:  = Z:\BIN
SEARCH10:  = Z:\DOS
SEARCH11:  = Z:\4DOS
SEARCH12:  = Z:\DEBUG
SEARCH13:  = Z:\TEXTUTIL
F:\>map root f:=andys/andys:
錯誤的命令或檔名 - "map"

F:\>CD \
F:\>capture /ec

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Worry the post text message seems not complete same as what the report so please kindly refer to the attachment.
[TEST REPORT 20220512.txt](https://github.com/joncampbell123/dosbox-x/files/8676326/TEST.REPORT.20220512.txt)

**Comment by LowLevelMahn** [comment]
closed this issue for now because my inital question was already answered (and i want to cleanup my open issue list)

@RBTCHENTPE  - please do not hijack issues but open your own if there are any further questions :)

**Comment by LowLevelMahn** [comment]
im closing this issue now - because MY initial question was already answered long time ago :) (and i want to cleanup my open issues list)

@RBTCHENTPE, please do not hijack issue from others :) - but open your own issue if there are any further questions
