### ISSUE TITLE
About free space on the mounted drive

### ISSUE THREAD

**Issue by Kurist2010** [joncampbell123/dosbox-x#2652]
It is in the state of being started as dosv = jp in the conf file.
When I tried to install Japanese Windows 3.1 using the host OS path registered with the mount command as the C drive, it came out and I could not proceed if there was no free space on the way.
The host OS drive has a total capacity of 12TB and 5TB of free space.
After setting "BPINT 21 36" in the debugger, I started setup.exe and traced it. As a result, it overflowed due to the following processing and the free space became 0.
``` asm
mov  ah,36
int  21
cmp  ax,FFFF
je   ($+6)
mul  cx
mul  bx
mov  dx,ax
lea  sp,[bp-02]
```
The return value of int 21 is AX = 0040, BX = F000, CX = 1000, DX = FFFF, which assumes a total capacity of 16GB (256KiB / cluster). Is it possible to set the return value so that the total capacity is 2GB (32KiB / cluster) assuming FAT16?

**Comment by Wengier** [comment]
I think the Int21/AH=36 function does intend to return a maximum of 2GB for older DOS programs. According to the source code, the function calls the AllocationInfo function when the DOS version is less than 7.10, or AllocationInfo32 + DOS_CommonFAT32FAT16DiskSpaceConv otherwise, and in both cases they are supposed to return a maximum of 2GB for this function. Can you check the reported DOS version?

**Comment by Kurist2010** [comment]
The default DOS version is 5.00 because it has not been set.

**Comment by Wengier** [comment]
What if you set the DOS version to 7.10 and see if there is any change?

**Comment by Kurist2010** [comment]
There was no change when I changed to 7.10.

**Comment by Wengier** [comment]
With the setting ver=7.10, the function DOS_CommonFAT32FAT16DiskSpaceConv (written by @joncampbell123) will be called for the disk size conversion. He may know what happens with this.

**Comment by maron2000** [comment]
Hi. Did you try the -freesize option?

**Comment by Kurist2010** [comment]
@maron2000 

mount c (path) -freesize 1024
Even if I mounted it with, the actual size was displayed with dir and setup was also NG.

**Comment by maron2000** [comment]
Actually, the drive size didn't matter.
I successfully installed and booted Win3.1 on a folder with 200GB+ free space.
`mount c [folder of host machine]`

Windows 3.1 seems to recognize the free space up to 2GB.
You basically follow the procedures in Wiki, but need to change to Japanese mode in order to install and boot. 
Used the conf file in Wiki, and copied required files to change to JP mode from PC-DOS 6.2/V.

![win31](https://user-images.githubusercontent.com/68574602/124925416-5f340580-e037-11eb-8b83-48f7d38312b4.png)
![c_drive](https://user-images.githubusercontent.com/68574602/124925424-622ef600-e037-11eb-93f0-01a84418fc39.png)

**Comment by Kurist2010** [comment]
I don't know what caused it at this point, but here it is. 
![win3-1'](https://user-images.githubusercontent.com/79298756/124940015-90ff9900-e044-11eb-9dc9-834175db0f42.png)

setup.exe looks like this. 
![win3-2](https://user-images.githubusercontent.com/79298756/124940060-9b219780-e044-11eb-9cd8-57a37b346d75.png)

**Comment by maron2000** [comment]
Very strange. `mount c [your host folder] -freesize 5` forces free space to be 5MB as expected, but still I can install and boot.

Your screenshot says that you require 500kB free space to install, that is also strange.

![krnl386_001](https://user-images.githubusercontent.com/68574602/124947219-9cee5980-e04a-11eb-8f9f-421f155fc748.png)

**Comment by Kurist2010** [comment]
Since it is setup.exe after copying the Windows folder of Win3.1 that was installed by creating an image file once, I am trying to reinstall it.
The root cause is that it overflows from int 21 (ah = 36) during the processing of setup.exe and sets the free space to 0.

**Comment by Wengier** [comment]
@Kurist2010 The free disk spaces as returned by Int21/AH=36 and Int21/AX=7303 functions are supposed to be completely different for large disks, as the former is not supposed to exceed 2GB, whereas the latter can virtually reach any size. While I don't think this issue should occur, but since you appear to be familiar with the code in this function, do you have any suggestions on how to fix it so that it will work on your computer? Thanks.

**Comment by Kurist2010** [comment]
I think it doesn't have to be limited to the dos version,
int 21h / AH = 36
Assuming FAT16, if the free space of the host drive exceeds 2GB, 2GB is returned.
I think that there is no problem with AX = 0040 / BX = FFFF / DX = FFFF / CX = 0200. 
I think the return value CX = 1000 is the biggest problem.
Is it because the bytes / sectors of the host drive are set as they are?
Currently, the HDD format is AF, so 4096 bytes / sector is natural, but at that time it was 512 bytes / sector.
Is it intentional that BX = F000 is slightly less than the total number of clusters?

int21 / AX = 7303
Since it is an additional function in FAT32, if the free space of the FAT32 host drive exceeds 2TB, 2TB is returned.
(I'm not familiar with this person, so I don't know what to return.)

**Comment by Wengier** [comment]
@Kurist2010 I have re-looked at the code and see what you meant. The byte per sector parameter was not really prepared for such a big size. Will fix.

Meanwhile, yes, you are right that it is intentional that BX = F000 is slightly less than the total number of clusters, in the case that the size is going to exceed 2GB.

**Comment by Wengier** [comment]
@Kurist2010 Can you try the updated Windows build and see if it fixes the issue on your system? Thanks!

* [dosbox-x-64-update.zip](http://cndos.fam.cx/dosware/dosbox-x-64-update.zip)

**Comment by Kurist2010** [comment]
@ Wengier Thank you for updating.
Japanese Windows 3.1 setup worked on C drive with a large host drive mounted in the updated Windows build.

Free space on the drive
![win3-3](https://user-images.githubusercontent.com/79298756/125787635-c4ab2d77-33e0-4954-9fcf-d270a1129a4d.png)

setup 
![win3-4](https://user-images.githubusercontent.com/79298756/125787669-002bcdd4-d4c7-4b62-9acd-9594a64df195.png)

**Comment by Wengier** [comment]
@Kurist2010 Thanks for confirming it works. I will close this issue then.
