### ISSUE TITLE
How can I save the settings (so that it gets used for every game)?

### ISSUE THREAD

**Issue by Toadfield** [joncampbell123/dosbox-x#2688]
When I set some setting while I am in a game (for example which cpu gets emulated or which filter gets use) then it works for the game,but when I exit the game and launch it again then those settings are gone.
I want to apply the settings so that they get used for every DOS Game (but I still want to be able to set specific settings for some games [for example if I would need to set that an older cpu gets emulated,so that the game works]).

**Comment by Wengier** [comment]
I am not quite sure exactly what type of settings you referred to. Do you mean you changed DOSBox-X settings from DOSBox-X's drop-down menus, or you change game settings from their own setup tools? If you mean the former, then after you change them please go to the Configuration Tool, click "Save..." button to save them to the config file. Otherwise the settings will only apply to the current DOSBox-X session. Hope this helps.

**Comment by Toadfield** [comment]
thanks
