### ISSUE TITLE
[git][French translation] Some typos in french translation I find reading the file.

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#2708]
**Describe the bug**
Hello.

After @aybe pushed french translation, and thanks for it, and after I report bug #2707, I wanted to report some typos I've seen in the translation. I used Gedit to do some search.

1) I found 16 times, we can see `C :` instead of `C:' ; there is an useless space between the letter and ":"
2) I found 6 times the same typo but with A instead of C
3) I found 3 times the same typo but with D instead of C
4) I found 5 times the same typo but with Z instead of C
5) In line 1607, instead of "La clé de l'hôte est" -> "La touche de l'hôte est"
6) In line 1969, instead of CHOIX, CHOICE as it is a dosbox command.
7) In line 1970, instead of "Spécifie les clés autorisées." -> "Spécifie les touches autorisées."

These typos are found in manual translations.

Menus typo.

1) Fichier / Touche spéciale / Envoyer la clé du logo -> Envoyer la touche logo -> line 3479
2) Fichier / Touche spéciale / Mapper "Send special key" : clé du logo -> Mapper "Envoyer une touche spéciale" : touche du logo -> line 3515
3) Aide / À propos de Dosbox-X -> bad character used. See Screenchot. À should be replaced by A.

![Capture d’écran de 2021-07-23 11-41-19](https://user-images.githubusercontent.com/8571419/126764747-40f7cd07-10b0-4049-adcc-93c7833e093c.png)

I hope this bug report will help making translation better.

Once again, thanks @aybe for your translation work.

**Comment by FredBezies** [comment]
Here is a modified version of the translation file. You can use it to create a patch.
[fr_FR.lng.txt](https://github.com/joncampbell123/dosbox-x/files/6867985/fr_FR.lng.txt)

I hope it will help :)

**Comment by aybe** [comment]
The problem with this language is that it's inevitably verbose when you want to be precise. 

Other than that in software, you see simplified terms or completely reworked so meaning is not lost, like sauver instead of sauvegarder or enregistrer. 

But even with that there is overflow... If you look at the row of buttons above them, they're radically different from English yet they are still  meaningful. 

Some things must stay as they are otherwise that looks really weird.

So yeah, UI should accommodate to this but not too much else the interface will look strange, it's best to crop as much as possible on the translation I guess. 

As for the spaces and so on, understand that I pre translated everything using Deepl, the program is in contrib, their API changed a bit of the spacing. 

But as I said in #2693, it isn't really the biggest issue, I already pushed a program that sorts them in order so hopefully they get easier to deal with. 

The main issues are fitting and being coherent, that'll take quite some time. You first translate the bulk, you ensure it fits, then that it's coherent.

Translation is a real job and I'm not one so that'll ever take longer! 

#2707

**Comment by FredBezies** [comment]
> The problem with this language is that it's inevitably verbose when you want to be precise.
> 

I know this kind of issues, translating some tools for EndeavourOS project.

> Other than that in software, you see simplified terms or completely reworked so meaning is not lost, like sauver instead of sauvegarder or enregistrer.

I do agree!

> 
> But even with that there is overflow... If you look at the row of buttons above them, they're radically different from English yet they are still meaningful.

I do not say the opposite, far from this!

> 
> Some things must stay as they are otherwise that looks really weird.
> 

Of course. But if you translate 4 or 5 lines with the same content (besides the end) and forget another right just after, it is looking "bad".

> So yeah, UI should accommodate to this but not too much else the interface will look strange, it's best to crop as much as possible on the translation I guess.

Sometimes you can, sometimes you cannot :(

> 
> As for the spaces and so on, understand that I pre translated everything using Deepl, the program is in contrib, their API changed a bit of the spacing.

I used Deepl too and noticed it used specific rules for each language. A simple search and replace could fix this useless space :)

> 
> But as I said in #2693, it isn't really the biggest issue, I already pushed a program that sorts them in order so hopefully they get easier to deal with.

I looked quickly at this bug, it is interesting.

> 
> The main issues are fitting and being coherent, that'll take quite some time. You first translate the bulk, you ensure it fits, then that it's coherent.

Indeed. This is why I reported bad translation for keys I see two or three times in the lng file.

> 
> Translation is a real job and I'm not one so that'll ever take longer!

Neither its mine. I just wanted to give some help. If you need more review, just tell me. I'll can do this on my spare time.
> 
> #2707

**Comment by aybe** [comment]
I wrote a translation guide, please check it out: https://github.com/joncampbell123/dosbox-x/issues/2693#issuecomment-885966334

**Comment by aybe** [comment]
Also, you may be interested in this: https://github.com/joncampbell123/dosbox-x/issues/2693#issuecomment-886003179

**Comment by FredBezies** [comment]
These strings are fixed. Let's close this bug.
