### ISSUE TITLE
ANSI sequences don't work using INT 29h

### ISSUE THREAD

**Issue by pcdosretro** [joncampbell123/dosbox-x#2754]
**Describe the bug**
ANSI sequences don't work using INT 29h

**To Reproduce**
Here are two DEBUG scripts which should clear the screen using ESC[2J

ANSITST1.TXT:
- - - - -
e 80 1b 5b 32 4a
a
mov si,80
mov cx,4
lodsb
int 29
loop 106
int 20

g
q
- - - - -
ANSITST2.TXT:
- - - - -
e 80 1b 5b 32 4a
a
mov dx,80
mov cx,4
mov bx,1
mov ah,40
int 21
int 20

g
q
- - - - -

debug < ansistst1.txt
debug < ansistst2.txt

**Expected behavior**
Both should clear the screen before exiting DEBUG. ANSITST1 does not work but instead prints the ANSI sequence. ANSITST2 which uses INT 21h function 40h to write the string to STDOUT works as expected.

**Environment**
DOSBox-X 0.83.16 running on Windows 7 SP1 64-bit

Once this is fixed, my DOSINFO utility will report that ANSI is loaded.

**Comment by joncampbell123** [comment]
This is for IBM PC/AT mode, correct?

In IBM PC/AT mode, INT 29h is treated as "fast console" output which bypasses ANSI processing. This behavior is inherited from DOSBox SVN.

In PC-98 mode, ANSI processing should happen even through INT 29h. Some PC-98 games will not display correctly otherwise, including Touhou Project.

Does ANSI.SYS in general intercept INT 29h or respond to INT 29h on real MS-DOS?

**Comment by pcdosretro** [comment]
INT 29h is hooked by ANSI.SYS on all versions of MS-DOS/PC DOS so ANSI sequences are processed. INT 29h is fast in the sense that you're going directly to the console driver (builtin or ANSI).

**Comment by joncampbell123** [comment]
They do now, in the latest commit.

Unless you are in IBM PC mode, and you add ansi.sys=false to your dosbox.conf.
