### ISSUE TITLE
cannot ./configure under Linux; SDL mis-identified

### ISSUE THREAD

**Issue by esternin** [joncampbell123/dosbox-x#279]
Under RHEL 6 (64bits):

$ ./configure --prefix=/usr
checking build system type... x86_64-unknown-linux-gnu
...
checking for sdl-config... no
checking for SDL - version >= 1.2.0... no
*** The sdl-config script installed by SDL could not be found
*** If SDL was installed in PREFIX, make sure PREFIX/bin is in
*** your path, or set the SDL_CONFIG environment variable to the
*** full path to sdl-config.
configure: error: *** SDL version 1.2.0 not found!

However, yum reports:

\# yum install SDL
...
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Install Process
rhel-x86_64-workstation-6                                                                    | 1.5 kB     00:00     
rhel-x86_64-workstation-optional-6                                                      | 1.5 kB     00:00     
Package SDL-1.2.14-7.el6_7.1.x86_64 already installed and latest version
Nothing to do

$ find /usr/lib64 -name "\*SDL\*" -print
/usr/lib64/libSDL-1.2.so.0.11.3
/usr/lib64/libSDL_net-1.2.so.0
/usr/lib64/libSDL-1.2.so.0
/usr/lib64/libSDL_net-1.2.so.0.0.7

**Comment by sikthehedgehog** [comment]
Not sure if related (same kind of error, different distro), but ran into this today trying to build DOSBox-X again after a long while. Let's just say I'm not amused:

* Can't build DOSBox-X because SDL 1.2.0 is missing
* Can't install `libsdl1.2-dev` because `libcaca-dev` is missing
* Can't install `libcaca-dev` because `libslang2-dev` is missing
* Can't install `libslang2-dev` because `libpng-dev` is missing
    * Note that `libpng-dev` doesn't exist, `libpng12-dev` took its place
* Can't install `libpng12-dev` because I already have `libpng16-dev` installed
    * No way in hell I'm uninstalling `libpng16-dev`
    * Still may have not worked since the name differs!

( °_° )

So as far as Ubuntu goes, building DOSBox-X using libraries from packages is a no-go because somebody forgot to update all dependencies deep down the line when splitting libpng into libpng12 and libpng16. ~~Considering building SDL 1.2 from source, but that may break SDL 2 and I definitely don't want that. Ugh.~~ Wait nevermind, it doesn't even build because of a problem with the definition of `_XData32`. Software rot at its finest.

Probably a better long term solution would be to port to SDL 2 altogether (since 1.2 development is pretty much abandoned by now) but the source of this specific bug may to be not related to DOSBox-X at all. It would still be nice to know what the exact problem is.

**Comment by joncampbell123** [comment]
Sounds like the same bullshit reason I'm unable to upgrade Linux Mint. It has the same bizarre attachment to libpng12-dev vs libpng16-dev that somehow prevents me from installing gcc-dev or other useful tools. I could go round and round with the package manager for days with that one.

libcaca is not a dependency of DOSBox-X, it's (apparently) a dependency of SDL.

I'm all for porting to SDL 2, let's do it.

**Comment by sikthehedgehog** [comment]
Yeah, all the libraries I listed are dependencies of each other (libcaca is a dependency because for whatever reason SDL can use it for video output, and it has other dependencies of its own because of course it has to be the whole package).

I admit I don't get why libpng12-dev and libpng16-dev can't be installed together. I'm assuming the header files conflict with each other :/ (both have `png.h` I think) This is why I hate when libraries get incompatible upgrades but then keep the same filenames, it prevents installing both side by side which is a problem when you need a program made for the other version (SDL used to be like this while it was still versioned as 1.3, it got fixed when it was bumped up to 2.0 at least).

**Comment by joncampbell123** [comment]
Please let me know if this is still an issue. I have been using CentOS, Windows 10, and a "compiled from scratch" Linux distro of my own making to test and compile this code.

**Comment by joncampbell123** [comment]
DOSBox-X of late now has it's own internal version of SDL 1.x which also has some bugfixes I've made as well. SDL 2.x support exists in the same branch. Use the ./configure script in Linux to compile against SDL 2.x. Make sure the SDL 2 development headers and libraries and "sdl2-config" are installed.

**Comment by esternin** [comment]
`yum install sdl-devel` or `yum install sdl2-devel` was needed. Compiling it now.

**Comment by esternin** [comment]
Under RHEL (7, and probably other versions), compilation from source requires SDL **and** SDL-devel, or SDL2 **and** SDL2-devel, e.g.:
`yum install SDL2 SDL2-devel`

**Comment by joncampbell123** [comment]
When compiling SDL 1 DOSBox-X uses it's own internal version (in the vs2015 directory), not the system library.
