### ISSUE TITLE
Key "~" doesn't work on Dosbox-X 0.83.16 SDL1 Windows

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#2829]
i have problems with ~ key in Dosbox-X , first time it works, but 2nd time it doesn't work , i have to switch to other application and then again switch to dosbox-x , and sometimes it keeps sending ``` key , i have to press BackSpace to stop

**Comment by ThePillenwerfer** [comment]
It doesn't work on Linux either.  Best to use SDL2.

**Comment by maron2000** [comment]
A fix is included in the latest commit, so if you can build on your own, please try and give feedbacks. f63e90ed39daa21db263b66eeeeb0aa933fcaa34
You can refer to https://github.com/joncampbell123/dosbox-x/issues/2770

**Comment by RobertJSawyer** [comment]
This is very similar to the problem I reported with the single open-quote / backtick key (`), which is the unshifted tilde (~) on US QWERTY keyboard:

[https://github.com/joncampbell123/dosbox-x/issues/2770](url)

According to the comments there, the problem has been identified and will be fixed in the next release. :)

**Comment by maron2000** [comment]
I think this issue can be closed.
