### ISSUE TITLE
Can't mount ram drive, or image file

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2876]
when i try to mount .IMG File or Ram Drive , it just says "Cannot Create Drive From File" , why?
![image](https://user-images.githubusercontent.com/71384075/131981135-26608b5c-5313-443e-a951-6981b76a6ab0.png)

**Comment by djkunkel** [comment]
I see the same behavior on Windows 10.0.19042 on version 0.83.17 x64. Version 0.83.16 x64 works as expected.

**Comment by Siddhant-Mashalkar** [comment]
ok

**Comment by Siddhant-Mashalkar** [comment]
might be a bug

**Comment by blindphoneman** [comment]
this is probably due to the added code which can mount more than one partition.  That's a major I, too, am having this problem.  I have gotten some images to mount in what almost seem to be random circumstances, but, can't predict when it will work.  Using the default Windows build, I have gotten errors when trying to imgmount anyhd images with 0.8.3.17.  Reverting back to August release for now.
