### ISSUE TITLE
Changing the internal date/time from the host OS

### ISSUE THREAD

**Issue by ekutner** [joncampbell123/dosbox-x#3137]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

For totally awful reasons I need to frequently change the current date for the DOS program running inside DOSBox-X.
It can obviously by done internally, inside the DOS environment, but that would require exiting the running program and entering the date manually, which gets pretty tedious when has to be done often.
If I enable the Synchronize host date/time option I can change the time on the host OS (Windows 11) and that affects the internal time as expected. That's great but it messes up the time on the host and causes a whole bunch of other issues. For example, web browsing becomes almost impossible because TLS handshake fails because of mismatched clocks.
So I'm looking for a way to dynamically change the internal date of the emulator by a program that will run outside of it, on the host.  Is there any way to do that?

Thanks

**Comment by Wengier** [comment]
I don't really think that dynamically changing DOSBox-X's internal date by an external host-system program that will run outside of DOSBox-X is the best solution for your problem. On the other hand, I have added DATE and TIME commands to DOSBox-X's debugger, so that you can now change the internal DATE and TIME directly from DOSBox-X's debugger window **without having to exiting the current running DOS program**. You can run the debugger from the "Debug" window while your current DOS program is running. Updated Windows builds:

* Windows SDL1: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

Hope this helps.

**Comment by ekutner** [comment]
Thank you!
Unfortunately, for my use case the debugger won't be a good option since the whole thing is meant for very non technical users who are forced to use an old DOS accounting program. I can imagine the panic just by opening the debugger and seeing all those HEX numbers :) so I don't see them using that for anything.
My goal was to write a small external Windows program that would show a nice calendar control and would allow them to easily change the date  inside the DOSBox. I can certainly see why that is not a common use case. I was just hoping there would be a way to do it somehow through some sort of inter-process communication. Anyway, I guess changing the whole system time is currently the best option. Thanks again.

**Comment by Wengier** [comment]
@ekutner I thought you are a technical user wanting to achieve this because I don't think a typical user would want to frequently change the current date/time for some DOS program as you described in the original post. I can understand the debugger interface is not for a typical user, but I also want to mention that for this particular application however, you can basically ignore almost everything in the debugger interface but just focus on the DATE and TIME commands themselves - the syntax for changing the DATE and TIME in the Debugger is **exactly the same as the syntax for changing them in the DOS shell**, e.g. (assuming country code 1):

``DATE 12-10-2021``
``TIME 10:11:12``

Once again, you can ignore everything else in the Debugger interface for this, and just type the DATE/TIME command in it as you do in the DOS shell. But of course I agree that the Debugger interface is not very user-friendly from a normal user's POV at this time, perhaps the UI can be improved latter on so that it is even easier for a typical user to get started.

**Comment by ekutner** [comment]
Got it, it would certainly be great if there was a UI for setting the date using the menus, but again, very clear why this is not a priority. Thank you.

**Comment by Wengier** [comment]
@ekutner There is a builtin BIOS Setup Utility in DOSBox-X, but the only things you can change at this time from the BIOS Setup Utility are the date and time, so I was thinking that adding a menu option for this as well would render the BIOS Setup Utility useless. The BIOS Setup Utility is desired by DOSBox-X, and I hope that it allows more things to be changed from there in the feature so that adding a menu option for changing the date and time would no longer makes the BIOS Setup Utility useless.

**Comment by ekutner** [comment]
@Wengier I'm not sure it's the same use case since the BIOS can only be set when the VM starts but I'm talking about changing it while it is running. It's closer to giving the debugger command you mentioned a UI, although I would have been happy with just being able to send a custom Windows Message, or something like that, to set a new time.

**Comment by Wengier** [comment]
@ekutner It is true that the BIOS Setup Utility can only be entered when the VM starts (or restarts), but still I was concerned that adding a menu option specifically for changing the date and time would make the BIOS Setup Utility useless. However, I decided to add the ability to enter (any) debugger commands directly from the UI - just go to "Debug" => "Show logging text" => "Enter Debugger Command", and then type a debugger command like `DATE 12-10-2021` and `TIME 10:11:12` (same as the DOS shell commands in this case). Then the internal date and time will be changed  while your current DOS program is still running, without any need to open the debugger or seeing the HEX numbers. Hope this helps.

**Comment by ekutner** [comment]
@Wengier  Sounds good, thank you! And thanks even more for maintaining a wonderful product!
