### ISSUE TITLE
How to wait sometimes for host commands to end

### ISSUE THREAD

**Issue by AlejandroSdeL** [joncampbell123/dosbox-x#3146]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

Hi.
Windows `START` command has a switch (`/W`) that allows to wait for the called command to end.  By default, in a batch file `START` does not wait.  So it is possible to wait for some commands (using the switch), and not to wait for some others (avoiding the switch).
If I am not wrong, by default DOSBox-X `START` command waits for the called host command to end, unless the `startwait` config option is unset.  Is there an easy way to wait sometimes and some others not?
I was thinking about adding `START` in the list of `startincon` commands, and then using `START START /W command` for waiting, and `START START command` for not waiting, but it seems too involved and maybe it does not work at all.
Thanks.

**Comment by Wengier** [comment]
@AlejandroSdeL With the current version you can change the `startwait` setting from the command-line, e.g.

`config -set startwait=true`
`start notepad`

`config -set startwait=false`
`start mspaint`

If you like, you can put these commands in two different batch files so that one batch file runs START with `startwait=true`, and one with `startwait=false`. Hope this helps.

**Comment by AlejandroSdeL** [comment]
@Wengier 
Great!  Is it documented which settings can be changed on the fly and which settings cannot?  (Assuming both types of setting exist.)

**Comment by Wengier** [comment]
@AlejandroSdeL There are numerous config options in DOSBox-X, and they are not static, so making a full list may not be possible. However, if a config option cannot be changed on the fly, then most likely there will be a prompt asking whether you want DOSBox-X to automatically restart itself in order to apply the new setting, see a screenshot below: 

![image](https://user-images.githubusercontent.com/8216923/146470013-cad1c867-32c4-4eb7-8b58-f80f5401bb5f.png)

**Comment by AlejandroSdeL** [comment]
Great, thank you.
