### ISSUE TITLE
Two problems setting configuration

### ISSUE THREAD

**Issue by AlejandroSdeL** [joncampbell123/dosbox-x#3174]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

Hi.  I am trying to modify the configuration either with the `-set` command line option of DB-X, or with the `config -set` commad within the emulation.

My first problem is that I do not fully understand the syntax.  For example, the wiki says that the syntax for `-set` command line option of DB-X is `-set <section property=value>`.  Is `section property` a single name (that is, the property)?  How the section is identified then?  The wiki gives as an example `-set machine=pc98`, but I do not see any "section" there (which I assume should be `dosbox` for property machine).

Regarding the syntax of the `config -set` commad, with `config /?` I got `-set "section property=value"`.  However, I tried several different forms that seems to work fine:

1. `config -set "parallel parallel1=file"`
2. `config -set parallel parallel1=file`
3. `config -set "parallel1=file"`
4. `config -set parallel1=file`

My second problem is about the spaces and quotes within the parameter of the `-set` command line option of DB-X.  How spaces and quotes can be included?  I guess that I can use quotes for including spaces, but if the setting also includes quotes, I do not know how to proceed.  For instance 
```
parallel1=file file:output1.prn timeout:1000 squote openwith:'"My special program.exe" /someflag %1'
```
where %1 is a variable value.  For this particular case I think I can use a batch file for running the actual (openwith) program, but in another situation maybe not.  With the `config -set` this problem does not occur because it seems to take everything after the `=` sign.

Thanks.

**Comment by Wengier** [comment]
The full syntax for ``config -set`` command is ``config -set <section property=value>``, but if ``property`` does not include a space, then you can omit the ``section``. So basically the full syntax ``config -set <section property=value>`` always work, whereas the second form works only in some cases (i.e. no space in ``property``). Quotes are required if there is at least a space, but optional otherwise.

For the second question, you can take %1 out since it is automatically included in the end. Otherwise I think the setting should work. Hope this helps.

**Comment by AlejandroSdeL** [comment]
@Wengier 
Hi.

I think I cannot take %1 out.  The file containing the captured output of the printer (output1.prn) is included automatically at the end, but not %1 which in my example is a parameter of a batch file that calls the emulation.  Anyway the general question is how to include quotes and spaces in a parameter of a command line option of DB-X.  Something like this:
```
REM This is my script which receives some parameters %1 %2...
...
dosbox-x.exe /someoption itsparameter /c "some command" /c "some other command that uses %2"
```
where `itsparameter` contains quotes and spaces.

**Comment by Wengier** [comment]
@AlejandroSdeL I think you asked earlier why ``dosbox-x.exe -c "MOUNT C C:\" did not work, and the reason is that DOSBox-X translates \" to ". So if you want to include quotes and spaces in a parameter of -c option, just use \" within ", e.g.

``dosbox-x.exe /c "some \"command\""``

In such case the actual command to be executed will be ``some "command"``. Hope this helps.

**Comment by AlejandroSdeL** [comment]
Yeah, I asked that, sorry.  I did not notice that it could be helpfull here.  Thanks.
