### ISSUE TITLE
Core type = full - how does it differ from the other types?

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#3218]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

core=full - what does it do? [DOSBox wiki](https://www.dosbox.com/wiki/Configuration:CPU) shows only "Deprecated".

Sorry for the basic question, but I couldn't find where the answer is documented.

**Comment by rderooy** [comment]
FYI, I updated the draft wiki cpu settings last weekend, this will be pushed to the regular wiki with the next dosbox-x release.
https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3ACPU-settings-in-DOSBox%E2%80%90X

**Comment by Torinde** [comment]
Thanks @rderooy !
I'm curious what it does, what's the history behind, why was it deprecated?

**Comment by rderooy** [comment]
I don't know the details. Most likely bitrot as the dynamic and normal cores got more attention.

**Comment by joncampbell123** [comment]
Additionally, the recursive page fault handling from DOSBox SVN requires full core, otherwise I would have removed it.

As far as I can tell, it appears to be an alternate implementation based on a lookup table that might have come from another emulator. It's not 100% updated to handle non-recursive page faults, which is why if you run Windows 95 with full core, a few things don't render properly (doesn't seem to crash though). Otherwise, it's not been maintained.

**Comment by Torinde** [comment]
Thanks for the explanation!
Should that be also in the wiki? Wengier/dosbox-x-wiki#11
