### ISSUE TITLE
(Suggestion) Add option to toggle between SDL2-drawn and Windows-drawn menu to the SDL2 build, if possible

### ISSUE THREAD

**Issue by DSN9990** [joncampbell123/dosbox-x#3240]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [x] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

Until now, SDL2 builds only offer the custom-drawn menu, which has a known limitation when using 3dfx Voodoo and GL shaders.

### What you want

If possible, please add an setting to toggle between custom- and native menus, This should alleviate these aforementioned limitations.

**Comment by rderooy** [comment]
For SDL1, which does support windows drawn menus, this was accomplished with a modified SDL1 version which is included in the DOSBox-X source tree.

SDL1 is end-of-life, and therefore no more updates will come from upstream, so modifying it is not a big deal.

For SDL2 the upstream version is used, so only SDL drawn menus.
https://discourse.libsdl.org/t/suggestion-native-gui/21103/5

**Comment by Wengier** [comment]
Just to show that Windows native menu is possible on SDL2 build:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

You cannot change the menu style via a config option. You need to change this line in the code to toggle the menu style:

https://github.com/joncampbell123/dosbox-x/blob/master/include/menu.h#L104

**Comment by Wengier** [comment]
It turns out that it is not really necessary to modify the SDL2 library in order to support native menus for Windows SDL2 builds. In other words, native menus in Windows SDL2 builds can be done by just modifying the DOSBox-X code itself, unlike Windows SDL1 builds. So native menus can be the default menus for both SDL1 and SDL2 builds, and an updated Windows SDL2 build with native menus is available from:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)
