### ISSUE TITLE
MT-32 emulation is lower pitch compared to other versions of DOSBox

### ISSUE THREAD

**Issue by emmanu888** [joncampbell123/dosbox-x#3277]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

0.83.22 SDL1

### Describe the bug

I have found out that DOSBox-X seems to have some weirdness when it comes to audio pitch when emulating the MT-32 when compared to other versions of DOSBox. 

Included as well is a video where the first minute and a half is recorded using DOSBox-X and the other minute and a half is recorded using DOSBox ECE to let everyone hear how the Red Baron main title tune is supposed to sound like.

https://youtu.be/tyR-RiIEZN8

### Steps to reproduce the behaviour

1. Configure Red Baron to use MT32 in DOSBox-X
2. Audio is lower pitched
3. Configure Red Baron to use MT32 in DOSBox ECE
4. Audio sounds as expected

### Additional context

Slight edit as i just tried other games that can use the MT32 in DOSBox-X and compared them to how they sound in DOSBox ECE and DOSBox-X definitely has an issue with its MT32 emulation as Space Quest 3, Police Quest 3 and Ultima 6 all exhibits the same lower pitched MT32 audio that Red Baron has. 
But in DOSBox ECE they all sound as they should sound like.

**Comment by Jkapp76** [comment]
I've noticed this difference in pitch. I personally can't say which is correct.

**Comment by Cerrseien** [comment]
But I can, since there are ScummVM games which use the MT-32 emulation (Legend of Kyrandia comes to mind immediately, and yes, ScummVM emulates the Kyrandia engine). maron2000 is right: your midi.mt32.rate value needs to be congruent with the mixer.rate value (which should be set to your sound device's current sample rate), otherwise not enough samples are being fed into the device, lowering the pitch.

And yes, I know this from personal experience.
