### ISSUE TITLE
Setting core=simple or trying to set the cycles to fixed XXX (any number) crashes on Windows 10 64bit

### ISSUE THREAD

**Issue by Dancovich** [joncampbell123/dosbox-x#335]
Intel Core i5-3570
8GB of RAM
GeForce GTX 760
Windows 10 Pro 64bit
DOSBox-X version 20171205-2228

Here is my default dosbox.conf that does work
```
[sdl]
windowresolution=1280x720
usescancodes=true

[render]
aspect=true

[sblaster]
irq=5
```

From that the following actions cause it to crash on both 32bit and 64bit executable:

- Adding core=simple on dosbox.conf under [cpu] crashes on start no matter what other options I set
- Adding cycles=fixed XXX DOES work when done on dosbox.conf but crashes if using the menu even if I disable automated cycles detection first
- When using cycles=1000 (on dosbox.conf or else it crashes) and trying to run Ultima VIII Pagan the game takes ages to load and is supper slow, but the exact same configuration for cycles on vanilla DOSBox 0.74 runs fine

**Comment by joncampbell123** [comment]
True, the 'simple' core has bitrotted since all focus is on core=normal or core=prefetch.

**Comment by Dancovich** [comment]
Makes sense.

And what about the problems with cycles? That happens independently of core=simple

I'm trying to run Ultima 8 with DOSBox-X but am having issues with the mouse on default settings although the game itself seems to run fine. I tried using some of the settings EA used on their Origin DOSBox version of the game to see if that solved something but found these issues.

**Comment by joncampbell123** [comment]
I understand from others on this issue tracker that there's a general problem with the mouse and some games, though I have been unable to recreate that on my Linux dev system.

**Comment by joncampbell123** [comment]
I just fixed mouse problems with SDL 1.x on Windows. SDL 1.x tracks mouse motion in a way that used to work 100% reliably in Windows, but is somewhat unreliable in Windows 10.

**Comment by joncampbell123** [comment]
I'm going to keep the simple core after all. It's just another variant of the normal core that doesn't like paging. It refers to the same normal CPU opcode handling header files as "normal".

**Comment by joncampbell123** [comment]
Segfault here on Linux with core=simple, as well. Looking into it now.

**Comment by joncampbell123** [comment]
No wonder!

    #define GETIP       (core.cseip-SegBase(cs)-MemBase)
    #define SAVEIP      reg_eip=GETIP;
    #define LOADIP      core.cseip=(MemBase+SegBase(cs)+reg_eip);

    static INLINE Bit8u Fetchb() {
        Bit8u temp=host_readb(core.cseip);
        core.cseip+=1;
        return temp;
    }

Now I get what's so simple about the "simple" core, and why it doesn't like paging! But, it's segfaulting in Fetchb(), so I guess the memory address is too far out to be a valid pointer.

**Comment by joncampbell123** [comment]
Fixed in commit 341a54dab0a7e7e4847a7b775cbf3510856d546a

**Comment by joncampbell123** [comment]
Issue is fixed. I will close this issue unless any other situations occur when core=simple.

**Comment by Dancovich** [comment]
So far this particular issue seems to be ok in my end, so at least for me it's ok to close the issue. Thanks.

**Comment by joncampbell123** [comment]
Certainly.

I will close out with an explanation: DOSBox-X emulates the Intel bootup behavior of executing from the top of 4GB memory (386 behavior) or 16MB memory (386SX behavior). The simple core is simple in that it assumes it can directly fetch from MemBase + cseip, which is fine as long as paging is not enabled AND cseip is within the range of valid system memory. Just below the top of 4GB is not within range, therefore segfault. The fix range-checks and defers to normal core in that case now, which is why it no longer crashes.

**Comment by Dancovich** [comment]
Thanks for the explanation. 

This makes me wonder what simple core has to gain working like that. I have Ultima 8 from Origin and their bundled DOSBox is configured to use simple core but I tried normal core for a bit and nothing changed. Is there an app or game that's known to crash unless simple core is used?

**Comment by joncampbell123** [comment]
I'm guessing that whoever wrote it assumed emulation speed could be improved if opcode execution were to read directly from memory instead of fetching through CPU paging and TLB lookup. It probably does some improvement for real-mode games that don't use paging, and for DOS games where 32-bit protected mode is used without paging. In any case the way it's written it just re-uses the normal core code (the headers) with some macros changed to do as described.

Just for reference: Most DOS extenders including DOS4GW.EXE and DOS32A.EXE won't turn on paging unless EMM386.EXE is resident or running under Windows, so for the most part, 32-bit DOS games (Ultima 8 probably as well) run without paging enabled.
