### ISSUE TITLE
Windows 98 widescreen resolutions don't work in the latest build

### ISSUE THREAD

**Issue by FrankyMc** [joncampbell123/dosbox-x#3373]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

0.83.24

### Describe the bug

In the most recent build, selecting any widescreen resolution in windows 98 with the 9x vbemp driver installed results in this: https://i.imgur.com/RFkN0k0.png

If I go back to version 0.83.22 it's working as expected.

### Steps to reproduce the behaviour

select any widescreen resolution

**Comment by Jkapp76** [comment]
That looks exactly like what happens when I set dosbox to opengl but do not have my computer set to prefer nvidia graphics.

**Comment by FrankyMc** [comment]
I tried every output mode but unfortunately this happens regardless of which one I use.

**Comment by rderooy** [comment]
You say it happens with 0.83.24 but not with 0.83.22? How about 0.83.23?

Are you able to do a `git bisect` to track down the issue?

**Comment by rderooy** [comment]
I can confirm the behaviour and that it broke between 0.83.22 and 0.83.23. So the issue has been there for over a month. Will try to do a `git bisect`.

**Comment by rderooy** [comment]
This is the offending commit: https://github.com/joncampbell123/dosbox-x/commit/4ee6873e3fc1898c0440527329657037633f0cab
```
4ee6873e3fc1898c0440527329657037633f0cab is the first bad commit
commit 4ee6873e3fc1898c0440527329657037633f0cab
Author: Jonathan Campbell <jonathan@castus.tv>
Date:   Sat Feb 26 23:16:32 2022 -0800

    INT 10 VESA BIOS: Add flag for specific S3 modes where the offset register (stride) must be rounded up to a power of 2 to display correctly. It seems the Windows 3.1 S3 drivers, when "640x480 (1 Meg) 16.7 million colors" is selected, requires 2048 bytes per scanline. Note that specific selection uses 24 bits/pixel, not 32 bits/pixel, and 640*3 == 1920

 src/ints/int10.h         | 1 +
 src/ints/int10_modes.cpp | 9 ++++++++-
 2 files changed, 9 insertions(+), 1 deletion(-)
```

**Comment by joncampbell123** [comment]
> This is the offending commit: [4ee6873](https://github.com/joncampbell123/dosbox-x/commit/4ee6873e3fc1898c0440527329657037633f0cab)
> 
> ```
> 4ee6873e3fc1898c0440527329657037633f0cab is the first bad commit
> commit 4ee6873e3fc1898c0440527329657037633f0cab
> Author: Jonathan Campbell <jonathan@castus.tv>
> Date:   Sat Feb 26 23:16:32 2022 -0800
> 
>     INT 10 VESA BIOS: Add flag for specific S3 modes where the offset register (stride) must be rounded up to a power of 2 to display correctly. It seems the Windows 3.1 S3 drivers, when "640x480 (1 Meg) 16.7 million colors" is selected, requires 2048 bytes per scanline. Note that specific selection uses 24 bits/pixel, not 32 bits/pixel, and 640*3 == 1920
> 
>  src/ints/int10.h         | 1 +
>  src/ints/int10_modes.cpp | 9 ++++++++-
>  2 files changed, 9 insertions(+), 1 deletion(-)
> ```
> 
> I tested this with 720p, but 1080p in limited testing behaved the same.

That was added to appease a very old S3 driver for Windows 3.1 made for a very old chipset with a specific constraint for it's 24bpp mode. Apparently the driver sets the mode and *assumes* the stride per scanline is a power of 2.

Perhaps it's best to limit that to only svga_s386c928 instead of S3 emulation in general.

**Comment by joncampbell123** [comment]
Hold on a second... the code is correctly rounding up to 2048 for that particular mode 0x212, but it still reports 1920 bytes/scanline when queried by the VBE interface.

It works with the Windows 3.1 driver because it just *assumes* 2048 bytes per scanline and doesn't bother to query it, but VBEMP obviously wants to know what the stride is and it uses the wrong value. Will fix.

**Comment by joncampbell123** [comment]
I did two things:

1. I fixed the VBE mode query to return the correct power of 2 scanline length of the mode.
2. I fixed the VBE interface not to list the mode in the VBE mode list so that VBEMP and other code are not tempted to try and use it. The mode still works fully, it's just not listed when the call is made to enumerate available modes.

**Comment by joncampbell123** [comment]
The latest commit should resolve the graphical issue.
