### ISSUE TITLE
No Audio from PCI Sound Card (HX-DOS Package)

### ISSUE THREAD

**Issue by WarPath2020** [joncampbell123/dosbox-x#3431]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

DOS

### What version(s) of DOSBox-X have this bug?

0.83.24

### Describe the bug

There is no audio when running the HX-DOS package. My machine has DOS 6 and on top of that runs the HX-DOS package. Using a PCI sound card (ES1989 chip).

### Steps to reproduce the behaviour

1. Install DOS on HDD.
2. Unzip/install HX-DOS package on C:\.
3. Run any DOS game.

**Comment by Wengier** [comment]
For running the HX-DOS package in your DOS environment, you need to load the DOS driver for your PCI sound card so that you can hear the audio. Similar for most other DOS software or games, in which case you also need to load such a DOS driver in order to hear sound from them from your computer. Some PCI sound cards may not provide native DOS drivers though. Meanwhile, since the HX-DOS package is based on the HX DOS Extender, you may be able to hear sound by replacing the included HX DOS Extender 2.18 with HX DOS Extender 2.17+ that supports some modern sound cards such as AC97, HDA, and some PCI sound cards, which may or may not work with your PCI sound card. HX DOS Extender 2.17+ is available from:

https://sound-dos.ucoz.ru/load/new_hxdos_extender_2_17/1-1-0-8

Hope this helps.

**Comment by joncampbell123** [comment]
DOSBox-X does not emulate PCI sound cards. Yet.

If you need ESS AudioDrive emulation use a driver for ISA-based cards/chipsets like the ESS 688 and set sbtype=ess688
