### ISSUE TITLE
I hope that the HX DOS version will not exit dosbox-x when pressing Ctrl + C

### ISSUE THREAD

**Issue by hlizard** [joncampbell123/dosbox-x#3439]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

MS-DOS 7.10

### What version(s) of DOSBox-X have this bug?

dosbox-x-mingw-hx-dos-20220401061701.zip

### Describe the bug

I hope that the HX DOS version will not exit dosbox-x when pressing Ctrl + C

### Steps to reproduce the behaviour

edit program, win98 ctrl+c not work

**Comment by Wengier** [comment]
The special key combination Ctrl+Break is controlled by HX DOS Extender (which the HX-DOS version uses) instead of DOSBox-X. You may want to report the issue in the HX DOS Extender issue tracker:

https://github.com/Baron-von-Riedesel/HX

**Comment by BridgeHeadland** [comment]
Now I have not followed anything on whether HX DOS has been updated or not since the last time I downloaded it (it's DOSBox-X for DOS we are talking about, right?), and that is a while ago. How often is HX DOS updated and will it come more updates? I ask because I'm curious and that I might want to try it out someday.

**Comment by Wengier** [comment]
HX-DOS build is based on both the DOSBox-X source code and the HX DOS Extender, and both are being updated of course. It is available in the Release section.

**Comment by Wengier** [comment]
@BridgeHeadland And yes, the HX-DOS build is basically DOSBox-X for DOS (using the HX DOS Extender approach; there is also the LOADLIN approach made by @grapeli). The HX-DOS build for the current DOSBox-X 0.83.25 version is based on HX DOS Extender v2.19 released this year (the most recent version). If the bug as initially reported by @hlizard is fixed in the HX DOS Extender, then it is expected to be used by later HX-DOS builds too.

**Comment by hlizard** [comment]
@Wengier Baron von riessel taught me a basic DOS command. Yes, just the "break off" command. That's what I want. So, this is not a bug.
