### ISSUE TITLE
fldpi only loads pi to 53-bit accuracy instead of 64-bit accuracy

### ISSUE THREAD

**Issue by pcdosretro** [joncampbell123/dosbox-x#3451]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 7 SP 1 (64-bit)

### What version(s) of DOSBox-X have this bug?

0.83.25, 0.84.0 (64-bit builds only)

### Describe the bug

fldpi only loads pi to 53-bit accuracy instead of 64-bit accuracy. The fraction loaded is C90FDAA2 2168C000

This is also true of the instructions fldl2t, fldl2e, fldlg2, fldln2

### Expected behavior

fldpi should load the fraction C90FDAA2 2168C234

### Steps to reproduce the behaviour

Get DEBUG or DEBUGX from my website - https://pcdosretro.github.io/enhdebug.htm

a
fninit
fldpi
fstp tbyte ptr [80]
int 3

g
d 80 la

**Comment by cimarronm** [comment]
On anything compiling for an x86 platform with the `C_FPU_X86` define set, it will use the `fldpi` instruction itself in emulation so this shouldn't be a problem. On compiler/platform combinations which support a long double type, PR #3453 should allow it to fill the full 64-bit mantissa. BTW, I am getting a mantissa of 0xc90fdaa22168c235 (instead of 0xc90fdaa22168c234 as you listed) which is closer to PI.

0x4000c90fdaa22168c235 = 3.141592653589793238**51...**
0x4000c90fdaa22168c234 = 3.141592653589793238**29...** 
PI = 3.141592653589793238**46...**

**Comment by pcdosretro** [comment]
The Intel manual says FLDPI loads C90FDAA2 2168C234 C which gives you 3.141592653589793238
I will recheck it with v0.83.26 which should have your fix for this (and hopefully a fix for my previous FPU bug #3440)

**Comment by pcdosretro** [comment]
The problem here is the damn MSVC compilers don't actually support long double as 80-bit floating point, long double is the same as double. The sad thing is the old 16-bit DOS MS C compilers did in fact support long double as 80-bit floating point.

**Comment by cimarronm** [comment]
Yeah, unfortunately microsoft decided not to support the extended precision long double nor inline assembly in the 64-bit version of the compiler. The MinGW 64-bit version for windows should support `C_FPU_X86` and give you a 64-bit version with the x87 instruction set.

**Comment by pcdosretro** [comment]
I switched to the 32-bit build which works fine. Technically this isn't a bug in DOSBox-X so I guess this can be closed.
