### ISSUE TITLE
Ability to chose preferred EGA variants

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3516]
### Is your feature request related to a problem? Please describe.

On some PCs I do not get the desired EGA palette.

### What you want

I have learned that EGA and older are analog, unlike VGA and newer, which are digital. This means that the EGA palette can vary slightly from video card to video card, depending on which video card you use, the same applies when running EGA software in DOSBox in general, and even though DOSBox is a digital program, a digital emulator, operating system, or whatever you want to call it, all versions of DOSBox-X and other DOSBoxs that have ever existed emulate analog graphics in EGA programs, and older, depending on which video card is in your computer (or another device). ). Previously, I (the hardware amateur) claimed that there is only 1 correct EGA palette, and 1 wrong EGA palette, but now I realize that both are correct. This does not mean that I am flexible on which EGA palette the program uses when I run it, because I have a favorite that I prefer more than the other (s), and there are probably more who have. Unfortunately, your video card (which you have chosen for some reason) does not allow you to select the EGA palette in DOSBox, as long as DOSBox only emulates the EGA palette based on which video card you use, because EGA is actually analog. Anyway, I think it will be possible to add an option in a future DOSBox-X, where you can choose between auto (depending on the video card) or one of the specific options, where I only know about 2 (it's too late add it to 0.82.26).
I add the 2 EGA palettes I know of as examples. If you do not see the difference, you can paste each of them in Paint, and compare the colors by picking each individual color.

![image](https://user-images.githubusercontent.com/85258509/170545482-4cac4999-d312-4c73-aa77-56a350700153.png)
![image](https://user-images.githubusercontent.com/85258509/170545527-a60275fe-4e72-4b81-994e-0a98e8542e75.png)

### Describe alternatives you've considered

I do not know much about EGA, as I did before, so this is just an example based on my bad experience. It is possible it is poorly worded.

EGA variant: possible values: auto, 1, 2.

### Additional information

I thought I could not be the only one in the world who is picky about the EGA experience. Even if EGA is analog, it does not mean that a future version of DOSBox can only emulate analog EGA, and not digital, I mean.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
No. MDA, CGA, EGA, Tandy, and PCjr are *digital* TTL signals. The EGA uses two per R, G, and B to display up to 64 colors, though only in the 640x350 graphics and text modes. Any other mode (200-line graphics) puts the monitor into a mode that is compatible with the video connector on CGA cards and only the 16-color CGA palette is available.

Video output on the PC platform did not become analog until IBM brought MCGA and VGA video hardware to the world. MCGA and VGA are analog signals.

If there is any variation in color and intensity, that is due to the EGA monitor's handling of TTL signals, not the TTL outputs of the card.

Please do your research:

https://en.wikipedia.org/wiki/Video_Graphics_Array

https://en.wikipedia.org/wiki/Enhanced_Graphics_Adapter
