### ISSUE TITLE
Printing with AirPrint oder IP

### ISSUE THREAD

**Issue by hardl1** [joncampbell123/dosbox-x#3662]
### Question

Is there a way to print from Mac via AirPrint or IP?
From the DosBox in a Windows VM, this works without any problems.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by hardl1** [comment]
There is a post in the WiKi: Setting up printing in DOSBox-X. 
There are examples for Windows and Linux. 
Does anyone have an example for macOS?

**Comment by hardl1** [comment]
I have already tested that.
I see the printout on the screen, but I can't find a file.

**Comment by rderooy** [comment]
Are you using DOSBox-X or DOSBox SVN? They are not the same thing!

**Comment by hardl1** [comment]
DosBox-X in my nee MacBook M1, SVN on my old MacBook

**Comment by rderooy** [comment]
If you follow the instructions on the wiki. Select a PostScript printer in the DOS application connected to LPT1. And in your dosbox-x config file set the settings as mentioned on the wiki.

If you then print from the DOS application the macOS Preview application should open with the printout. You should then be able to either print or save from the Preview application.

If the Preview application does not open, try to set the `captures=` setting to a different location where you can actually create files.

**Comment by hardl1** [comment]
Unfortunately does not work.
I use an old CLIPPER program, there I can choose the Postscript character set. 
Then text is output to the printer with e.g. 
@ 01,08 SAY "Name ".
The macOS Preview application does not open, the file is output in the DOSBox-X window, but not in a file. 
Change e.g. captures= /User has no effect.

**Comment by rderooy** [comment]
I have no macOS system, so I have no way to check myself. Perhaps it is something specific to ARM Macs.

**Comment by hardl1** [comment]
Ok, thanks anyway.
I am now trying to write directly to a file in the CLIPPER program.

**Comment by emendelson** [comment]
My setup of DOSBox-X for the Mac (DOSBox-X wrapped in an AppleScript)  prints to any attached printer, including AirPrint printers. You might want to look at its config file (it uses shell scripts to perform various printing tasks):

http://www.columbia.edu/~em36/dosboxapp.html

**Comment by hardl1** [comment]
Unfortunately the APP doesn't work for me on a macbook 16" M1.
After the download, you will be prompted to move the APP. After moving, an exception error appeared when clicking on the APP. When trying to open again appears
an icon with C:/ and closes immediately.
A new download doesn't change anything either.

**Comment by hardl1** [comment]
@emendelson 
This is the crash report that appears every time the DOSBox-X app is launched. The config files can be accessed by holding down the Option key.dosbox-x-2022-08-09-103009.ips

**Comment by emendelson** [comment]
@hardl1 - Thank you for this - I just saw it today. I'll have to fix this next week at the earliest when I have an Apple Silicon Mac to work with. I can guess what happened and the fix may be easy.

**Comment by hardl1** [comment]
@emendelson. Thanks very much! 
DOSBox-X runs fine under Rosetta.
Also the control commands for the printer with LPT2.
That's enough for me.
Nevertheless, please check the printer config. In the printer config are only LPT1-5. In dosboxapp.html LPT1-6.

**Comment by emendelson** [comment]
I'm glad it works under Rosetta. I'll try to fix it for ARM later this week if possible.

I haven't finished writing the code that will make LPT6 work correctly under macOS. It works in the Windows version. I'll make that clear on my web page.

**Comment by emendelson** [comment]
The "set window height" setting did not work if you chose 25 lines for the height. I have now fixed this. Thank you for pointing this out. Please download the current version.

I think you are asking for a smaller font in the DOSBox-X window. You will need to edit the ttf options in the base configuration.

I don't think you can start two different configurations with the current system, but of course you should feel free to edit the AppleScript for yourself and try to make this possible.

**Comment by hardl1** [comment]
I loaded the current version, but at 25/80 the window is still significantly wider than at 43/80.
I'm not looking for a smaller font, but a smaller window.
Do I have to rewrite the autoexec.bat with every update?
How can I switch to German keyboard?
With an earlier Dosbox you could specify two different e.g. heiz.conf and haus.conf when calling it. But that's not so important.

**Comment by emendelson** [comment]
To reduce the size of the window, specify a point size in the [ttf] section and experiment until you get the size you want.

For autoexec.bat *please* read the section on this page about running commands automatically at startup:

http://www.columbia.edu/~em36/dosboxapp.html

For information in selecting a keyboard, please read the wiki.

In ordinary DOSBox-X, you can choose between different configurations when launching. My app does not support that, but you can easily modify the AppleScript "wrapper" so that it does.

**Comment by hardl1** [comment]
Sorry .
The window size via lins and cols didn't work that way, but via winperc and ptsize.

I know the DOSBox-X wiki, but in DOSBox-X-App I can't enter keyboardlayout=de for [dos]. The KEYB command does not work at the prompt either.

**Comment by emendelson** [comment]
About the keyboard layout: I am traveling and can't test this. Try changing the keyboard layout in the current build of DOSBox-X. If it works in DOSBox-X and doesn't work in my app, then I will see if I can figure out which setting is needed in my app. Meanwhile, if it works in DOSBox-X, you'll need to use DOSBox-X instead of my app.

**Comment by hardl1** [comment]
Ok, I still use your app because printing works here.
In the DOSBox-X I had configured under [dos] keyboardlayout = GR and it worked there. 
Maybe you can change that later.

**Comment by emendelson** [comment]
Try de not gr.

**Comment by emendelson** [comment]
And I've now updated the app so that it should run in native Apple Silicon mode on M1/M2 Macs. And the German keyboard works perfectly in my app (so does French, UK, etc.), so I can't imagine why it isn't working for you. There is absolutely nothing in my build that handles keyboard/regional settings differently from standard DOSBox-X.

**Comment by hardl1** [comment]
I loaded the current version V22.08.17. This runs perfectly under Rosetta, without Rosetta I can now open the DOSBox-X-App.app, but my Clipper program starts with an "E" and hangs.

The KEYB and COUNTRY problem was mine! The Clipper program's config has overwritten "MOUNT C" and the "C:/ path". With %PATH% that's ok. I can now enter all commands at the prompt.

Under "Edit base configuration file" I did not find in [dos] "keyboardlayout =" and in [config] "country =". 
Can this be set somewhere else with DOSBox-X-App.app?

**Comment by emendelson** [comment]
> I loaded the current version V22.08.17. This runs perfectly under Rosetta, without Rosetta I can now open the DOSBox-X-App.app, but my Clipper program starts with an "E" and hangs.

Have you tried it in standard ARM DOSBox-X? If it works in standard DOSBox-X, use your program there. My app does *nothing* that can affect the way a program runs.
> 
> The KEYB and COUNTRY problem was mine! The Clipper program's config has overwritten "MOUNT C" and the "C:/ path". With %PATH% that's ok. I can now enter all commands at the prompt.
> 
> Under "Edit base configuration file" I did not find in [dos] "keyboardlayout =" and in [config] "country =". Can this be set somewhere else with DOSBox-X-App.app?

Add those lines to the file.

**Comment by hardl1** [comment]
I added the lines and changed some parameters in the config, now everything works as I want.
Thank you for your help and good luck with the project! 
I was able to learn a lot and probably wouldn't have done it on my own.

**Comment by Torinde** [comment]
@emendelson why not integrate those video modes/menu items in DOSbox-X itself?

**Comment by emendelson** [comment]
@Torinde - The video modes that I added are listed here, under "Alternate video modes":

http://www.columbia.edu/~em36/dosboxapp.html

They are (mostly) no longer needed, now that TrueType support makes it possible to have any combination of rows and columns. I created those video modes (and the commands that switch to them) in order to have them available back in the time when DOSBox and DOSBox-X only supported bitmap fonts. Also, I was never able to make them work perfectly: the DOS prompt disappears when you switch to some of them - and you need to type echo or ver or some other command to get the prompt back; I was never able to figure out how to make the screen rewrite automatically in order to avoid this (it seems to need a delay before the rewrite, and I don't know how to do this.

However, if anyone wants it, I'll post my fork on Github and anyone can experiment with it and improve it to the point where it would make sense to post a pull request for it.

As for the system-menu items, they point to my web page and list my custom default keystrokes (I disable most of the standard mapper keys in DOSBox-X because my app is for applications, not games.)

**Comment by emendelson** [comment]
@Torinde - I've posted a fork that contains my custom video modes, but they don't work well enough for me to create a pull request:

https://github.com/emendelson/dosbox-x

**Comment by Torinde** [comment]
I'm also not so experienced to tackle that.

**Comment by emendelson** [comment]
@Torinde - Download the free version of Visual Studio 2022; download my version; in the "vs" folder, double-click on the "sln" file, when it opens in Visual Studio, click Build on the menu, and you'll have a working copy of the program.

**Comment by Torinde** [comment]
Thank you @emendelson . Maybe I actually should, yes :)
