### ISSUE TITLE
Change machine type (vga, tandy, etc) without editing configuration file

### ISSUE THREAD

**Issue by Dwedit** [joncampbell123/dosbox-x#3674]
### Is your feature request related to a problem? Please describe.

While many games will work fine on a VGA machine, other games need to set a different machine type to work correctly.

### What you want

It would be really nice if there was a way to switch the Machine Type (VGA, Tandy, PCJR, etc) without needing to edit a configuration file first.

This would be done with a command on the menu bar, or a command in the shell.  Maybe type "machine tandy" into the Z:\ prompt or something.  We already have something like this for switching to the dynamic core ("core dynamic").

If it's necessary to restart emulation after changing machine type, then Dosbox could restart itself.

In theory, there should already be the command "config -set machine=tandy", but it just displays "This property cannot be changed at runtime".  Maybe add a restart of emulation in order to make it work.

### Describe alternatives you've considered

There is the configuration file editor built in, but it's not very user-friendly.  It requires you to know which specific text to type in for your options.

And when you want to change the setting back, you need to go through the configuration editor again.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
You can start dosbox-x from the cmdline with the machine type using either
```
dosbox-x -machine tandy
```
or
```
dosbox-x -set machine=tandy
```

**Comment by grapeli** [comment]
It also works directly from dosbox-x already running for about 9 months. From version 0.83.20.

>The command "config -set" is now case-insensitive
>for property names. Also, if an option cannot be
>changed at run-time, DOSBox-X will ask whether to
>restart itself to apply the new setting. (Wengier)

Due to this change in the code.
https://github.com/joncampbell123/dosbox-x/commit/380c7cd82fdcec9ce0b7c8956cca7606fdca7c3a

**Comment by BridgeHeadland** [comment]
@Dwedit I think I remember mentioning something about this earlier. I was wondering if someone could add experimental as machine type. As I see it, vesa_nolfb is the best, it is based on VESA 2.0 (latest version of VESA), and is even, in the case of the DOSBoxes, compatible with the earliest monochrome DOS software. VESA in general is perfect for Build games like Duke Nukem 3D (any version for DOS), if you're going to run it in 800x600 for example. The disadvantage of vesa_nolfb is that you cannot run the CGA games in a so-called full color mode - such as the DOS version of Donkey Kong, where the color palette is red, brown, green and black, if played in full color mode, and that the machine type is set to CGA in the DOSBox configuration file, and not higher/better. I have also read something that games like Ducktales: The Quest for Gold run with Tandy 3 Voice sound, if the machine type is only set to Tandy, and nothing else, and that Tandy in the PC-Speaker sector is activated. The point was really that experimental as a machine type should work like vesa_nolfb (or something better), in addition to Tandy sound and full color mode in certain CGA games.

**Comment by BridgeHeadland** [comment]
Come to think of it, adding auto as a machine value is most likely. There are already many auto as values ​​for different section settings in several sections, as I see it. Even though VGA, for example, is backwards compatible with, say, EGA, Tandy, CGA and Monochrome software, it does not necessarily mean that they are perfect in VGA, and therefore VGA is not something to recommend, if one is going to play certain pre-VGA software. If I'm not mistaken, the autos make it so that it jumps to the recommended existing setting value of the specific software. If machine is set to auto, auto will behave like, for example, the monochrome value, if you run a monochrome software in DOSBox-X. When it comes to Build software, like Duke Nukem 3D, I don't think it matters if you use the machine values ​​vesa_nolfb, vesa_oldvbe or vesa_oldvbe10, but then I would personally prefer vesa_nolfb, since it is based on VESA 2.0, which is newest, but that's my opinion. I would also like to think that vesa_nolfb is perfect for the prompt itself in DOSBox-X.

I imagine the following values: auto, auto_composite and auto_composite2, since not everyone likes composites.

**Comment by joncampbell123** [comment]
The machine type affects not only the video emulation but also the memory and BIOS resources allocated. It would be very difficult to change machine type while the virtual machine is running. PCjr and Tandy emulation for example carefully arrange the MCB chain as the real hardware does. Also changing an IBM into a PC-98 while the machine is running is out of the question. :)
