### ISSUE TITLE
Can't run "Reams of Chaos"

### ISSUE THREAD

**Issue by Alevam-Inc** [joncampbell123/dosbox-x#3725]
### Question

How I stop this error from occurring?

![ROC Error](https://user-images.githubusercontent.com/50853470/189418760-52288ef8-2227-43da-b1e5-a6a6e34ab159.png)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Why are you running Win98 in DOSBox-X, to then start a DOS game?

Why don't you just run the DOS game directly from DOSBox-X?

**Comment by rderooy** [comment]
In any case, the error is fairly clear. The Win98 DOS is not setting up the BLASTER environment variable and apparently REALMS OF CHAOS needs to have it set. So before starting the game you need to do a `SET BLASTER=` followed with the right values for your setup.

Normally in DOSBox-X you do not have to worry about setting the BLASTER environment variable as it is set automatically. But because you booted Win98 this is not the case and you need to do it yourself.

**Comment by Alevam-Inc** [comment]
Would I do this in windows or in dosbox?

**Comment by Alevam-Inc** [comment]
I managed to solve it.
