### ISSUE TITLE
Thunder in paradise stopped working after update

### ISSUE THREAD

**Issue by phasermaniac83** [joncampbell123/dosbox-x#3762]
### Question

Thunder in paradise worked for me with dosbox-x 0.82.14, but after update to Dosbox-x 2022.08.0 I get this error:
Expanded Memory (EMS) with a standard page frame was not found.
You may need to run MEMMAKER 

I launch it this way:
mount c "G:\arcade\roms\Microsoft MS-DOS\thunderinparadise"
c:
jemmex.exe frame=e000 load
THUNDER.exe

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
It worked on latest build (Windows x64 SDL1).
Make sure that you properly loaded JEMMEX.
I changed page frame to D000.
You may want to disable built-in XMS and EMS by editing .conf file in order to load JEMMEX.

![thunder](https://user-images.githubusercontent.com/68574602/192186582-6f783979-ac24-4f4f-a9dd-4b465d69968d.png)
![command_001](https://user-images.githubusercontent.com/68574602/192186628-87db9de8-9e5e-4cfd-985c-cc91bc3991c8.png)

**Comment by maron2000** [comment]
@phasermaniac83 
Happy to hear that. I think this thread can be closed.
