### ISSUE TITLE
E_Exit Illegal descriptor type 0 for int 8 comes on Duke Nukem Caribbean

### ISSUE THREAD

**Issue by sriramkukillaya** [joncampbell123/dosbox-x#3779]
### Question

Whenever I play duke3d dc or caribbean on Dosbox X . I am getting this message in the picture . But it never came on Dosbox SVN Daum . Could you please make these changes / improvements if you don't mind please ?

Yours sincerely
Sriram

![20221010_150213](https://user-images.githubusercontent.com/108211135/195131337-9a93bb93-2425-446c-a233-ca9f7e49741d.jpg)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [x] I agree to follow the code of conduct and the contributing guidelines.

**Comment by BridgeHeadland** [comment]
Why create 3 issiues about this?

**Comment by sriramkukillaya** [comment]
I misjudged completely and created 3 issues .

**Comment by maron2000** [comment]
You can close the duplicates so that discussion may not diffuse to multiple (identical) issues.

**Comment by sriramkukillaya** [comment]
Thank you for the clarification.

**Comment by sriramkukillaya** [comment]
May I know the update on the new version please .

**Comment by Allofich** [comment]
Can't confirm this.

There are a lot of Duke Nukem 3d versions and releases out there, so there is first the question of what version the issue happened with and whether the addon was installed correctly.

There is also the question of when and where the problem occurs, although I can assume based on the screenshot it happened during the ending (making this a bit of a pain to test).

I managed to get together an installation of Duke Nukem 3d version 1.5 with the Caribbean addon installed through the official installer from the Caribbean addon CD. I used cheat codes to get through to the ending, but no error happened.

Honestly, based on the way these reports were made I doubt the reporter will be able to give enough information to identify the problem, if there is one, so I would recommend closing this and the duplicate issues. To the reporter, please try reinstalling Duke Nukem 3d and the addon, and/or give more detailed information if you can. It could be reopened if a problem is confirmed with details of how to reproduce it, but I doubt there will be any progress otherwise.

**Comment by sriramkukillaya** [comment]
Thank you . I used duke nukem 3d non atomic version .

**Comment by sriramkukillaya** [comment]
1.3d

**Comment by Allofich** [comment]
The Caribbean addon readme says "Please note that the "Duke Caribbean:  Life's a Beach" add-on is designed and
tested for Duke 3D version 1.3d, 1.4 and 1.5.", so version 1.3d should be OK.

**Comment by sriramkukillaya** [comment]
I used that version . But that error message came .

**Comment by sriramkukillaya** [comment]
I am sending a short video of my wolf3d game on Dosbox 0.63 . If you csn
make the speed of dosbox like this one

https://photos.app.goo.gl/SSSK937Dc5PqcYN28

**Comment by sriramkukillaya** [comment]
https://photos.app.goo.gl/SSSK937Dc5PqcYN28

**Comment by sriramkukillaya** [comment]
Basically please make it run like this

**Comment by Allofich** [comment]
I completed Duke Caribbean again, this time with 1.3d, and still no error.

@sriramkukillaya, your last few comments were probably intended for https://github.com/joncampbell123/dosbox-x/issues/3595.

**Comment by sriramkukillaya** [comment]
On which version of dosbox x please

**Comment by sriramkukillaya** [comment]
Is it my graphics card problem

**Comment by Allofich** [comment]
Now I am getting the error. I'm not sure what's different from when I tested before. I'm using a build from the latest code (https://github.com/joncampbell123/dosbox-x/commit/38082111bc252e0023913bd59cd3058b0f1fd0fc). It also happened with the latest release, VS build win64.

**Comment by Allofich** [comment]
Sometimes it happens, sometimes it doesn't. I was getting a slightly different error: "Illegal descriptor type 1F for int 8", not type 0.

I managed to save a state just before it crashes, this time with "type 0 for int D".

CPU trace just before the crash:

```
0180:00283E14  add  ecx,0008                                          EAX:00000684 EBX:00000006 ECX:002E0B00 EDX:002E0B00 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:00283E17  mov  eax,[002BEE64]             ds:[002BEE64]=00000000 EAX:00000684 EBX:00000006 ECX:002E0B08 EDX:002E0B00 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E1C  xor  edx,edx                                           EAX:00000000 EBX:00000006 ECX:002E0B08 EDX:002E0B00 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E1E  xor  ebx,ebx                                           EAX:00000000 EBX:00000006 ECX:002E0B08 EDX:00000000 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E20  mov  dx,[eax+00000686]          ds:[00000686]=0000     EAX:00000000 EBX:00000000 ECX:002E0B08 EDX:00000000 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E27  mov  bx,[eax+00000688]          ds:[00000688]=FFF4     EAX:00000000 EBX:00000000 ECX:002E0B08 EDX:00000000 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E2E  add  edx,edx                                           EAX:00000000 EBX:0000FFF4 ECX:002E0B08 EDX:00000000 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E30  mov  eax,esi                                           EAX:00000000 EBX:0000FFF4 ECX:002E0B08 EDX:00000000 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E32  add  ebx,edx                                           EAX:0000068A EBX:0000FFF4 ECX:002E0B08 EDX:00000000 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
0180:00283E34  mov  edx,ecx                                           EAX:0000068A EBX:0000FFF4 ECX:002E0B08 EDX:00000000 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:00283E36  call 002AA8A9 ($+26a6e)                                EAX:0000068A EBX:0000FFF4 ECX:002E0B08 EDX:002E0B08 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC27C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8A9  push ecx                                               EAX:0000068A EBX:0000FFF4 ECX:002E0B08 EDX:002E0B08 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC278 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8AA  push esi                                               EAX:0000068A EBX:0000FFF4 ECX:002E0B08 EDX:002E0B08 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC274 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8AB  push edi                                               EAX:0000068A EBX:0000FFF4 ECX:002E0B08 EDX:002E0B08 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC270 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8AC  mov  ecx,ebx                                           EAX:0000068A EBX:0000FFF4 ECX:002E0B08 EDX:002E0B08 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC26C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8AE  mov  esi,edx                                           EAX:0000068A EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:0000068A EDI:000001BF EBP:00000FFA ESP:004CC26C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8B0  mov  edi,eax                                           EAX:0000068A EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:002E0B08 EDI:000001BF EBP:00000FFA ESP:004CC26C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8B2  push es                                                EAX:0000068A EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:002E0B08 EDI:0000068A EBP:00000FFA ESP:004CC26C DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8B3  mov  ax,ds                                             EAX:0000068A EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:002E0B08 EDI:0000068A EBP:00000FFA ESP:004CC268 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8B5  mov  es,ax                                             EAX:00000188 EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:002E0B08 EDI:0000068A EBP:00000FFA ESP:004CC268 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8B7  push edi                                               EAX:00000188 EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:002E0B08 EDI:0000068A EBP:00000FFA ESP:004CC268 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8B8  mov  eax,ecx                                           EAX:00000188 EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:002E0B08 EDI:0000068A EBP:00000FFA ESP:004CC264 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8BA  shr  ecx,02                                            EAX:0000FFF4 EBX:0000FFF4 ECX:0000FFF4 EDX:002E0B08 ESI:002E0B08 EDI:0000068A EBP:00000FFA ESP:004CC264 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:0 IF:1
0180:002AA8BD  repne movsd                                            EAX:0000FFF4 EBX:0000FFF4 ECX:00003FFD EDX:002E0B08 ESI:002E0B08 EDI:0000068A EBP:00000FFA ESP:004CC264 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1
0180:002AA8BD  repne movsd                                            EAX:0000FFF4 EBX:0000FFF4 ECX:00003FF9 EDX:002E0B08 ESI:002E0B18 EDI:0000069A EBP:00000FFA ESP:004CC264 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1
(many repne movsd commands follow. Last one before crash below)
0180:002AA8BD  repne movsd                                            EAX:0000FFF4 EBX:0000FFF4 ECX:00000735 EDX:002E0B08 ESI:002EEE28 EDI:0000E9AA EBP:00000FFA ESP:004CC264 DS:0188 ES:0188 FS:0000 GS:0020 SS:0188 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1
```

Luckily the source code for Duke Nukem 3D was released. It's for version 1.5, but I was able to locate the function where the crash is happening.

At https://github.com/videogamepreservation/dukenukem3d/blob/ef609159bd352985a0c63734a11241d86c873fe5/source/ANIMLIB.C, the crash happens during the second call to `memcpy` in `loadpage`. This call to `memcpy` is done with an EBX (`size` parameter) of FFF4, so that might be the problem. This value was gotten from `curlp.nBytes`, according to the Duke3d source page, and represents "Total number of bytes of contents, excluding header." from a "large page structure". I don't think I can dig much further than this, but maybe this information is enough to help shed some light on what is happening, and if there is something that needs fixing in DOSBox-X or if it is just a bug in the game.

**Comment by sriramkukillaya** [comment]
Oh shit
Sorry to hear this from your side .

**Comment by Allofich** [comment]
I couldn't find any old mentions of cutscenes crashing for Duke Nukem 3D (for the days when it would have been run without using an emulator), but there are some mentions in the Steam forums of the intro to "The Birth" crashing in Duke Nukem 3D: Megaton Edition. It could be a bug in the game, and not a problem in DOSBox-X.

**Comment by sriramkukillaya** [comment]
Try DVN Daum Dosbox please

**Comment by sriramkukillaya** [comment]
SVN Daum

**Comment by joncampbell123** [comment]
Not seeing any issues with Duke Nukem 3D here on Linux even with dynamic core.

However on my ARM based Macbook, dynamic core seems to have problems with Duke 3D that causes it to lock up if you start a game with it, and texture mapping errors if you switch it on after starting a game.

**Comment by Allofich** [comment]
The only place I confirmed the problem was in the ending cinematic of "Duke Caribbean: Life's A Beach]" running off of Duke Nukem 3D version 1.3 (this was to match sriramkukillaya's setup). It's a bit of trouble to get that all set up and make your way to the ending, even using cheats, but I do have saved game right before the ending where the problem will sometimes happen, and a DOSBox-X saved state right before it always happens, if you are interested.

I only tested briefly with the last version of Duke Nukem 3D (1.5) before I reinstalled to test with version 1.3. I then found out, while testing with 1.3, that the problem sometimes occurs and sometimes doesn't. Unfortunately, since I didn't test several times with 1.5 (I think I only tested there once), I don't know whether changing the version of Duke Nukem 3D mattered or not.

As I wrote above, there are mentions on the Steam forums of the intro cinematic to the 4th episode ("The Birth") as crashing, but I haven't tested that and don't know if it's the same problem.

**Comment by Allofich** [comment]
The intro to "The Birth" seems to run fine in DOSBox-X. (running version 1.5)

I next tried copying over just CINEOV3.ANM (Episode 3 ending) from the 1.3 installation with "Duke Caribbean: Life's A Beach" applied to the 1.5 installation (without "Duke Caribbean: Life's A Beach" applied), so that the "Duke Caribbean: Life's A Beach" ending plays when you beat Episode 3 in the original game (easily and quickly done using cheats), but no crash happened despite several tries.

I then tried the 1.3 installation with "Duke Caribbean: Life's A Beach" again, just to be sure, and sure enough the ending there crashed on the first try.

Next I'm going to try the 1.3 installation without "Duke Caribbean: Life's A Beach" installed, and see if the error happens when beating Episode 3 in the base game (I'll try both the original cinematic and the "Duke Caribbean: Life's A Beach" cinematic).

**Comment by Allofich** [comment]
The base game with version 1.3 doesn't crash in the Episode 3 ending, whether using the original ending or replacing it with the one from "Duke Caribbean: Life's A Beach". It seems like it's necessary to have "Duke Caribbean: Life's A Beach" installed (I haven't tested with "Duke It Out In D.C.", which the reporter claimed also crashes). I noticed that the DUKE3D.EXE is modified when "Duke Caribbean: Life's A Beach" is installed, so maybe that has something to do with it. Or maybe there is some issue with the final level of the addon, when transitioning from it to the cinematic.

**Comment by Allofich** [comment]
Alright, I installed "Duke Caribbean: Life's A Beach" onto version 1.5, and the crash occurred. So it doesn't need to be version 1.3 for it to happen.

It seems to not be related to the final level of "Duke Caribbean: Life's A Beach", either ,because it happened now when I completed the final level of Episode 3 from the original game (which will also make the ending of "Duke Caribbean: Life's A Beach" play if it's installed)

I saved a few games during the boss fight but I couldn't seem to get the crash to happen when loading from them, only by starting from a new game (maybe the crash is time sensitive and needs the game to have been running for a bit to happen?). Luckily, using cheats you can get to the ending very quickly.

1. Select "NEW GAME".
2. Select "LIFE'S A BEACH" (probably doesn't matter which you pick).
3. Select default difficulty (probably doesn't matter which you pick).
4. Once the game starts type DNKROZ to activate the invulnerability cheat.
5. Type DNSCOTTY309 to be warped to the final level of Episode 3 from the original game.
6. Type DNSTUFF to get all weapons (so you can easily kill the boss).
7. Kill the boss. I often get the "Illegal descriptor type for 0 for int 8" error from the original post this way. On one playthrough, though, the error wouldn't happen even after defeating the boss multiple times. After restarting DOSBox-X and trying again, though, it did occur.

**Comment by grapeli** [comment]
@Allofich 
You forgot to add the most important piece to this puzzle. The DOSBox-X **vsbuild** (windows) is required. In the dosbox-x mingw versions under windows you will not experience this error.

It's nothing new that windows **vsbuild** dosbox-x offers such surprises. There have been many cases like this one.

**Comment by Allofich** [comment]
@grapeli
The error also happens for me with the mingw build (x64). I just tested using the automatic builds from commit https://github.com/joncampbell123/dosbox-x/commit/1b0e1216abb3fe527fe009956d67098a240df3ac. Both the VS build (x64) and mingw build (x64) had the error.

The error does not always happen. I'm not sure what the difference is between when it happens and doesn't. Right now I had the error happen in both builds by following the steps I listed above, and as soon as the level with the boss began attacking the boss with the RPG weapon, holding down the left CTRL key to continually shoot until it died.

You are correct that I should have tested the mingw build before. Until now I only tested the vsbuild.

I normally use a .conf file with just a few edits from the default, but just to be sure I tried now with completely default settings (except for mount commands), and still, with the mingw build, the error occurred in 1 out of 2 tries.

**Comment by Allofich** [comment]
More info:
Testing with no sound and no music: No error in 3 tries
Testing with Soundblaster sound and no music: No error in 3 tries
Testing with no sound and Soundblaster music: No error in 3 tries
Testing with Soundblaster sound and General Midi music: No error in 3 tries
Testing with Soundblaster sound and Soundblaster music (as I have been using in testing until now): Error in 1 out of 3 tries

Not exactly conclusive (I'm getting tired of testing, so I want to stop for now), but it may be necessary to have Soundblaster selected for sound and music for the error to happen. By the way, my selections in the game's setup utility are:
Sound:
Sound Blaster 16 or AWE32
Address: 0x220
Interrupt: 7 (for use with the default .conf I am testing with now. Normally (and in earlier testing of this issue) I use an interrupt of 5)
8-bit DMA: 1
16-bit DMA: 5
8 Voices
16 Bit mixing
Stereo sound
22 Khz

Music:
Sound Blaster (there are no other options to choose after this)

Sound volume: 220, Music volume: 200

**Comment by grapeli** [comment]
@Allofich 
I tested under linux dosbox-x x86-64 SDL2. **Out of ten starts it always worked fine.**

Then through wine I ran dosbox-x-vsbuild-win64-sdl2. The error occurred the first time.
The next one was the dosbox-x-mingw-win64-sdl2 version and everything is fine under this one.
That's why I jumped to this conclusion quite hastily.

Checking the mingw version again today, it turns out that this error may also occur under it (not always).
Interesting. Why is this error only for Windows versions?

**Comment by Allofich** [comment]
One more thing: all my tests have been with sdl1 builds. But I see from @grapeli's test it can happen with sdl2 as well.

**Comment by Allofich** [comment]
I seem to have further zeroed in on the cause.

I noticed a difference in the ending cinematic when playing it in "Duke Caribbean: Life's A Beach" (where it can crash) and when playing it in the base game (by extracting the animation file CINEOV3.ANM from the "Duke Caribbean: Life's A Beach" file VACATION.GRP and placing it in the Duke Nukem 3D directory. This would not crash.). The difference was that music would play when the cinematic played in "Duke Caribbean: Life's A Beach". I also noticed that when the crash happened, it seemed to coincide with the timing of when this music would normally start.

I checked and found that the animation plays the sound file WIND54.VOC. This is just a quiet wind sound in the base game. "Duke Caribbean: Life's A Beach" has a file with this same file name that contains the music that plays. I extracted this file from VACATION.GRP and placed it in the base game installation, and now it crashes, 3 out of 3 times. (0 out of 3 times without this file)

Combined with what I found about the Soundblaster settings above, I feel pretty confident that the crash happens when the game tries to play this sound file. This also means it isn't necessary to install "Duke Caribbean: Life's A Beach". Just put the two files for that ending cinematic (in the attached .zip) into the Duke Nukem 3D folder, and defeat the episode 3 boss, and the error can occur.

[DNCrash.zip](https://github.com/joncampbell123/dosbox-x/files/10097932/DNCrash.zip)

**Comment by grapeli** [comment]
This error did not appear to me at all in the dosbox-x version under linux due to a slightly different configuration. I tested the windows versions of dosbox-x generally on the default configuration.

This error occurs because `memsize=16` is too small.
It should be increased. How minimal is needed I have not checked. With `memsize=32` it always works fine. Regardless of the version.

I'm sorry about all the confusion.

**Comment by grapeli** [comment]
@Allofich 
I also checked how it works under linux in dosbox-staging and dosbox-SVN.

In both cases, with the default value of `memsize=16`, Duke Caribbean Life's A Beach gives the same error.
dosbox-staging
`ABORT: Illegal descriptor type 0x0 for int 8`

dosbox-SVN
`Exit to error: Illegal descriptor type 0 for int 8`

**Comment by Allofich** [comment]
Confirmed, it works fine with memsize=32. Thanks grapeli, I didn't think to check that setting.
So, in the end, this may just be a problem with the software requiring more than 16 MB of RAM.

Searching online for Duke Nukem 3D system requirements brings up variously 8 MB RAM and 16 MB RAM, but the WIND54.VOC file (3041 KB) of "Duke Caribbean: Life's A Beach" probably pushes the requirement over 16 MB for just the ending cinematic.

I just tried SVN Daum, BTW, which the reporter said did not have this problem, but it crashes there, too. SVN Daum also has a default memsize of 16.

So maybe the issue here is, if possible, to have DOSBox-X detect when emulated memory has run out and give an appropriate error message (maybe even dynamically increase it?) I don't know how difficult that would be, though.

**Comment by grapeli** [comment]
@Allofich 
> I just tried SVN Daum, BTW, which the reporter said did not have this problem, but it crashes there, too. SVN Daum also has a default memsize of 16.
> 

Such information should always be verified. I have already encountered here several times assurances that something works under the old unpatched dosbox-daum. These assurances were almost always inconsistent with reality. Mostly because of the different configuration used.

As for settings other than the default, I would recommend changing `machine=vesa_nolfb`.
[Here](https://github.com/dosbox-staging/dosbox-staging/issues/366#issuecomment-629866230) is a list of games that work better in this configuration.

**Comment by sriramkukillaya** [comment]
Thank you so much . Could you please send me the link for VSBUILD Dosbox X

**Comment by Allofich** [comment]
@sriramkukillaya I think you misunderstand. The fix is to set `memsize=32` in your `dosbox.conf` file.

**Comment by grapeli** [comment]
32 is a value with a large safety margin.
I tested several times with `memsize=17` and it also worked. Although this setting may not work in every configuration.

**Comment by joncampbell123** [comment]
> So maybe the issue here is, if possible, to have DOSBox-X detect when emulated memory has run out and give an appropriate error message (maybe even dynamically increase it?) I don't know how difficult that would be, though.

32-bit DOS programs often allocate a large chunk of extended memory and then maintain their own malloc() allocator within it. How exactly would DOSBox-X "know" if their custom allocator ran out of memory, hm?

Even in 16-bit real mode, Open Watcom's malloc() uses it's own heap allocator within a one large block of conventional memory, as most compilers do. With some C compilers, exec() won't even work unless you make a special C library call that shrinks the DOS memory block down to only what you've allocated in order to make room for the program you're trying to run. Remember that in real mode, COM and EXE files by default are given the rest of conventional memory on load, although I think DOS will respect the "max paragraphs" field of the EXE header in that regard however.

**Comment by joncampbell123** [comment]
It sounds like the issue is not DOSBox-X but the game running out of memory, and therefore the issue should be closed, correct?

**Comment by rderooy** [comment]
Yes you are right in my opinion. The only thing I don't like is that DOSBox-X force closes, or closes with an error that will mean nothing to the user.

**Comment by Allofich** [comment]
> How exactly would DOSBox-X "know" if their custom allocator ran out of memory, hm?

I was just floating it out there in case it is possible somehow.

> The only thing I don't like is that DOSBox-X force closes, or closes with an error that will mean nothing to the user.

Yes, that was my thinking as well.

**Comment by joncampbell123** [comment]
That would be some fault that causes the emulator to call E_Exit(), which DOSBox-X, if run without a console, displays as a message box before closing.

Which is better than the DOSBox SVN approach of printing the E_Exit() message to a possibly invisible console and exiting suddenly, at least.

Normally E_Exit() is called when an error happens that the emulator cannot recover from.

**Comment by Allofich** [comment]
Well, I'm getting away from this issue specifically now, so I think I'll make use of the new discussions tab and put my comment above there. @joncampbell123, I'm fine with you closing this issue.

**Comment by sriramkukillaya** [comment]
[sdl]
# fullscreen -- Start dosbox directly in fullscreen.
# fulldouble -- Use double buffering in fullscreen.
# fullfixed -- Don't resize the screen when in fullscreen.
# fullresolution -- What resolution to use for fullscreen, use together
with fullfixed.
# output -- What to use for output: surface,overlay,opengl,openglnb,ddraw.
# hwscale -- Extra scaling of window if the output device supports hardware
scaling.
# autolock -- Mouse will automatically lock, if you click on the screen.
# sensitiviy -- Mouse sensitivity.
# waitonerror -- Wait before closing the console if dosbox has an error.
# priority -- Priority levels for dosbox: lower,normal,higher,highest.
#             Second entry behind the comma is for when dosbox is not
focused/minimized.
# mapperfile -- File used to load/save the key/event mappings from.

fullscreen=false
fulldouble=false
fullfixed=false
fullresolution=1024x768
output=surface
hwscale=1.00
autolock=true
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper.txt

[dosbox]
# language -- Select another language file.
# memsize -- Amount of memory dosbox has in megabytes.
# machine -- The type of machine tries to emulate:hercules,cga,tandy,vga.
# captures -- Directory where things like wave,midi,screenshot get captured.

language=
machine=vga
captures=capture
memsize=16

[render]
# frameskip -- How many frames dosbox skips before drawing one.
# aspect -- Do aspect correction.
# scaler -- Scaler used to enlarge/enhance low resolution modes.
#           Supported are
none,normal2x,advmame2x,advmame3x,advinterp2x,interp2x,tv2x.

frameskip=0
aspect=false
scaler=normal2x

[cpu]
# core -- CPU Core used in emulation: simple,normal,full,dynamic.
# cycles -- Amount of instructions dosbox tries to emulate each millisecond.
#           Setting this higher than your machine can handle is bad!
# cycleup   -- Amount of cycles to increase/decrease with keycombo.
# cycledown    Setting it lower than 100 will be a percentage.

core=normal
cycles=3000
cycleup=500
cycledown=20

[mixer]
# nosound -- Enable silent mode, sound is still emulated though.
# rate -- Mixer sample rate, setting any devices higher than this will
#         probably lower their sound quality.
# blocksize -- Mixer block size, larger blocks might help sound stuttering
#              but sound will also be more lagged.
# prebuffer -- How many milliseconds of data to keep on top of the
blocksize.

nosound=false
rate=22050
blocksize=2048
prebuffer=10

[midi]
# mpu401      -- Enable MPU-401 Emulation.
# intelligent -- Operate in Intelligent mode.
# device      -- Device that will receive the MIDI data from MPU-401.
#                This can be default,alsa,oss,win32,coreaudio,none.
# config      -- Special configuration options for the device.

mpu401=true
intelligent=true
device=default
config=

[sblaster]
# type -- Type of sblaster to emulate:none,sb1,sb2,sbpro1,sbpro2,sb16.
# base,irq,dma,hdma -- The IO/IRQ/DMA/High DMA address of the soundblaster.
# mixer -- Allow the soundblaster mixer to modify the dosbox mixer.
# oplmode -- Type of OPL emulation: auto,cms,opl2,dualopl2,opl3.
#            On auto the mode is determined by sblaster type.
# oplrate -- Sample rate of OPL music emulation.

type=sb16
base=220
irq=7
dma=1
hdma=5
mixer=true
oplmode=auto
oplrate=22050

[gus]
# gus -- Enable the Gravis Ultrasound emulation.
# base,irq1,irq2,dma1,dma2 -- The IO/IRQ/DMA addresses of the
#            Gravis Ultrasound. (Same IRQ's and DMA's are OK.)
# rate -- Sample rate of Ultrasound emulation.
# ultradir -- Path to Ultrasound directory.  In this directory
#             there should be a MIDI directory that contains
#             the patch files for GUS playback.  Patch sets used
#             with Timidity should work fine.

gus=true
rate=22050
base=240
irq1=5
irq2=5
dma1=3
dma2=3
ultradir=C:\ULTRASND

[speaker]
# pcspeaker -- Enable PC-Speaker emulation.
# pcrate -- Sample rate of the PC-Speaker sound generation.
# tandyrate -- Sample rate of the Tandy 3-Voice generation.
#              Tandysound emulation is present if machine is set to tandy.
# disney -- Enable Disney Sound Source emulation.

pcspeaker=true
pcrate=22050
tandyrate=22050
disney=true

[bios]
# Nothing to setup yet!


[dos]
# xms -- Enable XMS support.
# ems -- Enable EMS support.

xms=true
ems=true

[modem]
# modem -- Enable virtual modem emulation.
# comport -- COM Port modem is connected to.
# listenport -- TCP Port the modem listens on for incoming connections.

modem=false
comport=2
listenport=23

[directserial]
# directserial -- Enable serial passthrough support.
# comport -- COM Port inside DOSBox.
# realport -- COM Port on the Host.
# defaultbps -- Default BPS.
# parity -- Parity of the packets. This can be N, E or O.
# bytesize -- Size of each packet. This can be 5 or 8.
# stopbit -- The number of stopbits. This can be 1 or 2.

directserial=false
comport=1
realport=COM1
defaultbps=1200
parity=N
bytesize=8
stopbit=1

[ipx]
# ipx -- Enable ipx over UDP/IP emulation.

ipx=false

[autoexec]
# Lines in this section will be run at startup.


 Dosbox0.63 conifguration

**Comment by sriramkukillaya** [comment]
Sorry to complain
the Dosbox download file is missing in your website . Please reupload it .

Sriram
