### ISSUE TITLE
SDL 1.x/2.x touchscreen: Add code to assist double-tap as double-click to guest

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#380]
As handy as it is to use Windows 3.1 with a touchscreen, double-clicking on things is *very* difficult. It requires tapping the finger faster than what is comfortable to do with the human hand.

A good enhancement (for both SDL 1.x and SDL 2.x on all platforms) would be to have a configurable "double-click" time period. If two taps occur in the same place on the screen within that time period, then mouse emulation should generate two rapid mouse button press/release events to the guest to trigger double-click in the guest.

**Comment by sikthehedgehog** [comment]
Windows had a double click time setting since… 1.0 pretty much. Doesn't sound like worth the hassle if it's just for that. Also just checked how much Windows 3.11 waits if you move the slider to slowest and it's indeed a lot (certainly way more than you need to double tap).

I can see this feature becoming quite problematic to implement actually: you need to add a delay to all touches or you risk sending three clicks in a row (the click from the first tap, then the double click from the second tap). But then now you added lag to individual clicks, which is annoying for UI and would render many games practically unplayable.

Only way you could get this to work is if it was implemented as its own gesture rather than trying to correct a double tap. Not sure what it could be though.

**Comment by joncampbell123** [comment]
Good point.
