### ISSUE TITLE
Strange behavior of Pinball Mania

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3805]
### Describe the bug

First I want to say that the content from what I have downloaded from archive.org - I have transferred over to a mounted folder, which should represent a CD drive with a CD with those files, since I see what I have downloaded as something originating from a floppy disk. I believe that anything that only exists on floppy disk will be better on CD anyway.
Nevertheless, I find that it is difficult to predict whether the game will start or not, sometimes the exe file works, other times the bat file. still other times none of the parts work. Sometimes it works from the virtual CD driver, other times from the C drive, and still other times neither. Could there be something I'm doing wrong, or is the fault in the DOSBox?

### Steps to reproduce the behaviour

Have the contents of what was downloaded from archive.org in a mounted folder that acts as a virtual CD drive, have the folder with the game in the virtual C drive, now you can try while also starting the DOSBox in spaces, and judge for yourself.

### Expected behavior

That Pinball Mania should be run without problems.

### What operating system(s) this bug have occurred on?

Windows 10 Home, 21H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X, 64-bit Visual Studio buildd, win64, 20221031163862

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by NebularNerd** [comment]
I'm not sure what copy of Pinball Mania you are using but I had no issues running Pinball Fantasies Deluxe which includes Pinball Mania https://github.com/joncampbell123/dosbox-x/issues/2377#issuecomment-1273670576 

With this version as long as your CD image (a bin/cue in my case) is mounted then all should be well.

There are aspect ratio issues discussed #3546 but the game itself does run.

**Comment by BridgeHeadland** [comment]
@NebularNerd I'm using the game that contains only Pinball Mania.

**Comment by NebularNerd** [comment]
> @NebularNerd I'm using the game that contains only Pinball Mania.

Link?

**Comment by BridgeHeadland** [comment]
@NebularNerd I can’t find the archive.org link anymore, but I found a another download link with this game.

**Comment by NebularNerd** [comment]
The wowroms copy is pulled from the Pinball Power Pack/Pinball Gold Pack (The file `21STINFO.DAT` contains the string 'Pinball Power Pack. (c) 21st Century Entertainment. Ltd. 1996') and is an incomplete/hacked copy. 

It will run as long as the `21STCENT` folder is at the root of your C: drive, this is where the Pinball Fantasies Deluxe installer insists on putting the directory so Power/Gold must use the same installer. 

When running either `pinball.bat` or `pm.com` it will briefly flash up 'SYNTAX ERROR' a couple of times between the various stages of loading, this is where it's looking for a CD drive.

Mounting any CD image to D: cures the 'SYNTAX ERROR', this is a bit like a very old dodgy copy of Worms I have on floppy from back in the day, it too just needed to see there was a CD drive in order to run.

My best advice is to avoid the hooky version and grab Pinball Fantasies Deluxe which is on archive in it's complete and unmolested form. This too needs the CD mounted before play.

**Comment by BridgeHeadland** [comment]
Is there a complete full version of Pinball Mania anywhere, as a Stand-alone game, or has it only existed as part of Pinball Fantasies Deluxe and Pinball Power Pack/Pinball Gold Pack? I can't say I can find a complete Stand-alone version of it anywhere on the web.

**Comment by NebularNerd** [comment]
It was a seperate release on both the Amiga and PC [Mobygames info page](https://www.mobygames.com/game/dos/pinball-mania). Pretty much anywhere you'll easily find a copy it's going to be the same as the extracted wowroms version.

While I can't speak for the copy you originally sourced, there are a few options available to you:
- Use the wowrom copy you have, make sure it's set up as I described and it will play fine
- Use the Pinball Fantasies Deluxe version
- Find the full iso, it's out there with both the Win and Dos version on, I not posting it here as all the games are still sold on GOG so it's a bit of a grey area. Giving it a once over shows there is nothing really special over the copies you have aside from the Win 3.1 version, again when installed correctly it works just fine.

Can we close this thread to help keep the issue board tidy.
