### ISSUE TITLE
How to get pixels in RGBA, not in BGRA?

### ISSUE THREAD

**Issue by Miska711** [joncampbell123/dosbox-x#3840]
### Question

Hi, 

I use dosbox-x with opengl surface. Everything works fine. For a curiosity I compiled it and I try to output it to opengl es 2.0, but on my old raspberry is not extension for texture BGRA format (I have available RGBA8 for internal format and RGBA for format as parameters to glTexImage2D). So I swap R with B in shader. Not big deal, but better would be to have "pixels" in RGB order directly.  

I tried to hack GFX_LogSDLState with values below and it works, but not always. If I start win95 then drawn pixels are in RGBA to the point when I get to win95 desktop. There are again in BGRA. Can someone help me?

GFX_bpp = 32;
GFX_Rshift = 0;
GFX_Gshift = 8;
GFX_Bshift = 16;
GFX_Rmask = 00;
GFX_Gmask = 0;
GFX_Bmask = 0;

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by aybe** [comment]
Your first solution is the best, you've been able to fix the error externally without messing with the sources, I would stick to that.

**Comment by Miska711** [comment]
Thank you for fast response. I though there some kind of "flag" which can easily change the order. It inrested me why is used BGR format instead RGB, which looks to me more "intuitive", probably BGR is faster.

**Comment by aybe** [comment]
If I look at the snippet you've posted, to me it uses RGB since R is not shifted.

We write _RGB_ but when seen as bits it's _XXXXXXXX BBBBBBBB GGGGGGGG RRRRRRRR_ so R is first.

As on what to change, I'd look for [pixel format](https://github.com/joncampbell123/dosbox-x/search?q=pixel+format).

Keep in mind that this change should be applied everywhere, and that's another story.

Hence why I suggested if it works from shader then stick to it as it's simpler, after all, it's compiled and certainly optimized.

**Comment by Miska711** [comment]
Thank you very much. I will stay with shader solution, as you mentioned. For a fun I will look at pixelformat, digging into this brings me fun.

Thank you and have a nice day:)

**Comment by aybe** [comment]
You welcome, you too 😁
