### ISSUE TITLE
Windows: Remove overlay output (alias to OpenGL when task is complete)

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#398]

**Comment by joncampbell123** [comment]
Overlay output isn't really doing overlay output for the same reason OpenGL output wasn't signalling the ability to scale: "RGB only" flag.

However, the Overlay output involves YUV overlay buffers and the YUV colorspace.

![image](https://user-images.githubusercontent.com/6245486/34314453-c1824028-e728-11e7-8424-57c73858f7da.png)

Overlay output. What's the point?

**Comment by joncampbell123** [comment]
Anyone else here is free to defend the overlay output and explain why I should keep it. Otherwise, I will remove it.

**Comment by sikthehedgehog** [comment]
Was probably added "just because"? Can't think any reason of why it'd be even added to an emulator.

For the record, SDL2 still keeps YUV support mainly because there are programs that use it to simplify video playback by letting SDL do the conversion to RGB (it was considered for removal at some point, then some developers from outside the mailing list chimed in about that). But that's definitely not relevant to DOSBox-X so I would never bother implementing it in that version either.

**Comment by joncampbell123** [comment]
Done
