### ISSUE TITLE
Broken DOS games list December 2017

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#399]
# PASS
crystal caves 1 (1991) (apogee software ltd) [PASS]
crystal caves 2 (1991) (apogee software ltd) [PASS]
crystal caves 3 (1991) (apogee software ltd) [PASS]
god of thunder (1993) (software creations ltd) [PASS]
jazz jackrabbit cd (1994) (epic megagames, inc.) 2.0 full [PASS]
jazz jackrabbit special xmas edition (1994) (epic megagames, inc.) 2.0 full [PASS]
jurassic park (1993) (ocean) (rev) [PASS]
pinball dreams 2 (1995) (21st century entertainment) [PASS]
pushover (1992) (ocean) [PASS]
sleepwalker (1993) (ocean) [PASS]
the blues brothers jukebox adventures (1993) (titus interactive) [PASS] Only once did the music play erratically, will investigate later
the humans (1992) (gametek) [PASS]
the humans 2 the jurassic levels (1994) (gametek) [PASS]
the humans 3 evolution lost in time (1994) (gametek) [PASS]
night shift (1990) (lucas arts)	[PASS]
the lost vikings (1993) (interplay entertainment corp.) [PASS]
pinball dreams (1993) (21st century entertainment) [PASS] Sound Blaster MUST use IRQ=7
lollypop (1994) (softgold) [PASS]
psycho pinball (1995) (codemasters) [PASS] (found working copy)

# FAIL
none

# PENDING
none

**Comment by sikthehedgehog** [comment]
Can't test since I have trouble building (I need to check to see if the SDL2 version already works).

That said, does Tetris Deluxe (and its readme viewer) work? Both the game and its readme rely on advanced usage of text mode which tends to break things (the game uses a custom font and tries to set a 8×14 size so it works on both EGA and VGA, the readme uses split-screen and pixel-level scrolling and also resizes the cursor to do its scrollbar).

**Comment by joncampbell123** [comment]
I assume if DOSBox-X can handle a lot of the splitscreen/panning tricks in almost anything from the early Demoscene... it should be able to work.

**Comment by joncampbell123** [comment]
No problems with Tetris Deluxe that I can see.

**Comment by joncampbell123** [comment]
@sikthehedgehog To compile with SDL2 use --enable-sdl2 and check config.log to make sure it detects that SDL2 headers and libraries are available.
