### ISSUE TITLE
question about SVGA emulation in DOS

### ISSUE THREAD

**Issue by ssybesma** [joncampbell123/dosbox-x#4039]
### Question

I hope this is not off-base since it's not DOSBox or DOSBox-X related.

I tinker with Virtualbox VMs and their only support is for VBoxVGA, yet there is an app called SciTech Display Doctor which allows (for instance) Windows 98SE to display resolutions higher than what VBoxVGA allows.

So I'm guessing support for SVGA can be added the same way for DOS but I just wouldn't know if something exists that is out there.

There is a DOS version of SDD but it expects a SVGA chipset to be present already...so it's curious how the Windows version of that works when it's also not seeing a SVGA chipset (provided by Virtualbox).

My best guess is the 'Nucleus' virtual SVGA driver that's part of the Windows version of SDD is what makes that work...but I don't see a DOS version of that same 'Nucleus' virtual SVGA driver.

Your thoughts?

Steve

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
I have not used SDD for something like 25 years, and even than it was on OS/2.

One way to have unusual or higher display resolutions, such as wide-screen, with for instance Win9x running in DOSBox-X is to use special VESA BIOS Extension (VBE) modes, as documented on the DOSBox-X wiki on installing Win9x.

**Comment by ssybesma** [comment]
Thanks for your fast reply. I was trying to figure out how to do that on a DOS VM so I apologize for the inappropriate question. I have my fingers in all sorts of stuff, haha! I'm happy to support you on Patreon and will continue.

**Comment by joncampbell123** [comment]
The driver is possibly using what is known as the Bochs VBE extensions, which (obviously) originated with the Bochs emulator. When enabled, it's a set of I/O ports that can be used to directly program SVGA modes by writing a width, height, bit depth, and other parameters rather than trying to program through a simulated SVGA chipset. Some time in the late 2000s I wrote an experimental Linux fbdev driver that is able to use that to give Linux and fbset direct control over the emulator window.

VirtualBox, at least initially, also implemented this interface (it's still there as the VBoxVGA driver I believe). So anything written for Bochs VBE extensions also worked with VirtualBox. But VirtualBox *also* extends this interface to allow a more asynchronous command and response "OMAPI" protocol which then allow memory mapped packet transfers, video acceleration and multi-monitor emulation.

When you use the VirtualBox "Guest Additions" with Windows XP and higher, the drivers are using that interface to let Windows set arbitrary modes and multiple monitors and even receive events like emulator window resize. The only emulator trick not using this interface that I'm aware of is the host to guest pointer integration which I think is just emulating a USB tablet to transmit absolute coordinates.

**Comment by joncampbell123** [comment]
As for DOS and Windows 9x, the drivers are likely talking to the S3 chipset emulation of the emulator (assuming you use machine=svga_s3) and the guest thinks it's talking an actual S3-based SVGA card. Exceptions to that rule include the use of the VBEMP open source driver which then sets modes entirely using the INT 10h VESA BIOS extensions.
