### ISSUE TITLE
When/If Dolby Digital is added

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#4124]
### Question

When/If Dolby Digital is added to DOSBox-X, will it also support Dolby Pro Logic (II), DTS and the like?

Not too long ago, I installed Windows ME in DOSBox-X, with 16 GB, without problems. For that I realized that WME actually supports Dolby Digital 5.1 (in addition to other audio formats). I'm just saying it so I can confirm it. Those who have managed to install Windows XP in DOSBox-X know whether it supports Dolby Digital 7.1 or not. I don't know more than that there is a driver, which adds DD7.1 sound, just so it is said.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Are you asking if DOSBox-X is to support streaming AC-3 aka Dobly Digital, like a SPDIF connection on a sound card?

The only sound card emulation at this time is at most a Sound Blaster 16 PnP, which can only go up to stereo and cannot carry audio bitstreams.

There is interest, perhaps for Windows ME and XP, for AC'97 sound card emulation, and perhaps that would allow it someday, but what is more likely and just as useful for you when AC'97 emulation does appear is that it might enable emulating 6-channel (5.1 surround) PCM audio output from the card. SDL and SDL2 so far from my tests will happily allow code to request 6 channels (it doesn't mean the channels will actually be sent to your card of course). Perhaps it would be best for Windows ME/XP to decode AC-3 in software and send it as PCM to the sound card.

When that happens the audio mixer in DOSBox-X will require a fair bit of rewriting because everything so far is hardcoded for stereo output in a design inherited from DOSBox SVN and other forks.
