### ISSUE TITLE
Windows ME with VESA 2.0

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#4173]
### Question

Is there any way I can get Windows ME to handle VESA 2.0 (vefa_nolfb) in DOSBox-X?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Please see the wiki on both video adapter emulation and WinME.

vesa_lfb is just S3 Trio64 but with a linear framebuffer for the VESA modes.

**Comment by joncampbell123** [comment]
It's best to use machine=svga_s3 or S3 related machine types with Windows ME, which also provide a linear framebuffer.
If you're using VBEMP with Windows ME you should not use machine=vbe_nolfb because that machine type presents a VBE 1.2 compatible interface that does not provide a linear framebuffer. Linear framebuffers were not part of the standard until VBE 2.0. Most code past the 1990s, including VBEMP and Linux, don't even bother to try the non-linear (bank switching) video modes.
