### ISSUE TITLE
Pacific C 7.51 IDE has very laggy keyboard input

### ISSUE THREAD

**Issue by oboroc** [joncampbell123/dosbox-x#4211]
### Describe the bug

Pacific C 7.51 is freeware compiler: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/devel/c/pacific/freeware/
At some point it was used by FreeDOS project. All command-line tools work great in DosBox-X, but IDE (PPD.EXE), has very laggy keyboard input. In vanilla DosBox, there is no lag.

### Steps to reproduce the behaviour

1. Download and install Pacific C 7.51 from https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/devel/c/pacific/freeware/ in DosBox-X.
2. Go to bin directory and start PPD.EXE (Pacific C IDE)
3. Type in something

### Expected behavior

There should be no keyboard lag

### What operating system(s) this bug have occurred on?

Windows 10 Pro 22H2

### What version(s) of DOSBox-X have this bug?

dosbox-x-win64-2023.03.31 SDL1 VS

### Used configuration

```ini
default config, didn't muck with it
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
I confirm something is wrong.
Except that it must be regression, because, for example, under version 0.83.13 it worked very well. You would need to check when there was a change in operation. Even checking the [main release](https://github.com/joncampbell123/dosbox-x/releases). Best to do `git bisect`. I don't really have time for that right now. Maybe in a while.

**Comment by joncampbell123** [comment]
I noticed I can fix the pausing by going to the code that sets up INT 28h (idle interrupt) and patching out the HLT instruction with NOP. Hm..

**Comment by joncampbell123** [comment]
According to RBIL INT 28h by default does only a IRET in pure DOS mode.

I *think* I understand why someone would submit a patch to STI+HLT within INT 28h because doing that keeps CPU load way down when DOSBox-X is idle at the command prompt or waiting from input.

Now, if the program called INT 28h once and then checked keyboard input, STI+HLT would absolutely work that way, but it appears to call INT 28h multiple times before calling keyboard input, so you have to press several keys to break it out of the HLT to process keyboard input *or* it has to wait until several IRQ 0 timer interrupts to occur. At 18.2 ticks per second, that seems to mean the program pauses for about 1/3 a second before acting on input.

The fix is that perhaps the STI+HLT should be executed only once every, say, 1/4th of a second, so that constantly calling INT 28h doesn't cause this.

**Comment by joncampbell123** [comment]
Please try the latest commit to master. It limits INT 28h's STI+HLT to once per call following keyboard input DOS or BIOS calls which appears to resolve PPD.EXE issues, while at the same time, keeping CPU load down when the program is waiting for keyboard input or the DOS command prompt is idle.

**Comment by grapeli** [comment]
I confirm. With the latest fixes, it works fine.
