### ISSUE TITLE
Are INT 13h AH=42h, 43h supported or not?

### ISSUE THREAD

**Issue by maxpat78** [joncampbell123/dosbox-x#4215]
### Question

I can't understand if I'm wrong with the following C code

[RDWRRAW.TXT](https://github.com/joncampbell123/dosbox-x/files/11361975/RDWRRAW.TXT)

or INT 13h, functions AH=42h and AH=43h are not supported by current DOSBox-X version?

In fact, function AH=41h reports that extended drive functions are present, but attempting to read a single disk sector fails with a `INT13: 64-bit sector addressing not supported` error.

This seems strange to me, since only the sector lower DWORD is filled in the DAP, so it is in fact a simple 32-bit disk access, not 64 nor 48 bit!

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Make sure the upper 32 bits of the 64-bit value are zero.

At the same time, for INT 13h to E_Exit abort the entire emulator just because the upper 32 bits are nonzero is brutally stupid and asinine, and I will fix that now.

https://github.com/joncampbell123/dosbox-x/blob/master/src/ints/bios_disk.cpp#L1780

**Comment by maxpat78** [comment]
Thank you, there was an error about SEG:OFFSET matter. I've fixed my code and perhaps found the problem with VHD driver.
