### ISSUE TITLE
Dosbox-x 2023-05-01 crashes when trying to start Blocek editor

### ISSUE THREAD

**Issue by fritzmueller** [joncampbell123/dosbox-x#4385]
### Describe the bug

Dosbox-x 2023-05-01 crashes when I try to start Blocek for DOS, see: http://laaca.borec.cz/blocek/ .
It starts counting:
START 1/3
START 2/3
then dosbox-x crashes.
Dosbox requires CWSDPMI.

The bug seems to be in Windows version 2023-05-01. The programmer sent me and older version of dosbox (2022-09-0)
I simply replace the older dosbox-x.exe file by the newer one, and everything worked as it should.

The crash of dosbox-x also happened in Linux Mint, but there no START 1/3 and START 2/3 is shown.
I could not try to reproduce it as I have no older version under Linux.

### Steps to reproduce the behaviour

1. Install dosbox-x in Windows.
2. Create a folder "c:\dosfiles"
3. download Blocek and copy the files to "c:\dosfiles"
4. goto main - configuration - "autoexec.bat" 
5. enter. "keyb gr" (should not be necessary)
6. enter "mount c c:\dosfiles" (Backslash is not supported - another bug)
7. enter "c:" (maybe longer path)
8. Save and reboot dosbox-x
9. dosbox-x should start with C:\
10. enter "blocek"
11. START 1/3, START 2/3 appears, then dosbox-x should crash.
12. replace dosbox-x.exe by an older one (nothing else)
13. Blocek should work.

### Expected behavior

see above.

### What operating system(s) this bug have occurred on?

Windows 11

### What version(s) of DOSBox-X have this bug?

2023-05-01, Visual Studio commit

### Used configuration

```ini
dosbox-x.conf
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
It seems to work up to 2022.12.26 release.
If you boot a PC-DOS, it works on 2023.05.01 release as well. (Just a workaround)

**Comment by Laaca** [comment]
It could be a bug how DosBox-X does the CPU protected mode exception catching.
(setting what processor does if some unsupported or disabled instruction is called).

Blocek contains this code and I believe that problem is triggered somewhere there (EXCPTEST.PAS).

=================================================
implementation
uses dpmiexcp;

Function SignalHandler(i:longint):longint;cdecl;
var pexp:PException_State;
    jmp_rec:dpmi_jmp_buf;
    eip:longint;
begin
pexp:=djgpp_exception_state;
eip:=pexp^.__eip;
if {eip=$310f} 1=1 then
   begin
   signal_handler_was_excp:=true;
   Move(pexp^,jmp_rec,sizeof(dpmi_jmp_buf));
   jmp_rec.eip:=pexp^.__eip+2;
   jmp_rec.edx:=0;
   dpmi_LongJmp(jmp_rec,0);
   end;
end;


Procedure Install_Signal_handler(i:longint);
begin
Signal(i,@SignalHandler);
signal_handler_was_excp:=false;
end;


Procedure UnInstall_Signal_handler(i:longint);
begin
Signal(i,@SIG_DFL)
end;

**Comment by grapeli** [comment]
Blocek stopped starting right after this code change 79cca9d.

The title of the bug report is incorrect. DOSBox-X does not crash when I try to launch the Blocek.

**Comment by maron2000** [comment]
The following patch seems to work. Either the `attr` value or the conditional branch is wrong. 
@Allofich Do you have any comments on this?

```dos_files.cpp
diff --git a/src/dos/dos_files.cpp b/src/dos/dos_files.cpp
index b8327a132..d7f9bc14f 100644
--- a/src/dos/dos_files.cpp
+++ b/src/dos/dos_files.cpp
@@ -575,7 +575,8 @@ bool DOS_FindFirst(const char * search,uint16_t attr,bool fcb_findfirst) {
 	if (!DOS_MakeName(search,fullsearch,&drive,attr & DOS_ATTR_VOLUME)) return false;
 	//Check for devices. FindDevice checks for leading subdir as well
     bool device = false;
-    if (attr & DOS_ATTR_DEVICE)
+    LOG_MSG("dos_files: attr=%x, attr & DOS_ATTR_DEVICE = %x, attr & DOS_ATTR_VOLUME = %x", attr, attr & DOS_ATTR_DEVICE, attr & DOS_ATTR_VOLUME);
+    //if (attr & DOS_ATTR_DEVICE)
         device = DOS_FindDevice(search) != DOS_DEVICES;
```

**Comment by Laaca** [comment]
I do not fully understand your code. However I can confirm that my impression, that the error is due to wrong CPU exception handling was wrong.
The true is that the crash occurs somewhere between the font loader and the font cache. So change in the "dos_files.cpp" seems to be logical.

**Comment by Allofich** [comment]
@maron2000, https://github.com/joncampbell123/dosbox-x/commit/79cca9dcd82984a3587e7cdd9abee267a7c958f4 was primarily for fixing handling of the "volume" attribute, in order to fix some installer programs that used it. The change for the "device" attribute was, I think, not essential to that fix, just a minor change for consistency to what I thought would be proper behavior. If reverting that change fixes the problem, I don't mind it being changed. If the actual problem is elsewhere, though, fixing that would of course be better.

**Comment by maron2000** [comment]
@Allofich Thank you for your comment. So I put a PR to delete the conditional branch.
