### ISSUE TITLE
Dosbox-x run error under windows 7

### ISSUE THREAD

**Issue by Nikos1974** [joncampbell123/dosbox-x#452]
Dosbox-X is not running under windows XP only under windows 7.
dosbox-x-windows-20171222-2215 can be used under windows XP.

Pls fix that so we can test again.I dont want windows 7 in my PC.

**Comment by joncampbell123** [comment]
Windows XP is officially not supported (see #403) because the Windows dev tools available to me don't properly support XP even if they claim to support it.

However @aybe has indicated that his copy of VS2013 is able to compile this project and produce working binaries for Windows XP.

**Comment by joncampbell123** [comment]
I also want to point out that the versions of DOSBox-X that seem to run under Windows XP don't work properly because a key C runtime function stat() is broken in a way that prevents it from working under Windows XP. Even if you can run the program, you'll find that the broken stat() function prevents you from mounting any images or folders in the DOS environment.

**Comment by joncampbell123** [comment]
I would be more than happy to support Windows XP if the dev tools didn't cause breakage like that.
