### ISSUE TITLE
when will be a new release?

### ISSUE THREAD

**Issue by gfernval** [joncampbell123/dosbox-x#4744]
### Question

When will be a new release? (windows, linux, hx-dos) I know that there are specific build devs but are not for all platforms. Some time ago used to be a new release every month

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by BridgeHeadland** [comment]
There is probably a lot that needs to be done before the next public launch. I don't know what's being worked on these days, other than what's new in dev builds and nightly builds, and now it's been almost a week since the last dev build. It's been at least 2 days since the last nightly build, so the next one probably won't be many days.
