### ISSUE TITLE
Wing Commander 2 No Speech With Loadfix

### ISSUE THREAD

**Issue by brakenwagen** [joncampbell123/dosbox-x#4746]
### Describe the bug

Wing Commander 2 requires loadfix -32 to prevent a crash however on dosbox-x using loadfix -32 causes the speech pack to not work. This does not happen in regular dosbox you can use loadfx -32 and still have speech.

### Steps to reproduce the behaviour

run Wing Commander 2 with loadfix -32

### Expected behavior

for speech to play

### What operating system(s) this bug have occurred on?

Win 10

### What version(s) of DOSBox-X have this bug?

dosbox-x-mingw-win32-20231007055223 SDL2

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Not saying this will fix your issue, but with DOSBox-X, try to use `loadfix -a` instead of `loadfix -32`.

You want to reserve (block) the bottom 64KB of RAM, and with the `-32` option you don't really know if that covers enough, or perhaps too much as you just block the "next 32KB", while the DOSBox-X `-a` option will block the bottom 64KB regardless of how much is actually used, and not more.

How much of the bottom 64KB is used by default depends on many factors, so having `loadfix` figure it out itself is just easier.

**Comment by brakenwagen** [comment]
tried loadfix -a still no speech

**Comment by maron2000** [comment]
I can hear the speeches. 10.06 release VS and MinGW.
Skip to 2:00 of the following video.
Actually I only needed to launch WC2.exe without loadfix or other tweaks.

https://github.com/joncampbell123/dosbox-x/assets/68574602/0d44bc84-d17e-4155-ab03-51c11b005f74

**Comment by joncampbell123** [comment]
Same here. Speech works. GOG.COM purchase.
