### ISSUE TITLE
Support 256 color text mode hack

### ISSUE THREAD

**Issue by dxgldotorg** [joncampbell123/dosbox-x#4764]
### What you want

As it currently stands, the hack used to make text mode run in 256 color mode doesn't seem to work; tried vgaonly mode to emulate IBM VGA.
Example:  MegaZeux 2.69c the last 16-bit DOS version of the game creation system MegaZeux.
![image](https://github.com/joncampbell123/dosbox-x/assets/7480507/0c3e4f8b-7441-488e-8b30-1f268cbe83cf)
Screenshot shows a game that uses the game engine's "SMZX" mode which is not working as instead of vertical bars the graphics should be smooth colors.

### Additional information

MZX 2.69c is at https://www.digitalmzx.com/show.php?id=166 in case you need to test.  The game used is SMZX Tetris at https://www.digitalmzx.com/show.php?id=1586 which you can confirm the correct colors playing it in the web player.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by AliceLR** [comment]
To more accurately explain what is supposed to be going on in VGA terms: for '90s Nvidia, ATi, and possibly some Cirrus Logic and C&T graphics adapters, enabling the mode 13h pixel doubling bit of the VGA mode control register while in 640x350 text mode would result in a 256-color 320x350 text mode with 4 colors per character. The 4 colors are indexed using the background and foreground colors as the high and low nibbles of palette index for each color.

For reference, here is how modern MZX enables this hack: https://github.com/AliceLR/megazeux/blob/88a20a39ac50e70eabd4925a6a1433ae0be0e127/arch/djgpp/render_ega.c#L98

```C
static void ega_set_smzx(boolean is_ati)
{
  // Super MegaZeux mode:
  // In a nutshell, this sets bit 6 of the VGA Mode Control Register.
  // Bit 6 controls the pixel width - if 1, the pixel width is doubled,
  // creating one 8-bit pixel instead of two 4-bit pixels. HOWEVER,
  // normally, this is only done in Mode 13h.
  //
  // nVidia and some Cirrus Logic cards support this; ATI cards
  // also "support" it, but swap the order of joining the pixels
  // and require a weird horizontal pixel shift value - see below.
  outportb(0x3C0, 0x10);
  outportb(0x3C0, 0x4C);

  if(is_ati)
  {
    // set horizontal pixel shift to Undefined (0.5 pixels, in theory)
    outportb(0x3C0, 0x13);
    outportb(0x3C0, 0x01);
  }
}
```

I don't have any test programs for this ready since I wasn't prepared to request this yet, but in the [old DOS versions of MegaZeux](https://github.com/AliceLR/megazeux/releases/download/v2.70/mzx270.zip) you could load the file PAL_ED.MZX, press "P" to open the palette editor, and press "X" to display the entire 256 color palette. It should show something that looks like this:

![image](https://github.com/joncampbell123/dosbox-x/assets/1750531/dd29a630-47ae-4d50-a255-d4529ac1d80b)

**Comment by dxgldotorg** [comment]
I just tested on an old GeForce 6200 AGP card, and that card does SMZX mode correctly.

**Comment by joncampbell123** [comment]
Ew... very clever! Someone figured out how 256-color mode works and hacked text mode to fit within it! :+1: 

VGA 256-color mode is really just 4 bits shifted into an 8-bit register per dot clock, but that would make a strange unhelpful 640x200 256-color mode, so there is a bit to latch every other pixel so that you only see the completed 8-bit value and not the intermediate ones. This is also why it is impossible to do a 640x200 256-color tweakmode on standard VGA hardware.

**Comment by joncampbell123** [comment]
I can confirm:

A 486 laptop with a Paradise/Western Digital SVGA chipset doesn't work this way. You can set the bit and halve the resolution of text mode, but it doesn't allow this hack to work.

A Pentium laptop (Toshiba Satellite Pro) with a Chips & Tech chipset does appear to work in a way that allows this hack to work. Setting that bit halves the resolution and makes the text multicolored that suggest 256-color 4-bit shifting behavior.

**Comment by AliceLR** [comment]
Do you have specifics on these laptop models/graphics? I've been trying to keep a [list of every known model that's been tested so far](https://www.digitalmzx.com/wiki/Super_MegaZeux#Compatibility) so we have more data.

> A 486 laptop with a Paradise/Western Digital SVGA chipset doesn't work this way. You can set the bit and halve the resolution of text mode, but it doesn't allow this hack to work.

This sounds a lot like what happens with my ThinkPad 560X's NeoMagic chipset. The left pixel always gets doubled and tweaking the horizontal pixel shift register doesn't help.

Is the Satellite Pro a 400 CDS or comparable, by any chance? I had an unknown model Satellite Pro circa 2004 *most likely* with a C&T chipset that supported this hack. I remember it having used the same pixel ordering as the Nvidia cards (the left pixel of each pair contributes the low nibble of the color, IIRC).

The ATi cards that support this—in addition to needing that horizontal shift setting—apparently also have the nibbles in the opposite order.

**Comment by joncampbell123** [comment]
> Do you have specifics on these laptop models/graphics? I've been trying to keep a [list of every known model that's been tested so far](https://www.digitalmzx.com/wiki/Super_MegaZeux#Compatibility) so we have more data.
> 
> > A 486 laptop with a Paradise/Western Digital SVGA chipset doesn't work this way. You can set the bit and halve the resolution of text mode, but it doesn't allow this hack to work.
> 
> This sounds a lot like what happens with my ThinkPad 560X's NeoMagic chipset. The left pixel always gets doubled and tweaking the horizontal pixel shift register doesn't help.
> 
> Is the Satellite Pro a 400 CDS or comparable, by any chance? I had an unknown model Satellite Pro circa 2004 _most likely_ with a C&T chipset that supported this hack. I remember it having used the same pixel ordering as the Nvidia cards (the left pixel of each pair contributes the low nibble of the color, IIRC).
> 
> The ATi cards that support this—in addition to needing that horizontal shift setting—apparently also have the nibbles in the opposite order.

The Pentium laptop in question is a Toshiba Satellite Pro 465CDX. It was a great laptop for it's time for both DOS gaming and Windows 95 OSR2 gaming. Most Toshiba laptops of the time period including the Libretto use C&T chipsets.

The 486 laptop is a Compaq LTE Elite 450CX with a Paradise/Western Digital SVGA chipset.

**Comment by joncampbell123** [comment]
If your Toshiba laptop was made 1998-1999 or later it may have an Intel chipset instead of Chips & Tech because Intel acquired C&T around that time. https://en.wikipedia.org/wiki/Chips_and_Technologies

I have a Toshiba laptop I bought sometime around 2004 with an Intel graphics chipset (the 855GM) which runs perfectly fine with Linux and Windows XP.

**Comment by joncampbell123** [comment]
One thing that DOSBox-X has already implemented regarding this bit was the discovery some time ago that if you set up 320x200 256-color mode on VGA, and then switch OFF this bit, you get a strange 640x200 256-color mode because you get to see the intermediate "pixels" that result when the 8-bit value is halfway shifted out to shift the next pixel in. I suppose if you arrange the color palette just right you might exploit this odd tweakmode for high res 256-color graphics on standard VGA, but obviously not for gaming. While it seems to work on most chipsets I noticed Tseng ET4000 cards react in that case by just making it a 640x200 256-color mode with the 320x200 screen squeezed on the left side and the right side is just edge pixels repeated, but then again ET4000 cards have their own weird edge cases with standard VGA compatibility.

**Comment by joncampbell123** [comment]
How's this?

![mzxrun_000](https://github.com/joncampbell123/dosbox-x/assets/6245486/34b1c2e7-8ce7-4a05-aab2-c7e508e05996)

**Comment by AliceLR** [comment]
> How's this?

Looks great!

**Comment by joncampbell123** [comment]
Awesome. It's done.

**Comment by AliceLR** [comment]
Not sure if hardware testing follow-up belongs in this issue, but so far I've received feedback from a MegaZeux user with a Compaq 4704 motherboard (onboard S3 Trio64V) that suggests this chip performs the same left pixel doubling as the NeoMagic MagicGraph128XD.

**Comment by joncampbell123** [comment]
> Not sure if hardware testing follow-up belongs in this issue, but so far I've received feedback from a MegaZeux user with a Compaq 4704 motherboard (onboard S3 Trio64V) that suggests this chip performs the same left pixel doubling as the NeoMagic MagicGraph128XD.

So it does the same thing my 486 laptop with the Paradise/WD chipset does, and it only doubles pixels, instead of combining them into 8 bit pixels?

**Comment by AliceLR** [comment]
> So it does the same thing my 486 laptop with the Paradise/WD chipset does, and it only doubles pixels, instead of combining them into 8 bit pixels?

Yes, I think so. Here's a sample from PAL_ED.MZX that demonstrates the doubled pixels and 4-bit color:
![image](https://github.com/joncampbell123/dosbox-x/assets/1750531/83f7597a-b3cb-4902-bcb3-037a7ff38e0b)

**Comment by joncampbell123** [comment]
Yeah, that's pixel doubling. If it's just doubled pixels and there's no colors between the colors, that's what it's doing.
