### ISSUE TITLE
 Why can't Windows 9x be installed with the integrated DOS?

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#4768]
### Question

I have wondered about this for a while.
My theory is that the prompt/script in DOSBox-X emulates FAT12 (common in floppy drives), I know little about how DOSBox-X works, and am not sure if DOSBox-X emulates FAT12 or simply emulates itself (something that hopefully someone knows), but it clearly does not emulate FAT16, FAT32, and at least not NTFS, even we now know that an DOSBox-X created image file with a file system in the FAT family can be converted to NTFS in DOSBox-X, otherwise we would most likely be able to install Windows 9x in it integrated the DOS, and if DOSBox-X, and maybe (but unlikely, when I think about it) even install Windows NT with NTLDR from there, to a secondary folder, since NT is not DOS, I'm not sure if NTFS emulation is needed to "convert" the folder to NTFS.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
It can be installed **from** the integrated DOS to a harddisk image file, at least until the first reboot. That is exactly how the installation of Windows 9x is documented on the DOSBox-X wiki.

And obviously DOSBox does support FAT12, FAT16 and ISO9660 (level 1), otherwise it would never be able to read disk images in those formats.
DOSBox-X also supports FAT32, UDF and some additional ISO9660 extensions (level 2, Joliet, Rock Ridge, El Torito).

Other file systems such as NTFS were not used by DOS and I don't think should therefore be a target.

**Comment by BridgeHeadland** [comment]
@rderooy I am not familiar with ISO9660 and UFD, what is it?

**Comment by emendelson** [comment]
@BridgeHeadland - Have you tried Google for `ISO9660` and `UFD file system`? They're very helpful.

**Comment by rderooy** [comment]
UDF not UFD...

**Comment by emendelson** [comment]
Someday I'll learn how to type... Fixed.

**Comment by joncampbell123** [comment]
Beyond a certain point, Windows 95 and higher bypasses the DOS kernel and uses it's own protected mode 32-bit filesystem interface. If it recognizes the IDE controller, it will use it's own 32-bit disk drivers and bypass INT 13h as well.

This of course makes mounting a local folder in Windows 9x impossible. If at some point DOSBox is able to run WIN.COM and run Windows 95 from it, your C: drive will have to be a hard disk image file, not a local folder.

There is also a lot of low level detail about the DOS kernel that Windows 9x reads on startup in order to take over it's functions. It "sucks the brains out of DOS" at startup.https://devblogs.microsoft.com/oldnewthing/20071224-00/?p=24063

The DOSBox-X DOS kernel emulation isn't there yet, including the IFSHLP driver that Windows 95 relies on
