### ISSUE TITLE
[regression] IMGMOUNT / MSCDEX has an error when mounting .gog/.ins files

### ISSUE THREAD

**Issue by xvachon** [joncampbell123/dosbox-x#4881]
### Describe the bug

Discussed in https://github.com/joncampbell123/dosbox-x/discussions/4877, making a proper bug report for it.

Regression vs. dosbox-x 2023.10.06. Following the changes to IMGMOUNT in 2024.03.01, MSCDEX returns an error when attempting to mount a .ins file. Previously it used to be working fine.

### Steps to reproduce the behaviour

1. Load dosbox-x 2024.03.01.
2. Attempt to mount a .ins file combined to a .gog file. The example from the screenshots are from the GOG release of Might and Magic 4+5. This can be reproduced with any DOS game release on GOG that has at least 1 .ins and 1 .gog file, tried also with Heroes of Might and Magic 2 Gold.
3. Notice the MSCDEX error.
4. Load dosbox-x 2023.10.06.
5. Attempt to mount a .ins file combined to a .gog file in this version.
6. Notice that the mounting works.

Screenshot dosbox-x 2024.03.01
![image](https://github.com/joncampbell123/dosbox-x/assets/16070349/db13364b-86b7-468e-99f6-0238603bc056)

Screenshot dosbox-x 2023.10.06
![image](https://github.com/joncampbell123/dosbox-x/assets/16070349/59d31208-2d2e-4d03-9d66-a975aed967f6)

### Expected behavior

Mounting .ins files from GOG should be functional with IMGMOUNT

### What operating system(s) this bug have occurred on?

Windows 11

### What version(s) of DOSBox-X have this bug?

2024.03.01

### Used configuration

```ini
AFAIK not relevant
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I don't have any `.gog/.ins` file to test, but I assume `.ins` is a CUE sheet.
Try renaming `.ins` to `.cue` and see if it works.
If it works, I think is making the flaw, and adding `.ins` should work. 
https://github.com/joncampbell123/dosbox-x/blob/8e4349bf4a17c7c73c0af7c4894f8916b13726d5/src/dos/cdrom_image.cpp#L1287C1-L1293C3

**Comment by mickski56** [comment]
Just to add GoG have also used .gog / .dat. The .dat being a cue file in all but name. 
Renaming .dat to .cue works.
Modding the highlighted line in imgmount_cdrom.cpp didn't but that's probably my lack of c skill.

**Comment by maron2000** [comment]
Okay, understood that cue sheet for gog is `.dat`.
So what is actually a `.ins` file?

**Comment by xvachon** [comment]
@maron2000 Changing the 2 .ins files extension to .cue worked, I didn't need to change the .gog files extensions to .bin. After that change, the game loads fine!

**Comment by maron2000** [comment]
@xvachon @mickski56 
Thanks for your information. I think basically, the extension of cue sheets (.ins, .dat, inst, and more?) should be changed to .cue for a better compatibility.
Other software handling cue sheets should recognize the file as well.
On the other hand, .gog should be remained as is, since it is specified in the cue sheet or you have to edit the file to tell the new name of the .gog file.

**Comment by mickski56** [comment]
Yes , although it should be documented somewhere as dosbox-x behaviour has changed.

**Comment by maron2000** [comment]
I put PR #4882 not to reject the CUE sheets, so that you don't have to always rename files.
`imgmount [drive] [cue sheet] -t iso` should work.

![cue](https://github.com/joncampbell123/dosbox-x/assets/68574602/c95f4c11-d2fe-42c2-862d-77ef96b4edd3)

**Comment by mickski56** [comment]
PR https://github.com/joncampbell123/dosbox-x/pull/4882 works as expected for me. i.e. no changes on my part required.
Thanks

**Comment by Ohrwerk** [comment]
I also had this problem, but renaming the .INS to .CUE was not successful.
Could not load image file: ..\Das Schwarze Auge - Schatten über Riva\GAME FILES\game.cue
MSCDEX: Fehler: Ungültige Datei oder kann nicht geöffnet werden.

I use code page 858 in DOSBOX-X.
I also edit the configuration files in code page 858.
If there are umlaut characters (aöüÄÖÜ) in the filename or path of an image file, IMGMOUNT cannot find this image, I suspect similar problems occur with other country-specific characters.
Only renaming the folder so that it does not contain any country-specific characters was successful and I was able to mount the .GOG image with the .CUE.
The MOUNT command does not have this problem.
