### ISSUE TITLE
Suggestion: a HOSTRUN command (runs command on Windows host system)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#489]
I've found this useful in my SVN-based project. It's a command that runs a command on the Windows host system, like this: HOSTRUN notepad d:\path\filename.txt

In a project that I use for running DOS applications, I use the name START, but that won't work if the guest is a Win95/98 system that has its own internal START command, so I've renamed it HOSTRUN here. Here's the diff (and I'm only offering it for anyone who might find it useful, even if it doesn't go into DOSBox-X). And it's probably obvious that I don't understand this code, but simply took bits and pieces from other people's code until it worked.

https://github.com/emendelson/dosbox-x/commit/4db8647a1dfc590733b8cd05894a19fd1b25fd46

**Comment by joncampbell123** [comment]
I like the idea, but I have some reservations about it.

Generally when people run commands in DOSBox they expect the command to stay within DOSBox. People generally don't expect the DOS session to spawn programs on their host OS. So to prevent malicious dosbox.conf setups that format your hard drive in Windows, it would be off by default.

I propose that your version could be adopted with the requirement for the --async switch to indicate that you want it to run independently of DOSBox-X.

A future idea I do want to do with the command is that unless --async is given, the subprocess is spawned with STDIN/STDOUT/STDERR redirected to DOSBox-X and the program's console I/O is routed to the DOS console in DOSBox-X. A dummy DOS program runs until the actual process terminates.

You could run Microsoft's recent C++ compiler within DOSBox-X like any other DOS program that way. It looks like it's on the DOS console even though it's actually running the program on the host and handling STDIO to the console.

Other rules:
- If the subprocess terminates, then DOSBox-X returns to the command prompt like normal DOS termination
- CTRL+C and CTRL+BREAK would send the proper termination signal to the subprocess
- Closing DOSBox-X will terminate the subprocess right away
- Console I/O will be handled unless --async given even if the subprocess is a graphical Windows program. It's possible for graphical Windows programs to emit to STDERR even if you don't see it.
- Modifications will be added in the future to bring this command to Linux, Mac OS X, etc. (CreateProcess in Windows vs fork/exec in Linux)

**Comment by emendelson** [comment]
All those ideas sound vastly useful - and far beyond anything I had thought of when I added this to a project that mostly runs WordPerfect for DOS and uses the command to run file-conversion routines, etc., in the host.

Of course you're entirely welcome to do what you want with it. I'm honored that you think it's something worth starting from!

**Comment by Wengier** [comment]
I have added the START command for Windows host in my latest pull request. This command is disabled by default for security reasons, but can be enabled by either the "startcmd" config option (in [dos] section) or the -winrun command-line option (which will also enable the CLIP$ device).  The START command itself will wait for program, so it will return to the DOSBox-X shell when the program ends, but the user can press Ctrl+C in the DOSBox-X window to terminate the program right away of course (or by closing the DOSBox-X window). At this time console I/O will be done in the Command Prompt rather than within DOSBox-X.

**Comment by rderooy** [comment]
@emendelson mentions that using "START" will cause problems with Win9x. I know that right now you cannot run Win9x directly from the dosbox-x integrated DOS, but that may someday be possible.

**Comment by Wengier** [comment]
@rderooy That is why I added it as a program on the Z drive rather than as a shell command. On the Z drive there are also programs such as FIND, MOVE, XCOPY etc which use the same name as in DOS or Win9x, but this can be resolved by modifying PATH, e.g. C:\WINDOWS\COMMAND before Z:\.

**Comment by rderooy** [comment]
Regarding the Windows "START" command. On Linux systems you can use xdg-open to open for instance a PDF file, or a directory from the commandline with the default associated action. e.g. "xdg-open file.pdf" to open a PDF in your default PDF viewer, or "xdg-open ." will open the current directory in your file manager. Perhaps you could do something similar with this if the parameter is not an executable file, instead of just launching programs.

FYI, I have a "alias open=xdg-open" in my .bashrc as it's shorter, and I like "open" better than "xdg-open".

**Comment by Wengier** [comment]
@rderooy Have you tried the START command yourself? Both "START FILE.PDF" and "START ." as you mentioned do work at this time.

**Comment by joncampbell123** [comment]
HX DOS builds happen to run on Windows 98, even though they're not designed for Windows 98 :)

**Comment by emendelson** [comment]
Is there any hope of adding the START command to macOS and Linux builds? I've been using complicated kludges to run host commands from DOSBox-X under macOS, but these have mostly stopped working under Big Sur, and it would be very good to have a way to launch a bash script or AppleScript from DOSBox-X. I know that this won't be easy, but it seems like something that ought to exist on all platforms.

**Comment by Wengier** [comment]
@emendelson Yes, it is possible to make them work in macOS and Linux host systems, although the syntax of the START command will be somewhat different (and launching apps directly without START command is supported by Windows only because macOS/Linux do not use the same file extensions for executables). If you type ``START /?`` you will get the following help message on macOS/Linux systems:

```
START /OPEN file
START command [arguments]

  /OPEN: To open a file or URL with the associated program.
 file: The file or URL to open with the associated program.
 command: The command or program to start or run.
 arguments: Arguments to pass to the application.

Note: The path specified in this command is the path on the host system.

```

For example, ```START command``` to run the specified command, and ```START /OPEN file``` to open the specified file with the associated program in these systems. Hope this helps.

**Comment by emendelson** [comment]
@Wengier - That was fast! Thank you! I'll build current code on a Mac and will come back with any questions. I didn't realize this would take so little time to enable.

**Comment by emendelson** [comment]
This works perfectly is macOS. Thank you!
