### ISSUE TITLE
EGA VPTable provides wrong register values

### ISSUE THREAD

**Issue by MrMadguy64** [joncampbell123/dosbox-x#5046]
### Describe the bug

I'm not sure about other values, but CRTC MCR value for mode 0x10 is definitely wrong. MCR values for other modes also don't look good. All I try - is to modify bit 7 and write value back to register. Here is result.
![Bug](https://s1.hostingkartinok.com/uploads/images/2024/06/927d9b82529b657b709dd38909a91644.png)
Overall rule - VPTable should be used to program registers on real hardware. So, application can be sure, that default register values are exactly the same, as ones stored in VPTable. But it isn't true for DOSBox. Yeah, it doesn't matter, what values things like blanking and sync pulses have. But at least control registers should have proper values.

It's needed for two purposes:
1) To overcome write-only nature of almost all registers on EGA
2) To provide mode modification functionality, similar to Int 1Dh for CGA/MDA. And as DOSBox doesn't take timings from VPTable - any application, that relies on this feature would fail to work.

### Steps to reproduce the behaviour

New version of my program is still work in progress, so:
1) Set machine=ega
2) Switch to mode 0x10
3) Draw something on screen
4) Read env table address from 0040:00A8
5) Video parameters table address is first 4 bytes of env table
6) Choose table entry for mode 0x10 (>64Kb VRAM) - it's №18, size of every entry is 64 bytes , MCR offset is 33, so offset should be 0x04A1.
7) Write CTRC MCR value to corresponding CRTC port - imagine, that we want to modify it and then write back
8) See what happens

P.S. New version of my program is released - you can reproduce this problem via selecting 320x350x4 mode for EGA.drv. Behavior has changed for 640x350x4 mode! Standard mode should stay standard!

### Expected behavior

![No bug](https://s1.hostingkartinok.com/uploads/images/2024/06/8989865cc59ceeb5e539f47991a7c7a0.png)

### What operating system(s) this bug have occurred on?

Windows

### What version(s) of DOSBox-X have this bug?

Current

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I managed to find an IBM EGA card on eBay. If I plug it in and dump what the actual table looks like and implement that in DOSBox-X maybe that will help.

**Comment by MrMadguy64** [comment]
Ehh. I've answered before I could edit my initial post.

There are more problems with DOSBox:
1) I'm not sure, if it would be good idea to just dump real IBM EGA registers, as DOSBox's EGA isn't real EGA - it's more like "EGA on VGA". VGA uses different pixel clocks for example. Via using IBM EGA register values you would fix CRTC MCR, but break MOR instead. Be very careful!
2) DOSBox doesn't emulate Int 1Dh behavior for VPTable. My application uses CRTC reprogramming as workaround, but real software can rely on this feature. I don't know any such software though.

**Comment by MrMadguy64** [comment]
And also. You can use my program for testing. It falls back to IBM EGA timings, if 0040:00A8 = 0000:0000, or VPTable = 0000:0000 or first byte of VPTable entry is 0 (number of cols, if I remember correctly). It doesn't use all registers though. Only ones, it needs to change.

**Comment by MrMadguy64** [comment]
I've forgotten, that 640x350 mode behavior has changed in latest version of my program. No registers are reprogrammed for standard modes exactly to avoid such problems. Standard modes should stay standard. Use 320x350 mode instead. Don't forget to set compatibility mode to "Standard timings", if you would disable VPTable. Garbled screen in case of unsupported mode - is HX problem. Not DOSBox or my program's problem.

**Comment by joncampbell123** [comment]
It's very important for egaonly to emulate the EGA as best as possible, including register values set according to the official EGA VP table.

I think the issue here is that you're trying to program the EGA into the poorly documented 640x350 4-color mode, which is the only way 640x350 can be done on EGA cards that only have 64KB of RAM.

As I understand it, if the planar memory layout were as straightforward as normal 640x350 16-color mode, each bitplane would still take too much memory (28KB which is >= 16KB per bitplane) even for just two bitplanes in the 4-color mode. When I *tried* to add support for it, I figured it must involve something with odd/even mode to "fold" the 28KB across two 14KB bitplanes pairs, but I wasn't successful at it.

Looking at the VPTable published by IBM, the registers confirm the odd/even mode. Not much uses the 4-color mode but I do think it might be nice for DOSBox-X to emulate it just the same.

**Comment by rderooy** [comment]
Early Windows 1.0x versions had several EGA display options, perhaps one of them corresponds to this mode.
e.g. for Windows 1.04 (not the special IBM OEM release, as that changes a bunch of options):
![image](https://github.com/joncampbell123/dosbox-x/assets/17701098/b1677856-0836-48c7-9a93-54685a3774e8)

**Comment by MrMadguy64** [comment]
> I think the issue here is that you're trying to program the EGA into the poorly documented 640x350 4-color mode, which is the only way 640x350 can be done on EGA cards that only have 64KB of RAM.
Why do you think, I do? I don't do it. If I would - I wouldn't see any picture at all. Why? Because EGA VPTable has two copies of mode 10h. One for <64Kb and one for >64Kb. <64Kb one has all 0 in DOSBox VPTable. Trying to use it wouldn't give anything. Problem is caused by >64Kb mode in EGA VPTable having wrong values. Some mix of 320x200 and 640x350 ones.

My symptoms are: If I use DOSBox VPTable - I have problem. If I hardcode BIOS VPTable to return nullptr and use standard EGA VPTable instead - no problems.

And again. It doesn't matter, if VPTable values are real or not. They should match ones programmed to registers, so application would be able to modify them without messing things up. They exist for 2 purposes: 1) To overcome "read-only" problem 2) To be able to override standard VPTable with one with modified values. Similar to how Int 1Dh works. And DOSBox doesn't even emulate proper Int 1Dh-like behavior now. In order to provide proper behavior, you actually need to do following thing - instead of programming values directly to EGA registers, you need to store them for all modes in VPTable first. And then use VPTable ones to program register values. In this case application would be able to override VPTable the same way, it would do it for Int 1Dh.

**Comment by MrMadguy64** [comment]
If I'm still not clear enough. (This thing on EGA)[https://github.com/joncampbell123/dosbox-x/blob/29ae732ac23c6c17bda4bb5d8381cfa4a25af86f/src/ints/int10_vptable.cpp#L333] serves exactly the same purpose, as (this thing on MDA/CGA/etc)[https://github.com/joncampbell123/dosbox-x/blob/29ae732ac23c6c17bda4bb5d8381cfa4a25af86f/src/ints/int10_vptable.cpp#L28]. See (this code)[https://github.com/joncampbell123/dosbox-x/blob/29ae732ac23c6c17bda4bb5d8381cfa4a25af86f/src/ints/int10_vptable.cpp#L584] and (this one)[https://github.com/joncampbell123/dosbox-x/blob/29ae732ac23c6c17bda4bb5d8381cfa4a25af86f/src/ints/int10_modes.cpp#L1216].

**Comment by iamgreaser** [comment]
> Not much uses the 4-color mode but I do think it might be nice for DOSBox-X to emulate it just the same.

It's been a while since I've touched that code in 86Box but I do recall getting it working despite not having the hardware. Reading the schematic carefully is required in this case as the documentation lies about the high/low page select bit (or alternatively the CHIPS clone datasheet has a table... but the register description still has the same lie).

This affects both mono 64K and 4-colour 64K.

Also, for mono modes, you need a mono monitor, it's not like VGA in that regard.

I tried doing this off the top of my head but I had to look some stuff up anyway, so:

- Odd/Even mode is used for 4-colour 640x350 64K as well as all mono 640x350 modes.
- The *presence* of a memory expansion (which is needed for >64 KB) changes things...
  - The A0 line during CPU memory accesses is intercepted (sheet 4, top left-centre-ish, U29 74LS151):
    - Odd/Even off, or other cases: A0 is CPU A0.
    - **Unexpanded, non-128 KB memory mapping: A0 is CPU A14.**
    - Expanded, non-128 KB memory mapping: A0 is the INVERSION of the page select bit.
    - Expanded, 128 KB memory mapping: A0 is CPU A16.
- The 64 KB / memory expansion bit needs to be set appropriately - I *believe* this is in the Sequencer as it pertains to selecting one of 4 memory banks (or the "upper 2 bits"... but it actually controls chip select lines on an IBM EGA).
- The attribute controller has the plane output mask set to enable planes 0 and 2 only (this is *not* the plane write mask in the sequencer!). This is standard in the >64K mono mode, but the >64K colour mode enables all 4 planes.
- The CRTC needs to be told to wrap on internal address bit 13 instead of 15.

Speaking of the mono mode, you also have to deal with graphics blink mode (there's a decent chance you've done this already but this part can be easy to miss). The best documentation of this I've seen is in SVGA chipset datasheets. The Matrox MGA-G200 specification datasheet describes this *really* well, and is probably how it actually works on the original chipsets:
- In "monochrome" graphics mode (controlled by attr 0x10 bit 1), the plane 3 bit output toggles at the blink rate. This is used by the monochrome 640x350 modes.
- In colour graphics mode, if the plane 3 bit input is set, then it blinks as per colour graphics mode, otherwise the output is forced to 1. This is not used by a BIOS mode, but some versions of Lotus 1-2-3 use it in their WYSIWYG mode.

And after some quick testing with 86Box (which uses the actual video BIOS image), the default palette for 4-colour 640x350 mode is the high-intensity black-cyan-magenta-white CGA palette. GW-BASIC `SCREEN 9` makes checking for this case easy...

**Comment by MrMadguy64** [comment]
Well, side-by-side comparison of <64Kb and >64Kb modes show following differences for <64K modes:
1) Shift load bit is set in seq register 0x01. <64Kb modes are only modes, that use this setting.
2) Odd/Even mode is set via seq register 0x04
3) Extended memory is disabled via seq register 0x04
4) Some things, connected to horizontal display enable and retrace skews/delays happen. It's hard to understand them. They're different for different modes. For example text modes have different values, than graphic ones.
5) Display enable skew = 0 instead of 1.
6) Start horizontal retrace happens 2 cycles earlier
7) Odd start address is selected. Only <64Kb modes use this option by default.
8) Horizontal retrace delay is set to 1. Only 640x350 text modes also have this value >0.
9) Horizontal retrace end is 0x1A instead of 0x00.
10) Offset is 1/2, cuz we switch to word mode
11) Count by two is enabled
12) Word mode is selected
13) Address wrap is switched to MA0 = MA15 mode
14) Odd/Even mode is set in graphic controller
15) Chain odd maps to even mode is enabled
16) Enable only planes 0 and 2 in attr controller

And default palette isn't CGA one. It's 1, 4, 5, 7.

**Comment by iamgreaser** [comment]
...right, I assumed GW-BASIC would use the BIOS palette. Yeah that seems like the actual palette from having read the mode tables in the manual.

And a quick test in DEBUG with the same 86Box settings + disk does confirm that it is the palette.

**Comment by joncampbell123** [comment]
In the latest commit, I copied the VP table verbatim from IBM EGA and VGA BIOS images.

I also added support for INT 10h to use the VP table when called to set standard EGA/VGA video modes.

**Comment by MrMadguy64** [comment]
Nice! Can't wait to test it. I hope, we won't break anything else.

**Comment by joncampbell123** [comment]
> Nice! Can't wait to test it. I hope, we won't break anything else.

It should be part of the latest nightly build: https://github.com/joncampbell123/dosbox-x/actions

**Comment by MrMadguy64** [comment]
> It should be part of the latest nightly build: https://github.com/joncampbell123/dosbox-x/actions
Yeah. Unfortunately I don't have time to test everything and check how things are implemented right now. But I have immediate problem: everything works as expected in 320x350x4 mode, but exactly the same problem as before persists in 320x350x1 mode. It's strange, because 320x350x1 is based on 320x350x4, i.e. it's not mono mode, that would have different timings, like 18Khz hsync. All I do - mask unused planes and load different palette. Nothing else.

**Comment by joncampbell123** [comment]
> > It should be part of the latest nightly build: https://github.com/joncampbell123/dosbox-x/actions
> 
> Yeah. ~Unfortunately I don't have time to test everything and check how things are implemented right now. But I have immediate problem: everything works as expected in 320x350x4 mode, but exactly the same problem as before persists in 320x350x1 mode. It's strange, because 320x350x1 is based on 320x350x4, i.e. it's not mono mode, that would have different timings, like 18Khz hsync. All I do - mask unused planes and load different palette. Nothing else.~
> 
> It was completely my fault - 1bpp implementation wasn't completed, so everything is actually ok.
> 
> But. If you wonder about VPTable entries marked as "(FIXME: Again? Why?)" - they aren't actually graphic modes. They're text modes. They're VGA-specific mode 0/1, mode 2/3 and mode 7 - modes with VGA 8x16 font enabled. I.e. VGA VPTable actually has 3 different text mode variants: CGA 8x8, EGA 8x14 and VGA 8x16. And on VGA you should use 8x16. **I.e. [this code](https://github.com/joncampbell123/dosbox-x/blob/3ff38b6bfe39da9355f56c6203887f164cba4072/src/ints/int10_modes.cpp#L1328) is wrong!**



> > It should be part of the latest nightly build: https://github.com/joncampbell123/dosbox-x/actions
> 
> Yeah. ~Unfortunately I don't have time to test everything and check how things are implemented right now. But I have immediate problem: everything works as expected in 320x350x4 mode, but exactly the same problem as before persists in 320x350x1 mode. It's strange, because 320x350x1 is based on 320x350x4, i.e. it's not mono mode, that would have different timings, like 18Khz hsync. All I do - mask unused planes and load different palette. Nothing else.~
> 
> It was completely my fault - 1bpp implementation wasn't completed, so everything is actually ok.
> 
> But. If you wonder about VPTable entries marked as "(FIXME: Again? Why?)" - they aren't actually graphic modes. They're text modes. They're VGA-specific mode 0/1, mode 2/3 and mode 7 - modes with VGA 8x16 font enabled. I.e. VGA VPTable actually has 3 different text mode variants: CGA 8x8, EGA 8x14 and VGA 8x16. And on VGA you should use 8x16. **I.e. [this code](https://github.com/joncampbell123/dosbox-x/blob/3ff38b6bfe39da9355f56c6203887f164cba4072/src/ints/int10_modes.cpp#L1328) is wrong!**

I see. I'll correct the code.

**Comment by joncampbell123** [comment]
Ah, looking at the 3 entries I marked, they're clearly modes 0 and 1, modes 2 and 3, and mode 7 VGA style. They're combined because color/mono doesn't matter anymore on VGA hardware. There's no colorburst to enable/disable. The 3rd is clearly mode 7 because in the attribute controller section you can clearly see a monochrome palette mapping (a lot of 0x08, 0x18, etc)

**Comment by joncampbell123** [comment]
While I'm at it, I could also copy down this table for machine=cga and machine=mda: https://github.com/philspil66/IBM-PC-BIOS/blob/main/PCBIOSV3.ASM#L3523
