### ISSUE TITLE
Full HD video files plays slowly in DOS version of MPlayer under DOSBox-X

### ISSUE THREAD

**Issue by EgorKuzevanov** [joncampbell123/dosbox-x#5227]
### Describe the bug

In the DOS version of MPlayer under DOSBox-X, H.264 video files in MP4, MKV and MPEG-TS containers with a resolution of 1920x1080 (Full HD) plays slowly.

### Steps to reproduce the behaviour

1. Download the DOS version of MPlayer from the Old-DOS website: http://old-dos.ru/dl.php?id=8713
2. Unpack the downloaded archive into a folder that will later be mounted in DOSBox-X as a C: drive.
3. Launch DOSBox-X and mount the folder with the unpacked DOS version of MPlayer and any Full HD video files as a C: drive.
4. Run the following command:
`MPLAYER.EXE -screenw 640 -screenh 480 -fs <path_to_any_Full_HD_video_file>`
5. See slow playback.

### Expected behavior

Fast playback of Full HD video files in the DOS version of MPlayer under DOSBox-X.

### What operating system(s) this bug have occurred on?

Windows 10 LTSB 2016 (x64)

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2024.07.01 MinGW LowEnd SDL2 (x86), commit 214c0482674316aa8e8a8d895ab5b4ff94fc8141

### Used configuration

The DOSBox-X emulator is allocated 512 MB of RAM. SDL output type is "surface".

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Well to be fair... have you ever tried to play an HD file on a Pentium 100MHz?

From experience, a Pentium 100MHz can handle at most a 240p DivX AVI or MPEG-1 file.

A fast Pentium III can handle MPEG-2 DVD video.

Now consider that H.264 is a far more computationally expensive codec that needs at least mid to late 2000's era CPU and hardware to handle, and hardware into the 2010s if you want high definition!

Now imagine trying to play high definition H.264 video and audio on late 1990s Pentium to Pentium III system DOS/Win9x hardware. You're going to get very poor frame rates because that hardware is well below what is needed to play it realtime.

Just for reference, PCs weren't even powerful enough to play MP3 files until Pentium systems hit 100-133MHz and that's if you used something well optimized like WinAMP to play them.
