### ISSUE TITLE
Ultimate calculator by daniel corbier gives strange answers when I enter a maths problem

### ISSUE THREAD

**Issue by whocrazy** [joncampbell123/dosbox-x#5234]
### Describe the bug

When I run ultimate calculator dos version by Daniel Corbier, and enter a simple maths problem, for example 1+2, I get a whole string of numbers that don't make any sense, instead of the real answer, which is obviously 2.

### Steps to reproduce the behaviour

1. download ultimate calculator for dos from www.ucalc.com
2. start up dosbox-x and run the program
3. enter any math problem, such as 1+2, or 36*64
4. Press enter and watch what happens.

### Expected behavior

the proper answer should be given instead of a slew of nonsensical numbers

### What operating system(s) this bug have occurred on?

windows 10 22H2

### What version(s) of DOSBox-X have this bug?

2024-10-01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [ ] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
It is due to the precision of FPU emulation.
You can find out details in the [Wiki](https://github.com/joncampbell123/dosbox-x/wiki/Guide:CPU-settings-in-DOSBox%E2%80%90X/d4205d856c3da5787fc39f845452d184fbcb8ec4#floating-point-unit-fpu)

Your choices are:
 1. Disable FPU
 2. Change CPU core to Dynamic (Seems FPU is enabled regardless of the FPU setting)
 3. Use MinGW builds (and enable FPU)

The following screenshot is Visual Studio build with Dynamic core.
![image](https://github.com/user-attachments/assets/f9890680-bf73-4a4e-9278-632ddc7a0fef)

**Comment by whocrazy** [comment]
thank you so much for this.
