### ISSUE TITLE
Windows 3.1x installation problem

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#526]
You clearly already know about this, because there's a note about Windows 3.1 installation in the todo list, but, just for the record: when I tried to install Windows 3.11 under DOSBox-X, I got an error message labeled E_Exit with the message "JMP illegal descriptor type 0".

Is there a workaround for this, or should we wait for future changes in the code?

(And while I'm writing: thank you for shutting down that spam that was cluttering the mailboxes of everyone who is subscribed to this terrific project....)

**Comment by emendelson** [comment]
The first time I tried it I mistakenly used an old conf file (used successfully with SVN) with core=auto. This time I tried it with nothing in the conf file at all (except an autoexec section), therefore the DOSBox-X defaults and got the same error message at the end of the installation (which didn't complete).

And I realized that I may be wasting your time because I'm testing with my own build. I'll build your clean code later today and will try again. Meanwhile, just ignore this. (And I do hope you can ban that spammer whose messages keep cluttering up the mailboxes of everyone who subscribes to this code.)

**Comment by emendelson** [comment]
Have deleted my previous post, in order to write only about unmodified code instead of my own build. 

I've built the current code (downloaded last night), and tried setting up Win3.11 using a copy of dosbox.reference.conf as the conf file, and also with the same file, but with core=normal. Each time, DOSBox-X crashes (with a Windows error message saying that it has stopped working...) at the point where Setup says it is loading Windows.

I'll be happy to do more tests or provide more details that you specify. (And I still hope you can ban that spammer whose messages keep cluttering up the mailboxes of everyone who subscribes to this terrific project.)

**Comment by joncampbell123** [comment]
Does it crash with core=normal?

**Comment by emendelson** [comment]
Yes. Crashes with core = normal exactly the same way.

**Comment by emendelson** [comment]
Two more details: 

1. The crash happens at the moment when the Windows setup program says it is starting Windows.

2. If I use DOSBox-X to launch a Win311 setup that I installed using SVN, then core=auto and core=normal both work correctly, and I can run Win311 normally. The crash only occurs when installing using DOSBox-X.

**Comment by joncampbell123** [comment]
It seems some really odd A20 gate issue with Windows 3.1 has cropped up. I can confirm the crash.

**Comment by joncampbell123** [comment]
It seems Windows 3.1 is manipulating the A20 gate in a way that it crashes itself.

A quick hack is to add under the [dosbox] section of dosbox.conf:
a20=on

This sets the state of the A20 gate so that it's "stuck" on and Windows 3.1 can't switch it off, which seems to work as a temporary workaround for the install phase.

**Comment by emendelson** [comment]
And (though you don't need this confirmation) I can confirm that a20=on does in fact allow Win 3.11 installation to complete. (And why am I not amazed that Windows 3.1 crashes itself...??)

**Comment by joncampbell123** [comment]
I also noticed that if you run with umb=false and ems=false, Windows 3.1's setup program fails to enable A20 and corrupts itself a bit at some point, and when you exit to DOS it displays a "null pointer assignment" error. The only way around that is to first run "A20GATE ON" to switch on the A20 gate.

So whatever Windows 3.1 is doing to switch the A20 gate on, DOSBox-X isn't doing it.

**Comment by joncampbell123** [comment]
Apparently you can also avoid the crash if you install with umb=false, ems=false, and xms=false, so that Windows 3.1 cannot use standard DOS interfaces to touch the A20 gate.

That would mean running without XMS, but Windows 3.1 install happens to work somehow (?)

Yet after reboot, Windows 3.1 complains about missing HIMEM.SYS as expected.

Odd.

**Comment by emendelson** [comment]
This is way beyond my competence - thanks in advance for any fixes!

**Comment by joncampbell123** [comment]
Alright, I see a problem right away:

DOSBox-X inherited the XMS memcpy emulation from DOSBox, and the memcpy emulation copies extended memory blocks WITHOUT enabling the A20 gate!

This explains why it happened to work with DOSBox's fast A20 emulation, because the fast emulation faked it by remapping only the first 64KB past the 1MB boundary (HMA). But DOSBox-X got rid of that hack and masks ALL pages by A20, and that's where Windows corrupts itself and crashes (including the SETUP program).

So despite the popular game of blaming Microsoft for crappy code, this is really DOSBox's fault.

**Comment by emendelson** [comment]
Justice must be done - I've edited out the comment about Microsoft in my earlier post. Anyway, I'm glad this brought to light something else that DOSBox-X can improve (though I'm sorry to add to your workload...)

**Comment by joncampbell123** [comment]
This means I can also eliminate the "Enable A20 gate on Windows INT 2Fh init call" hack as well.

**Comment by joncampbell123** [comment]
DONE

**Comment by emendelson** [comment]
Amazing. Thank you!
