### ISSUE TITLE
Wrong palette is used in 4bpp packed pixel modes

### ISSUE THREAD

**Issue by MrMadguy64** [joncampbell123/dosbox-x#5278]
### Describe the bug

If I try to change EGA palette in 4bpp packed pixel mode via Int 10h 1002h - following problem happens:
![EGA](https://i124.fastpic.org/big/2024/1114/91/09c31fe808e162faaa5ccf86ecd67191.png)

Testing shows, that palette is set correctly in other modes.

### Steps to reproduce the behaviour

1) Set any 4bpp packed pixel mode
2) Try to change palette via Int 10h 1002h

### Expected behavior

![VGA](https://i124.fastpic.org/big/2024/1114/5a/c559cec03066a28a7944e971bc2ffa5a.png)

### What operating system(s) this bug have occurred on?

Windows

### What version(s) of DOSBox-X have this bug?

Latest

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by MrMadguy64** [comment]
Problem on second screenshot was my fault - it's fixed now.

**Comment by joncampbell123** [comment]
This is 320x200 or 640x200 16-color mode, correct?

The palette works differently in 200-line modes vs 350-line modes. It has to do with how the monitor interprets the 6-bit output pins where 200-line is RGBI and 350-line is the RRGGBB 64 possible colors.

http://www.ctyme.com/intr/rb-0116.htm

https://en.wikipedia.org/wiki/Enhanced_Graphics_Adapter

**Comment by joncampbell123** [comment]
This might also help: https://cosmodoc.org/topics/ega-functions/#SetPaletteRegister

**Comment by MrMadguy64** [comment]
Yeah, but there are two problems:
1) It's SVGA packed pixel mode. There is no reason to treat it as 200-lines CGA mode, because VGA/SVGA video card doesn't have to be compatible with CGA. EGA monitor had to be compatible with CGA, because IBM wanted to maintain compatibility between all 3 monitors and video cards. They wanted to allow users to connect EGA monitor to CGA video card and CGA monitor to EGA video card. That's why EGA monitor itself had hardcoded CGA palette in 200 lines modes. Video card itself didn't have hardcoded CGA palette. See IBM EGA manual page 124. As you can see, EGA BIOS loads 0x06 to attribute controller register 0x06 for mode 0x0D. Not 0x14, as it's done for mode 0x10. Why? Because hardcoded brown is implemented at monitor side. CGA palette was chosen by default even in 350 modes for compatibility reason only. It would be reasonable in one case only - in case of "mixed" EGA/VGA cards (like EGA Wonder or something like that), that had both EGA and VBE support at the same time.
2) This code works properly for 320x200x4 plane VGA mode. But it doesn't in packed pixel mode. What I load - is CGA-compatible palette. Even if bits 3 and 5 are set - they should be ignored by CGA, because corresponding pins aren't connected. In all cases. I don't use any CGA-incompatible colors at all. That's why I think, that it's bug. Reason I do it - is to replace 0x06 color only. Not because I don't like brown, but because brown is wrong color in case of dithering. But I reload whole palette in order to make code compatible with "emulated" 1bpp and 2bpp modes, where whole palette is reloaded. This code works properly in all other modes. Including 200 lines and text modes.

**Comment by MrMadguy64** [comment]
I'm not 100% sure, but my current guess - may be attribute controller isn't switched to 16 color DAC mode?

**Comment by MrMadguy64** [comment]
Now I know, what you talk about. Do you treat 320x200x4 packed pixel mode as "true" 200-lines mode, not VGA's 400-lines double-scan mode, so you think, that it should have CGA-compatible palette? While it's not bug, I really don't think, that SVGA mode should keep compatibility with CGA, as reason for loading CGA-compatible palette on EGA - to be able to connect CGA monitor to it. And, I guess, it just isn't possible in case of SVGA video card. Or possible? I don't know much about hybrid EGA/VGA cards, such as EGA Wonder. As I know, EGA and VGA modes were mutually exclusive on such video cards.

And even more - it's more about IBM treating EGA 200-lines modes are purely CGA ones. Nothing would break, if EGA-compatible palette would be loaded with bits 3 and 5 set (with dark yellow instead of brown of course), as CGA just don't have corresponding pins and EGA would simply ignore them in 200-lines modes. Such palette is also VGA 16-color DAC mode compatible. As all 3 intensity bits are equal, nothing would change, if VGA would ignore bits 4 and 5.

P.S. Do you have plans to standard VGA mode listing via VBE, as QEMU does? QEMU provides wrong info about some modes though. Mono modes are actually 2bpp and video memory window should be 32Kb in case of text modes.

P.P.S. Were 4bpp packed pixel modes actually possible on real standard VGA hardware? Sequencer sends data to attribute controller at 4bits/pixel clock rate. It's the same, as for 4bpp plane modes. I.e. if 256-colors mode would be disabled in attribute controller - each 4 bits would be treated as 16 colors.

**Comment by joncampbell123** [comment]
I mean that the 200-line EGA modes on EGA hardware the attribute controller maps like CGA style RGBI. That includes the CGA video modes emulated by the EGA.

EGA cards apparently allow you to configure via dip switches that all modes are 200-line (making text 8x8 and disabling the 640x350 mode), which would make all modes then CGA RGBI style modes. I was once sent an IBM-made game that relied on that to use a custom 8x8 font for "graphics" in text mode. DOSBox-X emulates that when machine=ega200. There's also a configuration that makes all modes 640x350 (or not at all) monochrome for people with MDA monitors which even DOSBox-X doesn't emulate.

The 4bpp packed mode was NOT part of EGA/VGA hardware. It's an SVGA feature that some chipsets, specifically S3 and Chips & Tech, had. Instead of 4 bitplanes, it's 4 bits per pixel packed together. They appear in the VESA BIOS enumeration. DOSBox-X's emulation is based on the 4bpp packed mode I observed on a Toshiba Libretto latpop (the VHS-sized one) with a Chips & Tech SVGA BIOS that offers it. There's even Windows 3.1/95 S3 and C&T drivers that use the 4bpp packed mode. I had to add it for S3 emulation because the Windows 95 drivers when you select 800x600 4-color or higher use the 4bpp packed, not planar, modes by default. Windows 98 dropped support for it though apparently and won't let you use it.

On most cards I've dealt with, they will faithfully emulate the EGA/VGA planar and palette mapping via AC/DAC that the original VGA does. However, once you go beyond that into SVGA modes, most cards start skipping or omitting some of the classic EGA/VGA functions. 256-color modes still typically respond to the traditional VGA palette registers, but the complex logic that makes planar access possible tends to disappear in SVGA modes and it's possible the Attribute Controller palette would no longer have any effect. SVGA modes are where tricks like unchained 256-color mode often stop working.

It's possible that the EGA palette INT 10h function you're using would cause just as much trouble on real hardware 4bpp packed as it would DOSBox-X. If you're programming 4bpp packed you're better off programming the VGA palette instead.

Text modes where the video memory is at segment B800h should be listed as 32KB windows. Are they not? That is something DOSBox-X should correct.

Monochrome modes are 1 bitplane, 1 bit per pixel. That's what makes them monochrome. Where are you getting 2bpp? The only video mode that should be 2bpp is the CGA 320x200 4-color mode and that would be 2bpp, 1 bitplane (never mind that EGA/VGA actually maps it across bitplanes 0+1 using the same odd/even mode as text mode).

By the way, playing with registers on the MCGA, there is almost a 4bpp packed mode as well, but probably as a quirk to how the hardware works and it only gives you 4bpp packed every even column on the screen.

**Comment by joncampbell123** [comment]
Final question: Do you make binary builds of your graphics library + demo? I have real DOS/Windows 9x hardware I can run it on to show you how it works on real hardware.

A sister project to DOSBox-X, DOSLIB, here on Github, exists with lots of various DOS code to run in both DOSBox-X and real hardware for that reason, and it's how many improvements to DOSBox-X were made.

**Comment by joncampbell123** [comment]
There is technically one way to get 4bpp on VGA, but you basically have to hack 256-color mode by switching off the bit that holds the DAC every other pixel. But then it's 4bpp made up of both the 256-color normal pixel and an intermediate 256-color value that's a 4-bit shift of the previous pixel and current pixel.

I suppose if you program the palette just right, you could control the color of the intermediate shift state and make what looks like a 4bpp packed 640x200 graphics mode.

As a reference, there's a "Megazeux mode" in DOSBox-X in reference to a game engine that on specific SVGA chipsets also abuses that bit in text mode to make a sort of 256-color text mode graphics mode.

**Comment by joncampbell123** [comment]
https://github.com/MrMadguy64/Engine/releases/tag/v0.69

No, you don't switch off 256-color mode. What you do is switch off another bit related to 256-color mode that tells the DAC to latch only every other pixel to hide the intermediate 4-bit shifted 8-bit values. If you turn that off, you get a 640x200 256-color mode where the odd columns of pixels are a mix of 4 bits from one byte and 4 bits from the next byte. Sounds useless, but theoretically you might be able to set the color palette in just the right way to make it a sort of 4bpp 640x200 mode.

**Comment by MrMadguy64** [comment]
> It's possible that the EGA palette INT 10h function you're using would cause just as much trouble on real hardware 4bpp packed as it would DOSBox-X. If you're programming 4bpp packed you're better off programming the VGA palette instead.

I did exactly this via adding "VGA only" compatibility BIOS mode. Problem is - I can't rely on specific attribute controller settings. It would be nice, if all video modes would be configured the same way. But 4bpp packed pixel modes are the greatest example that it may not be the case. And I can't even load universal palette either. Because there is collision between CGA light red and EGA's brown. It's the greatest example of hardware developers only making extra problems for themselves. If they would just use the same 0x0x-(0x38+x) palette in all EGA modes - we wouldn't have all that problems. This palette is truly universal. CGA ignores bits 3 and 5. VGA 16-color DAC mode is also supported.

So there are 3 ways for me to solver this problem:
1) Make driver for every specific video card
2) Make option to load specific DAC palette for any possible attribute controller configuration: CGA, EGA, VGA 16 colors, etc.
3) Allow user to simply disable palette loading and use standard palette instead, that isn't that bad.

**Comment by joncampbell123** [comment]
"Mode 0x07 and mode 0x0F are actually 2bpp modes"

What?? The MDA **connector** has 2 video signals. The video RAM seen by the CPU is still the same <char> <attribute> format that CGA uses, even if they're mapped to mono + intensity.

By that logic, you could claim EGA 640x350 mode is 6bpp because all 6 pins are used to carry the RRGGBB to the monitor!

And what would the bpp be for, say, a laptop where all video modes (VGA or not) are sent to the LCD panel as 640x480 5:5:5 RGB with dithering as laptops from the mid 1990s probably do?

As I understand it the VESA BIOS enumeration is supposed to reflect how the CPU sees the video memory, not how it's sent through the connector to the monitor!

Would it help if I were to write little video mode "demos" for various video modes for developers such as yourself to build on?

**Comment by joncampbell123** [comment]
One demo your game engine might appreciate is how to do CGA graphics modes on EGA/VGA, but with the memory interleave turned off, for example. I've been thinking about that trick for awhile.

**Comment by joncampbell123** [comment]
Even if QEMU reports standard VGA modes in VESA BIOS enumeration, it is uncommon at least from anything I've ever programmed for real SVGA BIOSes to do that.

**Comment by joncampbell123** [comment]
Are you thinking of Mode-X, which is supposed to be a tweaked 320x240 256-color mode? Or Mode-X (really Mode-Y) where you unchain 256-color mode and program it using the same planar logic as 16-color modes in order to access the full 256KB of VGA RAM?

As a side effect, the unchained mode makes it possible to write 4 pixels in one CPU write, because planar logic.

**Comment by joncampbell123** [comment]
One more thing. Unless you are programming EGA modes on an EGA, you might be better off leaving the Attribute Controller palette alone and focusing only on the VGA palette. Most EGA/VGA/SVGA BIOSes set up the Attribute Controller palette properly for you. Only EGA cards will need you to program the palette through the AC. For SVGA modes, including 4bpp packed, you are definitely best off not even touching the AC registers.

**Comment by joncampbell123** [comment]
One more thing. If you want to study the VGA register contents of some common chipsets, I have published on my Hackipedia site some register snapshots of some of my DOS machines. See if these help. http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/VGA%20register%20snapshots

**Comment by MrMadguy64** [comment]
> One more thing. Unless you are programming EGA modes on an EGA, you might be better off leaving the Attribute Controller palette alone and focusing only on the VGA palette. Most EGA/VGA/SVGA BIOSes set up the Attribute Controller palette properly for you. Only EGA cards will need you to program the palette through the AC. For SVGA modes, including 4bpp packed, you are definitely best off not even touching the AC registers.

That's exactly my problem. I can't be sure, how attribute controller is programmed. There are 3 possibilities:
1) CGA palette: 0x00..0x07,0x10..0x17
2) EGA palette: 0x00..0x07, 0x38..0x3F, 0x06=0x14 (collision with CGA)
3) VGA 16 colors: 0x00..0x0F. I accidentally programmed only first 16 DAC entries in v0.67 and v0.68, but all of a sudden everything worked in all modes. My only guess - VGA 16 colors DAC mode is used there.

And DAC should be programmed differently for all 3. Universal palette would be possible, if EGA brown wouldn't have collision with CGA. I.e. 0x08+x=0x10+x=0x38+x.

I'm not sure, what to do. VBE should have allowed programmers to avoid lots of options, but, I guess, I will need to add "What palette to load to DAC" option. For now I just want to disable palette changing, because EGA brown isn't that bad.

**Comment by joncampbell123** [comment]
This is the program I used to make those register snapshots. It's pretty simple. It won't capture anything not visible in the base VGA registers. https://github.com/joncampbell123/doslib/blob/master/hw/vga/tmodeset.c#L319

**Comment by joncampbell123** [comment]
Think of it this way: The card decodes a value from memory into a 4-bit value. It uses the 4-bit value as an index into the Attribute Controller "palette" to get a 6-bit value. The 6-bit value determines what goes out to the monitor.

How that 4-bit value is determined from memory contents of course depends on the video mode.

On the EGA, those 6 bits go to the 6 output pins on the connector, which are either 200-line RGBI and two ignored bits, or 350-line RRGGBB. Just not exactly in that order.

On the VGA, those 6 bits become an index into the VGA palette. This is why if you reprogram the VGA palette in text or EGA modes you have to change VGA palette indexes 0x00-0x07 and 0x38-0x3F.

That's really the basic idea.

**Comment by joncampbell123** [comment]
Of course the 4-bit value is modified according to various bitplane enable registers along the way, and the 6-bit value can be combined with additional VGA registers to make an 8-bit value.

Also 256-color mode is weird in that it's set up like a 640-wide value, and the 8-bit value read from memory is shifted in 4 bits at a time. It actually is affected by the AC, 4 bits at a time, and you can do a weird remap of 256-color mode that way.

**Comment by joncampbell123** [comment]
How that 4-bit value is made determines the video mode.

Text mode: As each pixel is draw from the character bitmap it's drawing, the bit selects whether the foreground or background color is chosen from the attribute byte.

CGA graphics: 640x200 monochrome is just 1 bit clocked out per pixel. It's really EGA 640x200 16-color mode but all but the first bitplane is switched off. 320x200 4-color mode uses a bit that tells the card to gather 2 bits instead of 1 to make 4-color mode.

EGA/VGA 16-color: 1 bit from each bitplane is clocked in to make a 4-bit value, 4-bit value goes through AC.

MCGA 640x480 monochrome graphics: 1 bit per pixel. It's really 640x480 16-color mode with only the first bitplane enabled.

VGA 256-color mode: One byte is read from all 4 bitplanes. They're then emitted as 4 pixels, in order of bitplane 0-3. They're shifted in 4 bits at a time to an 8-bit register which is why that bit is necessary to hold the DAC output to hide the intermediate states. VGA 256-color mode pretends to be a linear framebuffer by mapping CPU reads and writes such that the low 2 bits of the address determine the bitplane and the rest the byte offset in planar memory. Which is why when you "unchain" 256-color mode by changing memory access to planar, you can read/write 4 pixels at a time, but more importantly, it lets you access the full 256KB of VGA RAM.

SVGA modes tend to bypass the EGA/VGA compatible memory mapping and functions.

**Comment by joncampbell123** [comment]
Now based on experience, I get why text modes are technically 2 bitplanes, including MDA. On the EGA/VGA, the MDA/CGA text mode memory map is emulated by using Odd/Even mode to map the character to bitplane 0, and attribute to bitplane 1. Fine, that does count as 2 bitplanes. Except there's a 3rd bitplane that is also used by text mode. That third bitplane is where the character RAM is stored that makes text mode possible.

If you've ever written your own code to change the "font" of the DOS prompt... the way you do it is change the registers to turn off odd/even mode temporarily and then enable writing to bitplane 2 so you can write the character RAM through 0xB8000-0xBFFFF. Then put the registers back so normal text mode can work.

**Comment by joncampbell123** [comment]
There is a program in DOSLIB that can show you the video modes enumerated by the VESA BIOS.

Perhaps it would help if I were to make a version of this program that just straight dumps the modes to a TXT file and I could publish the VBE mode dumps on Hackipedia as well.

Not one of my DOS machine ever enumerates the standard VGA modes.

Maybe you can query the modes through VBE, I've never tried, but they don't show up in enumeration.

https://github.com/joncampbell123/doslib/blob/master/hw/vesa/test.c

**Comment by joncampbell123** [comment]
"Mode X" and "Mode Y" are standard well known tweaks to VGA 256-color mode that has been in common use since the early 1990s. It adjusts registers to change how CPU access works with 256-color mode using registers that are standard across all VGA cards. 320x240 256-color mode is an additional tweak where you setup 256-color mode and then program CRTC timings from 640x480 16-color mode, basically. They chose that as a way to maximize compatibility with the original fixed frequency VGA monitors of the time.

In both modes, the registers are altered to switch CPU memory access back into the planar memory I/O of 16-color, primarily because normal chained 256-color mode limits you to only 64KB of video memory which is not enough for 320x240 mode or if you need to do page flipping like DOOM/Wolf3D does.

**Comment by MrMadguy64** [comment]
> There is a program in DOSLIB that can show you the video modes enumerated by the VESA BIOS.
> 
> Perhaps it would help if I were to make a version of this program that just straight dumps the modes to a TXT file and I could publish the VBE mode dumps on Hackipedia as well.
> 
> Not one of my DOS machine ever enumerates the standard VGA modes.
> 
> Maybe you can query the standard VGA modes through VBE, I've never tried, but they don't show up in enumeration.
> 
> In the same way that mode 0x81FF, which is supposed to be a "mode" you can save/restore SVGA RAM with, is also not enumerated.
> 
> https://github.com/joncampbell123/doslib/blob/master/hw/vesa/test.c

Many thanks.

I guess, we have miscommunication. I don't ask newbie questions. If you would read my project's main page, you would notice, that I've already implemented almost all MDA, Hecules, CGA, EGA and VGA modes. Both standard and non-standard. Except may be some exotic hardware, such as PCjr/Tandy, that can be only emulated, because it's actually XT hardware and therefore my application wouldn't run on it. Like odd-even line 2bpp modes for example. And except some non-standard modes, that require non-standard monitor timings. I just can't verify them.

But SVGA hardware - is new challenge for me. The biggest problem - nothing is standard, i.e. anything can happen. VBE was intended to make things more clear, but opposite happened. Each vendor treating standard it's way made it very hard to distinguish specific video modes. VBE function 4F01h returns some set of mode parameters and they should be enough for application to find demanded mode. It's hard to do it, if some information is inconsistent. And overall you've answered my initial question. Answer is - I should be ready for everything.

P.S. Mono modes are 2bpp, because there are 4 colors possible there. Yeah, for you memory layout may be more important. But for me bpp is about distinguishing one pixel format from another. There should be some way for me to distinguish 640x350x1 from 640x350xMono. If both would be reported as 1bpp, how would I pick right renderers for them?

**Comment by MrMadguy64** [comment]
Question answered.

**Comment by johnnovak** [comment]
@joncampbell123 There's so much arcane knowledge you've shared here, you should write a book 😄 Or at least just dump these comments into a document somewhere. I mean, all this arcane info currently only exists in your head and it would be invaluable for DOSBox development in the future, so it's hard to find it in random GitHub posts.

I know we would benefit from it greatly. We rarely touch the vide emulation code because it's a monster and we lack the years of hand-on experience gained by reverse engineering actual hardware that you have.
