### ISSUE TITLE
PC-98: Dosbox logo is shown running some 200-line mode games

### ISSUE THREAD

**Issue by leonier** [joncampbell123/dosbox-x#529]
For example, 
Thexder:
![thex0](https://user-images.githubusercontent.com/6635408/36595321-a43df640-1899-11e8-82dc-005943e11c34.png)
Tetris:
![tet0](https://user-images.githubusercontent.com/6635408/36595328-ab739e74-1899-11e8-8904-69e9c5a79273.png)

I thought the logo displayed in PC-98 BIOS POST screen is not cleared from VRAM after successfully booting.
About these two games there are more problems such as "Packed file is corrupt" without running LOADFIX, not recognizing sound board, wrong colors, etc. However I don't think those problems could be easily fixed.

**Comment by leonier** [comment]
I made a quick and dirty fix to this issue. Here is the patch:
[clear_pc98_logo.zip](https://github.com/joncampbell123/dosbox-x/files/1751868/clear_pc98_logo.zip)

**Comment by joncampbell123** [comment]
DOSBox-X's BIOS does not clear the 4th bitplane, correct.

So games that use only the 8-color modes will be affected. That's easy to fix.

**Comment by joncampbell123** [comment]
However, the 8-color modes are not supposed to show the 4th bitplane, unless you switch the hardware to the analog mode to get the 16-color palette. Traditional PC-98 games I understand should leave bit set to the 8-color digital RGB mode.

The last time I pulled out a PC-98 laptop and poked at it with DEBUG.COM I noticed that the 8-color digital mode disables access to RAM at E000:0000 and switches the display to map from the digital color palette, which then also ignores the 4th bitplane.

Yet switching on the 16-color analog mode immediately maps memory to E000:0000 and the display begins showing the 4th bitplane.

So really, the fix is that the BIOS needs to show it's logo in 16-color mode then restore the 8-color digital mode and clear VRAM there afterward.

**Comment by joncampbell123** [comment]
Done. Try the latest commit.

**Comment by leonier** [comment]
So the problem with Thexder's wrong color is that PC-98 should boot into digital 8-colors mode and Dosbox-X switched to 16-colors analog mode displaying its logo?

**Comment by joncampbell123** [comment]
Exactly. The latest commit fixes that by switching back to 8-colors mode after the logo.

**Comment by leonier** [comment]
By the way I fixed Thexder's GAME ARTS logo by implementing INT 18H AH=43H.
```
		case 0x43:    //Palette register settings? Only works in digital mode?
		{
			unsigned int gbcpc = SegValue(ds)*0x10 + reg_bx;
			for(int i=0;i<4;i++)
			{
				unsigned char p=mem_readb(gbcpc+4+i);
				pc98_set_digpal_entry(7-2*i, p&0xF);
				pc98_set_digpal_entry(6-2*i, p>>4);
			}
			LOG_MSG("PC-98 INT 18 AH=43h CX=0x%04X DS=0x%04X", reg_cx, SegValue(ds));
			break;
		}
```
