### ISSUE TITLE
PC-98: DOS CLS command not working

### ISSUE THREAD

**Issue by leonier** [joncampbell123/dosbox-x#531]
The title described everything.
![cls](https://user-images.githubusercontent.com/6635408/36608274-47114b2a-18c1-11e8-99d4-8d191833c94b.png)

**Comment by joncampbell123** [comment]
That makes sense. CLS as implemented still tries to use IBM PC INT 10 to clear the screen.

**Comment by joncampbell123** [comment]
I need to figure out how CLS clears the screen.

I have two guesses:
- It might use a BIOS call, which seems unlikely considering that teletype and console management is entirely the domain of MS-DOS and that the BIOS is generally not involved.
- It might use ANSI codes, which seems more likely since NEC's version of MS-DOS seems to have ANSI escape code interpretation built-in.

Since CLS is apparently a command built into the command interpreter, I'm going to have to figure this out by running NEC's COMMAND.COM in DOSBox-X somehow.

**Comment by joncampbell123** [comment]
I got a COMMAND.COM copied off a PC-98 install of Windows 98 SE to run in DOSBox-X's environment.

VER SET 7 10
COMMAND.COM

Typing CLS from NEC's COMMAND.COM works in DOSBox-X, which suggests ANSI escape codes so far. If it was BIOS calls the CLS command wouldn't work.

**Comment by joncampbell123** [comment]
Logging MS-DOS console output shows that CLS emits \<ESC\>[2J which is the "clear screen" command. Therefore, ANSI codes, and therefore doable by DOSBox-X.

http://ascii-table.com/ansi-escape-sequences.php

**Comment by joncampbell123** [comment]
DONE

**Comment by emendelson** [comment]
For what it's worth, when I was creating my own text modes (43 lines, etc., using the standard VGA font), for a project based on SVN, one of the DOSBox authors gave me a CLS that does exactly what this new one does.
