### ISSUE TITLE
How to change mouse size in Dosbox-X

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#5322]
### Question

How to change mouse size in Dosbox-X

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by the-burrito-triangle** [comment]
Could you elaborate? Are you running DOS, or a Windows VM? Are you on Linux or Windows host OS?

If running a DOS game or a Windows guest in DBX, then set the output to openglpp and configure windowresolution to an integer multiple of the desktop resolution: if 640x480, then try 1280x960 for 2x or 2560x1920 for 3x scaling. A Windows guest will also have its own cursor and text scaling options, if needed, as well.

If the above is not what you want... then you will have to better explain what you are trying to achieve.

**Comment by Arthur3032** [comment]
In Doxbox-X, execute DOS
The host is Window Server 2019
output=ttf
Desktop resolution is: 2560x1920
Please tell me how to zoom 3x

**Comment by the-burrito-triangle** [comment]
Well, output=ttf is for scaling text mode programs (if I'm not mistaken). And I guess better looking font type. Anyways, that sounds like the problem here. You will need to use output=openglpp for integer scaling or use fractional scaling / stretching with output=opengl or output=direct3d.

If using DBX in windowed mode, and you know the native resolution of the program or DOS environment, you can open the dosbox-x.conf file and set windowresolution to an integer multiple of that--or however large you want (for fractional scaling). The DOSBox-X menu can interfere with openglpp integer scaling, but hiding it by pressing [F11]+[Esc] will fix that.

If using full-screen mode, openglpp will automatically scale as large as possible while keeping the original aspect ratio. For the other output settings, you will need to play around with the "Video" options in the main menu: "Aspect ratio", "Fit to aspect ratio", and possibly "Force scaler" and "Scaler" to get it to look right. Some of these affect the windowed mode too, mainly for opengl and direct3d output and manually resizing the window.

**Comment by Arthur3032** [comment]
I understand.
But I prefer output=ttf, it has a beautiful font.
Although it cannot adjust the mouse size, and cannot use the mouse to change the window size.
Thank you very much.

**Comment by the-burrito-triangle** [comment]
I think you bring up a good point about the the output=ttl option: For DOS programs that do slightly more than just text, the cursor or other non-text based elements won't scale in proportion to the text. A hybrid of openglpp and ttf options would fix this.

I would open a feature request to see if Jon (or another contributor) would be interested in implementing it. You should upload a few screen shots to show the discrepancy and help argue your use case. I think it would be a good feature to have.

But, before doing that, you should mark this question as "closed" first.

**Comment by Arthur3032** [comment]
> I think you bring up a good point about the the output=ttf option: For DOS programs that do slightly more than just text, the cursor or other non-text based elements won't scale in proportion to the text. A hybrid of openglpp and ttf options would fix this.
> 
> I would open a feature request to see if Jon (or another contributor) would be interested in implementing it. You should upload a few screen shots to show the discrepancy and help argue your use case. I think it would be a good feature to have (if it is actually possible to implement).
> 
> But, before doing that, you should mark this question as "closed" first.

Understood, thank you!
