### ISSUE TITLE
What is memory file?

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#5347]
### Question

Sorry if the question seems silly, but this memory file thing is unknown to me, even though I have used a PC for many several years. What is a memory file, how do I create them, and where will I be able to find them afterwards? Doing research doesn't make me any wiser.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
In the same section as memsize, set "memory file" to the name of a file and DOSBox-X will create the file if it does not exist, and re-use it if it does exist.

I like to use "memory file=memory.bin". When you run the emulator, a file named memory.bin will appear and all guest memory will appear in that file.

Instead of allocating from memory, it creates a file on disk and uses memory mapping instead.

Since DOSBox-X now allows up to 1TB of memory for the guest, it is safer to memory map a memory file than risk possibly grinding the host system to a halt allocating up to that amount of memory.

**Comment by joncampbell123** [comment]
Because the file is created sparse, it also lets DOSBox-X emulate that much memory without a long startup delay zeroing out that much memory.

**Comment by joncampbell123** [comment]
You don't need to prepare anything about the file. This is not a Linux swap file that must be pre-formatted as such, for example.
