### ISSUE TITLE
Dune 2 v1.20

### ISSUE THREAD

**Issue by Munin-** [joncampbell123/dosbox-x#554]
· dosbox-x 0.82.3: setup/install work but game crashes immediately with illegal opcode

· works in emucr build of DOSBox ECE SVN r4074

**Comment by joncampbell123** [comment]
I recently fixed a bug where the XMS driver emulation copied extended memory without enabling the A20 gate (with disastrous results).

I originally fixed the bug because it also caused Windows 3.1 to crash, both when you start Windows 3.1 and when you run SETUP.EXE to install it.

I see Dune II runs in real mode, which may be the same problem. Please try the latest release. If you can compile from source, please compile from the latest commit in master.

**Comment by joncampbell123** [comment]
![dune2_000](https://user-images.githubusercontent.com/6245486/36700740-94e8e1be-1b05-11e8-9de1-a96d318cdad2.png)

**Comment by joncampbell123** [comment]
I'm able to run this with core=normal.

Were you using core=dynamic?

**Comment by joncampbell123** [comment]
Please respond by April 1st or I will close this issue and move on.

**Comment by Munin-** [comment]
Sorry, for the late reply but the phone line is acting up again, causing the router to neither have a phone nor Internet connection most of the time.

<<
I'm able to run this with core=normal.

Were you using core=dynamic?
>>
No, the default; core=auto.

Will try all your suggestions and report back, and thanks a lot for your quick responses!
(I don't have a compiler on the notebook, so compiling the sources myself is currently not possible)

**Comment by Munin-** [comment]
With 0.82.4 the game runs fine now with both core=normal and core=auto.

**Comment by heydojo** [comment]
@joncampbell123 please close this. It works fine for me too.
