### ISSUE TITLE
Warcraft 2: Tides of Darkness + Beyond the Dark Portal v1.50

### ISSUE THREAD

**Issue by Munin-** [joncampbell123/dosbox-x#558]
· dosbox-x 0.82.3: setup and game crash with illegal opcode

· works in emucr build of DOSBox ECE SVN r4074

**Comment by goq** [comment]
Confirm. Cannot even install from original cd.
Console ouput:
`LOG:   29651420 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:   29651475 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1687
LOG:   29651498 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG: DOSBox switched to max cycles, because of the setting: cycles=auto. If the game runs too fast try a fixed cycles amount in DOSBox's options.
LOG:   29663271 ERROR BIOS:INT15:Unknown call ax=BF01
LOG:  189053580 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4A10`

**Comment by goq** [comment]
Found something interesting.
INT 2F 0x1687 is DOS Protected-Mode Interface - INSTALLATION CHECK
(not released in dos_misc.cpp)
http://www.oldlinux.org/Linux.old/docs/interrupts/int-html/rb-4621.htm

INT 15 0xBFDE is DESQview/X - DVDOS4GX.DVR - INSTALLATION CHECK
(not released in bios.cpp)
http://www.oldlinux.org/Linux.old/docs/interrupts/int-html/rb-1567.htm

I think that this is due to dos4gw issue, but I don't have enough experience to solve this problem

**Comment by Munin-** [comment]
using 0.82.4 the emulator closes without an error message

**Comment by goq** [comment]
If you execute a "cwsdpmi.exe", the installation process of warcraft 2 tides of darkness (from original CD) terminates with an error:
DOS/4GW Professional error (2001): exception 0Eh (page fault) at 1F7:FFFF024D
TSF32: prev_tsf32 6B20

I can repeat and write full log if needed

**Comment by Allofich** [comment]
I just tried to test this, not with a full version but with the shareware from here:
https://archive.org/details/WarcraftIiTidesOfDarknessDemo

`setup.exe` and `install.exe` (which executes `setup.exe`) both crashed. After executing, DOSBox-X log shows the following errors (same errors for both `setup.exe` and `install.exe`):

```
  ERROR BIOS:INT15:Unknown call ax=BFDE
  ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1687
  ERROR BIOS:INT15:Unknown call ax=BFDE
  ERROR BIOS:INT15:Unknown call ax=BF01
  BIOS:INT15:Function 0x88 Remaining 0000 kb
  ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4A10
  ERROR CPU:CPU:66:GRP5:Illegal call  7
  CPU:Illegal/Unhandled opcode FFFF
```
and then the DOS console shows
```
DOS CON: Loading.....DOS/4GW Professional error (2001): exception 06h (invalid opcode) at 180:02420240
DOS CON: TSF32: prev_tsf32 6B14
DOS CON: SS       188 DS       188 ES       188 FS         0 GS        20
DOS CON: EAX      200 EBX  23F023E ECX  23D0239 EDX  2350234
DOS CON: ESI  2300250 EDI  22B022A EBP   24D7DC ESP   24D640
DOS CON: CS:IP  180:02420240 ID 06 COD      200 FLG   200206
DOS CON: CS=  180, USE32, page granular, limit FFFFFFFF, base        0, acc CF9A
DOS CON: SS=  188, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
DOS CON: DS=  188, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
DOS CON: ES=  188, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
DOS CON: FS=    0, USE16, byte granular, limit        0, base       16, acc  0
DOS CON: GS=   20, USE16, byte granular, limit     FFFF, base     3080, acc 93
DOS CON: CR0: PG:0 ET:1 TS:0 EM:0 MP:0 PE:1   CR2: 0 CR3: 0
```

Since I can't get past this I can't test the actual game. The included `readme.txt` only lists Windows in the requirements for the scenario editor, not in the requirements for the game itself.

**Comment by Allofich** [comment]
> works in emucr build of DOSBox ECE SVN r4074

The shareware version's `install.exe` also launches (haven't tested whether it fully works) in DOSBox 0.74.

**Comment by Allofich** [comment]
The problem began with this commit: https://github.com/joncampbell123/dosbox-x/commit/2f47d9b8bc43c1ccd7a9a6a680d2f2933f1256d7

**Comment by joncampbell123** [comment]
Ah, that seems to be a fairly common failure mode for DOS games.

Too many VESA BIOS modes.

Try adding:

    [dosbox]
    vesa modelist cap=32

**Comment by joncampbell123** [comment]
You might try playing with these options to limit the VESA modelist:

vesa modelist width limit=0
vesa modelist height limit=0
allow low resolution vesa modes=true
allow 32bpp vesa modes=true
allow 24bpp vesa modes=true
allow 16bpp vesa modes=true
allow 15bpp vesa modes=true
allow 8bpp vesa modes=true
allow 4bpp vesa modes=true
allow 4bpp packed vesa modes=true
allow tty vesa modes=true

**Comment by Allofich** [comment]
`vesa modelist cap=32` allows the install program to start.

Looks like you already had a note about using this option with Warcraft 2. The description of the option says

```Warcraft II by Blizzard ................ Set to a value between 8 and 16. This game has a fixed buffer that it reads the modelist into. DOSBox-X's normal modelist is too long and the game will overrun the buffer and crash without this setting.```

**Comment by joncampbell123** [comment]
Good! Anything else before I close this issue?

**Comment by Allofich** [comment]
I'm fine, having modified my .conf file. Considering Warcraft II is such a major title, it does seem like maybe the default DOSBox-X configuration should be able to run it without a problem, or the VESA modelist could be dynamically limited if it was too large. But I don't know enough about this issue to say whether those are good or realistic options, so I'll leave it to you.
