### ISSUE TITLE
Can't generate dosbox.conf file [on Mac OS X]

### ISSUE THREAD

**Issue by forthrin** [joncampbell123/dosbox-x#573]
0.82.4 on macOS: Followed #126, but no `dosbox.conf`is generated in the current directory, nor anywhere else in my file system. I assume "current directory" means `$PWD` when running `dosbox-x`.

**Comment by joncampbell123** [comment]
It has to be generated somewhere.

Mac OS X is funny about what PWD is when you run it as an app.

**Comment by emendelson** [comment]
Apologies if this is obvious. I haven't built DOSBox-X under MacOS yet, but have you looked in:

/Users/YOURNAME/Library/Preferences/DOSBox-x 

or something similar?

**Comment by joncampbell123** [comment]
@emendelson Try using the ./build-debug script to compile, which should disable any attempt to compile against X11

**Comment by emendelson** [comment]
Thanks - but I also finally noticed that you have a prebuilt copy available for download. When I launched it and tried config -wc, and nothing got written. Will now try to build as you suggest.

**Comment by forthrin** [comment]
@emendelson: Nothing in `~/Library/Preferences/` or elsewhere. Even did `find / -mtime -15m` and `find / -iname '*dosbox*'`. However, DOSBox-X does *read* `dosbox.conf` if you manually copy it there:

```
cd
cp "Library/Preferences/DOSBox * Preferences" dosbox.conf
dosbox-x
```

**Comment by joncampbell123** [comment]
I just did a quick experiment.

I modded the main() function in DOSBox-X to print out argv[0] and the current working directory, then ran the compiled code as an app from the desktop.

Apparently, when a Mac OS X application is run from the desktop, the current working directory is "/".

So if you were root, DOSBox-X would have created a dosbox.conf at the root of your filesystem, but since you're not root, nothing was created.

Equally fun is that nothing I can find on the internet mentions this fact about the runtime environment of Mac OS X. Finding information on these apparently obscure facts is worse than looking up Windows APIs.

**Comment by joncampbell123** [comment]
It should work as you expect however, if you bring up the Terminal application and run it from the terminal.

**Comment by joncampbell123** [comment]
I just pushed a commit that changes the working directory to your $HOME directory if the current working directory was the root of the filesystem.

So if DOSBox-X is run from the Finder by double-clicking the icon, it will read and write configuration from the root of your home directory, which is more useful than doing nothing from the fileystem root!

**Comment by brunocastello** [comment]
> I just pushed a commit that changes the working directory to your $HOME directory if the current working directory was the root of the filesystem.
> 
> So if DOSBox-X is run from the Finder by double-clicking the icon, it will read and write configuration from the root of your home directory, which is more useful than doing nothing from the fileystem root!

I think that if they were in a folder in our home directory, would be great to use with Dropbox-like solutions. For example, I use symlinks in Dropbox to folders on my home directory, so when I go to my MacBook at work I have them, and when I am back at home on my "HackBook Pro" (just a friendly name for my Dell G7 running macOS) they are there too.

But, since now I use OneDrive, I have to have them on OneDrive folder. I might just put a symlink on my home directory to them. But my OCD freaks out when there are files cluttering my home directory...

**Comment by miroslavkoptik** [comment]
I am still struggling with this and I am unable to find solution anywhere. I have created dosbox.conf everywhere - in the home root, in the same folder as dosbox-x, in the preferences folder, nothing works. Any idea?

**Comment by sdsnatcher** [comment]
@miroslavkoptik 

What worked for me was to copy a sample dosbox.conf to my home folder, then boot dosbox-x. Only after this the conf -all -wc command started working fine.

**Comment by JuQiang** [comment]
The other solution, just press Cmd + Shift + . inside the folder "/Library/Preferences", then u can see lots of hidden files, also include "DOSBox 0.74-3-3 Preferences"

**Comment by DiegoAndresRa** [comment]
I did this to resolver the Problem 👍 

[https://github.com/DiegoAndresRa/Assembly_Configuration_MacOS]

I hope it works for you

**Comment by DiegoAndresRa** [comment]
I did this to solve  the problem

https://github.com/DiegoAndresRa/Assembly_Configuration_MacOS

I hope it works for you

**Comment by Apocaly-pse** [comment]
maybe you can see `/Applications/dosbox-x.app/Contents/Resources/dosbox-x.reference.conf`, copy and edit it, and then move it to `/Applications/dosbox-x.app/Contents/MacOS` path.
