### ISSUE TITLE
[cpu] cycles=max not working.

### ISSUE THREAD

**Issue by nemo838** [joncampbell123/dosbox-x#606]
[cpu] cycles=max not working.

bug reportring. :D

**Comment by joncampbell123** [comment]
Please clarify

**Comment by nemo838** [comment]
version = dosbox-x 0.82.4

in dosbox.conf
=======================
[cpu]
cycles=max       <- edited
=======================

dosbox-x running 3000 cyc/ms.

**Comment by nemo838** [comment]
i tried to run windows 95.
it needs cycles=max or max 105%
so i edited "cycled=auto" to "max"

**Comment by joncampbell123** [comment]
That's better.

Most of my testing with Windows 95 and later are usually done with fixed cycles counts and core=normal. I'll try it with cycles=max and see how it handles.

Generally, Windows 95 is going to be very slow in DOSBox-X because of the lack of dynamic core and the page fault handling needed to run it.

**Comment by joncampbell123** [comment]
cycles=auto seems to default to 3000 cycles, but if you adjust cycle count it seems to pick up to a reasonable speed.

**Comment by joncampbell123** [comment]
cycles=max also defaults to 3000, but again works fine if you adjust the cycles count up.
