### ISSUE TITLE
"KUKOO2" scrolling text and animation is a bit jumpy

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#66]
The scrolling text is slightly jumpy and if you single-frame-step during the demo it actually jumps backwards a little at times.

Will close as WONTFIX if the demo has the same problem on real hardware.

**Comment by wbcbz7** [comment]
AFAIK it is a bug in demo itself or it's related with horizontal pixel panning counter borrow from top field (scrolling checkerboard) to bottom (with kefrens bars\scroll\floor).
The demo sets pixel panning compatibility bit (attribute controller index 0x10 bit 5), so bottom field is not affected by horizontal pixel panning register, so it should not jump; also it does update screen position for top field by writing start address to CRTC regs before vertical retrace and pixel panning after it. Also scroll stuttering is definitely not caused by interrupts as demo disables them before entering to main part.
However sometimes it does even on real HW with some video cards. Don't remember exact results, but i.e. on Trident TVGA900C scroll is truly smooth, same for S3 Trio3D/2X (but due to the bug in video BIOS the right edge of screen is messed up); on Matrox Millennium and S3 ViRGE/DX (probably on earlier cards as well) scroll stutters.

P.S. sources are available: [https://files.scene.org/view/mirrors/hornet/code/demosrc/bbsintro/kuk2src.zip](url), so it is better to tweak them to find out the cause :)

**Comment by joncampbell123** [comment]
Personal experience says that, yes, any DOS demo that attempts to use wider than 320 pixels in 256-color VGA mode on S3 hardware will often have glitches on the right-hand screen. I remember my S3 Virge had a similar problem with Crystal Dream II back in the day.

I see in the source code that it does set bit 5 (pixel panning mode) so the screen after line compare stays still despite panning above it.

It only modifies panning once after vsync, and after writing 16 colors to the color palette. It's possible that the VGA card has already passed the point that it latches hpel on some cards. I also see that it uses a precomputed lookup table to program CRTC offset and hpel.

**Comment by joncampbell123** [comment]
Ah. Even though the demo is reading attribute controller register 0x10, and then writing it to set bit 5, somehow it's not actually setting bit 5.

I added debug code to vga_draw.cpp that forces bit 5 set, and scrolling on the bottom is smooth now.

That tells me where to look. Thanks!

**Comment by joncampbell123** [comment]
Fixed in commit 721f08f5b263d836ffe401bd214fb966eca71b0a
