### ISSUE TITLE
PC-98: Touhou games have faster game speed in 31-KHz mode

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#681]
I played TH4 in both 24-KHz and 31-KHz mode in Dosbox-X. 
in 24-KHz mode, from the beginning of stage 1 to the beginning of first mini-boss fight uses about 60 seconds; However it only uses about 48 seconds in 31-KHz mode. 

The music and sound had no differences. 
How about this on real PC-98s? if there is no speed difference between two video modes, this would indicate a bug.

**Comment by joncampbell123** [comment]
Touhou, even the Windows games, is said to be dependent on vertical refresh rate.

**Comment by yksoft1** [comment]
Seemed not only Touhou games run faster in Dosbox-X's 31-khz mode. A verification on real PC-98 is still necessary after all...

**Comment by joncampbell123** [comment]
I'll verify this later on a PC-9821 unit that I know comes up in 31khz mode by default.

I'm pretty sure that the game runs itself by the vertical refresh rate and that it doesn't have adjustments for either mode, but it's good to check.

I understand that the Windows versions of Touhou Project also use vertical refresh for timing. Some videos I've seen on YouTube claim to increase the challenge by setting the desktop refresh rate to 85Hz or faster so that everything runs faster.

**Comment by joncampbell123** [comment]
Hey, you're right.

Touhou Project appears to call INT 18h AH=31 once at startup. If that BIOS call reports a 31khz horizontal sync rate, the game slows sprite movement down to compensate.

Git pull the latest code and try it.

**Comment by yksoft1** [comment]
Tested the new INT 18H AH=31H code and seemed now TH games would add wait on 31-khz mode to keep the speed to 56fps.

**Comment by joncampbell123** [comment]
Certainly.

Looking at the vertical retrace handler and the way things move at 70Hz it seems like both Touhou and Rusty compensate by waiting an extra frame at the right intervals to slow 70Hz down to 56Hz.
