### ISSUE TITLE
FTBFS on Arch Linux (SDL 1.x)

### ISSUE THREAD

**Issue by heftig** [joncampbell123/dosbox-x#696]
The recent commit f4136db46bd731dcae1ecde76d46866835a0b39d refers to an `x11_sym` field that does not exist in SDL. The follow-up commit bd91e46c4f7cb4f231da3e1e3f12be8188500e2b elides the code for SDL2. However, the field does not exist in SDL1, either.

**Comment by joncampbell123** [comment]
DOSBox-X compiles now against it's own in-tree version of SDL 1.x, which has many modifications I've made to improve DOSBox-X and clean up the code. It does not use the system-wide SDL 1.x.

If you've already compiled DOSBox-X prior to the commit the old SDL header is still in effect if you git pull and compile.

You'll need to git pull, clean and reset --hard the Git repository, then compile the whole project again.

**Comment by joncampbell123** [comment]
DOSBox-X is however written to compile against the SDL2 library on your system.

**Comment by heftig** [comment]
> You'll need to git pull, clean and reset --hard the Git repository, then compile the whole project again.

I re-clone the repository on every build.

> DOSBox-X is however written to compile against the SDL2 library on your system.

Both SDL2 and SDL are installed. `configure` picks SDL by default unless `--enable-sdl2` is given explicitly.

> It does not use the system-wide SDL 1.x.

This is definitely wrong.

**Comment by heftig** [comment]
Anyway, I'd rather not use the SDL2 port as it's not feature complete (IPX support is missing).

**Comment by joncampbell123** [comment]
SDL 1.x seems to be deprecated, but a lot of DOSBox-X is written around it so I've been using the SDL library included in the source tree and I have been modifying it to fix various issues and improve DOSBox-X.

Off the top of my head, some of the changes are that I:
- Made SDL window management asynchronous (notice you can move/resize the window and use the menus without causing emulation to pause doing so)
- Made numerous fixes for foreign non-US keyboard layouts
- Fixed issues with display, fullscreen, and hacks in both Windows and Linux/X11
- Fixed issues with ALSA and PulseAudio in Linux
- Modified DOSBox-X and SDL to permit resizing the emulator window

Future plans:
- SDL 1.x menu API, so that the menus are portable instead of DOSBox-X loading a menu bar resource into the main window itself. I think the Windows menus would be far more usable if they were also available on Mac OS X and Linux.

A lot of the changes I've made to SDL 1.x are for a good reason. A lot of them have to do with DOSBox-X and usability. They're not likely to be accepted into the SDL 1.x library, as far as I understand.

**Comment by heftig** [comment]
The problem is that your patched SDL is not being used. `configure` always selects a SDL from the system, whether that is SDL1 or SDL2. If neither is installed, `configure` fails.

**Comment by heftig** [comment]
I found your `build` scripts. After some patching (use `bash -e`, don't override `MAKEFLAGS`, pass arguments through to `configure`, kill `RPATH`, build SDL_net) I think I have something workable now.

FTR, the proper way of building vendored libraries with autotools would be [subpackages](https://www.gnu.org/software/automake/manual/html_node/Subpackages.html#Subpackages).
