### ISSUE TITLE
About CMake, SDL2 and PC98

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#733]
I wanted to finalize the CMake list but have been encountering a few problems, since the branch is ~2000 commits behind master I've started (mostly) from scratch, with now the goal to push it as soon as possible so it doesn't rot in the repo as a couple of other things :)

The first thing is SDL2, does it builds without SDL1 ?

Edit: Apparently it does, the only thing is that headers were poorly referenced, i.e. ```sdl.h``` instead of ```SDL2/sdl.h```, a quick edit effectively removed all the errors (will know for sure once build succeeds)

The second thing is PC98 emulation,

I don't understand how the VS solution builds properly, since files such as `control.h` are not in the repo, I somehow copied it from the original emulator but it was until it shows that many others are missing.

So have you done anything special to the PC98 code brought over ?

Now regarding my new CMake, it's definitely much better:

 - stripped across many lists, the main list now only contains the principal stuff (600 lines removed)
 - it does use vcpkg and all dependencies are available through it
 - should allow to ditch that vs2015 folder once and for all

Why have you kept it (the solution), is it because for simplicity or are there some tricks involved in it ?

Is custom-SDL1 deprecated by now since SDL2 works well ?

Thanks

**Comment by joncampbell123** [comment]
I maintain the ability to compile with SDL2 but the custom SDL1 is still a major focus for me. Having the freedom to modify SDL 1.x as I see fit has allowed me to fix keyboard layout and graphical problems on Windows, Mac OS X, and Linux.

I like to keep the vs2015 folder so that people used to VS2015 have a way to compile DOSBox-X from source. I want to make sure that compiling from source is not very difficult.

I've added a lot to the PC-98 emulation over time, including cleanup and bug fixes.

I've cleaned up a lot of the code and fixed most of the compiler warnings, then I've added -Wall  -Wextra and -pedantic to reveal many other subtle bugs that might affect runtime.

I've updated the requirements for the code, and I've made it mandatory to compile with a C++ compiler that supports C++11.

I've replaced the Windows-only IDR_MENU resource with a C++ menu framework that allows the same menus to work on Windows, Mac OS X, and Linux. For Mac OS X menus, a new *.mm Objective C++ file was added. For Linux, menus are drawn by DOSBox-X itself on the SDL surface, or with OpenGL quads and a font texture if the output is set to OpenGL. For SDL2 builds, the SDL drawn menus are the only option. Since SDL2 is actively maintained, I will not be hacking up the SDL2 source code the way I have hacked up SDL1.

Part of the menu work is that some of the menu items are automatically tied to mapper shortcuts. The menu items will automatically show whatever key binding you've assigned through the mapper, so there's no problem with misleading shortcut text if you've changed any mapper bindings from the default.

To clean up the mess of keyboard shortcuts, a "host key" modifier was added (inspired by VirtualBox) and most of the shortcuts were changed to work from that host key, or were automatically given no binding. I also fixed the "hold" modifier, which I understand was a long-standing issue with DOSBox.

I have been maintaining the ability to compile with MinGW on Windows instead of VS2015/VS2017 as well. The code has been updated so that MinGW builds are almost equivalent in function to what VS2017 can provide including Direct3D9 output support. At the request of @yksoft1 I also maintain a build mode where using an older MinGW toolchain it is possible to compile to run under MS-DOS and the HX DOS extender (HXGUI) and the code contains support for that (SDL1 only).

I personally do not use CMake, but you're welcome to commit changes to the master branch to add CMake files for those who would rather compile with CMake instead of GNU autoconf or VS2015.

**Comment by aybe** [comment]
Had to get my hands really dirty, but now it builds, basically not all the PC98 files were included in vs2015.

In regards to your additions to SDL1, does that mean SDL2 is not able to achieve the same level of features ?

You've done an amazing job to say the least, don't understand much of it but it's neat ! The new menu approach is definitely the right way and building under DOS is just stellar !!!

CMake rocks in the sense that whatever changes you do on it are available to all of its platform generators, if say you update a CMakeLists by adding new files, you simply rebuild the CMake-provided ZERO_CHECK project and the VS solution asks to be reloaded. I will see if I can come up with SDL1 support for it but can't make any promises as it's still really vague to me (just as Linux is, too btw).

In regards to pre-VS2017 support, it's definitely able to target XP as I've shown before:

[installation of required component](https://github.com/joncampbell123/dosbox-x/issues/438)

[proof that indeed it works](https://github.com/joncampbell123/dosbox-x/issues/403)

i.e. VS2017 is free and can run on Windows 7, upgrade path is really easy

Here's the new CMake, simpler and friendlier:

[CMake: now using vcpkg for Windows (linux commented for now)](05ddb27f7b9b48ac38d3c0edd201a98d6ae4e53b)

[CMake: now using sublists for clarity](f0bd6254ce74c52d76043a1289102505718a7827)

There is still one error but the fix for it breaks the vs2017 version:

[dos_files.obj : error LNK2001: unresolved external symbol __nhandle
](https://github.com/joncampbell123/dosbox-x/issues/735)

_However_, just figured out that neither builds do run over-here, yours and mine :

[Neither the vs2017 or the CMake build do run properly](https://github.com/joncampbell123/dosbox-x/issues/736)

to be continued ...

**Comment by joncampbell123** [comment]
SDL2 will remain basic, yes. Much of the work on SDL 1.x is to incorporate menus and other needed functions into SDL 1.x so that I could get rid of many nasty hacks and workarounds that once existed in the DOSBox source code. Another important modification to SDL 1.x is the "async window" hack so that emulation does not stop when you drag or resize the window or use the menus.

**Comment by aybe** [comment]
Alright, now what I'd like to understand is, why bother with SDL2 at all if SDL1 is the preferred version ? :)

**Comment by joncampbell123** [comment]
Some people would prefer to compile with SDL2, especially in cases SDL1 cannot support.

One user brought up Wayland in Linux, for example.

**Comment by aybe** [comment]
Ping !

**Comment by joncampbell123** [comment]
Yes?

**Comment by aybe** [comment]
Whoops, edited the top post in fact.
