### ISSUE TITLE
SDL drawn menubar in SDL 2 builds on Mac OS X responds to both mouse and touchpad (needs touch/mouse input filtering)

### ISSUE THREAD

**Issue by CNAmira** [joncampbell123/dosbox-x#734]
Menubar will response to my mouse movement even when I don't touch the menubar.
And whether menu I click, the first submenu will finally show up.

**Comment by joncampbell123** [comment]
Menu items are supposed to highlight when you hover over them. Clicking on them is supposed to bring down the menu on-screen.

This is true of any case where the host OS's menu system is not used, including SDL 1.x.

**Comment by CNAmira** [comment]
I've uploaded a screen record to show what it happened.
[rec.zip](https://github.com/joncampbell123/dosbox-x/files/2033768/rec.zip)

**Comment by joncampbell123** [comment]
Locate the SDL2 touchscreen code in the menu loop, comment it out, see if that helps.

Are you using the mouse or the touchscreen?

**Comment by CNAmira** [comment]
I use mouse.

发自我的 iPhone

**Comment by joncampbell123** [comment]
Is that an external mouse plugged in by USB, bluetooth, etc. or is this "mouse" input from a touchpad on a macbook?

I test the SDL2 code on Mac OS X on a Mac Mini, and I've never seen this problem before.

**Comment by CNAmira** [comment]
Oh, I know. If I use external mouse, it works correctly, otherwise I use touchpad it doesn't works well.

**Comment by joncampbell123** [comment]
SDL2 has a constant already defined for mouse events to distinguish mouse events from "mouse" events coming from the touchscreen, maybe there's an identifier it can use to tell whether a touch event is coming from the trackpad, and ignore it?

**Comment by CNAmira** [comment]
What if I use touchpad only?

**Comment by joncampbell123** [comment]
I think the problem is that when you move the mouse with the trackpad, SDL2 reports both the mouse input generated by Mac OS X from the trackpad IN ADDITION TO the touch events from the trackpad directly. Moving the mouse with the trackpad generates both mouse and touch events at the same time, apparently. That's the problem.

**Comment by joncampbell123** [comment]
:) I know.

Thinking about it a bit more, I think it's because I forgot to add the code that ignores mouse input if it registers that a finger is down on the touch device.

But, that would make it difficult to operate the menus from the Macbook's touchpad, so, somehow I will need some SDL2 wizardry to identify events from the touchpad vs events from the touchscreen.

**Comment by joncampbell123** [comment]
SDL2's API lets you query the number of fingers supported and touch devices total in the system, but I don't see anything that lets me ask "what do you call yourself" that would allow me to enumerate them and ask "hey, are you something called Macbook touchpad?"

**Comment by joncampbell123** [comment]
The other problem is that I do not have a Macbook or any portable Apple device I can test and develop this against.

**Comment by CNAmira** [comment]
I made builds of `76d0284b5ac8adbb70587edab5517ece7fe02850` and `fa1c0f9ef8157cf1dcea93b2aaaa2411f4ef51a1` with official SDL 2.0.9.
Neither of them works as expect yet.
[rec.mov.zip](https://github.com/joncampbell123/dosbox-x/files/2617683/rec.mov.zip)

**Comment by CNAmira** [comment]
Thanks for your works!
Should I close this issue?

**Comment by joncampbell123** [comment]
Sure, go ahead.
