### ISSUE TITLE
DOSBox-X sources are really scary to say the least

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#759]
I've been trying to find an analogy of what the current code base looks like, and Jabba just came to my mind:

![jabba_the_hutt_ 10585038414](https://user-images.githubusercontent.com/1537591/41388530-a077dbe4-6f8c-11e8-8865-a78567c7886a.jpg)

Whenever I try to (eventually) improve some of the DOSBox-X features, around 90% of my time is wasted, looking at my GPS trying to find where am I and ever looking for directions.

The biggest issue for me is about navigating the code base, no matter which file structure/outline utility you threw at it, it is just useless having huge scrollbars:

![2018-06-14 04_41_32-dosbox-x](https://user-images.githubusercontent.com/1537591/41388652-3de93e04-6f8d-11e8-8eb6-76253af87e55.png)

Coming from the C# world where things look like a clean room compared to C++, I'm still hoping for an ideal structure that would make it much easier to work against, e.g. one class per file for instance. I have been trying to do that on sdl_mapper.cpp but failed miserably because I didn't have the skills nor the patience for it.

Currently, only the owner and probably a few others in the world can find their way in an efficient manner in the sources.

Is this a concern and has a chance to be improved in the (not so near I guess) future ?

**Comment by joncampbell123** [comment]
I'm not fond of the one class per CPP scheme, but I do agree the codebase needs cleaning up.

I've been cleaning it up bit by bit over time, but there's still a lot of mess.

This mess is the reason I am stopping development personally to document the code and how it works.

Long term, I think it would be nice to construct a new emulator with a cleaner design than this. A lot of the codebase is a mix of C++ and plain C tricks. The render scalar code for example uses the old trick of header files including other header files with #defines per variation, when C++ template functions would help to clean things up a lot.

Since I've made C++11 the minimum standard for this codebase, there's plenty of cleanup that is possible.

**Comment by aybe** [comment]
When I have some free time, I'll take a look at trying to clean the smallest file for a first, then try to help out further.
