### ISSUE TITLE
PC-98: Borland conio.h text output functions not emulated correctly

### ISSUE THREAD

**Issue by nmlgc** [joncampbell123/dosbox-x#769]
Two issues here:
- The first character of a string is always printed into the function row.
- The cursor always moves to a new line after a `cputs()` call.

[Here's my test source code, with a binary and linker map](https://github.com/joncampbell123/dosbox-x/files/2109051/COLORBUG.zip), compiled using the Japanese version of `Turbo C++ Version 4.02 Copyright (c) 1994 Borland International`.

Correct output on Neko Project 21, and what you would expect from how the same binary behaves on IBM-compatibles:
![colorbug np21](https://user-images.githubusercontent.com/2139424/41508728-68d4098c-7249-11e8-83ac-e23a6eac466a.png)

Output on DOSBox-X:
![colorbug dosbox-x](https://user-images.githubusercontent.com/2139424/41508725-67f55ade-7249-11e8-876b-e4a14b1a993e.png)

I've narrowed down the first issue to `__NEC_WHEREXY` reading the wrong row value from `[0060:0110]`, but wouldn't know how to fix this properly and non-hacky.

**Comment by joncampbell123** [comment]
Ick...

This is why the DOS kernel in DOSBox-X is written to start the DOS kernel at segment 80h instead of 60h in PC-98 mode, so that fixed variables could be allocated between 60h and 7Fh. Apparently it is considered normal for PC-98 games to read state directly from DOS kernel memory. Case in point: Touhou Project won't clear the text layer properly unless it can read the number of text layer rows from a fixed address somewhere around 60:114 (I forget exactly).

**Comment by joncampbell123** [comment]
So to fix this, CON device emulation in PC-98 mode needs to mirror the cursor position at that address.

**Comment by joncampbell123** [comment]
Booting a real PC-98 DOS bootdisk, I see where the row and column are stored:

![pc98rowval](https://user-images.githubusercontent.com/6245486/41582001-3df46fba-7355-11e8-8031-ae50fc11b01d.png)

**Comment by joncampbell123** [comment]
I suppose it was time to move console emulation away from re-using IBM PC BIOS locations anyway...

I just pushed a commit that removes cursor position from 40:xx and puts it in segment 60:110-60:11C in the same way that normal DOS does it.

I don't think I broke anything, but it's best to double-check.

It does allow your program to print properly IF run when the cursor is at the bottom of the screen, and it allows the last line to appear otherwise.

Borland C is making unknown calls to INT DCh that I do not know how to emulate.

    LOG: PC-98 INT 1Ah unknown call AX=040F BX=3574 CX=0000 DX=3574 SI=356E DI=3580 DS=0306 ES=0306
    LOG: PC-98 INT DCh unknown call AX=0310 BX=0CA0 CX=3010 DX=1410 SI=356E DI=3580 DS=0306 ES=A000
    LOG: PC-98 INT DCh unknown call AX=0300 BX=0006 CX=3010 DX=1500 SI=356E DI=3580 DS=0306 ES=0000
    LOG: PC-98 INT DCh unknown call AX=0300 BX=0006 CX=3110 DX=1500 SI=356E DI=3580 DS=0306 ES=0000

**Comment by joncampbell123** [comment]
Argh, hold on, the ANSI cursor positioning code is messed up right now...

**Comment by joncampbell123** [comment]
Okay, try it now.

**Comment by joncampbell123** [comment]
I just fixed a silly bug in the ANSI emulation that might have caused this issue.

**Comment by joncampbell123** [comment]
Just checked the COLORBUG.COM file, still happens.

**Comment by joncampbell123** [comment]
The latest commit seems to be able to render COLORBUG.COM properly now.

**Comment by nmlgc** [comment]
Yup, this has been working for a while.
