### ISSUE TITLE
Push the community bar to all green

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#807]
TODO

https://github.com/joncampbell123/dosbox-x/community

#786

**Comment by joncampbell123** [comment]
Community guidelines:

Be fair, and work cooperatively. This is a open source project where contributions are welcome from anyone with an interest in MS-DOS and emulation.

Leave your politics at the door. All that matters here is DOSBox-X, emulation, games, software, hardware, accuracy, code, development, and documentation. Anything else is off-topic and will be treated as such.

I will block users that are hostile to this project, it's developers, and/or users with an explicit explanation as to *why*. That includes personal attacks, harassment, damaging gossip, doxxing, and spreading misinformation and lies about myself and contributors to this project whether here or anywhere else, on the internet or in real life. Disagreement is not harassment, but an opportunity to work out the disagreement and/or have a discussion on the topic.

**Comment by aybe** [comment]
Will look at that tonight.

**Comment by aybe** [comment]
For the code of conduct, you have to choose a template and add an email:

https://github.com/joncampbell123/dosbox-x/community

**Comment by aybe** [comment]
@joncampbell123 

Preliminary issue templates (bug, feature):
908e0679ad9520939b2a43b88c85cfa34fbc0dd6

See how the issue tab works now:
https://github.com/joncampbell123/dosbox-x/issues/new/choose

**Comment by joncampbell123** [comment]
Now that's a nicely vague "code of conduct" that would never be abused to take anything anyone says out of context (sarcasm).

The people who write this stuff... they *do* realize there are people out there (especially today) ready to take offense at literally *anything*, right? "Harassment" isn't as well defined as it used to be.

Second, I don't regard DOSBox-X as a "professional setting". I regard it as a fun place for emulation and MS-DOS enthusiasts to hang out and hack on code. I don't want this project to be a stuffy corporate environment where you have to sit there and talk like a robot in case someone gets offended. Honest opinions are good, as are honest discussions, because that helps a project move forward. That includes an honest assessment and explanation on why something or some implementation is stupid or wrong. If someone takes opinions and discussions as personal attacks or has problems getting triggered over irrelevant details, that's not my problem and they probably shouldn't work on this project. They should either work on a project where they're happier with like-minded developers or fork this project where they can work on their fork in peace.

Another issue I have is "focusing on what's best for the community". I care what's best for this project, around which a healthy community forms out of interest anyway.

I know the common attitude is "well, whatever, just ignore it", but I know someone somewhere would consider merely adding this code of conduct to be binding and effective.

Now if we can edit the code of conduct to clarify some rules and suit our needs after adding it, then I'll allow it.

**Comment by joncampbell123** [comment]
The ironic thing is that my current attitude in maintaining this project *is* already inclusive. I like to work with people with a same or similar hobby/interest and sexual orientation or political leaning has nothing to do with it. That's what I mean when I say "leave your politics at the door". I want this to be a project about DOSBox-X, not about whether Donald Trump is a Nazi or other silly off-topic discussions.

**Comment by joncampbell123** [comment]
To clarify: I will not accept that code of conduct as written. It needs to be updated for this project.

**Comment by aybe** [comment]
We are 100% green now !

https://github.com/joncampbell123/dosbox-x/community

---
I agree with you, it's rather a lawyer-written text that says _we won't endorse anything and happily ban you without reason as soon as you give us the opportunity_ !

It can be changed, I added a dummy email then pasted your previously written text:
https://github.com/joncampbell123/dosbox-x/blob/master/CODE_OF_CONDUCT.md

---

For the template issues I've only slightly edited them from the provided ones.

---

Here's the PR template (wrote it by hand):
https://github.com/joncampbell123/dosbox-x/blob/master/PULL_REQUEST_TEMPLATE.md

---

https://github.com/joncampbell123/dosbox-x/blob/master/CONTRIBUTING.md

(wrote it)

---

Let me know what you think, edit them as you'd like and we'll see from there.

(there are close to no examples I could find on the web for all these)

**Comment by sikthehedgehog** [comment]
Just my two cents: I honestly haven't been happy with code of conducts because of the fact that in practice the worst harassers tend to be people who had already gained trust within their community before and hence people in charge are reluctant to do anything against them (and many will blindly defend them out of trust instead of trying to be impartial), which means that they end up having free reign to be assholes towards anybody that rubs them off wrong. This has always been an issue with forums (which nearly always have strict rules) and repos aren't any different.

I suppose I never cared much since I never intend my own projects to be community projects, but I wish there was a way they couldn't be undermined so easily.

**Comment by emendelson** [comment]
This is just a curiosity question: 

Have there been any unpleasant incidents related to this project in the past?

If not, couldn't Jon simply decide how to deal with them when they occur? Jon is the Bad actors aren't going to care about codes of conduct. (Honor codes in colleges have the same problem - they're merely insulting to honest people, and dishonest people sign and ignore them.)

**Comment by sikthehedgehog** [comment]
> Have there been any unpleasant incidents related to this project in the past?

There was somebody trying to promote their own project here in the past and trying to push things completely unrelated to emulation into DOSBox-X. I think Jon ended up yelling at them to stop.

...you know, why not just make a quick list of guidelines that resemble what you'd find in a forum and that's it? It's not like it'd be able to have more weight than that anyway.

**Comment by emendelson** [comment]
@sikthehedgehog - Yes, I remember that one. Jon was extremely patient and eventually he went away. Jon handled it perfectly, with a lot more patience than I would have had, which is probably why it ended so peacefully. I don't think community guidelines would have any effect in an incident like that one.

**Comment by joncampbell123** [comment]
I want to be careful about the Code of Conduct for a very good reason, in fact I will be very carefully revising it to clarify terms when I get some spare time.

Here's why:

Imagine your own CoC being used against you in every worst possible way. Imagine that something innocent you said angers a feminist or other minority group and they decide to do everything they can (including a social media mob) to shut down your account and ban you from GitHub.

If you have a Code of Conduct that says everyone must be "inclusive" and "respect other people's opinions and experiences", that's a wide open door for them to interpret anything you say as violating either one, including simply stating "I don't care about X, that's not relevant to this project".

I'm perfectly happy for anyone to contribute or help with this project and to enjoy the results. What I want to keep out of this project (and I am willing to block these kinds of users to do it), are those that are or would be hostile to this project including the professionally offended, politically radical antagonists, the outrage mob, and those who would subvert this project to push politically correct topics or cause divisiveness within this project and community. Users like that do nothing but suck the fun and energy out of a project like this and make everyone miserable, they don't belong here.

**Comment by sikthehedgehog** [comment]
I dunno why I keep thinking about this yet but:
```
# Code of Conduct

* Obvious "don't be a jerk" rule. If you start attacking somebody or being
racist or whatever you'll get the boot.
* Don't go around spreading personal information without consent, and even
with consent make sure you know what you're doing.
* This place is for DOSBox-X development, don't try to use it to promote your
own projects over it.
```
(guess the reason behind that last rule)

Dunno if anything else needs to be made explicit. Quite open-ended but as I said that always ends up being the case the moment you leave a person to judge it. Especially when the offender is somebody they normally would trust.

I don't think that GitHub requires you to pick one of their templates, right?

**Comment by emendelson** [comment]
@sikthehedgehog - The guy who promoted his own project didn't actually have a project. He forked the code, did nothing with it, came over here and asked Jon to do various pointless or irrelevant things for him, and eventually deleted his fork, never having done anything to the code. (GitHub keeps a complete record of his activity.) There's no indication there that he ever did anything at all with C code of any kind.

**Comment by Allofich** [comment]
@aybe, seems like this one can be closed, right?

**Comment by aybe** [comment]
closed :)

**Comment by joncampbell123** [comment]
I told you so :)

https://archive.is/7cL5s

https://archive.is/H6Azs

https://twitter.com/coralineada/status/1041784843540094976

https://www.reddit.com/r/linux/comments/9hg9to/sage_sharp_claims_top_linux_kernel_developer_theo/

https://twitter.com/nickmon1112/status/1042912846839992322
