### ISSUE TITLE
mt32 not enabled in windows-builts

### ISSUE THREAD

**Issue by landloafer** [joncampbell123/dosbox-x#827]
**Describe the bug**
mt32 not enabled in windows-builts (dosbox-x-windows-20180701-103732-windows)

**To Reproduce**
1. ren dosbox.reference.conf to dosbox.conf
2. mididevice=mt32 and ROM files in dosbox-x folder
3. mixer doesn't show mt32 as enabled Channel in all windows builts (dosbox-x-windows-20180701-103732-windows)
4. mixer show mt32 as enable Channel in all mingw builts (dosbox-x-windows-20180701-103732-mingw)

**Expected behavior**
mt32 should be enabled in windows builts (behave the same as mingw)

**Comment by aybe** [comment]
There isn't C_MT32 in the config so obviously it won't be in.

Thanks, will take a look.

**Comment by landloafer** [comment]
Thanks, aybe,
I used to use mingw-builts to enjoy mt32 capability. However, since 0.82.7, mingw-builts' win31 speed is substantially slower than that in windows-builts. I think it could have drop to 1/3 of the speed it used to be.
Windows-builts remain the same.

**Comment by aybe** [comment]
Try these,

[Release.zip](https://github.com/joncampbell123/dosbox-x/files/2172282/Release.zip)

[Release SDL2.zip](https://github.com/joncampbell123/dosbox-x/files/2172287/Release.SDL2.zip)

Would be great if you could post how you set MT32 up on Win31, I will then add it to a document describing common uses.

**Comment by heydojo** [comment]
Hi both,

> There isn't C_MT32 in the config so obviously it won't be in.

Specifically missing here: https://github.com/joncampbell123/dosbox-x/blob/master/vs2015/config.h

MT32 was likely disabled in Windows builds because of https://github.com/joncampbell123/dosbox-x/issues/310

I have mt32emu working perfectly on Windows 10. The files you need to look at if you want to port Dosbox-X to an updated version of libmt32emu (using code from my fork) are:

https://gitlab.com/TW3/dbxf/blob/master/src/gui/midi_mt32.h
https://gitlab.com/TW3/dbxf/blob/master/src/dosbox.cpp#L1679
https://gitlab.com/TW3/dbxf/blob/master/vs2017/config.h#L81
https://gitlab.com/TW3/dbxf/blob/master/src/gui/midi.cpp
https://gitlab.com/TW3/dbxf/blob/master/share/conf/dbxf.reference.conf#L658
and the contents of the directory: https://gitlab.com/TW3/dbxf/tree/master/src/mt32

Unfortunately, I neither have the time, or the motivation to do so myself.
It was _one_ of the reasons I forked.

Good Luck! 👍

**Comment by aybe** [comment]
That's a really good thing, when I have some time I will try to do it.

Thanks !!!

**Comment by landloafer** [comment]
Thanks for the new builts (release & release SDL2). I did some trying. Keep mingw as reference (using the same dosbox.conf).
- release.wav sounds i think the same as the 0.82.8 mingw-sdl2 except with some occasional cracking
- release SDL2.wav is with quite noticeable defects (because of #310?)

[capture.zip](https://github.com/joncampbell123/dosbox-x/files/2172485/capture.zip)

**Comment by landloafer** [comment]
To setup mt32 in win31 is very straight forward. Just need to enable mt32 and set straight MIDI Out without messing with the channels and patches. Same applys to setup any MIDI devices (mididevice=win32): -

1. mididevice=mt32 in [midi] section of dosbox.conf
2. MT32_CONTROL.ROM & MT32_PCM.ROM in dosbox-x folder
3. launch dosbox
4. type mixer to confirm mt32 is on
![command_001](https://user-images.githubusercontent.com/39210397/42407415-c1b2a108-81ee-11e8-91a6-aee608c654a0.png)
5. install win31 or win311 according ms manual
6. at Program Manager > Main > Control Panel > Drivers > Add > Roland MPU-401
![krnl386_000](https://user-images.githubusercontent.com/39210397/42407484-f2fe8c58-81ef-11e8-84c0-1686c1653b1b.png)
with all your favorite drivers
![krnl386_001](https://user-images.githubusercontent.com/39210397/42407666-0b4b908c-81f3-11e8-8e9b-f0978496cbc6.png)
7. at Program Manager > Main > Control Panel > MIDI Mapper > New
![krnl386_000](https://user-images.githubusercontent.com/39210397/42407854-797b0b1c-81f5-11e8-9068-3e56a969e383.png)
![krnl386_001](https://user-images.githubusercontent.com/39210397/42407885-0faec8f8-81f6-11e8-94cd-a1ae5fdb2129.png)
ignore MT32 that was preinstalled. It is completely irrelevant.
![krnl386_004](https://user-images.githubusercontent.com/39210397/42407940-94b989b0-81f7-11e8-913e-4fa88e3ab88c.png)
8. you are all set!

**Comment by landloafer** [comment]
9. setup in user program
![krnl386_005](https://user-images.githubusercontent.com/39210397/42408231-e1fb7a2c-81fb-11e8-96ed-fc6a9b548f78.png)
![krnl386_007](https://user-images.githubusercontent.com/39210397/42408216-a62c13a8-81fb-11e8-8c38-e5cda46c22ed.png)

**Comment by aybe** [comment]
@landloafer 

Thanks !

But you know what, even with your instructions I really struggled ...

That definitely confirms my idea of writing a proper Win31 guide because it's far from being obvious !

Did you get these screen ?

![krnl386_000](https://user-images.githubusercontent.com/1537591/42415975-84a5ab6a-8262-11e8-83d5-b1c08c9c1fc9.png)

![krnl386_001](https://user-images.githubusercontent.com/1537591/42415976-84bb8e76-8262-11e8-9af5-3cc3f4046d8b.png)

I have another outstanding issue, SB sound will play for a bit then stop, but then, it's impossible to exit Windows !!!

Did you experience the same issue ?

(and I didn't talk about that dumb issue with the S3 drivers where the second time it asks you for the floppy you have to change `a:\` to `a:` .... drove me nuts)

PS also can you please post your dosbox.conf, thanks !

**Comment by landloafer** [comment]
I remember we need to manually set Port/IRQ in the driver settings dialog to match dosbox as well. Win31 is rather granny not plug n play...

**Comment by aybe** [comment]
This all reminds me when I tried to switch on my old P200MMX again recently, not as obvious as it used to be !

**Comment by landloafer** [comment]
I only changed two setting from dosbox.reference.conf
- mididevice=mt32
- integration device=true

[dosbox.conf.zip](https://github.com/joncampbell123/dosbox-x/files/2174595/dosbox.conf.zip)

**Comment by landloafer** [comment]
I have just discovered an issue with the using of dosbox.reference.conf with "Windows for Workgroup 3.11". Keyboard is not responding once and ever since I load up WFG311 (keyboard will NOT be back even when I exit windows). Only to quit/relaunch dosbox-x.
dosbox.reference.conf does not cause such issue with "Windows 3.11". Haven't tried WFG311 in a guest OS.
But, interesting enough, I have this old .conf that I've been using for a quite while since svn-daum builts, WFG311 works...! I just can't find out yet which setting in dosbox.reference.conf is causing such behavior.
[svn-daum.conf.zip](https://github.com/joncampbell123/dosbox-x/files/2174774/svn-daum.conf.zip)

**Comment by aybe** [comment]
@landloafer 

You should post your problem as an issue instead: https://github.com/joncampbell123/dosbox-x/issues/new/choose

Doing so will give more visibility to it, as it is currently, it'll just get lost as a comment in an unrelated thread.

**Comment by aybe** [comment]
@landloafer 

Thanks for the MT32 explanations, I'll merge them on the Getting Started guide I'm writing.

**Comment by lexa2** [comment]
Hi, this is just a friendly reminder that MSVC builds of DosBox-X still have mt32 emulation disabled. Tested today with MSVC build 20181201-111520 vs MinGW win32 biuld 20181201110201.

**Comment by joncampbell123** [comment]
C_MT32 is now enabled for Windows builds
