### ISSUE TITLE
Sound clicks in Prehistorik 2

### ISSUE THREAD

**Issue by Dinis1979** [joncampbell123/dosbox-x#879]
Sound clicks in Prehistorik 2. I have tried to increase cycles but it still clicks.
Sound doesn't click in other games.

**Environment (please complete the following information):**
 - Windows 10 64 bit
 - DOSBox-X v0.82.9

**Comment by joncampbell123** [comment]
To be fair, some games have clicking problems not because of the sound output but because the digitized samples they play start/stop at nonzero samples. That seems to be the case here.

However, there does seem to be a problem with the mode selection (beginner/expert) scrolling. It seems to depend on VGA memory wraparound that's not being emulated properly here.

**Comment by joncampbell123** [comment]
Hm, the broken screen in question is actually using a 16-color planar EGA mode on VGA. So this is a planar VGA 16-color wraparound problem.

**Comment by joncampbell123** [comment]
Ew, I think the game is trying to set EGA 320x200 16-color mode then switch on the CGA compatible mapping to do 8KB wraparound. The only thing preventing interleaved lines is that the max scanline register is set to 1 instead of 2.

**Comment by joncampbell123** [comment]
Fixed.

**Comment by joncampbell123** [comment]
By fixed I mean the mode select screen appears correctly.

It actually is relying on setting CGA compatible mapping (replace bit 13 with bit 0 of row counter) to cause 8KB wraparound in EGA 320x200 16-color mode. The reason CGA interlacing doesn't affect it is that the max scanline register is also zero, so the row counter is always == 0. 200-line to 400-line doubling is enabled by bit 7 of the mode control register.

One screen in EGA 320x200 16-color mode can fit in 8KB, so it allows the demo to pan around a repeating background of caveman easily, overdrawing the center with the text as it goes. The overlay would be perfect except that timing issues make it occasionally glitch/jump a bit. I suspect this might happen on real hardware too, will need to check.

**Comment by Allofich** [comment]
FWIW, DOSBox-SVN seems to run pretty much the same as DOSBox-X does now. Seems to be the same audio clicking, and the occasional glitch/jump seems to be the same or at least similar. It also shows the repeating background correctly.

**Comment by joncampbell123** [comment]
Right, but at least the glitching/jumping on the mode select screen can be eliminated somewhat by setting the cycles count somewhere around cycles=15000.

I still think the audio clicking is no fault of the emulator but instead an artifact caused by the digital samples used by the music playback. Most programs of that time use sample-based music (like MOD, S3M etc) which can sound great but if the samples start/stop at a nonzero sample value, playback of the music can sound clicky.

**Comment by kcgen** [comment]
Some small progress on Prehistorik 2's audio problems here: https://github.com/dosbox-staging/dosbox-staging/issues/407#issuecomment-647140430, including a one-off dosbox hack to correct the DC offsets.

**Akuma** over at Vogons also [reported identical audio issues with Blues Brothers](https://www.vogons.org/viewtopic.php?f=33&t=74010).

Blues Brothers and Prehistorik 2 are both 1993 releases by Titus, and they both use mod-tracker music and the same broken audio driver.

**Comment by Dinis1979** [comment]
Blues Brothers uses FM music.

**Comment by kcgen** [comment]
> Blues Brothers uses FM music.

Thanks @Dinis1979 ; indeed, Akuma reports the issue with Blues Brothers **_Jukebox Adventures_**.
