### ISSUE TITLE
dynamic core: issues with Windows 95 OSR2 and similar cases

### ISSUE THREAD

**Issue by ghoul8765** [joncampbell123/dosbox-x#91]
The 1st issue is dosbox-x exits on error, "CS:IP mistmatch error...", where core=dynamic, non-recursive page fault=TRUE, and booting Windows 95b, but reverting the following (paging.cpp) commit fixes it:
"move down CS:IP check to warning, since normal core is now fixed up"

Also, there is a 2nd issue with or without the above "reversion" applied, where core=dynamic, non-recursive pf=FALSE, and booting Windows 95b, which shows an exit with error:
"Stack segment with invalid privileges"

The "fix" for the 2nd issue is in paging.cpp:
static Bits PageFaultCore(void) {
...
remove this line: Bits ret=CPU_Core_Full_Run();
add this line:	   Bits ret=CPU_Core_Normal_Run();
...

Thank you!

**Comment by joncampbell123** [comment]
For the first issue, revert back to head and see if setting apmbios=false helps with Windows 95 B. There are still some funny issues from APM BIOS emulation. I'll gen up a VM with Win95 B to see if it happens on my end.

**Comment by joncampbell123** [comment]
The second thing I want to point out is that the non-recursive page fault mechanism relies on being able to throw a C++ exception back out to the normal loop. As I've stated in the past that's not always possible from the dynamic core because the C++ stack frame needed to do that doesn't exist when running through the dynamic core. I'm making improvements right now in the normal core and I don't recommend using the non-recursive mode with dynamic core anymore. I'm considering adding code to disable non-recursive mode when dynamic core is selected for that reason.

**Comment by ghoul8765** [comment]
I have the apmbios disabled in the code.  :)

I appreciate your work on dosbox-x! And your goals for the project, especially.

Even if the non-recursive code is disabled under the dynamic core, then it may still be necessary to change the page fault core back to full? Perhaps that could be a dosbox.conf option?

**Comment by joncampbell123** [comment]
I added a notice to the dosbox.conf help text to state that dynamic core and Windows 95 is not supported anymore. Dynamic core continues to work fine with DOS games and Windows 3.1.
