### ISSUE TITLE
Windows 3.1 KRNL386.EXE fails to boot when core=normal and non-recursive page fault=false

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#97]
Is it time to start removing the recursive page fault mode?

**Comment by joncampbell123** [comment]
Windows 95 too.

**Comment by ghoul8765** [comment]
It may be worthwhile to restrict the main branch of dosbox-x to core=normal, non-recursive page fault=true, especially since your brilliant and extensive enhancements to that mode have a trade-off with respect to normal/false and dynamic/any. At least normal/true may be debugged properly in emulation, is portable, and allow the corner cases and WinME to work more reliably.

It may be worthwhile to create a single branch of dosbox-x without further updates that allows reasonably good functioning of the normal/false and dynamic/any modes. Others can contribute your main branch changes to that side branch instead and it would serve as a good test bed.

**Comment by joncampbell123** [comment]
Sounds good. I'll run back through the commit log until I find a version that Win31 boots with recursive page faults and then branch from current source with code taken from the branch where that still works.

**Comment by joncampbell123** [comment]
Normal core now forces nonrecursive mode on. Done.
