### ISSUE TITLE
VS2017 SDL1 build fails

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#986]
Building current code under VS2017, default settings, produces this error:

memory.obj : error LNK2001: unresolved external symbol "void __cdecl restart_program(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)" (?restart_program@@YAXAAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z)
8>F:\Users\Edward\Desktop\dosbox-x-master-1Jan\vs2015\..\bin\Win32\Release\/dosbox-x.exe : fatal error LNK1120: 1 unresolved externals

**Comment by emendelson** [comment]
Thank you! See new issue about remembering window position...

**Comment by yksoft1** [comment]
I don't think removing "Restart DOSBox-X" is a good fix for this.
Currently there are still some issues in "Reset guest system", for example that IMGMOUNTed disks won't be 
automatically unmounted.

**Comment by joncampbell123** [comment]
@yksoft1 "Restart DOSBox-X" is a terrible hack, using exec to self to restart the whole emulator. On my systems it often doesn't work because SDL gets caught up in some output driver it can't initialize.

I'd rather see that those issues are fixed when you "reset guest system". The obvious solution is to unmount those disk images when you "reset guest system".
